import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const root=path.resolve(process.argv[2]||'runtime'),load=n=>import(pathToFileURL(path.join(root,n)));
const dependencies=JSON.parse(fs.readFileSync('audit-fixes/n10-primary-pipeline-20261004/accepted-runtime-dependencies.json'));
for(const [file,hash] of Object.entries(dependencies.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),hash,'CHANGED_DEPENDENCY_REQUIRES_NEW_TEST:'+file);
const {RemoteD1Database}=await load('report2-d1-adapter.mjs'),{createUnifiedHttpBudget}=await load('src/unified-budget.mjs'),{reserveEvidenceSourceAttempts}=await load('src/evidence-source-store.mjs'),{parseHtxMarketJson}=await load('src/htx-trade-json.mjs'),{buildHtxPrimaryTechnicalReceipt,readHtxTechnicalStructure,clearHtxTechnicalSnapshots}=await load('src/htx-technical-structure.mjs'),{buildHtxReferencePrice}=await load('src/market-contracts.mjs'),{finalizeCandidateBlockCoverage}=await load('src/candidate-evidence-v2-runtime.mjs'),{buildRuntimeCanonicalBundle}=await load('src/canonical-runtime-adapter.mjs');
const worker=fs.readFileSync(path.join(root,'src/worker.js'),'utf8'),worker_sha256=crypto.createHash('sha256').update(worker).digest('hex');
assert.equal(worker_sha256,'db32a9a8954716c611d4532ec3930673f236c3cd4a6a8f12c8dfb653ec1999eb');assert.ok(worker.includes('PRIMARY_TECHNICAL_CONTEXT:primaryTechnicalReceipt'));
// Expose the exact production component functions for this audit only. No
// production export, deep check, MAIN, scheduled task or Telegram is invoked.
const exposed=path.join(root,'src/n10-component-audit.mjs');fs.writeFileSync(exposed,worker+'\nexport {futuresSnapshot,futuresTrajectory};\n');const {futuresSnapshot,futuresTrajectory}=await import(pathToFileURL(exposed));
const db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN),budget=createUnifiedHttpBudget(),phase=JSON.parse(fs.readFileSync('checkpoints/CLOUD_PHASE_STATE_20261004.json'));
assert.equal(phase.lease?.owner,process.env.REPORT2_CONTINUATION_OWNER);assert.ok(phase.lease.expires_ts>Date.now());assert.equal(phase.current_phase,'CORE_BLOCKS');
const bytes=fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'),universe=JSON.parse(zlib.gunzipSync(bytes)),run_id=`N10_PRIMARY_ACTUAL:${process.env.GITHUB_RUN_ID}`,raw=[],results=[],denials=[];
assert.equal(universe.status,'CLOSED');const targets=[universe.assets.find(a=>/[^\x00-\x7f]/.test(a.symbol))?.asset_analysis_contract].filter(Boolean);assert.equal(targets.length,1);for(const contract of targets)assert.ok(universe.contracts.some(c=>c.contract_code===contract&&c.production_market_adapter_supported));
const endpointPaths=new Set(['/linear-swap-api/v1/swap_contract_info','/linear-swap-ex/market/depth','/linear-swap-ex/market/bbo','/linear-swap-ex/market/history/trade','/linear-swap-api/v1/swap_open_interest','/linear-swap-api/v1/swap_funding_rate','/linear-swap-ex/market/history/kline','/linear-swap-api/v1/swap_his_open_interest','/linear-swap-api/v1/swap_historical_funding_rate']);
function save(error=null){fs.writeFileSync('audit-output/n10-primary-source-bodies.json',JSON.stringify(raw)+'\n');fs.writeFileSync('audit-output/n10-primary-live-verification.json',JSON.stringify({schema:'report2-primary-technical-actual-component-use-v1',github_head:process.env.GITHUB_SHA,run_id,worker_sha256,dependency_checks:'EXACT_CLOUD37236235424_VALIDATED_RUNTIME_REUSED_NO_REPEAT_TESTS',dependency_proof:dependencies,previous_btc_source_audit:'cloud37236235424:13HTTP:component_sources_received_but_audit_shape_error_no_fresh_acceptance_claim',error,common_universe_sha256:crypto.createHash('sha256').update(bytes).digest('hex'),common_contracts:universe.contracts.length,common_assets:universe.assets.length,all_common_contracts_retained:universe.contracts.map(c=>({contract_code:c.contract_code,market_kind:c.market_kind,production_market_adapter_supported:c.production_market_adapter_supported})),targets,results,denials,source_http:raw.length,database_usage:db.usageSnapshot(),all_15_live_accepted:false,full_main_acceptance:false,telegram_delivery_proven:false,deep_checks_started:0,production_canonical_writes:0,telegram_calls:0},null,2)+'\n');}
process.on('uncaughtExceptionMonitor',e=>save(String(e)));
for(const contract of targets){
 clearHtxTechnicalSnapshots();const cache=new Map();
 const requestJson=url=>{if(cache.has(url))return cache.get(url);const pending=(async()=>{
  const u=new URL(url);assert.equal(u.hostname,'api.hbdm.com');assert.ok(endpointPaths.has(u.pathname));assert.equal(u.searchParams.get('contract_code'),contract);assert.ok(raw.length<13);
  const id=run_id+':'+contract+':'+crypto.createHash('sha256').update(url).digest('hex'),whole=budget.reserve({logical_request_id:id,lane:'background',attempts:1});if(!whole.allowed){denials.push(whole);return{ok:false,data:null,error:whole.status};}
  const provider=await reserveEvidenceSourceAttempts(db,{source:'HTX_PUBLIC_RISK',reservation_id:id,attempts:1,daily_cap:144,now:Date.now()});if(!provider.allowed){denials.push(provider);return{ok:false,data:null,error:provider.status};}
  const r={url,started_ts:Date.now()};raw.push(r);
  try{const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(10000)}),body=await response.text();Object.assign(r,{http_status:response.status,received_ts:Date.now(),body_sha256:crypto.createHash('sha256').update(body).digest('hex'),body});save();const data=response.ok?parseHtxMarketJson(body,url):null;return{ok:response.ok&&data?.status==='ok',data,status:response.status,error:response.ok?data?.['err-msg']:'HTTP_'+response.status};}
  catch(e){Object.assign(r,{received_ts:Date.now(),error:String(e?.name||e)});save();return{ok:false,data:null,error:r.error};}
 })();cache.set(url,pending);return pending;};
 const settled=await Promise.allSettled([futuresSnapshot({contract,trades:2000,_fetch_json:requestJson}),futuresTrajectory({contract,trades:2000,kline_size:1600,_fetch_json:requestJson})]);
 const wrap=r=>r.status==='fulfilled'?{execution_status:'FULFILLED',data:r.value}:{execution_status:'REJECTED',data:null,error:String(r.reason)};const futures=wrap(settled[0]),trajectory=wrap(settled[1]),now=Date.now();
 const reference_price=buildHtxReferencePrice({contract,type:'MID_OBSERVATION',bid:futures.data?.bbo?.best_bid,ask:futures.data?.bbo?.best_ask,source_ts:Date.parse(futures.data?.liquidity?.depth_timestamp||''),received_ts:now});
 const receipt=buildHtxPrimaryTechnicalReceipt({contract,futures,trajectory,reference_price,now,route_state:'REJECTED'}),evidence=readHtxTechnicalStructure({contract,now}),coverage=finalizeCandidateBlockCoverage({evidence_result:{evidence,sources:{}},primary_sources:{PRIMARY_TECHNICAL_CONTEXT:receipt}});let report=null;
 const row={contract,futures,trajectory,reference_price,primary_receipt:receipt,block_coverage:coverage.block_coverage,report:null};results.push(row);save();
 if(receipt.check_completed){const input={contract,run_id,snapshot_id:run_id+':'+contract+':'+now,observed_ts:now,futures_component:futures,internal_market_context:{htx_reference_price:reference_price,evidence_v2:coverage,internal_only:true}},bundle=buildRuntimeCanonicalBundle(input);assert.equal(bundle.manual.ok,true);assert.ok(bundle.manual.text.includes('Фактический ценовой диапазон'));assert.equal(bundle.canonical.state,'REJECTED');assert.equal(bundle.canonical.metadata.automatic_execution,false);assert.equal(coverage.block_coverage.blocks.N10.checked,true);report={scope:'ACTUAL_SAME_CONTRACT_PRODUCTION_COMPONENTS_AND_CANONICAL_BUILDER_NOT_FULL_MAIN',canonical:bundle.canonical,manual:bundle.manual};}
 row.report=report;save();if(denials.length)break;
}
const usage=db.usageSnapshot();assert.equal(usage.unknown_ops,0);assert.ok(usage.rows_read<=10000&&usage.rows_written<=180);assert.ok(raw.length<=13);save();console.log(JSON.stringify({status:results.every(r=>r.report)&&results.length===targets.length?'CLOSED_ACTUAL_PRIMARY_COMPONENT_USE':'PARTIAL_PRIMARY_COMPONENT_USE',useful_contracts:results.filter(r=>r.report).map(r=>r.contract),source_http:raw.length,denials:denials.length,database_usage:usage,deep_checks_started:0,production_canonical_writes:0,telegram_calls:0}));
