import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import http from 'node:http';import {createRequire} from 'node:module';
import {FixtureDB} from '../../liquidation/liquidation-extension/delivery/tests/db-fixture.mjs';
import {createGTradeRuntimeCollector} from '../../liquidation/liquidation-extension/src/gtrade-runtime-collector.mjs';import {createNativeAcquisition} from '../../liquidation/liquidation-extension/src/runtime-bridge.mjs';import {createMultiLiquidationAcquisition} from '../../liquidation/liquidation-extension/src/gtrade-runtime-bridge.mjs';
const runtime=process.env.REPORT2_TEST_RUNTIME?new URL('file://'+process.env.REPORT2_TEST_RUNTIME.replace(/\/$/,'')+'/src/'):new URL('../../../repository/runtime/src/',import.meta.url);
const before=await import(new URL('../../liquidation/liquidation-extension/.verification/postv7-before/src/canonical-runtime-adapter.mjs',import.meta.url));
const after=await import(new URL('canonical-runtime-adapter.mjs',runtime));
const pub=await import(new URL('canonical-publication.mjs',runtime));const sender=await import(new URL('bound-telegram-delivery-sidecar.mjs',runtime));
const sdk=createRequire(new URL('../../liquidation/liquidation-extension/package.json',import.meta.url))('@gainsnetwork/sdk');const load=n=>JSON.parse(fs.readFileSync(new URL('../../liquidation/liquidation-extension/evidence/'+n,import.meta.url),'utf8'));const T=1790489991000;
async function inputs(){const state=structuredClone(load('hl_account_0.raw'));state.time=T-100;const receipt={...load('hl_account_0.receipt.json'),started_ts:T-200,received_ts:T-50};
 // Position shapes are captured; same-snapshot clocks and actionability are
 // deliberate SYNTHETIC TEST INPUTS, never a current market assertion.
 const hl=createNativeAcquisition({contract:'FIL-USDT',native_symbol:'FIL',run_id:'POSTV7:MERGE:TEST',acquisition_id:'HL:MERGE',collection_started_ts:T-500,collection_completed_ts:T,accounts:[{address:receipt.request_body.user,state,http_receipt:receipt}],provenance:{fixture:'SYNTHETIC_CLOCK_CAPTURED_NATIVE_POSITION'}});
 const fetch_impl=async url=>new Response(JSON.stringify(load(String(url).includes('/trading-variables')?'gtrade_variables_v2.raw':String(url).includes('/open-trades')?'gtrade_trades_v2.raw':'gtrade_prices.raw')));
 const gt=await createGTradeRuntimeCollector({sdk,fetch_impl,clock:()=>T})({contract:'FIL-USDT',native_symbol:'FIL',run_id:'POSTV7:MERGE:TEST',acquisition_id:'GT:MERGE',deadline_ts:T+20000});assert(gt.acquisition);
 return {contract:'FIL-USDT',run_id:'POSTV7:MERGE:TEST',snapshot_id:'EXACT:MERGE',observed_ts:T,discovery_row:{contract:'FIL-USDT',rolling_24h_change_pct:2,early_candidate_quality_0_100:80},
 publication_shadow:{entry_signal:{state:'WAIT_FOR_TRIGGER',direction:'LONG',trigger:{metric:'price',operator:'>=',value:1.15,unit:'USDT',timeframe:'5m',expires_ts:T+600000,next_recheck_ts:T+120000,cancel_condition:'цена ниже 1,05 USDT'}},score_interval:{score_lower_bound:72},scenario_plan:{execution_reference_price:1.14,target_price:1.22,begin_close_price:1.22,remaining_move_pct:6.9565,target_basis:'PRECOMMITTED_BASE_MEASURED_MOVE_AT_LEAST_5_PERCENT'}},
 public_evidence:{evidence:[]},liquidation_intelligence:{projected_clusters:[],projected_map_status:'NOT_CLOSED'},free_source_summary:{status:'CLOSED',owner:'source-registry.mjs',registry:{status:'CLOSED',entries:[]},entry_funnel:{status:'CLOSED',blockers:[],blocker_details:[]},continuous_collector_status:'PARTIAL_REALTIME_COVERAGE',hot_cycle_external_request_delta:0,d1_write_delta:0},
 native_liquidation_acquisition:createMultiLiquidationAcquisition({contract:'FIL-USDT',run_id:'POSTV7:MERGE:TEST',hyperliquid:hl,gtrade:gt.acquisition})};}
async function receiver(t){const received=[];const s=http.createServer(async(req,res)=>{let body='';for await(const x of req)body+=x;received.push(JSON.parse(body));res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,message_id:98101}));});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>s.close(r)));return{received,url:`http://127.0.0.1:${s.address().port}/only-test-receiver`};}
test('exact unified candidate preserves facts while universal liquidation zones remain available below five percent',async()=>{const a=await inputs();delete a.native_liquidation_acquisition;const x=after.buildRuntimeCanonicalBundle(a),y=before.buildRuntimeCanonicalBundle(a);for(const key of ['scores','direction','state','entry','trigger','invalidation','hard_gates','source_receipts'])assert.deepEqual(x.canonical[key],y.canonical[key],key);assert.equal(x.canonical.targets[0].price,y.canonical.targets[0].price);assert.equal(x.canonical.targets[0].start_closing,true);assert.ok(x.canonical.targets[0].potential_move_pct>=5);assert.equal(x.canonical.liquidations.pump.threshold_pct,5);assert.equal(x.canonical.liquidations.pump.upper_ceiling_pct,null);assert.equal(x.canonical.liquidations.status,'CLOSED');assert.equal(x.canonical.liquidations.above.length,4);assert.equal(x.canonical.liquidations.below.length,4);});
test('exact post-V7 owner keeps both independent sources and lets the verified panel adjust only the bounded score',async()=>{const a=await inputs(),b=after.buildRuntimeCanonicalBundle(a);assert.equal(b.status,'CLOSED',JSON.stringify(b.surface_contract));assert.equal(b.manual.ok,true);assert.match(b.manual.text,/РАННИЕ КАНДИДАТЫ ДО ДВИЖЕНИЯ/);assert.match(b.manual.text,/Hyperliquid FIL/);assert.match(b.manual.text,/gTrade FIL/);assert.match(b.manual.text,/USDC/);assert.match(b.manual.text,/ USD/);const old=before.buildRuntimeCanonicalBundle(a);for(const k of ['direction','state','hard_gates'])assert.deepEqual(b.canonical[k],old.canonical[k],k);assert.equal(b.canonical.targets[0].price,old.canonical.targets[0].price);assert.equal(b.canonical.targets[0].start_closing,true);assert.ok(b.canonical.targets[0].potential_move_pct>=5);assert.ok(Math.abs(b.canonical.scores.coin_interest_0_100-old.canonical.scores.coin_interest_0_100)<=10);assert.ok(b.canonical.metadata.supplemental_score_adjustment.receipts.some(x=>x.source_id==='DYNAMIC_LIQUIDATION_PANEL'));});
test('exact candidate canonical + saved manual -> database + queue -> real bound sender socket contains both sources',async t=>{const a=await inputs(),b=after.buildRuntimeCanonicalBundle(a),db=new FixtureDB();t.after(()=>db.close());const c=b.canonical;const saved=await pub.persistCanonicalSnapshot(db,{canonical:c,presentation_inputs:{manual_text:b.manual.text},wave_id:'MERGE:WAVE',now_ts:T});assert(saved.persisted);
 db.raw.prepare('INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1)').run('FIL-USDT','LONG','MERGE:WAVE','v3','WAIT','fixture',T,T+600000,T);
 db.raw.prepare("INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,'PENDING',?,?,1)").run('MERGE:DISPATCH','MERGE:KEY','FIL-USDT','LONG','MERGE:WAVE','WAIT','v3',T,T);
 const r=await receiver(t);const cfg={enabled:true,relay_url:r.url,relay_key:'LOCAL_TEST_ONLY',now_ts:T+1000,source_run_id:c.run_id};const result=await sender.runBoundTelegramDeliverySidecar(db,cfg);assert.equal(result.sent,1,JSON.stringify(result));assert(r.received[0].text.length<=850,'WAIT length must preserve approved limit');assert.equal(r.received.length,1);
 const manual=await pub.loadExactManual(db,{publication_id:saved.publication_id});assert(manual.ok);assert.equal(manual.text,b.manual.text);assert.equal(manual.analytical_fingerprint,c.analytical_fingerprint);assert.match(manual.text,/Hyperliquid FIL/);assert.match(manual.text,/gTrade FIL/);assert.match(manual.text,/USDC/);assert.match(manual.text,/ USD/);assert.match(r.received[0].text,/Сильные зоны выше:/);assert.match(r.received[0].text,/Сильные зоны ниже:/);assert.match(r.received[0].text,/Начинать закрывать позицию: 1,22 USDT/);
 const q=db.raw.prepare('SELECT * FROM v3_recheck_task_shadow WHERE publication_id=?').get(saved.publication_id);assert(q&&q.due_ts===c.trigger.next_recheck_ts);
 const again=await sender.runBoundTelegramDeliverySidecar(db,{...cfg,now_ts:T+2000});assert.equal(again.sent,0);assert.equal(r.received.length,1);
 fs.writeFileSync(new URL('../../proof/full-runtime-real-sender.json',import.meta.url),JSON.stringify({status:'PASS',node:process.version,scope:'EXACT_POSTV7_CANONICAL_AND_SAVED_MANUAL_THROUGH_REAL_BOUND_SENDER_TO_LOCAL_SOCKET',market_clocks:'SYNTHETIC_SAME_WINDOW_USING_CAPTURED_NATIVE_POSITION_SHAPES',canonical_fingerprint:c.analytical_fingerprint,receiver_requests:r.received.length,manual_preserved:true,independent_venues:2,raw_usdc_not_usd:true,real_telegram:false,production_changed:false},null,2));
});
