import test from 'node:test';import assert from 'node:assert/strict';
import {classifyFullEvidenceInsertAck,fullEvidenceInsertSql} from '../src/full-evidence-ack.mjs';
import {parseProjectedRow,classifyProjectedPayload,selectProjectedZones} from '../src/liquidation-normalizer.mjs';

test('full evidence persisted=true only on one inserted row',()=>{
 assert.deepEqual(classifyFullEvidenceInsertAck({meta:{changes:1,rows_written:1}}),{status:'CLOSED',persisted:true,deduplicated:false,insert_changes:1,reason:null});
 const z=classifyFullEvidenceInsertAck({meta:{changes:0,rows_written:0}});assert.equal(z.persisted,false);assert.equal(z.status,'NOT_PERSISTED');
 const d=classifyFullEvidenceInsertAck({meta:{changes:0,rows_written:0}},{duplicateConfirmed:true});assert.equal(d.persisted,false);assert.equal(d.status,'DEDUPLICATED');
});
test('full evidence SQL ignores only duplicate full_evidence_id, not arbitrary constraints',()=>{const s=fullEvidenceInsertSql();assert.match(s,/ON CONFLICT\(full_evidence_id\) DO NOTHING/);assert.doesNotMatch(s,/INSERT OR IGNORE/i);});
test('undocumented heatmap arrays fail closed',()=>{const r=parseProjectedRow([1,500,'short'],{current_price:1.1});assert.equal(r.status,'UNSUPPORTED_ARRAY_SCHEMA');assert.equal(r.cluster,null);});
test('explicit array schema can be used only when declared',()=>{const r=parseProjectedRow([1,'SHORT',90,12000],{provider:'fixture',current_price:.9,array_schema:{version:'EXPLICIT_V1',price_index:0,side_index:1,intensity_index:2,notional_index:3}});assert.equal(r.status,'CLOSED');assert.equal(r.cluster.level_price,1);assert.equal(r.cluster.notional_usd,12000);});
test('object projected row requires exact side and size/intensity',()=>{assert.equal(parseProjectedRow({price:1.1,intensity:80},{current_price:1}).status,'SIDE_NOT_CLOSED');assert.equal(parseProjectedRow({price:1.1,side:'SHORT'},{current_price:1}).status,'SIZE_OR_INTENSITY_MISSING');assert.equal(parseProjectedRow({price:1.1,side:'SHORT',intensity:80},{current_price:1}).status,'CLOSED');});
test('HTTP 200 is not a usable liquidation map when stale',()=>{const now=1_800_000;const r=classifyProjectedPayload({http_ok:true,schema_ok:true,source_ts:now-5617865,observed_ts:now,max_age_sec:1800,clusters:[{level_price:1}]});assert.equal(r.usable,false);assert.equal(r.status,'FRESHNESS_STALE');});
test('usable provider with zero significant zones is distinct from unavailable source',()=>{const now=10_000_000;const r=classifyProjectedPayload({http_ok:true,schema_ok:true,source_ts:now-1000,observed_ts:now,max_age_sec:1800,clusters:[]});assert.equal(r.status,'CLOSED_NO_SIGNIFICANT_ZONES');});
test('zone selection retains a large distant zone',()=>{const xs=[{side:'SHORT_LIQUIDATION_ABOVE',level_price:101,intensity:50},{side:'SHORT_LIQUIDATION_ABOVE',level_price:102,intensity:60},{side:'SHORT_LIQUIDATION_ABOVE',level_price:125,intensity:1000}];const r=selectProjectedZones(xs,{current_price:100,max_nearest:1,max_major:1});assert.ok(r.above.some(x=>x.level_price===125));});
import fs from 'node:fs';
test('CoinLobster free projected fixture has exact price/side/USD intensity/leverage schema',()=>{const f=JSON.parse(fs.readFileSync(new URL('../fixtures/coinlobster-btc-liq-zones.json',import.meta.url),'utf8'));const rows=f.projection.bands.map(x=>parseProjectedRow(x,{provider:'COINLOBSTER',source_path:'projection.bands',source_ts:f.projection.generatedAt,observed_ts:f.projection.generatedAt,current_price:f.projection.price}));assert.equal(rows.every(x=>x.status==='CLOSED'),true);assert.equal(rows[0].cluster.notional_usd,1429802144);assert.equal(rows[0].cluster.leverage_bucket,5);const z=selectProjectedZones(rows.map(x=>x.cluster),{current_price:f.projection.price});assert.ok(z.above.length);assert.ok(z.below.length);});
