import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const patch=fs.readFileSync(new URL('../patch_repo.py',import.meta.url),'utf8');
const workflow=fs.readFileSync(new URL('../.github/workflows/post-v7-unified-remediation-candidate.yml',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../migrations.sql',import.meta.url),'utf8');
const bound=fs.readFileSync(new URL('../src/bound-telegram-delivery-sidecar.mjs',import.meta.url),'utf8');
test('portable package is fail-closed and candidate-only',()=>{
  assert.match(patch,/EXACT_MAIN_BASE_REQUIRED/);
  assert.match(patch,/postV7CriticalLaneReserve/);
  assert.match(patch,/source_run_id:String\(cron\.run_id\|\|""\)/);
  assert.match(patch,/REPORT2_POST_V7_UNIFIED_ENABLED: "0"/);
  assert.doesNotMatch(patch,/git\s+push\s+[^\n]*main|merge\s+origin\/main|force[-_ ]push/i);
  assert.match(workflow,/node-version:\s*'24'/);
  assert.match(workflow,/REPORT2_V3_TELEGRAM_NETWORK_ENABLED:\s*"0"/);
  assert.match(workflow,/test "\$\(git rev-parse refs\/remotes\/origin\/main\)" = 'f7c5c77/);
  assert.doesNotMatch(workflow,/wrangler\s+deploy|git\s+push\s+[^\n]*main/i);
  assert.doesNotMatch(migration,/ALTER\s+TABLE\s+(?!IF)/i);
  assert.match(bound,/HEALTH_ALERT_CONFIRM_MS=20\*60_000/);
  assert.match(bound,/RECOVERY_WITHOUT_VISIBLE_DEGRADATION/);
});
