import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {loadSchedulerOwnership,actorOwnsPeriodicAnalytics,claimMaintenanceCadence,completeMaintenanceCadence} from '../src/scheduler-control.mjs';
function norm(sql,args){const picks=[];const q=String(sql).replace(/\?(\d+)/g,(_,n)=>{picks.push(Number(n)-1);return '?';});return picks.length?[q,picks.map(i=>args[i])]:[sql,args];}
class P{constructor(d,s,a=[]){this.d=d;this.sql=s;this.args=a;}bind(...a){return new P(this.d,this.sql,a)}async first(){const[q,a]=norm(this.sql,this.args);return this.d.prepare(q).get(...a)??null}async run(){const[q,a]=norm(this.sql,this.args);const r=this.d.prepare(q).run(...a);return{meta:{changes:Number(r.changes||0)}}}}
class DB{constructor(){this.s=new DatabaseSync(':memory:');this.s.exec(fs.readFileSync(new URL('../migrations.sql',import.meta.url),'utf8'));}prepare(s){return new P(this.s,s)}}
const NOW=1790448000000;
test('periodic analytics has one durable owner and hub fails closed',async()=>{const d=new DB();const o=await loadSchedulerOwnership(d);assert.equal(o.owner,'GITHUB_ACTIONS');assert.equal((await actorOwnsPeriodicAnalytics(d,{actor:'GITHUB_ACTIONS'})).allowed,true);assert.equal((await actorOwnsPeriodicAnalytics(d,{actor:'CLOUDFLARE_HUB'})).allowed,false);});
test('cadence is due by last success, not wall-clock minute',async()=>{const d=new DB();let c=await claimMaintenanceCadence(d,{job_key:'DISCOVERY_RECALL_HOURLY',now_ts:NOW,interval_ms:3600000});assert.equal(c.claimed,true);assert.equal((await completeMaintenanceCadence(d,{job_key:'DISCOVERY_RECALL_HOURLY',now_ts:NOW+1000,success:true,result:'CLOSED'})).completed,true);c=await claimMaintenanceCadence(d,{job_key:'DISCOVERY_RECALL_HOURLY',now_ts:NOW+30*60000,interval_ms:3600000});assert.equal(c.status,'NOT_DUE');c=await claimMaintenanceCadence(d,{job_key:'DISCOVERY_RECALL_HOURLY',now_ts:NOW+3601001,interval_ms:3600000});assert.equal(c.claimed,true);});
test('failed maintenance does not advance last success and becomes due after lease release',async()=>{const d=new DB();let c=await claimMaintenanceCadence(d,{job_key:'R820_HOURLY',now_ts:NOW,interval_ms:3600000});assert.equal(c.claimed,true);await completeMaintenanceCadence(d,{job_key:'R820_HOURLY',now_ts:NOW+1000,success:false,result:'CAPACITY_DEFERRED'});c=await claimMaintenanceCadence(d,{job_key:'R820_HOURLY',now_ts:NOW+2000,interval_ms:3600000});assert.equal(c.claimed,true);});
test('active lease prevents duplicate scheduler execution',async()=>{const d=new DB();const a=await claimMaintenanceCadence(d,{job_key:'X',actor:'GITHUB_ACTIONS',now_ts:NOW,interval_ms:3600000});assert.equal(a.claimed,true);const b=await claimMaintenanceCadence(d,{job_key:'X',actor:'GITHUB_ACTIONS',now_ts:NOW+1000,interval_ms:3600000});assert.equal(b.status,'LEASE_ACTIVE');});
