import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {readCanonicalPublicationScores as read} from '../src/score-origin-reader.mjs';import {transformFormatter} from '../patches/prepare-score-origin-v2.mjs';
const stable=v=>Array.isArray(v)?v.map(stable):(v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().filter(k=>v[k]!==undefined).map(k=>[k,stable(v[k])])):v);const fp=c=>{const x={...c};delete x.analytical_fingerprint;return crypto.createHash('sha256').update(JSON.stringify(stable(x))).digest('hex');};
const binding={contract:'FIL-USDT',direction:'LONG',snapshot_id:'S1',run_id:'R1',observed_ts:1790449000000};
function c(scores={overall_0_100:72,coin_interest_0_100:64,entry_readiness_0_100:null,is_probability:false}){const x={status:'CLOSED',...binding,candidates:[{contract:'FIL-USDT'}],metadata:{contract:'FIL-USDT'},scores};x.analytical_fingerprint=fp(x);return x;}
test('explicit null/undefined binding fails closed without throw',()=>{for(const b of [null,undefined,{},'',[]])assert.equal(read(c(),b).status,'NOT_CLOSED');});
test('exact canonical scores pass unchanged',()=>assert.deepEqual(read(c(),binding).scores,{overall_0_100:72,coin_interest_0_100:64,entry_readiness_0_100:null,is_probability:false}));
test('display direction binding is critical',()=>assert.equal(read(c(),{...binding,direction:'SHORT'}).status,'NOT_CLOSED'));
test('contract/snapshot/run/time mismatch rejected',()=>{for(const [k,v] of Object.entries({contract:'APT-USDT',snapshot_id:'S2',run_id:'R2',observed_ts:binding.observed_ts+1}))assert.equal(read(c(),{...binding,[k]:v}).status,'NOT_CLOSED');});
test('tampered canonical score without new fingerprint rejected',()=>{const x=c();x.scores.overall_0_100=100;assert.equal(read(x,binding).reason,'CANONICAL_CONTENT_MISMATCH');});
test('missing is null, factual zero stays zero, probability/out-of-range refused',()=>{const z=c({overall_0_100:0,coin_interest_0_100:null,entry_readiness_0_100:0,is_probability:false});assert.equal(read(z,binding).scores.overall_0_100,0);for(const s of [{overall_0_100:101,coin_interest_0_100:50,entry_readiness_0_100:null,is_probability:false},{overall_0_100:50,coin_interest_0_100:true,entry_readiness_0_100:null,is_probability:false},{overall_0_100:50,coin_interest_0_100:50,entry_readiness_0_100:null,is_probability:true}])assert.equal(read(c(s),binding).status,'NOT_CLOSED');});
test('formatter transform removes local score inputs and injects canonical reader',()=>{const fixture=`header\nfunction scoreLines({final,shadow,early,feature,opportunity,status}={}){\n const interest=fmtScore(early?.early_detection_quality_0_100);\n return [];\n}\nfunction marketFacts(x){}\nconst x=[...scoreLines({final,shadow,early,feature,opportunity:opp,status})];`;const out=transformFormatter(fixture,{enforceHash:false});assert.match(out,/readCanonicalPublicationScores/);assert.doesNotMatch(out,/early_detection_quality_0_100/);assert.match(out,/direction:dir/);});
