import test from 'node:test';import assert from 'node:assert/strict';
import {persistMicrostructureMinute,loadMicrostructureForContracts,featureInputsFromMicrostructureRows} from '../../../r10_7_auth/src/v3-market-microstructure-persistence.mjs';
import {parseStage0CompactPayload,buildEarlyObservation} from '../../../r10_7_auth/src/v3-early-discovery.mjs';
import {applyEarlyCandidateBridge} from '../src/early-candidate-bridge.mjs';
import {buildRuntimeCanonicalBundle} from '../src/canonical-runtime-adapter.mjs';
const NOW=1_810_000_000_000;
class Stmt{constructor(sql,db){this.sql=sql;this.db=db;this.args=[];}bind(...a){this.args=a;return this;}async all(){if(this.sql.includes('FROM v3_market_microstructure_1m')){const [start,end,...contracts]=this.args;return{results:this.db.rows.filter(r=>r.bucket_ts>=start&&r.bucket_ts<=end&&contracts.includes(r.contract_code))};}return{results:[]};}}
class DB{constructor(){this.rows=[];}prepare(sql){return new Stmt(sql,this);}async batch(stmts){for(const s of stmts){if(!s.sql.includes('INSERT INTO v3_market_microstructure_1m'))continue;const a=s.args;this.rows.push({contract_code:a[0],venue:a[1],bucket_ts:a[2],price:a[3],mark:a[4],index_price:a[5],oi:a[6],oi_value_usdt:a[7],funding_rate:a[8],funding_interval_hours:a[9],bid:a[10],ask:a[11],top1_bid_usdt:a[12],top1_ask_usdt:a[13],top20_bid_usdt:a[14],top20_ask_usdt:a[15],imbalance:a[16],trade_count:a[17],taker_buy_usdt:a[18],taker_sell_usdt:a[19],delta_usdt:a[20],trade_notional_coverage_closed:a[21],top_account_ratio:a[22],top_position_ratio:a[23],book_gap_detected:a[24],coverage_json:a[25],observed_ts:a[26],persisted_ts:a[27],shadow_only:1});}return stmts.map(()=>({meta:{changes:1}}));}}
function payload(ts,{oi=1000,funding=-0.0001}={}){return JSON.stringify({schema:'stage0-compact-v2',timestamp:ts,contracts:[['BTC-USDT',50000,1e9,100000,5e9,0.0001,8,1,'CLOSED',false,false,0,0],['ETH-USDT',3000,5e8,90000,3e9,0.0001,8,1,'CLOSED',false,false,0,0],['MICRO-USDT',100,1_000_000,oi,1e7,funding,8,1,'CLOSED',false,false,0,0]]});}
function stage0Snapshots(){const out=[];for(let i=72;i>=0;i--){const ts=NOW-i*300000;const recentHour=i<=12;out.push(parseStage0CompactPayload(payload(ts,{oi:1000+(72-i)*2,funding:recentHour?-0.0001-(12-i)*0.00001:-0.0001}),ts));}return out;}
function stage0FeatureInputs(snapshots,contract,baseObservation,microInputs){const rows=[];for(const snap of snapshots){const r=snap?.rows?.get?.(contract);if(r?.data_status==='CLOSED')rows.push(r);}const price_series=rows.map(r=>({ts:r.ts,price:r.price,open:null,high:null,low:null,close:r.price}));const oi_series=rows.map(r=>({ts:r.ts,oi:r.oi_contracts}));const funding_series=rows.map(r=>({ts:r.ts,venue:'HTX',rate:r.funding_rate,interval_hours:r.funding_interval_hours}));const relative=baseObservation?.relative_strength||{};const relative_strength={...relative,coverage_closed:[relative.btc_1h_pct_points,relative.eth_1h_pct_points,relative.btc_4h_pct_points,relative.eth_4h_pct_points].some(Number.isFinite)};return{price_series,oi_series,funding_series,relative_strength,...microInputs};}
test('microstructure writer -> fresh load -> feature fusion -> early rank -> canonical/report reason',async()=>{const db=new DB();const rows=[];for(let i=0;i<14;i++){const ts=NOW-(13-i)*60000;for(const [venue,offset] of [['BYBIT',0],['GATE',0.01]])rows.push({contract_code:'MICRO-USDT',venue,bucket_ts:ts,price:100,mark:100.1,index:100,oi:1100+i,oi_value_usdt:1e7,funding_rate:-0.0002,funding_interval_hours:8,bid:99.99,ask:100.01,top20_bid_usdt:180000,top20_ask_usdt:80000,imbalance:.35,trade_count:20,taker_buy_usdt:800,taker_sell_usdt:1400,delta_usdt:-600,trade_notional_coverage_closed:true,top_account_ratio:1+i*.01+offset,top_position_ratio:1.1+i*.01+offset,book_gap_detected:false,observed_ts:ts});}
 const persisted=await persistMicrostructureMinute(db,rows,{persisted_ts:NOW});assert.equal(persisted.status,'CLOSED');const loaded=await loadMicrostructureForContracts(db,['MICRO-USDT'],{end_ts:NOW,lookback_ms:3600000});assert.equal(loaded.status,'CLOSED');assert.equal(loaded.rows.length,24);assert.equal(persisted.persisted,24);
 const snaps=stage0Snapshots();const base=buildEarlyObservation({contract:'MICRO-USDT',snapshots:snaps,now_ts:NOW});const microInputs=featureInputsFromMicrostructureRows(loaded.rows,{contract:'MICRO-USDT'});const obs=buildEarlyObservation({contract:'MICRO-USDT',snapshots:snaps,now_ts:NOW,feature_inputs:stage0FeatureInputs(snaps,'MICRO-USDT',base,microInputs)});assert.equal(obs.feature_fusion.status,'CLOSED');assert.ok(obs.evidence.some(x=>x.domain==='ORDERFLOW_ABSORPTION'));assert.equal(obs.direction_hint,'LONG');
 const scanRow={contract_code:'MICRO-USDT',data_status:'CLOSED',freshness:{stale:false,market_age_sec:5},quality:{market_present:true,oi_present:true,funding_present:true,history_available:true},symbol_fingerprint:{resolution_status:'RESOLVED_HTX_EXACT'},instrument_scope:{classification:'CRYPTO_CONFIRMED'},turnover_24h_usdt:1_000_000,transitions:{'24h':{price_change_pct:5}}};const earlyRow={contract_code:'MICRO-USDT',wave_id:'W-MICRO',last_seen_ts:NOW,feature_observed_ts:NOW,lifecycle_stage:'DISCOVERY',early_detection_quality_0_100:obs.early_detection_quality_0_100,long_evidence_domain_count:obs.long_evidence_domain_count,short_evidence_domain_count:obs.short_evidence_domain_count,direction_hint:obs.direction_hint,shadow_only:1,feature_json:JSON.stringify({feature_fusion:obs.feature_fusion}),evidence_json:JSON.stringify(obs.evidence)};
 const bridged=applyEarlyCandidateBridge({discovery_prefilter:{shortlist:[],counts:{},parameters:{max_shortlist:24}},scan:{timestamp:NOW,contracts:[scanRow]},deep_check_queue:{queue:[{contract:'MICRO-USDT'}]},early_rows:[earlyRow],now:NOW});const d=bridged.shortlist[0];assert.equal(d.microstructure_priority_confirmed,true);assert.ok(d.microstructure_priority_domains.includes('ORDERFLOW_ABSORPTION'));
 const bundle=buildRuntimeCanonicalBundle({contract:'MICRO-USDT',run_id:'R-MICRO',snapshot_id:'S-MICRO',observed_ts:NOW,discovery_row:d,opportunity:{newest_event:{event_id:'E',timeframe:'15m',minute_decomposition:{classification_allowed:true,one_minute_bars:15}}},publication_shadow:{entry_signal:{state:'OBSERVE'},score_interval:{score_lower_bound:60}},public_evidence:{evidence:[]},liquidation_intelligence:{projected_clusters:[]},data_sufficiency:{classification:'PARTIAL'}});assert.equal(bundle.canonical.microstructure.status,'CLOSED');assert.ok(bundle.canonical.reasons.some(x=>x.label==='Микроструктурные подтверждения'));assert.match(bundle.telegram.message,/Микроструктурные подтверждения:/);assert.match(bundle.manual.text,/ПРИЧИНЫ/);});
