import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
const root=path.resolve(process.argv[2]||'runtime'),phase=process.argv[3]||'evidence',output=path.resolve(process.argv[4]||`audit-${phase}.json`),load=rel=>import(pathToFileURL(path.join(root,rel)).href);
const {RemoteD1Database}=await load('report2-d1-adapter.mjs'),db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN,{fetchImpl:globalThis.fetch,timeoutMs:45000});
const run_id=`SOURCE_AUDIT:${process.env.GITHUB_RUN_ID||Date.now()}:${phase}`,now=Date.now(),records=[];let sourceCalls=0;
const {createUnifiedHttpBudget}=await load('src/unified-budget.mjs'),budget=createUnifiedHttpBudget();
function checkDb(){const usage=db.usageSnapshot();if(usage.rows_read>30000||usage.rows_written>480||usage.unknown_ops>0)throw Error('AUDIT_DB_HEADROOM_NOT_CLOSED');}
const fetch_impl=async(url,init)=>{const host=new URL(String(url)).hostname;if(/telegram|t\.me/i.test(host))throw Error('TELEGRAM_NETWORK_PROHIBITED');if(sourceCalls>=28)throw Error('AUDIT_SOURCE_HTTP_CAP_EXHAUSTED');sourceCalls++;return globalThis.fetch(url,init);};
const compact=result=>({status:result?.status??'NOT_CLOSED',reason:result?.reason??result?.error??null,network_calls:result?.network_calls??null,cache_status:result?.cache_status??null,summary:result?.summary??null,
 evidence:(result?.evidence||[]).map(r=>({provider_id:r.provider_id,block_id:r.block_id,metric_family:r.metric_family,source_ts:r.source_ts,observed_ts:r.observed_ts,first_known_ts:r.first_known_ts,expires_at:r.expires_at,coverage_status:r.coverage_status,coverage_fraction:r.coverage_fraction,identity_status:r.identity_status,finality_status:r.finality_status,validation_status:r.validation_status,directional_strength:r.directional_strength,risk_strength:r.risk_strength})),
 receipts:result?.receipts??[],admission:result?.admission??null,whole_job_admission:result?.whole_job_admission??null,source_details:result?.sources??null,transport_receipts:result?.receipts??null,internal_only:result?.internal_only??true});
async function capture(source,contract,action,consumer=null){checkDb();const start=Date.now(),before=sourceCalls;let result;try{result=await action();}catch(error){result={status:'CODE_OR_STORE_ERROR',error:String(error?.message||error).slice(0,240),network_calls:sourceCalls-before};}
 const row={source,contract,started_ts:start,completed_ts:Date.now(),actual_http:sourceCalls-before,result:compact(result),consumer:consumer?await consumer(result):null};records.push(row);console.log(JSON.stringify({source,contract,status:row.result.status,actual_http:row.actual_http,consumer:row.consumer}));return result;}
const refResponse=await fetch_impl('https://api.hbdm.com/v2/linear-swap-ex/market/detail/batch_merged'),refPayload=refResponse.ok?await refResponse.json():null;const priceRows=Array.isArray(refPayload?.ticks)?refPayload.ticks:[];const prices=new Map(priceRows.filter(r=>typeof r.contract_code==='string'&&Number(r.close)>0).map(r=>[r.contract_code,Number(r.close)]));
if(phase==='evidence'){
 const {compileOfficialSourceRegistry}=await load('src/official-source-registry.mjs'),compiled=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'official-event-sources.json')))),entry=compiled.registry.LDO;
 if(!entry)throw Error('EXACT_LDO_REGISTRY_REQUIRED');
 const common={db,fetch_impl,request_admit:budget.reserve,run_id,now,contract:'LDO-USDT',asset_identity:{chain:entry.chain,contract_or_mint:entry.contract_or_mint},asset_metadata:entry}, {validateEvidenceV2}=await load('src/evidence-v2.mjs');
 const consumer=result=>{const rows=result?.evidence||[],ts=Date.now();return{validator:'EvidenceV2.1',observed_facts:rows.length,admissible_facts:rows.filter(r=>validateEvidenceV2(r,{decision_ts:ts}).usable&&Number(r.coverage_fraction)>0).length,score_changed:false};};
 const plans=[['HTX_PUBLIC_RISK','htx-public-risk-evidence.mjs','collectHtxPublicRiskEvidence',{contract:'TAO-USDT'}],['MACRO_CALENDAR','macro-calendar-evidence.mjs','collectMacroCalendarEvidence',{}],['CHAIN_RPC','chain-supply-evidence.mjs','collectChainSupplyEvidence',{}],['OFFICIAL_EVENTS','official-events-evidence.mjs','collectOfficialEventsEvidence',{}],['SNAPSHOT_GOVERNANCE','snapshot-governance-evidence.mjs','collectSnapshotGovernanceEvidence',{asset_metadata:{...entry,snapshot_space:entry.snapshot_space||'lido-snapshot.eth'}}],['SOURCIFY_ABI','sourcify-abi-evidence.mjs','collectSourcifyAbiEvidence',{}],['BLUESKY_PUBLIC','bluesky-attention-evidence.mjs','collectBlueskyAttentionEvidence',{}],['GDELT_NEWS_DISCOVERY','gdelt-official-discovery.mjs','collectGdeltOfficialDiscovery',{contract:'LINK-USDT',asset_metadata:{official_name:'Chainlink',official_domains:['chain.link']}}],['DERIBIT_ALT_OPTIONS','deribit-alt-options-evidence.mjs','collectDeribitAltOptionsEvidence',{contract:'SOL-USDT'}],['BLOCKSCOUT_INDEX','blockscout-index-evidence.mjs','collectBlockscoutIndexEvidence',{blockscout_api_key:process.env.BLOCKSCOUT_PRO_API_KEY||''}]];
 for(const [source,file,fn,overrides] of plans){const module=await load(`src/${file}`),p={...common,...overrides,run_id:`${run_id}:${source}`,now:Date.now()};await capture(source,p.contract,()=>module[fn](p),consumer);}
}else if(phase==='liquidation'||phase==='native-roles'){
 const {loadLiquidationVenueCatalog}=await load('src/liquidation-extension/venue-catalog-cache.mjs'),catalog=await capture('NATIVE_VENUE_CATALOG','SOL-USDT',()=>loadLiquidationVenueCatalog({db,fetch_impl,now}));
 const {createD1SourceAdmission}=await load('src/liquidation-extension/d1-source-admission.mjs'),{LIQUIDATION_ALLOWANCE_GENERATION}=await load('src/liquidation-extension/install-source-allowances.mjs');
 const allowances=await db.prepare(`SELECT provider,scope_id,config_fingerprint FROM report2_liq_source_allowance_shadow WHERE active=1 AND window_start_ts<=?1 AND window_end_ts>?1 AND scope_id LIKE ?2`).bind(Date.now(),`${LIQUIDATION_ALLOWANCE_GENERATION}:%`).all(),scope_bindings={};for(const row of allowances.results||[])scope_bindings[row.provider]={scope_id:row.scope_id,config_fingerprint:row.config_fingerprint};
 const provider_admit=createD1SourceAdmission({db,scope_bindings,within_run_budget:()=>{const u=db.usageSnapshot();return{allowed:u.rows_read+64<34000&&u.rows_written+16<560&&u.unknown_ops===0};}}),{createCombinedLiquidationService}=await load('src/liquidation-extension/combined-runner-service.mjs'),{createLiquidationSourceWeightStore}=await load('src/liquidation-source-weighting.mjs'),{attachNativeContext}=await load('src/liquidation-extension/runtime-bridge.mjs'),{buildDynamicLiquidationPanel}=await load('src/dynamic-liquidation-panel.mjs');
 const {loadOxArchiveReadiness}=await load('src/oxarchive-cost-probe.mjs'),oxReadiness=await loadOxArchiveReadiness({db,api_key:process.env.OXARCHIVE_API_KEY||''});
 const require=createRequire(path.join(root,'src/liquidation-extension/package.json')),sdk_loader=()=>({version:require('@gainsnetwork/sdk/package.json').version,sdk:require('@gainsnetwork/sdk')});
 for(const [mode,cap,contract,onlyRole] of (phase==='native-roles'?[['FULL',5,'SOL-USDT','GTRADE'],['LIQUIDATION_ONLY',8,'SOL-USDT','GTRADE'],['FULL',5,'SOL-USDT','HYPERLIQUID'],['LIQUIDATION_ONLY',8,'SOL-USDT','HYPERLIQUID']]:[['FULL',5,'SOL-USDT',null],['LIQUIDATION_ONLY',8,'ARB-USDT',null]])){
  const base=contract.replace('-USDT',''),service=createCombinedLiquidationService({mode:'SHADOW_ONLY',provider_admit:onlyRole?async req=>Object.keys(req.requests||{}).every(p=>onlyRole==='GTRADE'?p==='GTRADE':['HYPERLIQUID','LIQFLOW'].includes(p))?provider_admit(req):{allowed:false,status:'AUDIT_SEPARATE_PROVIDER_ROLE',reserved:false,quota_reserved:false}:provider_admit,secondary_enabled:onlyRole!=='HYPERLIQUID',fetch_impl,sdk_loader,max_http_per_run:cap,liqflow_key:process.env.LIQFLOW_API_KEY||'',oxarchive_config:{api_key:process.env.OXARCHIVE_API_KEY||'',db,readiness:oxReadiness},source_weight_store:createLiquidationSourceWeightStore({db})}),params={contract,native_symbol:base,run_id:`${run_id}:${mode}:${onlyRole||"DEFAULT"}`,deep_started_ts:Date.now(),max_deep_ms:45000,source_identity:onlyRole?{}:catalog?.entries?.[base]||{}};
  const acquisition=await capture(`COMBINED_${mode}_${onlyRole||"DEFAULT"}`,contract,async()=>{const result=await service.collect(params),summary=service.summary();return{status:result?'ACQUISITION_RETURNED':'NOT_CLOSED',network_calls:summary.shared_budget.actual_http,summary,acquisition:result};},result=>{if(!result.acquisition)return{status:'NO_ACQUISITION',entry_authorization:false};if(!prices.get(contract))return{status:'CURRENT_HTX_REFERENCE_REQUIRED',entry_authorization:false};const bound=attachNativeContext({},result.acquisition,{contract,run_id:params.run_id,snapshot_id:`AUDIT:${params.run_id}`,observed_ts:Date.now(),direction:null}),panel=buildDynamicLiquidationPanel({contexts:[bound.native_extension,...(bound.independent_extensions||[])].filter(Boolean),reference_price:prices.get(contract),observed_ts:Date.now()});return{binding_status:bound?.multi_source_extension?.status??bound?.native_extension?.status??null,panel_status:panel.status,target_eligible_clusters:(panel.clusters||[]).filter(x=>x.decision_target_eligible).length,reference_price_source:'HTX_OFFICIAL_BATCH_MERGED',entry_authorization:false};});
 }
 if(phase==='liquidation'){const {createRunnerLiquidationExtension}=await load('src/liquidation-extension/runner-extension.mjs'),native=createRunnerLiquidationExtension({mode:'SHADOW_ONLY',admit:provider_admit,fetch_impl,max_http_per_run:5,liqflow_key:process.env.LIQFLOW_API_KEY||''});
 await capture('HYPERLIQUID_LIQFLOW_NATIVE','SOL-USDT',async()=>{const result=await native.collect({contract:'SOL-USDT',native_symbol:'SOL',run_id:`run_id:HL:${run_id}`,deep_started_ts:Date.now()});return{status:native.summary().records.at(-1)?.status||'NOT_CLOSED',summary:native.summary(),network_calls:result?.provenance?.transport_count??null};});}
}else if(phase==='markets'){
 const {collectCrossExchangeRiskContext}=await load('src/cross-exchange-risk-context.mjs'),{loadGlobalMarketContext}=await load('src/global-market-context.mjs'),{collectSupplementalCandidateContext}=await load('src/supplemental-candidate-context.mjs'),{createShadowMarketPilot}=await load('src/shadow-market-pilot.mjs');
 await capture('GLOBAL_DERIBIT_COINLOBSTER','BTC_ETH_BACKGROUND',()=>loadGlobalMarketContext({db,fetch_impl,now:Date.now()}));
 for(const lane of ['HISTORY','DEPTH','REALIZED'])await capture(`CROSS_EXCHANGE_${lane}`,'TAO-USDT',()=>collectCrossExchangeRiskContext({db,fetch_impl,contract:'TAO-USDT',run_id:`${run_id}:${lane}`,now:Date.now(),reference_price:prices.get('TAO-USDT')??null,coinalyze_api_key:process.env.COINALYZE_API_KEY||'',lane_override:lane,realized_sample_ms:6000}),result=>({status:result.status,sources:result.sources,reference_price_source:'HTX_OFFICIAL_BATCH_MERGED',entry_authorization:false}));
 const {collectGateLiquidationHistory}=await load('src/gate-liquidation-history.mjs');await capture('GATE_LIQUIDATION_HISTORY_DIRECT','TAO-USDT',()=>collectGateLiquidationHistory({db,fetch_impl,contract:'TAO-USDT',run_id:`${run_id}:GATE_DIRECT`,now:Date.now(),max_http:2}),r=>({status:r.status,exact_identity:r.exact_identity,original_source_ts:r.source_ts,unit:r.unit,entry_authorization:false}));
 const pilot=createShadowMarketPilot({fetch_impl,admit:({provider_id,requests})=>budget.reserve({logical_request_id:`${run_id}:${provider_id}`,lane:'background',attempts:requests})});
 for(const [provider_id,identity_map] of [['KRAKEN_FUTURES',{BTC:'PF_XBTUSD',ETH:'PF_ETHUSD'}],['DYDX_INDEXER',{BTC:'BTC-USD',ETH:'ETH-USD'}]])await capture(provider_id,'BTC_ETH_BACKGROUND',()=>pilot.collect({provider_id,run_id,identity_map}),r=>({schema_status:r.schema_status,coverage_status:r.coverage_status,mapped_markets:r.markets,mode:'SHADOW',score_changed:false}));
}else if(phase==='sector'){
 const {compileOfficialSourceRegistry}=await load('src/official-source-registry.mjs'),official=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'official-event-sources.json'))));const entry=official.registry.LINK;
 const {collectCoinpaprikaSectorEvidence}=await load('src/coinpaprika-sector-evidence.mjs'),{consumeEvidenceV2}=await load('src/evidence-v2.mjs');
 await capture('COINPAPRIKA_SECTOR','LINK-USDT',()=>collectCoinpaprikaSectorEvidence({db,fetch_impl,request_admit:budget.reserve,contract:'LINK-USDT',run_id,now:Date.now(),asset_identity:{chain:entry.chain,contract_or_mint:entry.contract_or_mint},asset_metadata:{coinpaprika_id:'link-chainlink',sector_tag:'blockchain-service'}}),r=>({current_htx_market_present:prices.has('LINK-USDT'),actual_score_consumer:consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:Date.now()}),entry_authorization:false}));
}else if(phase==='chain-events'){
 const {compileOfficialSourceRegistry}=await load('src/official-source-registry.mjs'),official=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'official-event-sources.json'))));
 const {collectFinalizedChainEvents}=await load('src/finalized-chain-events.mjs'),{collectChainSupplyEvidence}=await load('src/chain-supply-evidence.mjs'),{consumeEvidenceV2,validateEvidenceV2}=await load('src/evidence-v2.mjs');
 for(const [base,mode] of [['LDO','TOKEN_TRANSFER'],['LINK','AAVE_CREDIT'],['JUP','SUPPLY']]){
  const entry=official.registry[base];if(!entry)throw Error('VERIFIED_IDENTITY_REQUIRED');const contract=`${base}-USDT`,p={db,fetch_impl,request_admit:budget.reserve,run_id:`${run_id}:${base}:${mode}`,now:Date.now(),contract,asset_identity:{chain:entry.chain,contract_or_mint:entry.contract_or_mint}};
  await capture(`FINALIZED_${mode}`,contract,()=>mode==='SUPPLY'?collectChainSupplyEvidence(p):collectFinalizedChainEvents({...p,event_mode:mode}),r=>({status:r.status,current_htx_market_present:prices.has(contract),evidence_validator_receipts:(r.evidence||[]).map(row=>validateEvidenceV2(row,{decision_ts:Date.now()})),actual_score_consumer:consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:Date.now()}),entry_authorization:false}));
 }
}else if(phase==='market-coverage'){
 const {collectCrossExchangeRiskContext,loadVenueCatalog}=await load('src/cross-exchange-risk-context.mjs');
 await capture('CEX_CATALOG_WITH_FAILURE_RECEIPTS','GLOBAL',()=>loadVenueCatalog({db,fetch_impl,now:Date.now()}));
 for(const contract of ['SOL-USDT','LINK-USDT'])await capture('CROSS_EXCHANGE_DEPTH_ALL_VENUES',contract,()=>collectCrossExchangeRiskContext({db,fetch_impl,contract,run_id:`${run_id}:${contract}`,now:Date.now(),reference_price:prices.get(contract)??null,lane_override:'DEPTH'}),r=>({status:r.status,sources:r.sources,entry_authorization:false}));
 const endpoints=[['BYBIT_PUBLIC_ANNOUNCEMENTS','https://api.bybit.com/v5/announcements/index?locale=en-US&limit=5'],['COINGECKO_CATEGORY_DIRECTORY','https://api.coingecko.com/api/v3/coins/categories/list']];
 for(const [source,url] of endpoints)await capture(source,'DISCOVERY_ONLY',async()=>{const grant=budget.reserve({logical_request_id:`${run_id}:${source}`,lane:'background',attempts:1});if(!grant.allowed)return{status:grant.status,network_calls:0};const res=await fetch_impl(url),raw=await res.json().catch(()=>null),rows=source==='BYBIT_PUBLIC_ANNOUNCEMENTS'?raw?.result?.list:raw;return{status:res.ok&&Array.isArray(rows)&&rows.length?'RAW_SCHEMA_AVAILABLE':'SOURCE_NOT_CLOSED',network_calls:1,summary:{http_status:res.status,row_count:Array.isArray(rows)?rows.length:null,rows:Array.isArray(rows)?rows.slice(0,5):null,raw_available_is_not_production_connection:true,free_auth_probe_only:true}};},r=>({status:'NOT_CONNECTED_TO_REPORT',entry_authorization:false}));
}else if(phase==='supplemental'){
 const {collectSupplementalCandidateContext,chooseSupplementalLane,parseSupplementalIdentityRegistry}=await load('src/supplemental-candidate-context.mjs'),{compileOfficialSourceRegistry,mergeOfficialAndConfiguredRegistries}=await load('src/official-source-registry.mjs'),official=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'official-event-sources.json')))),merged=mergeOfficialAndConfiguredRegistries({official,configured:process.env.REPORT2_SUPPLEMENTAL_IDENTITY_REGISTRY_JSON||'{}'}),registry=merged.registry,parsed=parseSupplementalIdentityRegistry(registry);
 const plans=[['JUP-USDT','DEX_RISK']];for(const [base,entry] of Object.entries(parsed.entries)){if(entry.identity?.chain==='solana')plans.push([`${base}-USDT`,'DEX_RISK']);if(entry.protocol_slug)plans.push([`${base}-USDT`,'PROTOCOL']);}
 for(const [contract,wanted] of plans.filter((p,i,a)=>a.findIndex(x=>x[0]===p[0]&&x[1]===p[1])===i).slice(0,6)){const base=contract.replace('-USDT',''),manual=parsed.entries[base]||{};const entry={...manual,base,coinbase_product:manual.coinbase_product||`${base}-USD`};let seed=null;for(let i=0;i<40;i++){const candidate=`${run_id}:${wanted}:${i}`;if(chooseSupplementalLane({run_id:candidate,contract,entry,derivatives_venues:0,critical_conflict:true})===wanted){seed=candidate;break;}}if(!seed){records.push({source:wanted,contract,result:{status:'NOT_APPLICABLE',reason:'EXACT_CONFIGURED_ROLE_REQUIRED'},actual_http:0});continue;}await capture(wanted,contract,()=>collectSupplementalCandidateContext({db,fetch_impl,registry,contract,run_id:seed,primary_price:prices.get(contract)??null,derivatives_venues:0,critical_conflict:true,now:Date.now()}),r=>{if(r.lane&&r.lane!==wanted)throw Error(`AUDIT_ROLE_MISMATCH:${wanted}:${r.lane}`);return {requested_lane:wanted,lane:r.lane,status:r.status,sources:r.sources,identity_status:r.identity_status};});}
}else throw Error('AUDIT_PHASE_UNKNOWN');
const usage=db.usageSnapshot(),result={schema:'report2-bounded-live-source-audit-v1',captured_at:new Date().toISOString(),run_id,phase,github_head:process.env.GITHUB_SHA,records,actual_source_http:sourceCalls,max_source_http:28,whole_job_budget:budget.summary(),database_usage:usage,telegram_calls:0,trade_calls:0,secrets_included:false,all_sources_working:false};
fs.writeFileSync(output,JSON.stringify(result,null,2)+'\n');if(usage.rows_written>560||usage.rows_read>34000||usage.unknown_ops>0||sourceCalls>28)throw Error('AUDIT_ENVELOPE_NOT_CLOSED');

