import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
const root=new URL('../',import.meta.url);
const runtime=new URL('../test-runtime/src/',import.meta.url);
const {persistCanonicalSnapshot,renderCanonicalTelegram,renderCanonicalManual,canonicalFingerprint}=await import(new URL('canonical-publication.mjs',runtime));
const {reconcilePendingPublications}=await import(new URL('publication-reconciler.mjs',runtime));
const {runBoundTelegramDeliverySidecar,HEALTH_ALERT_CONFIRM_MS}=await import(new URL('bound-telegram-delivery-sidecar.mjs',runtime));
function norm(sql,args){const picks=[];const q=String(sql).replace(/\?(\d+)/g,(_,n)=>{picks.push(Number(n)-1);return '?';});return picks.length?[q,picks.map(i=>args[i])]:[sql,args];}
class Prep{constructor(owner,sql,args=[]){this.owner=owner;this.sql=sql;this.args=args;}bind(...args){return new Prep(this.owner,this.sql,args);}async first(){const [q,a]=norm(this.sql,this.args);const r=this.owner.db.prepare(q).get(...a)??null;this.owner.read(r?1:0);return r;}async all(){const [q,a]=norm(this.sql,this.args);const r=this.owner.db.prepare(q).all(...a);this.owner.read(r.length);return {results:r};}async run(){const [q,a]=norm(this.sql,this.args);const r=this.owner.db.prepare(q).run(...a);const c=Number(r.changes||0);this.owner.write(c);return {meta:{changes:c}};}}
class DB{constructor(){this.db=new DatabaseSync(':memory:');this.u={requests:0,rows_read:0,rows_written:0,unknown_ops:0};}prepare(sql){return new Prep(this,sql);}read(n){this.u.requests++;this.u.rows_read+=Number(n||0);}write(n){this.u.requests++;this.u.rows_written+=Number(n||0);}usageSnapshot(){return structuredClone(this.u);}async batch(stmts){const out=[];this.db.exec('BEGIN');try{for(const s of stmts){const [q,a]=norm(s.sql,s.args);if(/^\s*(SELECT|PRAGMA)/i.test(q)){const r=this.db.prepare(q).all(...a);this.read(r.length);out.push({results:r});}else{const r=this.db.prepare(q).run(...a);const c=Number(r.changes||0);this.write(c);out.push({meta:{changes:c}});}}this.db.exec('COMMIT');return out;}catch(e){this.db.exec('ROLLBACK');throw e;}}}
function schema(d){d.db.exec(fs.readFileSync(new URL('migrations.sql',root),'utf8'));d.db.exec(`
CREATE TABLE v3_user_lifecycle_shadow(contract TEXT,direction TEXT,wave_id TEXT,rules_version TEXT,status TEXT,reason TEXT,observation_ts INTEGER,valid_until_ts INTEGER,updated_ts INTEGER,shadow_only INTEGER,PRIMARY KEY(contract,direction,wave_id,rules_version));
CREATE TABLE v3_telegram_dispatch_shadow(dispatch_id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE,contract TEXT,direction TEXT,wave_id TEXT,lifecycle_event TEXT,rules_version TEXT,state TEXT,decision_id TEXT,message_hash TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);
CREATE TABLE v3_pipeline_health_shadow(namespace TEXT PRIMARY KEY,status TEXT,reasons_json TEXT,changed_ts INTEGER,last_checked_ts INTEGER,shadow_only INTEGER);
CREATE TABLE v3_pipeline_health_event_shadow(event_id TEXT PRIMARY KEY,transition TEXT,from_status TEXT,to_status TEXT,reasons_json TEXT,state TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);
`);}
function canonical({now=1790448000000,overall=76,interest=73,dir='LONG',state='WAIT_FOR_TRIGGER'}={}){const c={version:'fixture',status:'CLOSED',snapshot_id:'snap-1',run_id:'run-1',observed_ts:now,snapshot_time_utc:new Date(now).toISOString(),universe:[{contract:'RAY-USDT'}],candidates:[{contract:'RAY-USDT',ticker:'RAY-USDT'}],state,direction:dir,scores:{overall_0_100:overall,coin_interest_0_100:interest,entry_readiness_0_100:null,is_probability:false},reasons:[],source_receipts:[{metric:'HTX OI 1h',venue:'HTX',value:2.1,unit:'%',window_start_ts:now-3600000,window_end_ts:now,source_ts:now}],hard_gates:[{gate:'HTX_EXECUTION',status:'CLOSED'}],current_price:1.5,entry:null,trigger:{metric:'price',operator:'>=',value:1.55,unit:'USDT',timeframe:'5m',cancel_condition:'price<1.42',expires_ts:now+1800000,next_recheck_ts:now+300000},invalidation:'price<1.42',targets:[],costs:null,early_candidate:null,opportunity:null,microstructure:null,liquidations:{above:[{price:1.7,distance_pct:13.3,selection_role:'LARGEST_DISTANT',liquidated_side:'SELLERS'}],below:[]},data_quality:null,free_sources:null,changes_from_previous:[],metadata:{contract:'RAY-USDT'},safety:{strategy_weights_changed:false,hard_gates_bypassed:false,automatic_execution:false,validated_signal:false}};c.analytical_fingerprint=canonicalFingerprint({...c,analytical_fingerprint:undefined});return c;}
async function seedActionable(d,{now=1790448000000}={}){const c=canonical({now});const p=await persistCanonicalSnapshot(d,{canonical:c,contract:'RAY-USDT',direction:'LONG',wave_id:'W1',decision_id:null,now_ts:now});assert.equal(p.persisted,true);d.db.prepare(`INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1)`).run('RAY-USDT','LONG','W1','v3','WAIT','DIRECTION_CLOSED_ENTRY_WINDOW_NOT_READY',now,now+1800000,now);d.db.prepare(`INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,decision_id,message_hash,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)`).run('D1','K1','RAY-USDT','LONG','W1','WAIT','v3','PENDING',null,null,now,now);const rec=await reconcilePendingPublications(d,{now_ts:now});assert.equal(rec.results[0].status,'BOUND_ACTIONABLE');return {c,p};}
test('network sends exact persisted canonical Telegram text and never reconstructs market facts',async()=>{const d=new DB();schema(d);const now=1790448000000;const {p}=await seedActionable(d,{now});const stored=d.db.prepare(`SELECT telegram_text FROM canonical_publication_shadow WHERE publication_id=?`).get(p.publication_id).telegram_text;let body=null;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://relay.invalid',relay_key:'x',now_ts:now+1000,fetch_impl:async(_u,o)=>{body=JSON.parse(o.body);return{ok:true,status:200,json:async()=>({ok:true,status:'SENT',message_id:991})};}});assert.equal(r.sent,1);assert.equal(body.text,stored);assert.equal(d.db.prepare(`SELECT state,telegram_message_id FROM v3_telegram_dispatch_shadow WHERE idempotency_key='K1'`).get().state,'SENT');assert.ok(r.usage_delta);assert.ok(r.usage_delta.rows_read<=320);assert.ok(r.usage_delta.rows_written<=32);assert.ok(r.usage_delta.requests<=48);});
test('retry/dedup does not send a SENT dispatch twice',async()=>{const d=new DB();schema(d);const now=1790448000000;await seedActionable(d,{now});let calls=0;const fetch_impl=async()=>{calls++;return{ok:true,status:200,json:async()=>({ok:true,message_id:1})}};await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now+1000,fetch_impl});await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now+2000,fetch_impl});assert.equal(calls,1);});
test('tampered persisted Telegram text is rejected before network',async()=>{const d=new DB();schema(d);const now=1790448000000;const {p}=await seedActionable(d,{now});d.db.prepare(`UPDATE canonical_publication_shadow SET telegram_text=telegram_text||'\nTAMPER' WHERE publication_id=?`).run(p.publication_id);let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now+1000,fetch_impl:async()=>{calls++;throw new Error('must not send')}});assert.equal(calls,0);assert.equal(r.lifecycle[0].status,'FAILED_FINAL');});
test('wrong lifecycle snapshot/state is rejected before network',async()=>{const d=new DB();schema(d);const now=1790448000000;await seedActionable(d,{now});d.db.prepare(`UPDATE v3_user_lifecycle_shadow SET status='IDEA_REMOVED' WHERE contract='RAY-USDT'`).run();let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now+1000,fetch_impl:async()=>{calls++;throw new Error('must not send')}});assert.equal(calls,0);assert.equal(d.db.prepare(`SELECT state,last_error FROM v3_telegram_dispatch_shadow WHERE idempotency_key='K1'`).get().state,'FAILED_FINAL');});
test('manual and Telegram artifacts share one canonical fingerprint',async()=>{const d=new DB();schema(d);const now=1790448000000;const {c,p}=await seedActionable(d,{now});const row=d.db.prepare(`SELECT analytical_fingerprint,manual_text,telegram_text FROM canonical_publication_shadow WHERE publication_id=?`).get(p.publication_id);assert.equal(row.analytical_fingerprint,c.analytical_fingerprint);assert.match(row.manual_text,/Общая оценка: 76 из 100/);assert.match(row.telegram_text,/Общая оценка: 76 из 100/);});

function seedHealth(d,{now=1790482834676,transition='DEGRADED',age_ms=0,latest_sent_transition=null,current_status=null}={}){
 const created=now-age_ms;
 const to=current_status||(transition==='DEGRADED'?'DEGRADED_PIPELINE':'HEALTHY_NO_IDEA');
 const from=transition==='DEGRADED'?'HEALTHY_NO_IDEA':'DEGRADED_PIPELINE';
 d.db.prepare(`INSERT INTO v3_pipeline_health_shadow(namespace,status,reasons_json,changed_ts,last_checked_ts,shadow_only) VALUES('PIPELINE',?,?,?,?,1)`).run(to,to==='DEGRADED_PIPELINE'?JSON.stringify(['CRITICAL_FEED_DEGRADED']):'[]',created,now);
 if(latest_sent_transition){
   const prevTo=latest_sent_transition==='DEGRADED'?'DEGRADED_PIPELINE':'HEALTHY_NO_IDEA';
   const prevFrom=latest_sent_transition==='DEGRADED'?'HEALTHY_NO_IDEA':'DEGRADED_PIPELINE';
   d.db.prepare(`INSERT INTO v3_pipeline_health_event_shadow(event_id,transition,from_status,to_status,reasons_json,state,telegram_message_id,last_error,created_ts,updated_ts,sent_ts,shadow_only) VALUES(?,?,?,?,?,'SENT','777','SENT',?,?,?,1)`).run('H-PREV',latest_sent_transition,prevFrom,prevTo,latest_sent_transition==='DEGRADED'?JSON.stringify(['CRITICAL_FEED_DEGRADED']):'[]',created-60000,created-60000,created-60000);
 }
 d.db.prepare(`INSERT INTO v3_pipeline_health_event_shadow(event_id,transition,from_status,to_status,reasons_json,state,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,'PENDING',?,?,1)`).run('H-CUR',transition,from,to,transition==='DEGRADED'?JSON.stringify(['CRITICAL_FEED_DEGRADED']):'[]',created,created);
}
test('transient technical degradation is debounced and never reaches Telegram before 20 minutes',async()=>{const d=new DB();schema(d);const now=1790482834676;seedHealth(d,{now,transition:'DEGRADED',age_ms:HEALTH_ALERT_CONFIRM_MS-1});let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now,fetch_impl:async()=>{calls++;throw new Error('must not send')}});assert.equal(calls,0);assert.equal(r.health[0].status,'DEBOUNCE_PENDING');assert.equal(d.db.prepare(`SELECT state FROM v3_pipeline_health_event_shadow WHERE event_id='H-CUR'`).get().state,'PENDING');});
test('persistent technical degradation is sent only after debounce window',async()=>{const d=new DB();schema(d);const now=1790482834676;seedHealth(d,{now,transition:'DEGRADED',age_ms:HEALTH_ALERT_CONFIRM_MS+1});let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now,fetch_impl:async()=>{calls++;return{ok:true,status:200,json:async()=>({ok:true,status:'SENT',message_id:778})}}});assert.equal(calls,1);assert.equal(r.health[0].status,'SENT');assert.equal(r.health[0].confirmed_persistent,true);});
test('recovery is not sent when user never saw a degradation alert',async()=>{const d=new DB();schema(d);const now=1790483998964;seedHealth(d,{now,transition:'RECOVERED',age_ms:HEALTH_ALERT_CONFIRM_MS+1});let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now,fetch_impl:async()=>{calls++;throw new Error('must not send')}});assert.equal(calls,0);assert.equal(r.health[0].reason,'RECOVERY_WITHOUT_VISIBLE_DEGRADATION');const row=d.db.prepare(`SELECT state,last_error FROM v3_pipeline_health_event_shadow WHERE event_id='H-CUR'`).get();assert.equal(row.state,'FAILED_FINAL');assert.equal(row.last_error,'RECOVERY_WITHOUT_VISIBLE_DEGRADATION');});
test('recovery is sent only after a previously visible persistent degradation',async()=>{const d=new DB();schema(d);const now=1790483998964;seedHealth(d,{now,transition:'RECOVERED',age_ms:HEALTH_ALERT_CONFIRM_MS+1,latest_sent_transition:'DEGRADED'});let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now,fetch_impl:async()=>{calls++;return{ok:true,status:200,json:async()=>({ok:true,status:'SENT',message_id:779})}}});assert.equal(calls,1);assert.equal(r.health[0].status,'SENT');});
test('superseded health event is terminally closed instead of remaining pending forever',async()=>{const d=new DB();schema(d);const now=1790483998964;seedHealth(d,{now,transition:'DEGRADED',age_ms:HEALTH_ALERT_CONFIRM_MS+1});d.db.prepare(`UPDATE v3_pipeline_health_shadow SET status='HEALTHY_NO_IDEA',reasons_json='[]',last_checked_ts=? WHERE namespace='PIPELINE'`).run(now);let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://r',relay_key:'x',now_ts:now,fetch_impl:async()=>{calls++;throw new Error('must not send')}});assert.equal(calls,0);assert.equal(r.health[0].reason,'SUPERSEDED_HEALTH_STATE');assert.equal(d.db.prepare(`SELECT state FROM v3_pipeline_health_event_shadow WHERE event_id='H-CUR'`).get().state,'FAILED_FINAL');});
