import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {canonicalFingerprint,assessActionability,persistCanonicalSnapshot,finalizePublication,bindDispatchToPublication,loadBoundTelegram,loadExactManual} from '../src/canonical-publication.mjs';
import {enqueueRecheck,claimDueRecheck,completeRecheck,dueByLastSuccess,analyticsOwner} from '../src/recheck-scheduler.mjs';
class St{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...a){return new St(this.db,this.sql,a);}async run(){const q=this.sql.replace(/\?(\d+)/g,(_,n)=>'?'),order=[];this.sql.replace(/\?(\d+)/g,(_,n)=>{order.push(Number(n)-1);return _;});const args=order.length?order.map(i=>this.args[i]):this.args;const r=this.db.prepare(q).run(...args);return {meta:{changes:Number(r.changes||0)}};}async first(){const q=this.sql.replace(/\?(\d+)/g,(_,n)=>'?'),order=[];this.sql.replace(/\?(\d+)/g,(_,n)=>{order.push(Number(n)-1);return _;});const args=order.length?order.map(i=>this.args[i]):this.args;return this.db.prepare(q).get(...args)??null;}async all(){const q=this.sql.replace(/\?(\d+)/g,(_,n)=>'?'),order=[];this.sql.replace(/\?(\d+)/g,(_,n)=>{order.push(Number(n)-1);return _;});const args=order.length?order.map(i=>this.args[i]):this.args;return {results:this.db.prepare(q).all(...args)};}}
class DB{constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(fs.readFileSync(new URL('../migrations.sql',import.meta.url),'utf8'));}prepare(sql){return new St(this.sqlite,sql);}}
const NOW=1790449000000;
function canonical({state='WAIT_FOR_TRIGGER',direction='LONG',overall=72,interest=68,trigger=true,entry=false,hard=true,snapshot='S1',run='R1',observed=NOW-1000}={}){const c={status:'CLOSED',snapshot_id:snapshot,run_id:run,observed_ts:observed,snapshot_time_utc:new Date(observed).toISOString(),state,direction,scores:{overall_0_100:overall,coin_interest_0_100:interest,entry_readiness_0_100:null,is_probability:false},candidates:[{contract:'FIL-USDT',ticker:'FIL-USDT'}],universe:[{contract:'FIL-USDT'}],metadata:{contract:'FIL-USDT',source_role_view:{status:'CLOSED',classified:[{source_key:'HTX_OFFICIAL',source_family:'HTX_OFFICIAL',assigned_roles:['EXECUTION_TRUTH'],registry_known:true},{source_key:'BINANCE_OFFICIAL',source_family:'BINANCE_OFFICIAL',assigned_roles:['OI_CROSS_VENUE'],registry_known:true}]}},hard_gates:hard?[{status:'CLOSED'},{status:'CLEAR'}]:[{status:'NOT_CLOSED'}],trigger:trigger?{metric:'price',operator:'>=',value:1.2,unit:'USDT',timeframe:'5m',expires_ts:NOW+600000,cancel_condition:'price<1.0',next_recheck_ts:NOW+60000}:null,entry:entry?{area:'1.18–1.20 USDT'}:null,invalidation:entry?'price<1.0':null,targets:entry?[{price:1.4}]:[],source_receipts:[],reasons:[]};c.analytical_fingerprint=canonicalFingerprint(c);return c;}
function texts(c,{direction=c.direction}={}){const ru=direction==='LONG'?'покупка':'продажа',emoji=direction==='LONG'?'🟢 ПОКУПКА':'🔴 ПРОДАЖА';return {manual:`МОЙ ОТЧЁТ 2\nНаправление: ${ru}\nОбщая оценка: ${Math.round(c.scores.overall_0_100)} из 100\nМонета интересна: ${Math.round(c.scores.coin_interest_0_100)} из 100`,telegram:`FIL\n${emoji}\nОбщая оценка: ${Math.round(c.scores.overall_0_100)} из 100\nМонета интересна: ${Math.round(c.scores.coin_interest_0_100)} из 100`};}
async function ready(db,c=canonical(),event='WAIT',extra={}){const p=await persistCanonicalSnapshot(db,{canonical:c,presentation_inputs:{same_snapshot:true},wave_id:'W1',decision_id:extra.decision_id??null,now_ts:NOW});assert.ok(['CLOSED','DEDUPLICATED'].includes(p.status));const t=texts(c);const f=await finalizePublication(db,{publication_id:p.publication_id,lifecycle_event:event,direction:c.direction,manual_text:t.manual,telegram_text:t.telegram,prior_sent:extra.prior_sent??false,now_ts:NOW});return {p,f,t};}
test('migration is additive and core tables enforce shadow constraints',()=>{const db=new DB();const names=db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(x=>x.name);assert.ok(names.includes('canonical_publication_shadow'));assert.ok(names.includes('v3_recheck_task_shadow'));});
test('OBSERVE without exact action contract stays internal even with high score',()=>{const c=canonical({state:'OBSERVE',overall:100,interest:100,trigger:false});assert.equal(assessActionability({canonical:c,lifecycle_event:'OBSERVE'}).deliver,false);});
test('strong early OBSERVE is deliverable only with working area + exact trigger + TTL + recheck',()=>{const c=canonical({state:'OBSERVE',overall:72,interest:68,trigger:true,entry:true});const a=assessActionability({canonical:c,lifecycle_event:'OBSERVE'});assert.equal(a.deliver,true);assert.equal(a.reason,'EARLY_ACTIONABLE_OBSERVE');assert.equal(a.create_recheck,true);const weak=canonical({state:'OBSERVE',overall:72,interest:59,trigger:true,entry:true});assert.equal(assessActionability({canonical:weak,lifecycle_event:'OBSERVE'}).deliver,false);});
test('strong early OBSERVE may keep canonical overall missing without inventing a proxy score',()=>{const c=canonical({state:'OBSERVE',overall:null,interest:72,trigger:true,entry:true});const a=assessActionability({canonical:c,lifecycle_event:'OBSERVE'});assert.equal(a.deliver,true);assert.equal(a.reason,'EARLY_ACTIONABLE_OBSERVE');const tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'OBSERVE'});assert.equal(tg.ok,true);assert.match(tg.text,/Общая оценка: не подтверждена/);assert.match(tg.text,/Монета интересна: 72 из 100/);const weakOverall=canonical({state:'OBSERVE',overall:59,interest:72,trigger:true,entry:true});assert.equal(assessActionability({canonical:weakOverall,lifecycle_event:'OBSERVE'}).reason,'CANONICAL_OVERALL_BELOW_USER_THRESHOLD');});
test('weak ZKC/APT/AVNT-like WAIT stays internal',()=>{const c=canonical({overall:39,interest:53});assert.equal(assessActionability({canonical:c,lifecycle_event:'WAIT'}).reason,'CANONICAL_OVERALL_BELOW_USER_THRESHOLD');});
test('FIL-like 100 without trigger cannot publish',()=>{const c=canonical({overall:100,interest:89,state:'OBSERVE',trigger:false});assert.equal(assessActionability({canonical:c,lifecycle_event:'WAIT'}).deliver,false);});
test('WAIT requires complete trigger and creates recheck intent',()=>{const a=assessActionability({canonical:canonical(),lifecycle_event:'WAIT'});assert.equal(a.deliver,true);assert.equal(a.create_recheck,true);const b=assessActionability({canonical:canonical({trigger:false}),lifecycle_event:'WAIT'});assert.equal(b.deliver,false);});
test('ENTRY needs strict state context and hard gates, score alone never creates it',()=>{const c=canonical({state:'ENTRY_NOW_ANALYTICAL',entry:true,trigger:false});assert.equal(assessActionability({canonical:c,lifecycle_event:'ENTRY'}).deliver,true);assert.equal(assessActionability({canonical:canonical({state:'ENTRY_NOW_ANALYTICAL',entry:true,hard:false}),lifecycle_event:'ENTRY'}).deliver,false);assert.equal(assessActionability({canonical:canonical({state:'OBSERVE',overall:100,interest:100}),lifecycle_event:'ENTRY'}).deliver,false);});
test('persist -> finalize -> exact dispatch binding -> sender reads only same publication',async()=>{const db=new DB(),c=canonical();const {p,f}=await ready(db,c);assert.equal(f.status,'ACTIONABLE');const b=await bindDispatchToPublication(db,{idempotency_key:'K1',publication_id:p.publication_id,contract:'FIL-USDT',direction:'LONG',wave_id:'W1',lifecycle_event:'WAIT',rules_version:'v3',now_ts:NOW});assert.equal(b.bound,true);const out=await loadBoundTelegram(db,{idempotency_key:'K1',now_ts:NOW});assert.equal(out.ok,true);assert.equal(out.canonical.snapshot_id,'S1');const man=await loadExactManual(db,{publication_id:p.publication_id});assert.equal(man.ok,true);assert.equal(man.analytical_fingerprint,out.analytical_fingerprint);assert.equal(man.presentation_hash,out.presentation_hash);});
test('tampered score after fingerprint is rejected before persistence',async()=>{const db=new DB(),c=canonical();c.scores.overall_0_100=100;const p=await persistCanonicalSnapshot(db,{canonical:c,wave_id:'W1',now_ts:NOW});assert.equal(p.persisted,false);assert.equal(p.reason,'CANONICAL_FINGERPRINT_MISMATCH');});
test('display direction mismatch is rejected',async()=>{const db=new DB(),c=canonical();const p=await persistCanonicalSnapshot(db,{canonical:c,wave_id:'W1',now_ts:NOW});const bad=texts(c,{direction:'SHORT'});const f=await finalizePublication(db,{publication_id:p.publication_id,lifecycle_event:'WAIT',direction:'LONG',manual_text:bad.manual,telegram_text:bad.telegram,now_ts:NOW});assert.equal(f.deliver,false);assert.match(f.reason,/DIRECTION/);});
test('wrong snapshot cannot be substituted because binding names publication id',async()=>{const db=new DB();const a=await ready(db,canonical({snapshot:'S1'}));const b=await ready(db,canonical({snapshot:'S2',observed:NOW-500}));await bindDispatchToPublication(db,{idempotency_key:'K1',publication_id:a.p.publication_id,contract:'FIL-USDT',direction:'LONG',wave_id:'W1',lifecycle_event:'WAIT',rules_version:'v3',now_ts:NOW});db.sqlite.prepare("UPDATE canonical_publication_shadow SET snapshot_id='S2' WHERE publication_id=?").run(a.p.publication_id);const out=await loadBoundTelegram(db,{idempotency_key:'K1',now_ts:NOW});assert.equal(out.ok,false);assert.equal(out.status,'BOUND_PUBLICATION_MISMATCH');assert.notEqual(a.p.publication_id,b.p.publication_id);});
test('ENTRY exact decision id is binding-critical',async()=>{const db=new DB(),c=canonical({state:'ENTRY_NOW_ANALYTICAL',entry:true,trigger:false});const {p}=await ready(db,c,'ENTRY',{decision_id:'D1'});const wrong=await bindDispatchToPublication(db,{idempotency_key:'E1',publication_id:p.publication_id,contract:'FIL-USDT',direction:'LONG',wave_id:'W1',lifecycle_event:'ENTRY',rules_version:'v3',decision_id:'D2',now_ts:NOW});assert.equal(wrong.bound,false);assert.equal(wrong.status,'DECISION_ID_MISMATCH');});
test('IDEA_REMOVED is preserved only after a prior delivered idea',()=>{const c=canonical({state:'REJECTED'});assert.equal(assessActionability({canonical:c,lifecycle_event:'IDEA_REMOVED',prior_sent:false}).deliver,false);assert.equal(assessActionability({canonical:c,lifecycle_event:'IDEA_REMOVED',prior_sent:true}).deliver,true);});
test('WAIT durable recheck task is due by timestamp, not a 15m transient TTL',async()=>{const db=new DB();const {p}=await ready(db);const q=await enqueueRecheck(db,{publication_id:p.publication_id,contract:'FIL-USDT',direction:'LONG',wave_id:'W1',snapshot_id:'S1',run_id:'R1',due_ts:NOW+60_000,expires_ts:NOW+600_000,now_ts:NOW});assert.equal(q.enqueued,true);assert.equal((await claimDueRecheck(db,{now_ts:NOW+30_000})).claimed,false);const cl=await claimDueRecheck(db,{now_ts:NOW+60_000});assert.equal(cl.claimed,true);assert.equal(cl.task.wave_id,'W1');const done=await completeRecheck(db,{task_id:cl.task.task_id,result:'DONE',new_publication_id:'PUB:NEW',now_ts:NOW+70_000});assert.equal(done.status,'CLOSED');assert.equal((await claimDueRecheck(db,{now_ts:NOW+80_000})).claimed,false);});
test('scheduler ownership prevents duplicate analytics execution',()=>{assert.equal(analyticsOwner({actor:'GITHUB_ACTIONS'}).allowed,true);assert.equal(analyticsOwner({actor:'CLOUDFLARE_HUB'}).allowed,false);});
test('hourly statistics cadence is due-time/last-success, not minute==2',()=>{assert.equal(dueByLastSuccess({now_ts:NOW,last_success_ts:NOW-3_600_001,interval_ms:3_600_000}),true);assert.equal(dueByLastSuccess({now_ts:NOW,last_success_ts:NOW-3_599_000,interval_ms:3_600_000}),false);assert.equal(dueByLastSuccess({now_ts:NOW,last_success_ts:null,interval_ms:3_600_000}),true);});
import {renderCanonicalTelegram,renderCanonicalManual} from '../src/canonical-publication.mjs';
test('canonical renderers preserve approved Telegram/manual score and direction layout',()=>{const c=canonical();c.metadata.oi_window_receipts={"1h":{status:'CLOSED',change_pct:-2.39,unit:'CONTRACTS',window_start_ts:1790442000000,window_end_ts:1790445600000},"4h":{status:'CLOSED',change_pct:-7.86,unit:'CONTRACTS',window_start_ts:1790431200000,window_end_ts:1790445600000}};c.analytical_fingerprint=canonicalFingerprint(c);const tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'WAIT'}),m=renderCanonicalManual({canonical:c,lifecycle_event:'WAIT'});assert.equal(tg.ok,true);assert.equal(m.ok,true);assert.match(tg.text,/🟢 ПОКУПКА/);assert.match(tg.text,/Общая оценка: 72 из 100/);assert.match(tg.text,/Открытый интерес HTX: -2,39% за 1h; CONTRACTS/);assert.match(tg.text,/Следующая автоматическая проверка/);assert.match(m.text,/Направление: покупка/);assert.match(m.text,/Общая оценка: 72 из 100/);});

test('reconciler preserves the canonical manual presentation when it was saved at analysis time',async()=>{
 const db=new DB(),c=canonical();
 const preserved=`МОЙ ОТЧЁТ 2\nСнимок рынка: ${c.snapshot_time_utc}\nКАНОНИЧЕСКОЕ СОСТОЯНИЕ\nНаправление: покупка\nОбщая оценка: 72 из 100\nМонета интересна: 68 из 100\nУтверждённый ручной формат сохранён без пересборки.`;
 const p=await persistCanonicalSnapshot(db,{canonical:c,presentation_inputs:{manual_text:preserved},wave_id:'W1',now_ts:NOW});
 db.sqlite.exec(`CREATE TABLE v3_user_lifecycle_shadow(contract TEXT,direction TEXT,wave_id TEXT,rules_version TEXT,status TEXT,reason TEXT,observation_ts INTEGER,valid_until_ts INTEGER,updated_ts INTEGER,shadow_only INTEGER);CREATE TABLE v3_telegram_dispatch_shadow(dispatch_id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE,contract TEXT,direction TEXT,wave_id TEXT,lifecycle_event TEXT,rules_version TEXT,state TEXT,decision_id TEXT,message_hash TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);`);
 db.sqlite.prepare(`INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1)`).run('FIL-USDT','LONG','W1','v3','WAIT','DIRECTION_CLOSED_ENTRY_WINDOW_NOT_READY',c.observed_ts,c.trigger.expires_ts,NOW);
 db.sqlite.prepare(`INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,?,?,?,1)`).run('D1','K-PRESERVE','FIL-USDT','LONG','W1','WAIT','v3','PENDING',NOW,NOW);
 const {reconcilePendingPublications}=await import('../src/publication-reconciler.mjs');
 const r=await reconcilePendingPublications(db,{now_ts:NOW});assert.equal(r.results[0].status,'BOUND_ACTIONABLE');
 const row=db.sqlite.prepare(`SELECT manual_text FROM canonical_publication_shadow WHERE publication_id=?`).get(p.publication_id);assert.equal(row.manual_text,preserved);
});


test('reconciler binds the exact source run even when lifecycle observation timestamp differs',async()=>{
 const db=new DB(),c=canonical({run:'R-EXACT',snapshot:'S-EXACT',observed:NOW-5000});
 const p=await persistCanonicalSnapshot(db,{canonical:c,presentation_inputs:{same_snapshot:true},wave_id:'W1',now_ts:NOW-4000});
 assert.equal(p.persisted,true);
 db.sqlite.exec(`CREATE TABLE v3_user_lifecycle_shadow(contract TEXT,direction TEXT,wave_id TEXT,rules_version TEXT,status TEXT,reason TEXT,observation_ts INTEGER,valid_until_ts INTEGER,updated_ts INTEGER,shadow_only INTEGER);CREATE TABLE v3_telegram_dispatch_shadow(dispatch_id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE,contract TEXT,direction TEXT,wave_id TEXT,lifecycle_event TEXT,rules_version TEXT,state TEXT,decision_id TEXT,message_hash TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);`);
 db.sqlite.prepare(`INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1)`).run('FIL-USDT','LONG','W1','v3','WAIT','DIRECTION_CLOSED_ENTRY_WINDOW_NOT_READY',NOW-2500,c.trigger.expires_ts,NOW-2000);
 db.sqlite.prepare(`INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,?,?,?,1)`).run('D-RUN','K-RUN','FIL-USDT','LONG','W1','WAIT','v3','PENDING',NOW-1500,NOW-1500);
 const {reconcilePendingPublications}=await import('../src/publication-reconciler.mjs');
 const r=await reconcilePendingPublications(db,{now_ts:NOW,source_run_id:'R-EXACT'});
 assert.equal(r.results[0].status,'BOUND_ACTIONABLE');
 const b=db.sqlite.prepare(`SELECT run_id,snapshot_id FROM v3_dispatch_publication_binding_shadow WHERE idempotency_key='K-RUN'`).get();
 assert.equal(b.run_id,'R-EXACT');assert.equal(b.snapshot_id,'S-EXACT');
});

test('reconciler fails closed when one run contains multiple canonical snapshots for the same wave',async()=>{
 const db=new DB();
 const a=canonical({run:'R-AMB',snapshot:'S-A',observed:NOW-5000});
 const b=canonical({run:'R-AMB',snapshot:'S-B',observed:NOW-4000});
 assert.equal((await persistCanonicalSnapshot(db,{canonical:a,wave_id:'W1',now_ts:NOW-3500})).persisted,true);
 assert.equal((await persistCanonicalSnapshot(db,{canonical:b,wave_id:'W1',now_ts:NOW-3000})).persisted,true);
 db.sqlite.exec(`CREATE TABLE v3_user_lifecycle_shadow(contract TEXT,direction TEXT,wave_id TEXT,rules_version TEXT,status TEXT,reason TEXT,observation_ts INTEGER,valid_until_ts INTEGER,updated_ts INTEGER,shadow_only INTEGER);CREATE TABLE v3_telegram_dispatch_shadow(dispatch_id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE,contract TEXT,direction TEXT,wave_id TEXT,lifecycle_event TEXT,rules_version TEXT,state TEXT,decision_id TEXT,message_hash TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);`);
 db.sqlite.prepare(`INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1)`).run('FIL-USDT','LONG','W1','v3','WAIT','DIRECTION_CLOSED_ENTRY_WINDOW_NOT_READY',NOW-2500,a.trigger.expires_ts,NOW-2000);
 db.sqlite.prepare(`INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,?,?,?,1)`).run('D-AMB','K-AMB','FIL-USDT','LONG','W1','WAIT','v3','PENDING',NOW-1500,NOW-1500);
 const {reconcilePendingPublications}=await import('../src/publication-reconciler.mjs');
 const r=await reconcilePendingPublications(db,{now_ts:NOW,source_run_id:'R-AMB'});
 assert.equal(r.results[0].status,'AMBIGUOUS_CANONICAL_SNAPSHOT');assert.equal(r.results[0].matches,2);
 assert.equal(db.sqlite.prepare(`SELECT count(*) n FROM v3_dispatch_publication_binding_shadow WHERE idempotency_key='K-AMB'`).get().n,0);
});

test('BEAT 43/56 early observation from screenshot stays internal',()=>{const c=canonical({state:'OBSERVE',overall:43,interest:56,trigger:false});const a=assessActionability({canonical:c,lifecycle_event:'OBSERVE'});assert.equal(a.deliver,false);assert.ok(['CANONICAL_INTEREST_BELOW_USER_THRESHOLD','CANONICAL_OVERALL_BELOW_USER_THRESHOLD','EARLY_ACTION_CONTRACT_INCOMPLETE'].includes(a.reason));});
test('ZEC IDEA_REMOVED is suppressed when its earlier observation was never delivered',()=>{const c=canonical({state:'REJECTED',overall:38,interest:46});const a=assessActionability({canonical:c,lifecycle_event:'IDEA_REMOVED',prior_sent:false});assert.equal(a.deliver,false);});
