import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const root=path.resolve(process.argv[2]||'runtime'),load=name=>import(pathToFileURL(path.join(root,name))),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const {RemoteD1Database}=await load('report2-d1-adapter.mjs');
const {collectOfficialTokenSchedule}=await load('src/official-token-schedule.mjs');
const {collectOfficialEventsEvidence}=await load('src/official-events-evidence.mjs');
const {compileOfficialSourceRegistry}=await load('src/official-source-registry.mjs');
const {consumeEvidenceV2}=await load('src/evidence-v2.mjs');
const {consumeBlockResultContext}=await load('src/block-result-context.mjs');
const {auditCandidateBlocks,planCandidateEvidenceRoutes}=await load('src/candidate-evidence-v2-runtime.mjs');
const {buildRuntimeCanonicalBundle}=await load('src/canonical-runtime-adapter.mjs');
const {createUnifiedHttpBudget}=await load('src/unified-budget.mjs');
const accepted=JSON.parse(fs.readFileSync('prior-output/cardano-official-live-verification.json'));assert.equal(accepted.github_head,'e39ca6a26d3b310ec1ffc2cede1cc26a3616f9ce');assert.equal(accepted.source_http,2);assert.equal(accepted.database_usage.unknown_ops,0);assert.match(fs.readFileSync('prior-output/validation.json','utf8'),/CURRENT_GENERATION_VALIDATED/);const priorSource=JSON.parse(fs.readFileSync('prior-output/cardano-official-source-body.json'));assert.equal(priorSource.length,2);assert.ok(priorSource.every(x=>x.http_status===200));
const files=['src/official-token-schedule.mjs','src/official-events-evidence.mjs','src/block-result-context.mjs','main-official-event-sources.json'];
const runtime_sha256=Object.fromEntries(files.map(f=>{const b=fs.readFileSync(path.join(root,f));assert.equal(hash(b),hash(fs.readFileSync(path.join('current-generation/files',f))),f);assert.equal(hash(b),accepted.runtime_sha256[f],'CODE_CHANGED_REQUIRES_NEW_VALIDATION');return[f,hash(b)];}));
const phase=JSON.parse(fs.readFileSync('checkpoints/CLOUD_PHASE_STATE_20261004.json'));assert.equal(phase.lease?.owner,process.env.REPORT2_CONTINUATION_OWNER);assert.ok(phase.lease.expires_ts>Date.now());assert.equal(phase.current_phase,'CORE_BLOCKS');
const universeBytes=fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'),universe=JSON.parse(zlib.gunzipSync(universeBytes));assert.equal(universe.status,'CLOSED');assert.equal(universe.assets.length,102);assert.equal(universe.contracts.length,119);assert.ok(universe.assets.some(x=>x.symbol==='ADA'&&x.asset_analysis_contract==='ADA-USDT'));
const entry=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'main-official-event-sources.json')))).registry.ADA,identity={chain:entry.chain,asset_kind:entry.asset_kind,native_asset_id:entry.native_asset_id,contract_or_mint:entry.contract_or_mint};assert.deepEqual(identity,{chain:'cardano',asset_kind:'NATIVE',native_asset_id:'cardano:mainnet',contract_or_mint:null});
const planned=planCandidateEvidenceRoutes({contract:'ADA-USDT',asset_identity:identity,asset_metadata:entry,run_id:'OFFICIAL_ACTUAL',now:Date.now()});assert.ok(planned.routes.some(x=>x.name==='TOKEN_SCHEDULE'));assert.ok(planned.routes.some(x=>x.name==='OFFICIAL'));
const db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN),budget=createUnifiedHttpBudget(),run_id=`ADA_OFFICIAL_ACTUAL:${process.env.GITHUB_RUN_ID}`,raw=[],results=[];
function save(error=null){fs.writeFileSync('audit-output/cardano-official-source-body.json',JSON.stringify(raw)+'\n');fs.writeFileSync('audit-output/cardano-official-live-verification.json',JSON.stringify({schema:'report2-cardano-official-context-acceptance-v1',github_head:process.env.GITHUB_SHA,run_id,error,accepted_code_validation_run:37263699095,accepted_source_artifact:11325855506,accepted_source_http:2,source_body_sha256:hash(fs.readFileSync('prior-output/cardano-official-source-body.json')),runtime_sha256,common_universe_sha256:hash(universeBytes),common_future_assets:102,common_future_contracts:119,all_assets_retained:universe.assets.map(x=>x.symbol),results,source_http:raw.length,source_limits:{provider_numeric_minute_day_month_limit:null,unknown_limit_is_not_unlimited:true,key_required:false,paid_api_used:false,internal_document_daily_cap:2,internal_feed_daily_cap:4,internal_worst_case_31_days:186,document_cache_ms:86400000,feed_cache_ms:21600000,timeout_ms:8000,retries:0,shared_official_daily_cap:288,shared_job_http_cap:164},database_usage:db.usageSnapshot(),production_canonical_writes:0,full_main_acceptance:false,all_15_live_accepted:false,telegram_calls:0,telegram_delivery_proven:false},null,2)+'\n');}
process.on('uncaughtExceptionMonitor',e=>save(String(e)));
const fetch_impl=async(url,opts)=>{throw Error('FRESH_PACKAGE_CACHE_MUST_REUSE_ACCEPTED_SOURCE_REQUESTS');assert.ok(['https://cardano.org/genesis/','https://cardano.org/news/rss.xml'].includes(String(url)));assert.ok(raw.length<2);const response=await fetch(url,opts),body=await response.clone().text();raw.push({url:String(url),http_status:response.status,observed_ts:Date.now(),body_sha256:hash(body),body});save();return response;};
const base={db,fetch_impl,request_admit:r=>budget.reserve(r),contract:'ADA-USDT',run_id,asset_identity:identity,asset_metadata:entry,now:Date.now(),clock:Date.now,strict_fresh_manual:false};
const document=await collectOfficialTokenSchedule(base),feed=await collectOfficialEventsEvidence({...base,now:Date.now()});
assert.equal(document.status,'CLOSED');assert.equal(feed.status,'CLOSED');assert.equal(document.network_calls,0);assert.equal(feed.network_calls,0);assert.equal(document.cache_status,'HIT');assert.equal(feed.cache_status,'HIT');assert.equal(raw.length,0);assert.ok(feed.evidence.length>=1);
for(const [source,result] of [['https://cardano.org/genesis/',document],['https://cardano.org/news/rss.xml',feed]]){const old=priorSource.find(x=>x.url===source);assert.ok(old);assert.ok(result.evidence.every(x=>x.observed_ts>=old.observed_ts-10000&&x.observed_ts<=old.observed_ts+10000));}
const evidence=[...document.evidence,...feed.evidence],sources={OFFICIAL_TOKEN_SCHEDULE:document,OFFICIAL_EVENTS:feed};assert.ok(evidence.every(x=>x.asset_id==='cardano:native:mainnet'&&x.htx_contract==='ADA-USDT'&&x.directional_strength===null&&x.risk_strength===null));assert.equal(consumeEvidenceV2(evidence,{base_interest:70,decision_ts:Date.now()}).adjustment,0);
const context=consumeBlockResultContext({evidence,contract:'ADA-USDT',now:Date.now()});assert.ok(context.facts.some(x=>x.block_id==='N01'));assert.ok(context.facts.some(x=>x.block_id==='N07'));const audit=auditCandidateBlocks({sources,evidence,decision_ts:Date.now()});for(const b of ['N01','N07']){assert.equal(audit.blocks[b].checked,true);assert.ok(audit.blocks[b].observed_facts>=1);assert.equal(audit.blocks[b].decision_path,'ADMITTED_NEUTRAL_CONTEXT');assert.equal(audit.blocks[b].usable_facts,0);}
const observed_ts=Date.now(),input={contract:'ADA-USDT',run_id,snapshot_id:`${run_id}:ADA-USDT:${observed_ts}`,observed_ts},before=buildRuntimeCanonicalBundle(input),after=buildRuntimeCanonicalBundle({...input,internal_market_context:{internal_only:true,evidence_v2:{evidence,sources}}});
assert.equal(after.manual.ok,true);assert.ok(after.manual.text.includes('Официальное первоначальное распределение ADA'));assert.ok(after.manual.text.includes('Официальное объявление проекта'));for(const b of ['N01','N07'])assert.ok(after.block_rendered_results.used_context_block_ids.includes(b));assert.deepEqual(after.canonical.scores,before.canonical.scores);assert.equal(after.canonical.direction,before.canonical.direction);assert.equal(after.canonical.state,before.canonical.state);assert.deepEqual(after.canonical.targets,before.canonical.targets);assert.equal(after.canonical.metadata.automatic_execution,false);
results.push({contract:'ADA-USDT',identity,document,feed,context,audit,report:{scope:'FRESH_OFFICIAL_CONTEXT_IN_CANONICAL_BUILDER_APPROVED_MANUAL_NO_SIGNAL',manual:after.manual,rendered_use:after.block_rendered_results}});save();const usage=db.usageSnapshot();assert.equal(usage.unknown_ops,0);assert.ok(usage.rows_read<=1000&&usage.rows_written<=80);save();console.log(JSON.stringify({status:'CLOSED_ACTUAL_CARDANO_N01_N07_REPORT_CONTEXT',source_http:raw.length,database_usage:usage,production_canonical_writes:0,telegram_calls:0,full_main_acceptance:false}));
