import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import http from 'node:http';import {createHash} from 'node:crypto';
import {FixtureDB} from './db-fixture.mjs';
import {canonicalFingerprint,persistCanonicalSnapshot,renderCanonicalTelegram,renderCanonicalManual,loadExactManual,validatePresentation} from '../src/canonical-publication.mjs';
import {reconcilePendingPublications} from '../src/publication-reconciler.mjs';
import {runBoundTelegramDeliverySidecar} from '../src/bound-telegram-delivery-sidecar.mjs';
import {verifyNativeLiquidationView,NATIVE_LIQ_FRESHNESS_MS} from '../src/native-liquidation-publication.mjs';
const bytes=fs.readFileSync(new URL('../fixtures/captured-canonical.json',import.meta.url));
assert.equal(createHash('sha256').update(bytes).digest('hex'),'856acb9bc55365c9a23863238cc6c9d6954e124a605df51ebf9b661141e2af36');
const captured=JSON.parse(bytes);const NOW=captured.observed_ts;
const sign=c=>{c.analytical_fingerprint=canonicalFingerprint(c);return c;};
function syntheticValidWait(){const c=structuredClone(captured);c.state='WAIT_FOR_TRIGGER';c.scores={overall_0_100:76,coin_interest_0_100:73,entry_readiness_0_100:null,is_probability:false};c.hard_gates=[{gate:'HTX_EXECUTION',status:'CLOSED'}];c.trigger={metric:'price',operator:'>=',value:1.16,unit:'USDT',timeframe:'5m',cancel_condition:'цена ниже 1,10',expires_ts:NOW+1800000,next_recheck_ts:NOW+300000};c.metadata.test_fixture='SYNTHETIC_ACTIONABILITY_WITH_UNCHANGED_CAPTURED_NATIVE_CONTEXT_NOT_LIVE_SIGNAL';return sign(c);}
async function seed(db,{c=syntheticValidWait(),event='WAIT',key='LQ1',now=NOW,manual_text=null}={}){
 const p=await persistCanonicalSnapshot(db,{canonical:c,presentation_inputs:manual_text?{manual_text}:{},wave_id:'W1',now_ts:now});assert(p.persisted,JSON.stringify(p));
 db.raw.prepare(`INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1) ON CONFLICT(contract,direction,wave_id,rules_version) DO UPDATE SET status=excluded.status,updated_ts=excluded.updated_ts,observation_ts=excluded.observation_ts,valid_until_ts=excluded.valid_until_ts`).run('FIL-USDT','LONG','W1','v3',event,'TEST_ONLY',now,now+1800000,now);
 db.raw.prepare(`INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,decision_id,message_hash,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,'PENDING',NULL,NULL,?,?,1)`).run(key,key,'FIL-USDT','LONG','W1',event,'v3',now,now);return {p,c};
}
const ack=async()=>new Response(JSON.stringify({ok:true,status:'SENT',message_id:901}),{status:200,headers:{'content-type':'application/json'}});
const options=(extra={})=>({enabled:true,relay_url:'http://127.0.0.1/test-only',relay_key:'TEST_ONLY_NO_REAL_SECRET',now_ts:NOW+1000,fetch_impl:ack,...extra});
test('original captured canonical stays internal: native levels cannot invent missing score or trigger',async()=>{const db=new FixtureDB();await seed(db,{c:structuredClone(captured),event:'OBSERVE'});let calls=0;const r=await runBoundTelegramDeliverySidecar(db,options({fetch_impl:async()=>{calls++;return ack();}}));assert.equal(calls,0);assert.equal(r.sent,0);assert.equal(db.raw.prepare('SELECT state FROM v3_telegram_dispatch_shadow').get().state,'FAILED_FINAL');db.close();});
test('both actual publication formatters display producer-prepared native lines with no 20% pump gate',()=>{const c=syntheticValidWait(),tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'WAIT'}),man=renderCanonicalManual({canonical:c,lifecycle_event:'WAIT'});assert(tg.ok);assert(man.ok);for(const line of c.liquidations.display_lines)assert(tg.text.split('\n').includes(line));for(const line of c.liquidations.manual_lines)assert(man.text.split('\n').includes(line));assert.match(tg.text,/USDC/);assert.match(man.text,/0\.9017706/);assert.equal(c.liquidations.pump.is_pump,false);});
test('Node24 real sender, durable queue, local HTTP receiver and current manual read share exact captured liquidation data',async()=>{
 const db=new FixtureDB();const {p,c}=await seed(db);let received=null,calls=0;
 const server=http.createServer((req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',()=>{calls++;received=JSON.parse(body);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,status:'SENT',message_id:901}));});});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{
  const r=await runBoundTelegramDeliverySidecar(db,options({relay_url:`http://127.0.0.1:${server.address().port}/test-only`,fetch_impl:globalThis.fetch}));assert.equal(r.sent,1,JSON.stringify(r));assert.equal(calls,1);
  const stored=db.raw.prepare('SELECT * FROM canonical_publication_shadow WHERE publication_id=?').get(p.publication_id);assert.equal(received.text,stored.telegram_text);
  const manual=await loadExactManual(db,{publication_id:p.publication_id,now_ts:NOW+1000});assert(manual.ok);assert.equal(manual.text,stored.manual_text);assert.equal(manual.analytical_fingerprint,c.analytical_fingerprint);assert.deepEqual(manual.canonical.liquidations,captured.liquidations);assert.equal(manual.historical_only,false);
  assert(r.usage_delta.rows_read<=272);assert(r.usage_delta.rows_written<=32);assert(r.usage_delta.requests<=52);
  const proof={status:'CAPTURED_NATIVE_CONTEXT_THROUGH_REAL_PUBLICATION_QUEUE_SENDER_AND_MANUAL_PASS',node:process.version,captured_fixture_sha256:createHash('sha256').update(bytes).digest('hex'),canonical_as_of:NOW,source_ts:captured.liquidations.sources[0].source_ts,source_time_rewritten:false,synthetic_actionability_only:true,actual_Telegram_network:false,receiver:'ISOLATED_LOOPBACK_HTTP',receiver_requests:calls,message_id:901,canonical_fp:manual.analytical_fingerprint,presentation_hash:manual.presentation_hash,fixture_logical_db_usage:r.usage_delta,production_d1_measured:false,full_project_runtime_test:false,production_changed:false};
  fs.writeFileSync(new URL('../proof/real-sender-node24.json',import.meta.url),JSON.stringify(proof,null,2));
 }finally{await new Promise(resolve=>server.close(resolve));db.close();}
});
test('current manual loader rejects manual-text tampering, not only canonical tampering',async()=>{const db=new FixtureDB();const {p}=await seed(db);await reconcilePendingPublications(db,{now_ts:NOW});db.raw.prepare("UPDATE canonical_publication_shadow SET manual_text=manual_text||' changed'").run();assert.equal((await loadExactManual(db,{publication_id:p.publication_id,now_ts:NOW+1})).status,'PRESENTATION_CONTENT_MISMATCH');db.close();});
test('saved manual without liquidation block cannot be silently accepted',async()=>{const db=new FixtureDB();await seed(db,{manual_text:'Направление: покупка\nОбщая оценка: 76 из 100\nМонета интересна: 73 из 100'});const r=await reconcilePendingPublications(db,{now_ts:NOW});assert.equal(r.results[0].reason,'NATIVE_LIQUIDATION_TEXT_MISSING_OR_CHANGED');db.close();});
test('native source TTL is checked at send time, even when scenario TTL has not expired',async()=>{const db=new FixtureDB();await seed(db);await reconcilePendingPublications(db,{now_ts:NOW});let calls=0;const later=captured.liquidations.sources[0].source_ts+NATIVE_LIQ_FRESHNESS_MS+1;const r=await runBoundTelegramDeliverySidecar(db,options({now_ts:later,fetch_impl:async()=>{calls++;return ack();}}));assert.equal(calls,0);assert.equal(r.lifecycle[0].reason,'NATIVE_LIQ_STALE_RECHECK_REQUIRED');assert.equal(db.raw.prepare("SELECT count(*) n FROM v3_recheck_task_shadow WHERE state='PENDING'").get().n,1);db.close();});
test('archival read is labelled historical; current manual refuses stale levels',async()=>{const db=new FixtureDB();const {p}=await seed(db);await reconcilePendingPublications(db,{now_ts:NOW});assert.equal((await loadExactManual(db,{publication_id:p.publication_id,now_ts:NOW+900000})).ok,false);const old=await loadExactManual(db,{publication_id:p.publication_id});assert(old.ok);assert.equal(old.historical_only,true);db.close();});
test('wrong symbol, wrong canonical snapshot, future data, unknown schema and false quote conversion fail closed',()=>{
 for(const edit of [c=>c.liquidations.sources[0].native_symbol='ETH',c=>c.liquidations.analysis_binding.snapshot_id='other',c=>c.liquidations.sources[0].source_ts=NOW+1,c=>c.liquidations.version='liq-canonical-context-next',c=>c.liquidations.above[0].notional_unit='USDT']){const c=syntheticValidWait();edit(c);sign(c);assert.equal(renderCanonicalTelegram({canonical:c,lifecycle_event:'WAIT'}).ok,false);}
});
test('native liquidation text parity detects relabelling of USDC as USDT',()=>{const c=syntheticValidWait(),man=renderCanonicalManual({canonical:c,lifecycle_event:'WAIT'}),tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'WAIT'});assert.equal(validatePresentation({canonical:c,manual_text:man.text,telegram_text:tg.text.replace('USDC','USDT'),direction:'LONG',lifecycle_event:'WAIT'}).reason,'NATIVE_LIQUIDATION_TEXT_MISSING_OR_CHANGED');});
test('second sender invocation never repeats a SENT dispatch',async()=>{const db=new FixtureDB();await seed(db);let calls=0;const o=options({fetch_impl:async()=>{calls++;return ack();}});await runBoundTelegramDeliverySidecar(db,o);await runBoundTelegramDeliverySidecar(db,{...o,now_ts:NOW+2000});assert.equal(calls,1);db.close();});
test('network retry after source expiry cannot bypass the freshness gate',async()=>{const db=new FixtureDB();await seed(db);let calls=0;await runBoundTelegramDeliverySidecar(db,options({fetch_impl:async()=>{calls++;return new Response('{}',{status:429});}}));const r=await runBoundTelegramDeliverySidecar(db,options({now_ts:NOW+900000,fetch_impl:async()=>{calls++;return ack();}}));assert.equal(calls,1);assert.equal(r.sent,0);db.close();});
test('cancellation of a previously delivered idea survives stale map filtering without republishing old levels',async()=>{const db=new FixtureDB();await seed(db);await runBoundTelegramDeliverySidecar(db,options());const c=syntheticValidWait(),later=NOW+1200000;c.run_id='CANCEL_RUN';c.snapshot_id='CANCEL_SNAPSHOT';c.observed_ts=later;c.state='REJECTED';c.scores.overall_0_100=null;sign(c);await seed(db,{c,event:'IDEA_REMOVED',key:'LQ2',now:later});let message;const r=await runBoundTelegramDeliverySidecar(db,options({source_run_id:c.run_id,now_ts:later+1000,fetch_impl:async(_u,o)=>{message=JSON.parse(o.body).text;return ack();}}));assert.equal(r.sent,1,JSON.stringify(r));assert.match(message,/ИДЕЯ СНЯТА/);assert.doesNotMatch(message,/0\.9017706/);db.close();});
test('high notional cannot rescue a weak canonical score',async()=>{const db=new FixtureDB(),c=syntheticValidWait();c.scores.overall_0_100=37;sign(c);await seed(db,{c});let calls=0;await runBoundTelegramDeliverySidecar(db,options({fetch_impl:async()=>{calls++;return ack();}}));assert.equal(calls,0);db.close();});
