import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const root=path.resolve(process.argv[2]||'runtime'),load=n=>import(pathToFileURL(path.join(root,n)));
const {RemoteD1Database}=await load('report2-d1-adapter.mjs');
const {createFuturesCoverageDatabase,validateFuturesCoverageDatabase,saveFuturesCoverageDatabase,loadFuturesCoverageDatabase,futuresLiquidationAdmission}=await load('src/liquidation-futures-coverage.mjs');
const state=JSON.parse(fs.readFileSync('checkpoints/CLOUD_PHASE_STATE_20261004.json','utf8'));
assert.equal(state.current_phase,'CORE_BLOCKS');assert.equal(state.lease?.owner,process.env.REPORT2_CONTINUATION_OWNER);assert.ok(state.lease.expires_ts>Date.now());
const bytes=fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'),universe=JSON.parse(zlib.gunzipSync(bytes));
const db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN),now=Date.now();
const prior=await loadFuturesCoverageDatabase({db,now});
if(prior)assert.equal(validateFuturesCoverageDatabase(prior),true);
const database=prior||createFuturesCoverageDatabase({universe,universe_sha256:crypto.createHash('sha256').update(bytes).digest('hex'),now});
assert.equal(database.universe_sha256,crypto.createHash('sha256').update(bytes).digest('hex'));assert.equal(database.crypto_future_assets,102);assert.equal(database.crypto_future_contracts,119);
const admit=extra=>{const u=db.usageSnapshot();return{allowed:u.unknown_ops===0&&u.rows_read+extra.rows_read<=1000&&u.rows_written+extra.rows_written<=40};};
const persisted=prior?{status:'VALID_EXISTING_MATRIX_PRESERVED',saved:true}:await saveFuturesCoverageDatabase({db,database,now,db_admit:admit});assert.equal(persisted.saved,true);
const readback=await loadFuturesCoverageDatabase({db,now});assert.equal(validateFuturesCoverageDatabase(readback),true);assert.deepEqual(readback.assets,database.assets);
const source=fs.readFileSync(path.join(root,'runner-main.mjs'),'utf8'),pump=fs.readFileSync(path.join(root,'src/pump-liquidation-zones.mjs'),'utf8');
assert.match(source,/lease_started_ts:cadence\.lease_started_ts/);assert.match(source,/publish_verified_24h:false/);assert.doesNotMatch(pump,/buildHtxSourceBackedLiquidationModel\s*\(/);
const admissions=database.assets.map(a=>({contract:a.analysis_contract,...futuresLiquidationAdmission(database,{contract:a.analysis_contract,now})}));
if(!prior)assert.equal(admissions.filter(a=>a.eligible).length,0);
const usage=db.usageSnapshot();assert.equal(usage.unknown_ops,0);assert.ok(usage.rows_read<=1000&&usage.rows_written<=40);
const report={schema:'coverage-cadence-durable-foundation-v1',github_head:process.env.GITHUB_SHA,observed_ts:now,common_future_universe_sha256:database.universe_sha256,crypto_future_assets:database.crypto_future_assets,crypto_future_contracts:database.crypto_future_contracts,asset_source_cells:database.assets.length*8,source_checks_complete:database.source_checks_complete,persistence: persisted,readback_verified:true,prior_verified_cells_preserved:!!prior,source_checks_started:0,source_http:0,deep_checks_started:0,canonical_writes:0,telegram_calls:0,database_usage:usage,raw_24h_publication_deferred:true,calculated_htx_fallback_enabled:false,all_15_live_accepted:false,coverage_live_gate_and_weekly_refresh_accepted:false,admissions};
fs.writeFileSync('audit-output/coverage-cadence-live-verification.json',JSON.stringify(report,null,2)+'\n');
fs.writeFileSync('audit-output/liquidation-coverage-database.json',JSON.stringify(readback)+'\n');
console.log(JSON.stringify({...report,admissions:undefined}));
