import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeBinanceHistoryFeature,recoverCoinbaseSequence,decideBitgetUtility,auditHyperliquidRecorderRuntime} from '../src/history-sequence-utility.mjs';
import {consumeExistingSourceReceipts} from '../src/existing-source-consumer.mjs';

test('Binance 90d history feature closes only with gap-free factual rows',()=>{const r=normalizeBinanceHistoryFeature({span_days:91.9,rows:120000,gaps:0,first_close:100,last_close:110});assert.equal(r.status,'CLOSED');assert.ok(r.return_pct>9&&r.return_pct<11);assert.equal(r.directional_vote,false);});
test('Binance history with gaps fails closed',()=>{assert.equal(normalizeBinanceHistoryFeature({span_days:91,rows:100,gaps:1,first_close:1,last_close:2}).status,'NOT_CLOSED');});
test('Coinbase sequence gap recovers by factual snapshot reload',()=>{const r=recoverCoinbaseSequence({last_sequence:100,event_sequence:103,snapshot_sequence:120});assert.equal(r.status,'CLOSED');assert.equal(r.gap_detected,true);assert.equal(r.recovery,'REST_L2_SNAPSHOT_RELOAD');assert.equal(r.absence_is_negative,false);assert.equal(r.institutional_buying_claim,false);});
test('Coinbase invalid recovery snapshot fails closed',()=>{assert.equal(recoverCoinbaseSequence({last_sequence:100,event_sequence:103,snapshot_sequence:99}).status,'NOT_CLOSED');});
test('Bitget measured utility stays shadow and never voting',()=>{const r=decideBitgetUtility({overlap_pct:87.25,live_context_status:'CLOSED'});assert.equal(r.status,'CLOSED');assert.equal(r.decision,'KEEP_SHADOW_THIRD_VENUE_CONTEXT_ONLY');assert.equal(r.fallback_enabled,false);assert.equal(r.automatic_voting,false);});
test('Hyperliquid recorder audit refuses to invent an absent hot-path recorder',()=>{const r=auditHyperliquidRecorderRuntime({runtime_files:[{path:'src/worker.js',content:'const x=1'}]});assert.equal(r.status,'NOT_CLOSED');assert.equal(r.production_recorder_extension_found,false);});
test('consumer accepts history sequence and utility only as advisory facts',()=>{const r=consumeExistingSourceReceipts({binance_history:{status:'CLOSED',symbol:'BTCUSDT',market:'spot',span_days:91.9,rows:120000,gaps:0,return_pct:5},coinbase_sequence:{status:'CLOSED',snapshot_sequence:200,gap_detected:true,recovery:'REST_L2_SNAPSHOT_RELOAD'},bitget_utility:{status:'CLOSED',decision:'KEEP_SHADOW_THIRD_VENUE_CONTEXT_ONLY',overlap_pct:87.25}});assert.equal(r.status,'CLOSED');assert.ok(r.facts.some(x=>x.source==='Binance Public Data Archive'));assert.ok(r.facts.some(x=>x.source==='Coinbase Exchange'&&x.gap_detected===true));assert.ok(r.facts.some(x=>x.source==='Bitget'&&x.enabled_as_fallback===false));assert.ok(r.facts.every(x=>x.advisory_only&&x.directional_vote===false&&x.hard_gate===false));});
