import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {createD1SourceAdmission} from '../src/d1-source-admission.mjs';
const T=1790501760000;
function fixture(){const s=new DatabaseSync(':memory:');s.exec(fs.readFileSync(new URL('../integration/source-quota-shadow.sql',import.meta.url),'utf8'));let batchCalls=0,omitReadback=false;
 s.prepare('INSERT INTO report2_liq_source_allowance_shadow(scope_id,provider,unit,window_start_ts,window_end_ts,allowance_units,config_fingerprint,shared_quota_reviewed,active) VALUES(?,?,?,?,?,?,?,?,?)').run('scope-hl','HYPERLIQUID','REQUEST',T-1000,T+600000,20,'policy-hash',1,1);
 const norm=(sql,args)=>{const positions=[];const q=sql.replace(/\?(\d+)/g,(_,n)=>{positions.push(Number(n)-1);return '?';});return [q,positions.length?positions.map(i=>args[i]):args];};
 const db={prepare(sql){return{sql,args:[],bind(...a){this.args=a;return this;}};},async batch(stmts){batchCalls++;if(omitReadback&&batchCalls===3)return [];s.exec('BEGIN');try{const out=stmts.map(q=>{const [sql,args]=norm(q.sql,q.args);if(/^\s*SELECT/.test(sql))return{success:true,results:s.prepare(sql).all(...args),meta:{changes:0}};const r=s.prepare(sql).run(...args);return{success:true,results:[],meta:{changes:Number(r.changes)}};});s.exec('COMMIT');return out;}catch(e){s.exec('ROLLBACK');throw e;}}};
 return{s,db,get calls(){return batchCalls;},omit:()=>{omitReadback=true},close:()=>s.close()};}
const request=()=>({reservation_id:'test-res',run_id:'run',contract:'FIL-USDT',requests:{HYPERLIQUID:5},max_requests:5,deadline_ts:T+45000});
const build=(f,binding={})=>createD1SourceAdmission({db:f.db,clock:()=>T,scope_bindings:{HYPERLIQUID:{scope_id:'scope-hl',config_fingerprint:'policy-hash',...binding}},within_run_budget:()=>({allowed:true})});
test('exact D1 allowance five units recorded and read back',async()=>{const f=fixture();try{const r=await build(f)(request());assert.equal(r.allowed,true);assert.equal(f.s.prepare('SELECT used_units FROM report2_liq_source_allowance_shadow').get().used_units,5);}finally{f.close();}});
test('negative: empty D1 readback is not a successful factual reservation',async()=>{const f=fixture();try{f.omit();const r=await build(f)(request());assert.equal(r.allowed,false);}finally{f.close();}});
test('negative: extra config units cannot silently underreserve a requested batch',async()=>{const f=fixture();try{const r=await build(f,{units:1})(request());assert.equal(r.allowed,true);assert.equal(f.s.prepare('SELECT used_units FROM report2_liq_source_allowance_shadow').get().used_units,5);}finally{f.close();}});
test('negative: unknown deadline cannot reserve even if all balances exist',async()=>{const f=fixture();try{const r=await build(f)({...request(),deadline_ts:undefined});assert.equal(r.allowed,false);assert.equal(f.calls,0);}finally{f.close();}});
test('negative: stated maximum must equal the requested provider counts',async()=>{const f=fixture();try{const r=await build(f)({...request(),max_requests:1});assert.equal(r.allowed,false);assert.equal(f.calls,0);}finally{f.close();}});
test('retry and spent balance do not acquire a second network authorization',async()=>{const f=fixture();try{const a=build(f);assert.equal((await a(request())).allowed,true);assert.equal((await a(request())).allowed,false);assert.equal(f.s.prepare('SELECT used_units FROM report2_liq_source_allowance_shadow').get().used_units,5);}finally{f.close();}});
