import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const root=path.resolve(process.argv[2]||'runtime'),load=rel=>import(pathToFileURL(path.join(root,rel)).href);
const {RemoteD1Database}=await load('report2-d1-adapter.mjs');
const {reserveEvidenceSourceAttempts,reserveEvidenceSourceCredits}=await load('src/evidence-source-store.mjs');
const {SOURCE_POLICIES}=await load('src/evidence-source-adapters.mjs');
const {createUnifiedHttpBudget}=await load('src/unified-budget.mjs');
const budget=createUnifiedHttpBudget(),policy=SOURCE_POLICIES.BLOCKSCOUT_INDEX;
const key=String(process.env.BLOCKSCOUT_PRO_API_KEY||'').trim();assert.ok(key,'EXISTING_SOURCE_KEY_REQUIRED');
const db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN);
const now=Date.now(),reservation_id=`SOURCE_AUDIT:${process.env.GITHUB_RUN_ID}:BLOCKSCOUT_BACKOFF_ONE_REQUEST`;
const whole=budget.reserve({logical_request_id:reservation_id,lane:'background',attempts:1});assert.equal(whole.allowed,true);
const attempt=await reserveEvidenceSourceAttempts(db,{source:'BLOCKSCOUT_INDEX',reservation_id,attempts:1,daily_cap:policy.daily_cap,now});assert.equal(attempt.allowed,true,'SOURCE_ATTEMPT_CAP');
const credit=await reserveEvidenceSourceCredits(db,{source:'BLOCKSCOUT_INDEX',reservation_id:`CREDIT:${reservation_id}`,credits:30,daily_credit_cap:policy.daily_credit_cap,now});assert.equal(credit.allowed,true,'SOURCE_CREDIT_CAP');
const url='https://api.blockscout.com/56/api/v2/tokens/0x444045b0ee1ee319a660a5e3d604ca0ffa35acaa/transfers';
const response=await fetch(url,{headers:{accept:'application/json',authorization:`Bearer ${key}`,'user-agent':'My-Report-2/blockscout-index-v1'},signal:AbortSignal.timeout(8000)});
const body=await response.text();assert.ok(!body.includes(key),'RESPONSE_SECRET_ECHO');
const remaining=response.headers.get('x-credits-remaining');
const capture={url,http_status:response.status,credits_remaining:remaining,body,body_sha256:createHash('sha256').update(body).digest('hex'),observed_ts:Date.now(),actual_source_http:1,reserved_credits:30};
fs.writeFileSync('audit-output/blockscout-actual-response.json',JSON.stringify(capture,null,2)+'\n');
assert.ok([404,410].includes(response.status),'ACTUAL_UNSUPPORTED_ROUTE_NOT_CONFIRMED');
class Stmt{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new Stmt(this.db,this.sql,args);}async run(){return this.db.sqlite.prepare(this.sql).run(...this.args);}async first(){return this.db.sqlite.prepare(this.sql).get(...this.args)||null;}}
class MemoryDB{constructor(){this.sqlite=new DatabaseSync(':memory:');}prepare(sql){return new Stmt(this,sql);}async batch(rows){this.sqlite.exec('BEGIN');try{const results=[];for(const row of rows)results.push(await row.run());this.sqlite.exec('COMMIT');return results;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}}
const prior='6e5d5c8c5a9a8b35c4c3c02aea8dd63d23896866';
const beforePath=path.join(root,'src/blockscout-index-before.mjs');
fs.writeFileSync(beforePath,execFileSync('git',['show',`${prior}:current-generation/files/src/blockscout-index-evidence.mjs`]));
const before=await import(pathToFileURL(beforePath).href),after=await load('src/blockscout-index-evidence.mjs');
async function replay(module,strict=false){const db=new MemoryDB();let calls=0;const outputs=[];
 const fetch_impl=async()=>{calls++;return new Response(body,{status:response.status,headers:remaining===null?{}:{'x-credits-remaining':remaining}});};
 for(let i=0;i<2;i++)outputs.push(await module.collectBlockscoutIndexEvidence({db,fetch_impl,request_admit:()=>({allowed:true}),contract:'BTW-USDT',run_id:`REPLAY-${i}`,asset_identity:{chain:'bsc',contract_or_mint:'0x444045b0ee1ee319a660a5e3d604ca0ffa35acaa'},blockscout_api_key:'REPLAY_ONLY',main_index_failure_backoff:true,strict_fresh_manual:strict,now:Date.now()+i*40*60_000}));
 return{calls,credits:db.sqlite.prepare("SELECT credits FROM report2_evidence_source_credit_daily WHERE source='BLOCKSCOUT_INDEX'").get().credits,outputs};}
const baseline=await replay(before),candidate=await replay(after),fresh=await replay(after,true);
assert.equal(baseline.calls,2);assert.equal(baseline.credits,60);assert.equal(candidate.calls,1);assert.equal(candidate.credits,30);assert.equal(candidate.outputs[1].status,'SOURCE_ERROR_BACKOFF');assert.equal(candidate.outputs[1].evidence.length,0);assert.equal(fresh.calls,2);
fs.unlinkSync(beforePath);
const usage=db.usageSnapshot();assert.ok(usage.rows_read<=500&&usage.rows_written<=50&&usage.unknown_ops===0,'BOUNDED_D1_LEDGER_USAGE');
const result={status:'EXACT_ACTUAL_RESPONSE_BACKOFF_ACCEPTED',github_head:process.env.GITHUB_SHA,prior_main:prior,actual_source_http:1,body_sha256:capture.body_sha256,http_status:response.status,baseline,candidate,strict_fresh:fresh,production_writes_scope:'SOURCE_QUOTA_LEDGER_ONLY',database_usage:usage,telegram_calls:0,main_accepted:false,secrets_included:false};
fs.writeFileSync('audit-output/blockscout-live-replay.json',JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({status:result.status,actual_source_http:1,http_status:response.status,before_calls:2,after_calls:1,telegram_calls:0}));
