import fs from 'node:fs';
import path from 'node:path';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(process.argv[2]||'runtime');
const load=rel=>import(pathToFileURL(path.join(root,rel)).href);
const {parseHtxTradePayload}=await load('src/htx-trade-json.mjs');
const worker=fs.readFileSync(path.join(root,'src/worker.js'),'utf8');
const source=worker.replace(/from (['"])\.\/([^'"\n]+)\1/g,(_,quote,name)=>`from ${JSON.stringify(pathToFileURL(path.join(root,'src',name)).href)}`);
const api=await import('data:text/javascript;base64,'+Buffer.from(source+'\nexport {normalizeKlines,flattenTrades,sortedTrades,buildTrajectoryWindow};\n').toString('base64'));
const bodies={};
for(const name of ['trades','klines'])bodies[name]=gunzipSync(fs.readFileSync(new URL(`./fixtures/${name}.json.gz`,import.meta.url)));
const hash=b=>createHash('sha256').update(b).digest('hex');
assert.equal(hash(bodies.trades),'a044d735326affa47faab60f16230ecfdf3871ea8a5f367881471e80d25fcdbc');
assert.equal(hash(bodies.klines),'5098793ae72c4217ba1659ed34711a62a781a0269c2ba79eb4eddae350c86f03');
const trades=api.sortedTrades(api.flattenTrades(parseHtxTradePayload(bodies.trades.toString())));
const endMs=Date.parse('2026-10-04T09:45:00Z'),startMs=endMs-86_400_000;
const window=api.buildTrajectoryWindow({label:'24h',startMs,endMs,klines:api.normalizeKlines(JSON.parse(bodies.klines)),orderedTrades:trades,contractSize:1,minTrades:20,oi:{usable:false}});
assert.equal(window.price.received_1m_bars,1440);
assert.equal(window.price.trade_count,15694);
assert.equal(window.order_flow.usable,false);
assert.equal(window.order_flow.history_covers_window_start,false);
const result={schema:'report2-actual-htx-flow-replay-v1',github_head:process.env.GITHUB_SHA||null,worker_sha256:hash(worker),contract:'BTW-USDT',actual_public_http:2,acceptance_replay_http:0,trades_sha256:hash(bodies.trades),klines_sha256:hash(bodies.klines),captured_at:'2026-10-04T09:45:40.814Z',window,telegram_calls:0,main_accepted:false};
fs.writeFileSync('audit-output/actual-htx-flow-replay.json',JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({status:'ACTUAL_WIRE_REPLAY_REJECTS_INCOMPLETE_24H',factual_count:window.price.trade_count,flow_usable:window.order_flow.usable,telegram_calls:0}));
