import fs from 'node:fs';
import assert from 'node:assert/strict';
const workflow=fs.readFileSync('.github/workflows/report2.yml','utf8');
const declared=workflow.match(/cron: "([^"]+)"/)[1];
const guard=workflow.match(/github.event.schedule == '([^']+)'/)[1];
assert.equal(declared,guard,'Declared schedule must admit the analytics job');
assert.equal(declared,'7,27,47 * * * *');
const minutes=declared.split(' ')[0].split(',').map(Number);
assert.deepEqual(minutes,[7,27,47]);
assert.deepEqual([minutes[1]-minutes[0],minutes[2]-minutes[1],60+minutes[0]-minutes[2]],[20,20,20]);
assert.equal(minutes.length*24,72);
assert.match(workflow,/needs.execution-gate.outputs.admitted == 'true'/);
assert.equal(JSON.parse(fs.readFileSync('REPORT2_CURRENT_GENERATION.json')).scheduled_analytics_minimum_interval_minutes,40);
console.log(JSON.stringify({status:'SCHEDULE_DECLARATION_AND_JOB_GUARD_MATCH',cron:declared,interval_minutes:20,effective_minimum_minutes:40,quota_increased:false}));
