import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeInheritedTimestamp,parseCexContract,buildInheritedCexIdentity,normalizeInheritedFact,normalizeInheritedFactEnvelope} from '../src/inherited-fact-contract.mjs';

const now=1790345443688;
const htx={contract_code:'DOT-USDT',source:'HTX_OFFICIAL_VIA_REPORT2_HUB',venue:'HTX',metric:'htx_oi_1h_change_pct',status:'CLOSED',value:1.2,unit:'pct',market_type:'USDT_PERP',primary_market_id:'DOT-USDT:HTX:USDT_PERP',symbol_verified:true,asset_identity_verified:false,alias_required:false,source_compatible:true,source_ts:now,observed_ts:now,coverage_pct:100};

test('sec ms us timestamps normalize to same millisecond epoch',()=>{const ms=1790345443000;assert.equal(normalizeInheritedTimestamp(ms).ms,ms);assert.equal(normalizeInheritedTimestamp(ms/1000).ms,ms);assert.equal(normalizeInheritedTimestamp(ms*1000).ms,ms);});
test('quotes remain distinct and ticker-only identity is forbidden',()=>{assert.deepEqual(parseCexContract('AAA-USDT'),{base:'AAA',quote:'USDT'});assert.deepEqual(parseCexContract('AAA-USDC'),{base:'AAA',quote:'USDC'});const bad=buildInheritedCexIdentity({...htx,primary_market_id:null});assert.equal(bad.status,'NOT_CLOSED');assert.equal(bad.ticker_only_identity,false);});
test('exact HTX venue instrument closes without inventing chain or multiplier',()=>{const i=buildInheritedCexIdentity(htx);assert.equal(i.status,'CLOSED');assert.equal(i.asset_identity_verification_method,'EXACT_VENUE_INSTRUMENT_NO_ALIAS_REQUIRED');assert.equal(i.chain_status,'NOT_APPLICABLE_CEX');assert.equal(i.contract_or_mint_status,'NOT_APPLICABLE_CEX');assert.equal(i.multiplier_status,'NOT_APPLICABLE_FOR_METRIC');});
test('alias-required instrument must have explicit asset identity proof',()=>{const i=buildInheritedCexIdentity({...htx,venue:'OKX',primary_market_id:'DOT-USDT-SWAP',alias_required:true,asset_identity_verified:false});assert.equal(i.status,'NOT_CLOSED');});
test('full fact contract inherits factual envelope quality without zero invention',()=>{const f=normalizeInheritedFact(htx,{default_quality_status:'PARTIAL'});assert.equal(f.fact_contract_status,'CLOSED');assert.equal(f.identity_status,'CLOSED');assert.equal(f.quality_status,'PARTIAL');assert.equal(f.raw_value,1.2);assert.equal(f.normalized_value,1.2);assert.equal(f.missing_is_zero,false);assert.equal(f.cross_venue_values_averaged,false);});
test('explicit missing semantic status stays null not zero',()=>{const f=normalizeInheritedFact({...htx,status:'BUDGET_EXHAUSTED',value:null},{default_quality_status:'PARTIAL'});assert.equal(f.status,'BUDGET_EXHAUSTED');assert.equal(f.raw_value,null);assert.equal(f.normalized_value,null);assert.equal(f.missing_is_zero,false);});
test('envelope retains all facts independently',()=>{const e=normalizeInheritedFactEnvelope([htx,{...htx,venue:'OKX',source:'OKX Public V5',primary_market_id:'DOT-USDT-SWAP',asset_identity_verified:true,alias_required:true}],{default_quality_status:'PARTIAL'});assert.equal(e.counts.total,2);assert.equal(e.counts.identity_closed,2);assert.equal(e.counts.fact_contract_closed,2);assert.equal(e.cross_venue_values_averaged,false);});
