import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
test('architecture overlay is small and never carries worker.js',()=>{const paths=[...manifest.existing_files,...manifest.new_files].map(x=>x.path);assert.equal(paths.some(x=>/worker\.js$/.test(x)),false);assert.ok(paths.length<=10);});
test('overlay starts from exact V4 module hashes',()=>{const expected={'src/capability-registry.mjs':'e1c4841a17ad945211dd42ac5baca1d105cda290fd91481125e544e6b0f8ea40','src/source-registry.mjs':'513db290f3e914a65b52d7413d757d0306be57076b542a73fabc2c6985714045','src/funnel-diagnostics.mjs':'ef35f3164d273a935bcfbde7e755ba55b166a30bea4ce8f5a3e623278ad5a478','src/canonical-runtime-adapter.mjs':'4d0a28be8c3b2c59f08e8e339b768b384bc11513f7b6193c833ed6ecb3a68428','src/manual-report-formatter.mjs':'7014e86d17626fab4ac11e35a4cf4717a6ec7101ba2bee5a262aea226f067c2f','src/telegram-compact-formatter.mjs':'461486b66ec265fcbd5007ddb52ef55c232b8dbe48d0fbfe528730bbefedcfe5'};for(const e of manifest.existing_files)assert.equal(e.before_sha256,expected[e.path],e.path);});
test('late layer retains early/free-source feature symbols',()=>{const cap=fs.readFileSync(path.join(root,'src/capability-registry.mjs'),'utf8'),can=fs.readFileSync(path.join(root,'src/canonical-runtime-adapter.mjs'),'utf8'),src=fs.readFileSync(path.join(root,'src/source-registry.mjs'),'utf8');for(const x of ['supporting_risk','onchain','resolveCrossVenueConflict','verifyHtxExecutionIdentity'])assert.match(cap,new RegExp(x));for(const x of ['buildPumpLiquidationZones','earlyCandidate','opportunityCompact','sourceReceipts'])assert.match(can,new RegExp(x));for(const x of ['GoPlus','Solana Public RPC','Bitget','Coinbase Exchange','Deribit'])assert.match(src,new RegExp(x));});


test('canonical final overlay owns exactly one worker copy and replaces historical apply order',()=>{const croot=path.resolve(root,'..','canonical-final-overlay');const m=JSON.parse(fs.readFileSync(path.join(croot,'manifest.json'),'utf8'));const workers=[...m.existing_files,...m.new_files].filter(x=>x.path==='src/worker.js');assert.equal(workers.length,1);assert.equal(m.safety.single_worker_copy,true);assert.deepEqual(m.equivalent_to_sequence,['UNIFIED_OVERLAY_V2','FREE_SOURCES_V4','ARCHITECTURE_CLEANUP_V1']);});
