import test from 'node:test';import assert from 'node:assert/strict';
import {rankCapabilitySources,sourceExhaustion} from '../src/capability-registry.mjs';
const NOW=1_800_000_000_000;
test('NO_RECEIPTS_FAIL_CLOSED',()=>{const r=rankCapabilitySources({metric:'funding',capabilities:[],now:NOW});assert.ok(r.length>0);assert.ok(r.every(x=>x.usable===false));assert.ok(r.every(x=>x.reason==='NO_FACTUAL_CAPABILITY_RECEIPT'));});
test('BLOCKED_SOURCE_NOT_USABLE',()=>{const r=rankCapabilitySources({metric:'funding',capabilities:[{source:'HTX',connected:true,fresh:true,health:'HEALTHY',runtime_state:'BLOCKED',coverage_pct:100}],now:NOW});const h=r.find(x=>x.source==='HTX');assert.equal(h.usable,false);assert.equal(h.runtime_state,'BLOCKED');});
test('stale rate limit timeout are not usable',()=>{const caps=[{source:'HTX',connected:true,source_ts:NOW-100000,max_age_ms:1000,health:'OK'},{source:'Bybit',connected:true,fresh:true,health:'RATE_LIMITED'},{source:'OKX',connected:true,fresh:true,health:'TIMEOUT'}];const r=rankCapabilitySources({metric:'funding',capabilities:caps,now:NOW});assert.ok(r.filter(x=>['HTX','Bybit','OKX'].includes(x.source)).every(x=>x.usable===false));});
test('unknown source is never admitted by static plan',()=>{const r=rankCapabilitySources({metric:'funding',capabilities:[{source:'Mystery',connected:true,fresh:true,health:'HEALTHY',coverage_pct:100}],now:NOW});assert.equal(r.some(x=>x.source==='Mystery'),false);assert.ok(r.every(x=>x.usable===false));});
test('factual attempt can close without static usability',()=>{const r=sourceExhaustion({metric:'spot_flow',capabilities:[],now:NOW,attempts:[{source:'HTX',status:'RATE_LIMITED'},{source:'OKX',status:'CLOSED',value:7.1,source_ts:NOW-1000}]});assert.equal(r.status,'CLOSED');assert.equal(r.source,'OKX');assert.equal(r.selection.reason,'FACTUAL_ATTEMPT_RECEIPT_CLOSED_FAIL_CLOSED_NO_STATIC_USABILITY');});
test('missing stale rate limit timeout values never become zero',()=>{const r=sourceExhaustion({metric:'spot_flow',capabilities:[],now:NOW,attempts:[{source:'HTX',status:'RATE_LIMITED',value:null},{source:'OKX',status:'TIMEOUT',value:null},{source:'Binance',status:'UNSUPPORTED',value:null}]});assert.equal(r.status,'SOURCE_EXHAUSTED');assert.equal(r.value,null);assert.ok(r.trail.every(x=>x.value!==0));});
