import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';

const runtime=path.resolve(process.argv[2]||'');
if(!runtime)throw new Error('RUNTIME_PATH_REQUIRED');
const mod=name=>import(pathToFileURL(path.join(runtime,'src',name)).href);
const [{immutableReceipt},{prepareHtxExecutionFacts},{buildTz101ScenarioPlan},{buildTz101CostAssessment},{buildTz101PublicationGate},{routeEntrySignal},{buildApprovedPublicationInputs}]=await Promise.all([
 mod('upstream-proof-utils.mjs'),mod('tz101-execution-facts.mjs'),mod('tz101-scenario-plan.mjs'),mod('tz101-cost-assessment.mjs'),mod('tz101-publication-gate.mjs'),mod('entry-signal-router.mjs'),mod('user-approved-publication-policy.mjs'),
]);

const NOW=Date.UTC(2026,8,27,21,0,0),CONTRACT='TEST-USDT',SNAP='S392:TEST:APPROVED';
const campaign={campaign_id:'MW:TEST:APPROVED',schema_version:'multi-wave-decision-state-v1',rules_version:'multi-wave-decision-state-rules-v1',contract_code:CONTRACT,campaign_start:NOW-20*60_000,first_detected_time:NOW-20*60_000,last_observed_ts:NOW-1_000,campaign_end:null,current_phase:'ENTRY_TRIGGER',direction:'LONG',direction_at_detection:'LONG',direction_locked_ts:NOW-19*60_000,direction_lock_observation_id:'E1',wave_index:1,completed_wave_count:0,current_wave_id:'MW:TEST:APPROVED:W1',base_start:null,entry_trigger_time:NOW-60_000,entry_trigger_price:100.5,impulse_start:null,impulse_start_price:null,impulse_peak_price:null,impulse_peak_ts:null,exhaustion_warning_ts:null,edge_spent_ts:null,last_event_id:'E1',last_event_ts:NOW-2_000,origin_episode_id:'EP1',episode_revision:1,state_revision:4,observation_id:'OBS4',wave_facts_immutable:true,cas_persisted:true,wave_ledger_offset:0,wave_ledger_anchor:null,transition_history:[],history_truncated:false,history_anchor:null,wave_ledger:[]};
const anchor={schema_version:'multi-wave-entry-scenario-anchor-v1',rules_version:'multi-wave-campaign-v1',scenario_type:'FIRST_IMPULSE_THRESHOLD',campaign_id:campaign.campaign_id,contract_code:CONTRACT,wave_index:1,direction:'LONG',source_phase:'ENTRY_TRIGGER',source_observation_ts:campaign.last_observed_ts,base_start:NOW-10*60_000,base_low:94,base_high:101,entry_trigger_time:campaign.entry_trigger_time,entry_trigger_price:100.5,invalidation_price:94,invalidation_basis:'PRECOMMITTED_CAMPAIGN_BASE_BREAK',target_move_pct:6,target_price:106.53,target_basis:'PRECOMMITTED_BASE_MEASURED_FAVORABLE_MOVE',prospective_only:true};
const entryWindow={status:'CLOSED',contract_code:CONTRACT,snapshot_id:SNAP,campaign_id:campaign.campaign_id,wave_id:campaign.current_wave_id,campaign_state_revision:4,observation_id:'OBS4',action_id:'FDE:APPROVED',single_use:true,consumed:false,source_ts:campaign.entry_trigger_time,valid_until_ts:NOW+10*60_000,max_age_ms:30*60_000,persistence:{status:'CLOSED'}};
const proof=immutableReceipt({schema_version:'multi-wave-decision-bridge-v1',status:'SHADOW_CAMPAIGN_EVALUATED',snapshot_id:SNAP,admitted_event_id:'E1',observation_id:'OBS4',campaign,chase_risk:{status:'CLOSED',active:false,contract_code:CONTRACT,snapshot_id:SNAP,source_ts:campaign.last_observed_ts,available_ts:campaign.last_observed_ts,max_age_ms:60_000,valid_until_ts:NOW+60_000,rules_version:'chase-risk-state-v1'},entry_window:entryWindow,entry_scenario_anchor:anchor},`CMR:${campaign.campaign_id}:4:OBS4`,campaign.last_observed_ts);
const decision={decision_id:'FD:APPROVED',snapshot_id:SNAP,contract_code:CONTRACT,observation_ts:NOW,direction:'LONG',entry_action:'SHADOW_ENTRY_ELIGIBLE',entry_action_id:'FDE:APPROVED',entry_quality:'CLOSED',data_quality:'CLOSED',execution_quality:'CLOSED',independence_state:'CLOSED',timing_state:'ENTRY_WINDOW',risk_state:'CLEAR',hard_veto:false,hard_veto_state:'CLEAR',campaign_receipt_id:proof.persistence.receipt_id,safety_gate_receipt_id:'SGR:APPROVED'};
const prepared=prepareHtxExecutionFacts({contract_code:CONTRACT,requested_notional_usdt:1000,received_ts:NOW-500,info_response:{ok:true,data:{status:'ok',ts:NOW-2_000,data:[{contract_code:CONTRACT,contract_size:1,price_tick:.1,contract_status:1}]}},depth_response:{ok:true,data:{status:'ok',ch:`market.${CONTRACT}.depth.step0`,ts:NOW-600,tick:{ts:NOW-700,bids:[[100.4,100],[100.3,100]],asks:[[100.5,100],[100.6,100]]}}}});
const execution={authoritative:true,snapshot_id:SNAP,contract_code:CONTRACT,safety_gate_receipt_id:'SGR:APPROVED',factual_basis:prepared};
const evidence=[{status:'CLOSED',eligible_for_decision:true,stance:'LONG',snapshot_id:SNAP,contract_code:CONTRACT,causal_family:'PRICE_RESPONSE'},{status:'CLOSED',eligible_for_decision:true,stance:'LONG',snapshot_id:SNAP,contract_code:CONTRACT,causal_family:'RELATIVE_STRENGTH'}];
const policy=buildApprovedPublicationInputs({decision_summary:decision,observed_ts:NOW});assert.equal(policy.status,'CLOSED');
const scenario=buildTz101ScenarioPlan({decision_summary:decision,campaign_proof:proof,execution_gate:execution,decision_evidence:evidence,entry_area_rule:policy.entry_area_rule,observed_ts:NOW});
assert.equal(scenario.status,'CLOSED',JSON.stringify(scenario));assert.ok(scenario.remaining_move_pct>0);assert.equal(scenario.minimum_reportable_move_pct,null);assert.equal(scenario.begin_close_price,scenario.target_price);
const funding={rate_pct:.02,interval_hours:8,observed_ts:NOW-1_000,next_funding_time_ts:NOW+2*60*60_000};
const costs=buildTz101CostAssessment({decision_summary:decision,execution_gate:execution,scenario_plan:scenario,funding_context:funding,fee_schedule:policy.fee_schedule,holding_plan:policy.holding_plan,observed_ts:NOW});
assert.equal(costs.status,'CLOSED',JSON.stringify(costs));assert.ok(costs.funding_cost_usdt>0);assert.equal(costs.funding_basis,'CONSERVATIVE_FUNDING_RESERVE');
const gate=buildTz101PublicationGate({final_decision:decision,score_interval:{is_probability:false,score_lower_bound:75,score_upper_bound:80,wholly_missing_blocks:[],weighted_blocks:[]},scenario_plan:scenario,cost_assessment:costs,funding_context:funding,liquidation_context:{status:'PARTIAL'},observed_ts:NOW});
assert.equal(gate.status,'CLOSED',JSON.stringify(gate));
const route=routeEntrySignal({final_decision:decision,publication_gate:gate,scenario_plan:scenario,current_price:scenario.execution_reference_price,observed_ts:NOW,validation_status:'OPEN',structure_interesting:true,useful_observation:true});
assert.equal(route.state,'ENTRY_NOW_ANALYTICAL',JSON.stringify(route));assert.equal(route.reason,'STRICT_ANALYTICAL_ENTRY_CLOSED');
console.log(JSON.stringify({status:'APPROVED_ENTRY_PATH_REACHABLE',scenario:scenario.status,costs:costs.status,gate:gate.status,route:route.state,minimum_move_pct:scenario.remaining_move_pct}));
