import test from 'node:test';
import assert from 'node:assert/strict';
import {reconcileBitgetFlow,acquireBitgetFourHourFlow,exactBitgetBinding} from '../files/src/bitget-four-hour-flow.mjs';
const end=1791633600000,start=end-14400000;
const fixture=()=>({contract:'LINK-USDT',market:'SPOT',window_end_ts:end,observed_ts:end+1000,candles:{code:'00000',data:Array.from({length:240},(_,i)=>[String(start+i*60000),'2','2','2','2','1.00000000','2.00000000','2.00000000'])},pages:[{code:'00000',data:Array.from({length:240},(_,i)=>({symbol:'LINKUSDT',tradeId:String(1000-i),ts:String(end-(i+1)*60000+5),side:i%2?'Buy':'Sell',price:'2',size:'1'}))}]});
test('all 240 native minutes match both base and quote before directional context',()=>{const r=reconcileBitgetFlow(fixture());assert.equal(r.check_completed,true);assert.equal(r.buy_quote,240);assert.equal(r.sell_quote,240);assert.equal(r.verified_minutes,240);assert.equal(r.raw_trade_counter_independently_verified,false);assert.equal(r.score_contribution,0);});
test('missing fills, duplicate IDs, missing minutes, foreign instruments and unit mistakes fail closed',()=>{for(const mutate of [f=>f.pages[0].data.pop(),f=>f.pages[0].data[1].tradeId=f.pages[0].data[0].tradeId,f=>f.candles.data.pop(),f=>f.pages[0].data[0].symbol='OTHERUSDT',f=>f.pages[0].data[0].size='1000',f=>f.pages[0].data[0].ts=String(end)]){const f=fixture();mutate(f);assert.equal(reconcileBitgetFlow(f).check_completed,false);}});
test('displayed zero is exact zero, no one-unit tolerance invents missing volume',()=>{const f=fixture();f.candles.data[0][5]='0';f.candles.data[0][6]='0';f.candles.data[0][7]='0';assert.equal(reconcileBitgetFlow(f).check_completed,false);});
test('same-timestamp pagination keeps ID boundary and fixed time window',async()=>{const f=fixture(),seen=[];const r=await acquireBitgetFourHourFlow({...f,clock:()=>end+1000,get:async(url,part)=>{seen.push(url);return part.kind==='candles'?f.candles:f.pages[0];}});assert.equal(r.check_completed,true);assert.equal(seen.length,2);assert.ok(seen.every(u=>u.includes('endTime='+String(end-1))));});
test('ticker alone and wrapped native token cannot authorize exact asset flow',()=>{const base={contract:'BTC-USDT',identity:{chain:'bitcoin',asset_kind:'NATIVE',native_asset_id:'bitcoin:mainnet',contract_or_mint:null},market:'SPOT',instrument:{symbol:'BTCUSDT',baseCoin:'BTC',quoteCoin:'USDT',status:'online'},coins:{code:'00000',data:[{coin:'BTC',chains:[{chain:'BEP20',contractAddress:'0x123'}]}]}};assert.equal(exactBitgetBinding(base),false);base.coins.data[0].chains.push({chain:'BTC',contractAddress:null});assert.equal(exactBitgetBinding(base),true);});

test('two ID pages retain multiple trades sharing one millisecond',async()=>{const f=fixture();f.candles.data.forEach(r=>{r[5]='6.00000000';r[6]=r[7]='12.00000000';});const rows=Array.from({length:1440},(_,i)=>({symbol:'LINKUSDT',tradeId:String(5000-i),ts:String(end-(Math.floor(i/6)+1)*60000+5),side:i%2?'Buy':'Sell',price:'2',size:'1'}));const cursors=[];const r=await acquireBitgetFourHourFlow({...f,clock:()=>end+1000,get:async(url,part)=>{if(part.kind==='candles')return f.candles;cursors.push(part.cursor);return{code:'00000',data:part.page===0?rows.slice(0,1000):rows.slice(1000)};}});assert.equal(r.check_completed,true);assert.equal(r.trade_count,1440);assert.deepEqual(cursors,[null,'4001']);assert.equal(r.pages,2);});

test('recent slices use only reconciled original fills without another request',()=>{const r=reconcileBitgetFlow(fixture());assert.equal(r.recent_windows[0].trade_count,15);assert.equal(r.recent_windows[1].trade_count,60);assert.equal(r.recent_windows[0].buy_quote+r.recent_windows[0].sell_quote,30);assert.equal(r.large_individual_trades_available,true);});
