import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {collectBitgetFlow} from '../files/src/bitget-flow-collector.mjs';
import {installEvidenceSourceStore,writeEvidenceSourceCache} from '../files/src/evidence-source-store.mjs';
import {installProviderMinuteLedger} from '../files/src/provider-minute-ledger.mjs';
class Statement{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new Statement(this.db,this.sql,args);}async run(){return this.db.s.prepare(this.sql).run(...this.args);}async first(){return this.db.s.prepare(this.sql).get(...this.args)||null;}}
class DB{constructor(){this.s=new DatabaseSync(':memory:');}prepare(sql){return new Statement(this,sql);}async batch(rows){return Promise.all(rows.map(r=>r.run()));}}
const end=1791633600000,now=end+1000,identity={chain:'ethereum',contract_or_mint:'0x514910771af9ca656af840dff83e8264ecf986ca'},VERSION='bitget-flow-collector-v1-20261010',SOURCE='N05_OFFICIAL_FLOW:BITGET';
async function warm(db){await installEvidenceSourceStore(db);await installProviderMinuteLedger(db);for(const [kind,payload] of Object.entries({coins:{code:'00000',data:[{coin:'LINK',chains:[{chain:'ERC20',contractAddress:identity.contract_or_mint}]}]},spot:{code:'00000',data:[{symbol:'LINKUSDT',baseCoin:'LINK',quoteCoin:'USDT',status:'online'}]},futures:{code:'00000',data:[{symbol:'LINKUSDT',baseCoin:'LINK',quoteCoin:'USDT',symbolStatus:'normal',symbolType:'perpetual'}]}}))await writeEvidenceSourceCache(db,{source:SOURCE,asset_key:'METADATA:'+kind,observed_ts:now-60000,expires_ts:now+3600000,payload:{version:VERSION,observed_ts:now-60000,payload,receipt:{body_sha256:'a'.repeat(64),received_ts:now-60000,http_status:200}}});}
const candles={code:'00000',data:Array.from({length:240},(_,i)=>[String(end-14400000+i*60000),'2','2','2','2','1.00000000','2.00000000','2.00000000'])},fills={code:'00000',data:Array.from({length:240},(_,i)=>({symbol:'LINKUSDT',tradeId:String(1000-i),ts:String(end-(i+1)*60000+5),side:i%2?'Buy':'Sell',price:'2',size:'1'}))};
const params=db=>({db,contract:'LINK-USDT',asset_identity:identity,identity_method:'HTX_OFFICIAL_CURRENCY_CHAIN_ADDRESS',run_id:'CONTROLLED',now,clock:()=>now,source_health_admit:()=>({allowed:true}),request_admit:()=>({allowed:true})});
test('controlled cached identities permit four bounded transports, two reconciled markets, then immutable zero-HTTP reuse',async()=>{const db=new DB();await warm(db);let actual=0;const p={...params(db),fetch_impl:async u=>{actual++;return new Response(JSON.stringify(u.includes('/candles?')?candles:fills));}};const a=await collectBitgetFlow(p);assert.equal(a.network_calls,4);assert.equal(actual,4);assert.equal(a.components.filter(c=>c.check_completed).length,2);const b=await collectBitgetFlow({...p,run_id:'NEXT'});assert.equal(b.network_calls,0);assert.equal(actual,4);assert.equal(b.components[0].observed_ts,a.components[0].observed_ts);assert.equal(b.components[0].window_end_ts,end);});
test('durable backoff and denied D1 headroom stop before any provider transport',async()=>{const db=new DB();await warm(db);let actual=0;const p={...params(db),fetch_impl:async()=>{actual++;throw Error('UNEXPECTED_HTTP');}};await writeEvidenceSourceCache(db,{source:'N05_PROVIDER_BACKOFF:BITGET',asset_key:'SHARED',observed_ts:now-1000,expires_ts:now+900000,payload:{http_status:403}});const r=await collectBitgetFlow(p);assert.equal(r.network_calls,0);assert.equal(r.components.some(c=>c.check_completed),false);const denied=await collectBitgetFlow({...p,source_health_admit:()=>({allowed:false})});assert.equal(denied.status,'FLOW_DB_HEADROOM_REQUIRED');assert.equal(actual,0);});
test('partial fills and exhausted durable daily cap do not fabricate zero flow',async()=>{const db=new DB();await warm(db);const p={...params(db),fetch_impl:async u=>new Response(JSON.stringify(u.includes('/candles?')?candles:{...fills,data:fills.data.slice(0,239)}))};const r=await collectBitgetFlow(p);assert.equal(r.components.some(c=>c.check_completed),false);assert.equal(r.components[0].buy_quote,null);await db.prepare("UPDATE report2_evidence_source_daily SET attempts=16 WHERE source=?1").bind(SOURCE).run();let actual=0;const b=await collectBitgetFlow({...p,run_id:'DENIED',fetch_impl:async()=>{actual++;throw Error('UNEXPECTED');}});assert.equal(b.network_calls,0);assert.equal(actual,0);assert.equal(b.components.some(c=>c.check_completed),false);});
