import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
const root=process.env.REPORT2_CACHE_TRANSPORT_ROOT||fileURLToPath(new URL('../files/src/',import.meta.url));
const load=name=>import(pathToFileURL(path.resolve(root,name)).href);
const {reuseEvidenceSourceResult,installEvidenceSourceStore,writeEvidenceSourceCache}=await load('evidence-source-store.mjs');
const {normalizeCoingeckoSector,collectCoingeckoSectorEvidence,COINGECKO_SECTOR_VERSION}=await load('coingecko-sector-evidence.mjs');
const {normalizeCoinpaprikaSector,collectCoinpaprikaSectorEvidence,COINPAPRIKA_SECTOR_VERSION}=await load('coinpaprika-sector-evidence.mjs');
const {collectBlockscoutIndexEvidence,BLOCKSCOUT_INDEX_EVIDENCE_VERSION}=await load('blockscout-index-evidence.mjs');
const f=JSON.parse(fs.readFileSync(new URL('./fixtures/ready-sector-36745185948.json',import.meta.url)));
const T=f.provenance.observed_ts,link={chain:'ethereum',contract_or_mint:'0x514910771af9ca656af840dff83e8264ecf986ca'},jup={chain:'solana',contract_or_mint:'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN'};
const gm={coingecko_id:'chainlink',coingecko_category_id:'oracle',coingecko_category_name:'Oracle'};
function db(){const sql=new DatabaseSync(':memory:');return{sql,prepare(s){return{args:[],bind(...a){this.args=a;return this;},async run(){return sql.prepare(s).run(...this.args);},async first(){return sql.prepare(s).get(...this.args)||null;},async all(){return{results:sql.prepare(s).all(...this.args)};}};},async batch(rows){return Promise.all(rows.map(r=>r.run()));}};}
// Actual retained provider projections, unchanged original clocks. Transport
// envelopes below are explicit component controls, not a second live call.
function transport(r,version,requests=3){return{...r,version,network_calls:requests,admission:{allowed:true,status:'OLD_GRANT'},whole_job_admission:{allowed:true},credit_admission:{allowed:true},route_credit_cost:30,receipts:[{route:'ORIGINAL_ROUTE',status:'RECEIVED',actual_http:1,http_status:200,received_ts:T}]};}
function cg(){return transport(normalizeCoingeckoSector({...f.coingecko,identity:link,contract:'LINK-USDT',coin_id:'chainlink',category_id:'oracle',category_name:'Oracle',observed_ts:T}),COINGECKO_SECTOR_VERSION);}
function cp(){return transport(normalizeCoinpaprikaSector({...f.coinpaprika,identity:jup,contract:'JUP-USDT',coin_id:'jup-jupiter-exchange-token',tag_id:'exchange',observed_ts:T}),COINPAPRIKA_SECTOR_VERSION);}
function noNetwork(){let n=0,a=0;return{fetch_impl:async()=>{n++;throw Error('NO_NEW_HTTP');},request_admit:()=>{a++;throw Error('NO_NEW_ADMISSION');},assert(){assert.equal(n,0);assert.equal(a,0);}};}
function sameFact(before,after){assert.deepEqual(after.evidence,before.evidence);assert.deepEqual(after.summary,before.summary);assert.equal(after.network_calls,0);assert.match(after.cache_status,/CACHE_HIT/);assert.equal(after.admission,null);assert.equal(after.whole_job_admission,null);assert.equal(after.credit_admission,null);assert.equal(after.route_credit_cost,0);assert.deepEqual(after.original_transport.receipts,before.receipts);assert.equal(after.original_transport.network_calls,before.network_calls);assert.equal(after.receipts[0].actual_http,0);assert.deepEqual(after.receipts[0].original_receipt,before.receipts[0]);}
test('original-clock actual provider context survives transport-only reuse',()=>{for(const r of [cg(),cp()]){assert.equal(r.status,'CLOSED');const copy=JSON.parse(JSON.stringify(r));sameFact(r,reuseEvidenceSourceResult(r));assert.deepEqual(r,copy);}});
test('CoinGecko complete-context cache reuses real facts with zero new HTTP and grants',async()=>{const d=db(),n=noNetwork(),r=cg();await installEvidenceSourceStore(d);await writeEvidenceSourceCache(d,{source:'COINGECKO_SECTOR',asset_key:'LINK-USDT:ethereum:'+link.contract_or_mint+':chainlink:oracle:Oracle',observed_ts:T,expires_ts:r.evidence[0].expires_at,payload:r});const got=await collectCoingeckoSectorEvidence({db:d,contract:'LINK-USDT',asset_identity:link,asset_metadata:gm,run_id:'REUSE',now:T+1000,...n});sameFact(r,got);n.assert();d.sql.close();});
test('CoinPaprika complete-context cache does not repeat the original charged attempts',async()=>{const d=db(),n=noNetwork(),r=cp();await installEvidenceSourceStore(d);await writeEvidenceSourceCache(d,{source:'COINPAPRIKA_SECTOR',asset_key:'JUP-USDT:solana:'+jup.contract_or_mint+':jup-jupiter-exchange-token:exchange',observed_ts:T,expires_ts:r.evidence[0].expires_at,payload:r});const got=await collectCoinpaprikaSectorEvidence({db:d,contract:'JUP-USDT',asset_identity:jup,asset_metadata:{coinpaprika_id:'jup-jupiter-exchange-token',sector_tag:'exchange'},run_id:'REUSE',now:T+1000,...n});sameFact(r,got);n.assert();d.sql.close();});
test('controlled Blockscout transport reuse does not charge old credits again',async()=>{const d=db(),n=noNetwork(),r=transport({status:'CLOSED',evidence:[],summary:null,contract:'LINK-USDT',transfers:[]},BLOCKSCOUT_INDEX_EVIDENCE_VERSION,1);await installEvidenceSourceStore(d);await writeEvidenceSourceCache(d,{source:'BLOCKSCOUT_INDEX',asset_key:'1:'+link.contract_or_mint,observed_ts:T,expires_ts:T+5000,payload:r});const got=await collectBlockscoutIndexEvidence({db:d,contract:'LINK-USDT',asset_identity:link,blockscout_api_key:'CONTROL_KEY_NEVER_SENT',run_id:'REUSE',now:T+1000,...n});sameFact(r,got);n.assert();d.sql.close();});
test('reused failure remains a failure without a new checked event or evidence',()=>{const old={status:'SOURCE_ERROR',evidence:[],network_calls:1,admission:{allowed:false},receipts:[{route:'FAILED_ORIGINAL',status:'SOURCE_ERROR',http_status:403}]};const r=reuseEvidenceSourceResult(old);assert.equal(r.status,'SOURCE_ERROR');assert.deepEqual(r.evidence,[]);assert.equal(r.network_calls,0);assert.equal(r.receipts[0].status,'REUSED_RESULT_CACHE');assert.equal(r.receipts[0].original_receipt.http_status,403);assert.equal(r.original_transport.admission.allowed,false);});
