import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(process.argv[2]||'runtime');
const source=fs.readFileSync(path.join(runtime,'src/worker.js'),'utf8').replace(/from (['"])\.\/([^'"\n]+)\1/g,(_,q,name)=>`from ${JSON.stringify(pathToFileURL(path.join(runtime,'src',name)).href)}`);
const worker=await import('data:text/javascript;base64,'+Buffer.from(source+'\nexport {spotSnapshot,buildShadowDecisionTelemetry};\n').toString('base64'));
const {buildHtxSpotMarketConfirmation,applyCandidateDataRequirements,runOptionalCompactStatistics}=await import(pathToFileURL(path.join(runtime,'src/candidate-data-requirements.mjs')).href);
const {buildFullEvidenceShadowRecord}=await import(pathToFileURL(path.join(runtime,'src/full-evidence-shadow-model.mjs')).href);
const NOW=1790792400000,CONTRACT='NIL-USDT';let calls=0;const realNow=Date.now;Date.now=()=>NOW;
let spot;
try{spot=await worker.spotSnapshot({symbol:CONTRACT,_fetch_json:async url=>{
 calls++;const u=new URL(url);assert.equal(u.searchParams.get('symbol'),'nilusdt');
 if(u.pathname==='/market/detail/merged')return{ok:true,data:{status:'ok',ch:'market.nilusdt.detail.merged',ts:NOW-500,tick:{close:100,bid:[99,100],ask:[100,100],vol:10000,amount:100,count:1}}};
 if(u.pathname==='/market/depth')return{ok:true,data:{status:'ok',ch:'market.nilusdt.depth.step0',ts:NOW-500,tick:{ts:NOW-600,bids:[[99,100]],asks:[[100,100]]}}};
 if(u.pathname==='/market/history/trade')return{ok:true,data:{status:'ok',ch:'market.nilusdt.trade.detail',data:[{data:[{'trade-id':'real-producer-sample',ts:NOW-1000,price:100,amount:1,direction:'buy'}]}]}};
 if(u.pathname==='/market/history/kline')return{ok:true,data:{status:'ok',data:[]}};
 throw Error('Unexpected producer request');
 }});}finally{Date.now=realNow;}
assert.equal(calls,4);assert.equal(spot.quality_status,'YELLOW');assert.equal(spot.coverage.htx_spot_order_flow,'not_closed');
const receipt=buildHtxSpotMarketConfirmation({contract:CONTRACT,spot,available_ts:NOW,now:NOW});assert.equal(receipt.status,'CLOSED');assert.equal(receipt.value,9900);
const wrap=data=>({execution_status:'FULFILLED',available_ts:NOW,data});
const f=wrap({contract:CONTRACT,coverage:Object.fromEntries(['htx_futures_liquidity','htx_futures_order_flow_sample','htx_open_interest','htx_funding'].map(k=>[k,'closed']))});
const t=wrap({coverage:Object.fromEntries(['price_5m','price_15m','price_1h','price_4h','oi_1h','oi_4h','funding_current','funding_history'].map(k=>[k,'closed']))});
const h=wrap({health:{data_db:true},coverage:{persistent_history:'closed',complete_5m_window:true},series:[{}]});
const dataSufficiency=applyCandidateDataRequirements({receipt:{classification:'PARTIAL',gaps:['futures_trajectory.flow_24h','spot_snapshot.quality_status_GREEN'],components:{spot_snapshot:{execution_status:'FULFILLED'}}},futures:f,trajectory:t,history:h});
assert.equal(dataSufficiency.classification,'PARTIAL');assert.equal(dataSufficiency.core_classification,'SUFFICIENT');
const shadow=worker.buildShadowDecisionTelemetry({contract:CONTRACT,now:NOW,futures:f,spot:wrap(spot),trajectory:t,history:h,dataSufficiency});
assert.equal(shadow.evidence_flags.spot_flow_delta_pct,null);assert.equal(shadow.evidence_flags.spot_market_confirmation.status,'CLOSED');
const rs=['rs_vs_btc_1h','rs_vs_eth_1h','rs_vs_btc_4h','rs_vs_eth_4h','rs_vs_btc_24h','rs_vs_eth_24h'].map(metric=>({contract_code:CONTRACT,chain:'MARKET_STRENGTH_SPOT',metric,source:'FACTUAL_RS_FIXTURE',venue:'HTX',market_type:'USDT_PERP',value:1,unit:'pct',observed_ts:NOW,source_ts:NOW-1000,available_ts:NOW,max_age_sec:300,coverage_pct:100,status:'CLOSED',symbol_verified:true,source_compatible:true,independence_group:'HTX_RELATIVE_STRENGTH',primary_market_id:`${CONTRACT}:HTX:USDT_PERP`,error:null}));
const record=buildFullEvidenceShadowRecord({shadow_decision:shadow,public_evidence:{evidence:rs},now:NOW});
assert.equal(record.chain_status.MARKET_STRENGTH_SPOT.chain_closed,true);
const depth=record.evidence_compact.find(r=>r.metric==='spot_depth_two_sided_usdt');assert.equal(depth.status,'CLOSED');assert.equal(depth.eligible_for_chain_closure,true);assert.equal(depth.market_type,'SPOT');
assert.equal(record.evidence_compact.find(r=>r.chain==='MARKET_STRENGTH_SPOT'&&r.metric==='htx_spot_flow_delta_pct').status,'NOT_CLOSED');
assert.equal(buildFullEvidenceShadowRecord({shadow_decision:shadow,public_evidence:{evidence:rs.slice(1)},now:NOW}).chain_status.MARKET_STRENGTH_SPOT.chain_closed,false);
const absent=structuredClone(shadow);absent.evidence_flags.spot_market_confirmation={status:'NOT_CLOSED'};
assert.equal(buildFullEvidenceShadowRecord({shadow_decision:absent,public_evidence:{evidence:rs},now:NOW}).chain_status.MARKET_STRENGTH_SPOT.chain_closed,false);
const stale=structuredClone(shadow);stale.evidence_flags.spot_market_confirmation.source_ts=NOW-300001;
assert.equal(buildFullEvidenceShadowRecord({shadow_decision:stale,public_evidence:{evidence:rs},now:NOW}).chain_status.MARKET_STRENGTH_SPOT.chain_closed,false);
const stats=await runOptionalCompactStatistics(async()=>{throw Error('simulated failure');});assert.equal(stats.report_blocked,false);
const runner=fs.readFileSync(path.join(runtime,'runner-main.mjs'),'utf8');assert.match(runner,/await runOptionalCompactStatistics\(/);assert.ok(runner.indexOf('await runOptionalCompactStatistics(')>runner.indexOf('await runBoundTelegramDeliverySidecar('));
assert.ok(!runner.includes('throw new Error(`R8_20_PROSPECTIVE_VALIDATION_SMOKE_FAIL_CLOSED'));
console.log(JSON.stringify({status:'CANDIDATE_REQUIREMENTS_EXACT_RUNTIME_PASS',native_producer:'HTX_SPOT_SNAPSHOT',incomplete_flow_not_promoted:true,short_flow_not_24h:true,core_gaps_fail_closed:true,spot_market_requires_all_six_rs_windows:true,missing_or_stale_depth_rejected:true,statistics_error_nonfatal:true,new_external_requests:0,new_d1_statements:0,extra_directional_votes:0}));
