import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {canonicalLifecycleAuthority} from '../files/src/canonical-lifecycle-authority.mjs';
import {buildRoleEvidenceView} from '../files/src/source-role-consumer.mjs';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/actual-lifecycle-37382044550.json',import.meta.url)));
function input(){const row=structuredClone(fixture.row);return {row,early:structuredClone(fixture.early),now_ts:fixture.now_ts,handoff:{contract_code:row.contract_code,source_run_id:row.run_id,wave_id:row.wave_id,deep_started_ts:row.observed_ts-60000,deep_completed_ts:row.observed_ts+60000}};}
function controlledRoles(c){const mk=(source,venue,metric,value)=>({status:'CLOSED',fact_contract_status:'CLOSED',identity_status:'CLOSED',identity:{status:'CLOSED',contract_code:c.metadata.contract,venue},contract_code:c.metadata.contract,source,provider:source,venue,metric,decision_usable:true,source_compatible:true,quality_status:'OK',coverage_pct:100,normalized_value:value,unit:metric==='execution_gate_status'?'boolean':'pct',event_ts:c.observed_ts,received_ts:c.observed_ts,max_age_sec:60,freshness_status:'CURRENT_AT_OBSERVATION',interval:'SNAPSHOT'});return buildRoleEvidenceView([mk('HTX','HTX','execution_gate_status',1),mk('Gate Public Futures','GATE','price_change_4h',1)],{contract:c.metadata.contract,observed_ts:c.observed_ts});}
function closed(){const x=input(),c=JSON.parse(x.row.canonical_json);c.direction='LONG';c.state='OBSERVE';c.scores.coin_interest_0_100=73;c.metadata.direction_resolution={status:'CLOSED',direction:'LONG',facts:[{direction:'LONG',evidence_id:'FIXTURE_ASSIGNED_DIRECTION'}]};c.metadata.source_role_view=controlledRoles(c);x.row.direction='LONG';x.row.canonical_state='OBSERVE';x.row.canonical_json=JSON.stringify(c);return x;}
test('actual 01:24 FIL canonical and mixed wave never become LONG from a shadow bias',()=>{const x=input(),before=JSON.stringify(x);assert.equal(canonicalLifecycleAuthority(x).status,'CANONICAL_DIRECTION_NOT_CLOSED');assert.equal(x.early.direction_state,'DIRECTION_NOT_CLOSED');assert.equal(JSON.stringify(x),before);});
test('only the same fresh canonical assigned direction permits a new lifecycle publication',()=>{const x=closed();assert.equal(canonicalLifecycleAuthority(x).status,'CLOSED');for(const field of ['run_id','snapshot_id','wave_id','contract_code','analytical_fingerprint']){const y=structuredClone(x);y.row[field]='OTHER';assert.equal(canonicalLifecycleAuthority(y).status,'CURRENT_RUN_CANONICAL_IDENTITY_MISMATCH');}const y=closed();y.now_ts=y.row.observed_ts+600001;assert.equal(canonicalLifecycleAuthority(y).status,'CURRENT_RUN_CANONICAL_TIME_NOT_CLOSED');});
test('REJECTED, absent directional consumer and sub70 observation are preserved',()=>{for(const mode of ['reject','unassigned','threshold']){const x=closed(),c=JSON.parse(x.row.canonical_json);if(mode==='reject'){c.state='REJECTED';x.row.canonical_state=c.state;}if(mode==='unassigned')c.metadata.direction_resolution.facts=[];if(mode==='threshold')c.scores.coin_interest_0_100=69.999;x.row.canonical_json=JSON.stringify(c);assert.notEqual(canonicalLifecycleAuthority(x).status,'CLOSED');}assert.equal(canonicalLifecycleAuthority({}).status,'CURRENT_RUN_CANONICAL_NOT_FOUND');});

test('source-role capability or one HTX origin cannot occupy a new observation lifecycle',()=>{const x=closed(),c=JSON.parse(x.row.canonical_json);c.metadata.source_role_view.classified=c.metadata.source_role_view.classified.filter(r=>r.source_key==='HTX_OFFICIAL');x.row.canonical_json=JSON.stringify(c);assert.equal(canonicalLifecycleAuthority(x).status,'OBSERVE_SOURCE_ROLES_NOT_CLOSED');});
