import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {canonicalFingerprint} from '../files/src/canonical-publication.mjs';
import {confirmOriginalClosedCandle,prepareTerminalLifecycle,confirmTerminalDelivery} from '../files/src/closed-candle-terminal-lifecycle.mjs';

const OBS=1791620714334,DUE=1791621014334,EXP=1791622514334,CHECK=1791621300000,OPEN=1791621300000,CLOSE=1791621600000,NOW=1791621605000;
function original(direction='LONG'){
 const canonical={status:'CLOSED',state:'OBSERVE',run_id:'RUN:ORIGINAL',snapshot_id:'SNAP:ORIGINAL',observed_ts:OBS,direction,metadata:{contract:'TEST-USDT'},scores:{coin_interest_0_100:82,is_probability:false},trigger:{trigger_type:'PRICE_CONFIRMATION',metric:'price',operator:direction==='LONG'?'>=':'<=',value:direction==='LONG'?100:90,unit:'USDT',timeframe:'5m',expires_ts:EXP,next_recheck_ts:DUE,cancel_condition:direction==='LONG'?'price<80':'price>110',level_origin:'VERIFIED_CLOSED_CANDLE_RANGE'}};
 canonical.analytical_fingerprint=canonicalFingerprint(canonical);
 const task={task_id:'RCHK:ORIGINAL',publication_id:'PUB:ORIGINAL',contract_code:'TEST-USDT',direction,wave_id:'WAVE:ORIGINAL',run_id:canonical.run_id,snapshot_id:canonical.snapshot_id,analytical_fingerprint:canonical.analytical_fingerprint,telegram_message_id:'174',due_ts:DUE,expires_ts:EXP};
 const light={schema:'LIGHT_PRICE_RECHECK_V1',scope:'PRICE_AND_CANCELLATION_ONLY',status:'TRIGGER_PRICE_REACHED_FULL_ANALYSIS_REQUIRED',source:'HTX_OFFICIAL_COLLECTOR',task_id:task.task_id,publication_id:task.publication_id,run_id:task.run_id,snapshot_id:task.snapshot_id,analytical_fingerprint:task.analytical_fingerprint,telegram_message_id:'174',checked_ts:CHECK,source_ts:CHECK-1000,observed_ts:CHECK-1000,price:direction==='LONG'?101:89,entry_authorized:false,full_analysis_completed:false,settlement_confirmed:false};
 return {canonical,task,light_receipt:light,wave_id:task.wave_id};
}
function candle(close,direction='LONG'){return {schema:'HTX_CLOSED_CANDLE_V1',source:'HTX_OFFICIAL_KLINE',venue:'HTX',contract:'TEST-USDT',timeframe:'5m',open_ts:OPEN,close_ts:CLOSE,source_ts:CLOSE+1000,observed_ts:CLOSE+1500,close,closed:true};}
function entryCanonical(direction='LONG'){
 const c={status:'CLOSED',state:'ENTRY_NOW_ANALYTICAL',run_id:'RUN:FRESH',snapshot_id:'SNAP:FRESH',observed_ts:CLOSE+2000,direction,metadata:{contract:'TEST-USDT'},scores:{overall_0_100:82,coin_interest_0_100:82,is_probability:false},entry:{area:direction==='LONG'?'100–101 USDT':'89–90 USDT',min_price:direction==='LONG'?100:89,max_price:direction==='LONG'?101:90},targets:[{price:direction==='LONG'?115:75,basis:'VERIFIED_STRUCTURE'}],invalidation:direction==='LONG'?'price<80':'price>110',hard_gates:[{status:'PASS'}],liquidations:{}};
 c.analytical_fingerprint=canonicalFingerprint(c);return c;
}
const pass=()=>confirmOriginalClosedCandle({canonical:original().canonical,task:original().task,light_receipt:original().light_receipt,candle:candle(102),now_ts:NOW});

test('price touch is not enough; only exact closed HTX candle confirms',()=>{const o=original();assert.equal(confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:{...candle(102),closed:false},now_ts:NOW}).status,'EXACT_HTX_CLOSED_CANDLE_REQUIRED');assert.equal(pass().status,'CLOSED_CANDLE_CONFIRMED_FULL_ANALYSIS_REQUIRED');assert.equal(pass().entry_authorized,false);});
test('open interval, wrong timeframe, venue, contract and stale clocks fail closed',()=>{const o=original();for(const bad of [{...candle(102),close_ts:NOW+300000},{...candle(102),timeframe:'1m'},{...candle(102),venue:'BINANCE'},{...candle(102),contract:'OTHER-USDT'},{...candle(102),source_ts:CLOSE-1}])assert.equal(confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:bad,now_ts:NOW}).ok,false);});
test('touch followed by close outside level stays waiting and never authorizes analysis',()=>{const o=original();const r=confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(99),now_ts:NOW});assert.equal(r.status,'CLOSED_CANDLE_DID_NOT_CONFIRM');assert.equal(r.full_analysis_required,false);});
test('closed cancellation condition has priority and creates exact terminal evidence',()=>{const o=original();const r=confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(79),now_ts:NOW});assert.equal(r.status,'CANCELLED_BY_CLOSED_CANDLE');assert.equal(r.terminal_disposition,'CANCELLED');});
test('SHORT uses the original operator and cancellation without direction reversal',()=>{const o=original('SHORT');assert.equal(confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(88,'SHORT'),now_ts:NOW}).status,'CLOSED_CANDLE_CONFIRMED_FULL_ANALYSIS_REQUIRED');assert.equal(confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(111,'SHORT'),now_ts:NOW}).status,'CANCELLED_BY_CLOSED_CANDLE');});
test('changed original ids, unsent message and fabricated settlement are rejected',()=>{for(const mutate of [o=>o.task.snapshot_id='FOREIGN',o=>o.task.telegram_message_id=null,o=>o.light_receipt.settlement_confirmed=true,o=>o.light_receipt.task_id='FOREIGN']){const o=original();mutate(o);assert.equal(confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(102),now_ts:NOW}).ok,false);}});
test('retained real WLD174 waiting price cannot be upgraded to candle confirmation',()=>{const actual=JSON.parse(fs.readFileSync('checkpoints/WLD174_ACTUAL_SAME_RUN_SENT_AND_LIGHT_RECHECK_20261010.json'));assert.equal(actual.telegram_message_id,'174');assert.equal(actual.light_recheck.status,'WAITING_FOR_PRICE');const o=original('SHORT');o.task.task_id=actual.task_id;o.task.publication_id=actual.publication_id;o.task.contract_code=actual.contract;o.task.run_id=actual.source_run_id;o.task.snapshot_id=actual.snapshot_id;o.task.analytical_fingerprint=actual.fingerprint;o.task.telegram_message_id=actual.telegram_message_id;o.canonical.metadata.contract=actual.contract;o.canonical.run_id=actual.source_run_id;o.canonical.snapshot_id=actual.snapshot_id;o.canonical.observed_ts=actual.original_trigger.next_recheck_ts-300000;o.canonical.trigger.value=actual.original_trigger.price;o.canonical.trigger.expires_ts=actual.original_trigger.expires_ts;o.canonical.trigger.next_recheck_ts=actual.original_trigger.next_recheck_ts;o.canonical.trigger.cancel_condition='price>'+actual.original_trigger.cancel_price_above;o.canonical.analytical_fingerprint=canonicalFingerprint(o.canonical);o.task.analytical_fingerprint=o.canonical.analytical_fingerprint;o.light_receipt={...o.light_receipt,status:actual.light_recheck.status,task_id:o.task.task_id,publication_id:o.task.publication_id,run_id:o.task.run_id,snapshot_id:o.task.snapshot_id,analytical_fingerprint:o.task.analytical_fingerprint,telegram_message_id:o.task.telegram_message_id,checked_ts:actual.light_recheck.checked_ts,source_ts:actual.light_recheck.source_ts,observed_ts:actual.light_recheck.source_ts,price:actual.light_recheck.price};assert.equal(confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(.48),now_ts:actual.read_ts}).status,'LIGHT_PRICE_TRIGGER_NOT_REACHED');});
test('fresh same-idea full analysis prepares ENTRY approval but never claims exchange fill',()=>{const o=original(),confirmation=pass(),fresh=entryCanonical();const t=prepareTerminalLifecycle({original:o,confirmation,disposition:'ENTRY_APPROVED',fresh_publication:{publication_id:'PUB:FRESH',wave_id:o.task.wave_id,canonical:fresh},now_ts:NOW+1000});assert.equal(t.status,'TERMINAL_DISPATCH_READY');assert.equal(t.event,'ENTRY');assert.equal(t.entry_authorized,true);assert.equal(t.strategy_approved,true);assert.equal(t.exchange_order_filled,false);assert.equal(t.automatic_trading,false);});
test('ENTRY rejects reused run, wrong wave and non-actionable fresh analysis',()=>{for(const change of [(o,f,p)=>f.run_id=o.task.run_id,(o,f,p)=>p.wave_id='FOREIGN',(o,f,p)=>f.hard_gates=[{status:'FAIL'}]]){const o=original(),f=entryCanonical(),p={publication_id:'PUB:FRESH',wave_id:o.task.wave_id,canonical:f};change(o,f,p);f.analytical_fingerprint=canonicalFingerprint(f);assert.equal(prepareTerminalLifecycle({original:o,confirmation:pass(),disposition:'ENTRY_APPROVED',fresh_publication:p,now_ts:NOW+1000}).ok,false);}});
test('cancellation and expiry preserve original ids and stable deduplication key',()=>{const o=original(),cancelEvidence=confirmOriginalClosedCandle({canonical:o.canonical,task:o.task,light_receipt:o.light_receipt,candle:candle(79),now_ts:NOW});const a=prepareTerminalLifecycle({original:o,confirmation:cancelEvidence,disposition:'CANCELLED',now_ts:NOW+1000}),b=prepareTerminalLifecycle({original:o,confirmation:cancelEvidence,disposition:'CANCELLED',now_ts:NOW+1000});assert.equal(a.idempotency_key,b.idempotency_key);assert.equal(a.original_telegram_message_id,'174');const e=prepareTerminalLifecycle({original:o,disposition:'EXPIRED',now_ts:EXP});assert.equal(e.disposition,'EXPIRED');assert.equal(e.original_task_id,o.task.task_id);});
test('terminal acknowledgement requires a distinct confirmed message and pre-send task state',()=>{const o=original(),e=prepareTerminalLifecycle({original:o,disposition:'EXPIRED',now_ts:EXP}),state={task_id:o.task.task_id,state:'EXPIRED',disposition:'EXPIRED',read_ts:EXP+1};assert.equal(confirmTerminalDelivery({terminal:e,network_result:'CONFIRMED_SENT',telegram_message_id:'174',task_at_delivery:state,sent_ts:EXP+2}).ok,false);const r=confirmTerminalDelivery({terminal:e,network_result:'CONFIRMED_SENT',telegram_message_id:'175',task_at_delivery:state,sent_ts:EXP+2});assert.equal(r.status,'TERMINAL_DELIVERY_CONFIRMED');assert.equal(r.telegram_message_id,'175');assert.equal(r.exchange_order_filled,false);});
test('expiry cannot be announced before the original TTL',()=>{const o=original();assert.equal(prepareTerminalLifecycle({original:o,disposition:'EXPIRED',now_ts:EXP-1}).status,'ORIGINAL_TTL_NOT_EXPIRED');});
