import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {verifyCoinpaprikaIdentity,normalizeCoinpaprikaSector,collectCoinpaprikaSectorEvidence} from '../files/src/coinpaprika-sector-evidence.mjs';import {consumeEvidenceV2} from '../files/src/evidence-v2.mjs';
const NOW=Date.now(),address='0x514910771AF9Ca656af840dff83E8264EcF986CA',identity={chain:'ethereum',contract_or_mint:address},metadata={id:'link-chainlink',symbol:'LINK',is_active:true,contracts:[{platform:'eth-ethereum',contract:address}],tags:[{id:'oracles'}]},tag={id:'oracles',type:'functional',coins:['link-chainlink','p1','p2','p3','missing']};
const quote=(id,change,symbol=id,ts=NOW-60000)=>({id,symbol,last_updated:new Date(ts).toISOString(),quotes:{USD:{price:1,volume_24h:200000,percent_change_24h:change}}}),tickers=[quote('link-chainlink',5,'LINK'),quote('p1',-2),quote('p2',1),quote('p3',3)];
const params={metadata,tag,tickers,identity,contract:'LINK-USDT',coin_id:'link-chainlink',tag_id:'oracles',observed_ts:NOW};
function db(){const sqlite=new DatabaseSync(':memory:');return{sqlite,prepare(sql){return{args:[],bind(...a){this.args=a;return this;},async run(){return sqlite.prepare(sql).run(...this.args);},async first(){return sqlite.prepare(sql).get(...this.args)||null;},async all(){return{results:sqlite.prepare(sql).all(...this.args)};}};},async batch(rows){return Promise.all(rows.map(r=>r.run()));}};}
test('provider identity requires exact chain contract, symbol, active status and active status; sector membership is verified separately',()=>{assert.equal(verifyCoinpaprikaIdentity(metadata,{identity,base:'LINK',coin_id:metadata.id,tag_id:'oracles'}),true);for(const changed of [{...metadata,symbol:'OTHER'},{...metadata,is_active:false},{...metadata,contracts:[{platform:'sol-solana',contract:address}]},{...metadata,contracts:[{platform:'eth-ethereum',contract:'0x'+'1'.repeat(40)}]}])assert.equal(verifyCoinpaprikaIdentity(changed,{identity,base:'LINK',coin_id:metadata.id,tag_id:'oracles'}),false);});
test('sector median uses exact fresh peers and contributes only a bounded supporting weight',()=>{const r=normalizeCoinpaprikaSector(params);assert.equal(r.status,'CLOSED');assert.equal(r.summary.peer_median_change_24h_pct,1);assert.equal(r.summary.relative_strength_pct_points,4);assert.equal(r.summary.peer_coverage_fraction,.75);assert.equal(r.summary.entry_eligible,false);assert.equal(r.summary.is_htx_price,false);const used=consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:NOW});assert.equal(used.receipts[0].reason,'CONSUMED');assert.ok(used.adjustment>0&&used.adjustment<=.6);});
test('stale, future, duplicate, missing-return or asynchronous peer cannot manufacture a sector baseline',()=>{for(const altered of [[...tickers,quote('p1',10)],tickers.map(r=>r.id==='p1'?quote('p1',-2,'p1',NOW+1):r),tickers.map(r=>r.id==='p1'?quote('p1',-2,'p1',NOW-16*60000):r),tickers.map(r=>r.id==='p1'?quote('p1',null):r),tickers.map(r=>r.id==='p1'?quote('p1',-2,'p1',NOW-4*60000):r)])assert.equal(normalizeCoinpaprikaSector({...params,tickers:altered}).status,'INSUFFICIENT_FRESH_SECTOR_PEERS');assert.equal(normalizeCoinpaprikaSector({...params,tag:{...tag,type:'consensus'}}).evidence.length,0);assert.equal(normalizeCoinpaprikaSector({...params,tag:{...tag,coins:['p1','p2','p3']}}).evidence.length,0);});
test('source cache avoids real requests and preserves a failure backoff',async()=>{for(const ok of [true,false]){const database=db();let calls=0;const options={db:database,asset_identity:identity,asset_metadata:{coinpaprika_id:metadata.id,sector_tag:'oracles'},contract:'LINK-USDT',run_id:'LIVE',now:NOW,request_admit:r=>{assert.equal(r.attempts,1);return{allowed:true};},fetch_impl:async url=>{calls++;return new Response(JSON.stringify(url.includes('/coins/')?(ok?metadata:{...metadata,symbol:'OTHER'}):url.includes('/tags/')?tag:tickers));}};const a=await collectCoinpaprikaSectorEvidence(options),b=await collectCoinpaprikaSectorEvidence({...options,now:NOW+1000,run_id:'NEXT'});assert.equal(calls,ok?3:1);assert.equal(b.network_calls,0);assert.equal(b.status,a.status);assert.equal(b.cache_status,'HIT');database.sqlite.close();}});
test('a rejected or unrelated functional tag prevents unnecessary ticker request',async()=>{
 for(const failure of [true,false]){const database=db(),urls=[];const r=await collectCoinpaprikaSectorEvidence({db:database,contract:'LINK-USDT',run_id:'TAG_FAIL',now:NOW,asset_identity:identity,asset_metadata:{coinpaprika_id:metadata.id,sector_tag:'oracles'},request_admit:()=>({allowed:true}),fetch_impl:async url=>{urls.push(url);return new Response(JSON.stringify(url.includes('/coins/')?metadata:{...tag,coins:['p1','p2','p3']}),{status:url.includes('/tags/')&&failure?429:200});}});assert.equal(r.evidence.length,0);assert.equal(urls.length,2);assert.ok(urls.every(url=>!url.includes('/tickers')));database.sqlite.close();}
});
