import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(process.env.REPORT2_TEST_RUNTIME||process.argv[2]||'runtime');
const mod=name=>import(pathToFileURL(path.join(runtime,'src',name)).href);
const adapterPath=path.join(runtime,'src/canonical-runtime-adapter.mjs');
const baselinePath=path.join(runtime,'src/canonical-runtime-adapter.observe-baseline.mjs');
const source=fs.readFileSync(adapterPath,'utf8');
const repaired="['OBSERVE','WAIT_FOR_TRIGGER','ENTRY_NOW_ANALYTICAL','ENTRY_NOW_VALIDATED'].includes(text(route?.state))";
const previous="['WAIT_FOR_TRIGGER','ENTRY_NOW_ANALYTICAL','ENTRY_NOW_VALIDATED'].includes(text(route?.state))";
assert.equal(source.split(repaired).length,2);
fs.writeFileSync(baselinePath,source.replace(repaired,previous));
const baseline=await import(pathToFileURL(baselinePath).href);
fs.unlinkSync(baselinePath);
const adapter=await mod('canonical-runtime-adapter.mjs');
const {routeEntrySignal}=await mod('entry-signal-router.mjs');
const ts=1791282416554,contract='TEST-USDT';
const routeFor=direction=>routeEntrySignal({final_decision:{direction,directional_quality:'CLOSED',hard_veto:false,hard_veto_state:'CLEAR',entry_action:'WAIT',entry_quality:'PARTIAL',data_quality:'PARTIAL',execution_quality:'CLOSED',independence_state:'CLOSED',timing_state:'EARLY',risk_state:'CAUTION'},observed_ts:ts,structure_interesting:true,useful_observation:true});
const input=direction=>({contract,run_id:'controlled-deep-observe-regression',snapshot_id:'S392:'+contract+':'+ts,observed_ts:ts,discovery_row:{contract,current_price:100,early_candidate_quality_0_100:82},publication_shadow:{entry_signal:routeFor(direction)},shadow_decision:{dc_long:95,dc_short:95,dq_status:'CLOSED'},opportunity:{observed_ts:ts,newest_event:{event_id:'CONTROLLED-CLOSED-CANDLE',event_close_ts:ts-1000,candle:{open:100,close:101,high:110,low:90},minute_decomposition:{classification_allowed:true}}}});
test('unchanged final router produces OBSERVE; prior adapter loses its confirmed direction',()=>{for(const d of ['LONG','SHORT']){const route=routeFor(d);assert.equal(route.state,'OBSERVE');assert.equal(baseline.resolveCanonicalDirection({route,decision_ts:ts}).status,'UNKNOWN');}});
test('confirmed LONG and SHORT OBSERVE retain analytical direction and no entry authority',()=>{for(const d of ['LONG','SHORT']){const c=adapter.buildRuntimeCanonicalBundle(input(d)).canonical;assert.equal(c.direction,d);assert.equal(c.state,'OBSERVE');assert.equal(c.metadata.direction_resolution.status,'CLOSED');assert.equal(c.metadata.direction_resolution.authorized_entry_direction,'UNKNOWN');assert.equal(c.metadata.score_basis.selected,'DEEP_CANONICAL_INTEREST_SCORE');assert.ok(c.scores.coin_interest_0_100>=70);assert.equal(c.trigger.value,d==='LONG'?110:90);assert.equal(c.invalidation.price,d==='LONG'?90:110);}});
test('opposite independently qualified early direction remains conflicting',()=>{const route=routeFor('LONG');const discovery={contract,early_candidate_bridge:true,early_candidate_wave_id:'CONTROLLED-WAVE',wave_id:'CONTROLLED-WAVE',early_candidate_receipt:{status:'CLOSED',contract,wave_id:'CONTROLLED-WAVE',source_ts:ts-1000,available_at:ts-1000,direction_hint:'SHORT',direction_state:'SHORT_WATCH',evidence:[{status:'CLOSED',side:'SHORT'}]}};const r=adapter.resolveCanonicalDirection({route,discovery,decision_ts:ts});assert.equal(r.status,'CONFLICT');assert.equal(r.direction,null);assert.equal(r.authorized_entry_direction,'UNKNOWN');});
test('rejected route, missing direction and bidirectional hint cannot create direction',()=>{for(const route of [{state:'REJECTED',direction:'LONG'},{state:'OBSERVE',direction:null}])assert.equal(adapter.resolveCanonicalDirection({route,decision_ts:ts}).status,'UNKNOWN');const discovery={contract,early_candidate_bridge:true,early_candidate_wave_id:'W',wave_id:'W',early_candidate_receipt:{status:'CLOSED',contract,wave_id:'W',source_ts:ts-1000,available_at:ts-1000,direction_hint:'LONG',direction_state:'BIDIRECTIONAL_REQUIRES_DEEP_RESOLUTION',evidence:[{status:'CLOSED',side:'LONG'}]}};assert.equal(adapter.resolveCanonicalDirection({discovery,decision_ts:ts}).status,'UNKNOWN');});
test('hard veto still prevents router OBSERVE',()=>{assert.equal(routeEntrySignal({final_decision:{direction:'LONG',hard_veto:true,hard_veto_state:'BLOCKED'},observed_ts:ts,structure_interesting:true,useful_observation:true}).state,'REJECTED');});
test('existing WAIT and ENTRY authority are unchanged',()=>{for(const state of ['WAIT_FOR_TRIGGER','ENTRY_NOW_ANALYTICAL','ENTRY_NOW_VALIDATED']){const args={route:{state,direction:'SHORT'},decision_ts:ts};assert.deepEqual(adapter.resolveCanonicalDirection(args),baseline.resolveCanonicalDirection(args));}});
