import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';
import {createCombinedLiquidationService} from '../files/src/liquidation-extension/combined-runner-service.mjs';
import {decodeDydxPinnedSnapshot} from '../files/src/liquidation-extension/dydx-pinned-conditional-levels.mjs';
import {buildDydxRouting} from '../files/src/liquidation-extension/dydx-runtime-collector.mjs';
import {buildNativeWalletRouting} from '../files/src/liquidation-extension/native-wallet-routing.mjs';
import {bindScopedProviderAcquisition} from '../files/src/liquidation-extension/scoped-provider-runtime-bridge.mjs';
const raw=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/source-inputs/dydx-native-exact-37623708779.json.gz'))),T=Math.max(...raw.raw.map(r=>r.receipt.received_ts))+1,snapshot=decodeDydxPinnedSnapshot({raw,now:T}),assets=new Set(['WIF','ETH']),routing=buildDydxRouting({snapshot,crypto_assets:assets,now:T}),address='0x'+'1'.repeat(40),run_id='CONTROLLED_SHARED_PAIR_BUDGET_RETAINED_DYDX';
// Hyperliquid values are explicitly controlled, while dYdX payloads are retained.
// This is an offline budget trace, never a fresh multi-provider market proof.
const state={time:T,marginSummary:{accountValue:'10',totalNtlPos:'20',totalMarginUsed:'5'},assetPositions:['WIF','ETH'].map(coin=>({position:{coin,szi:'10',entryPx:'1',positionValue:'10',liquidationPx:'.7',marginUsed:'2.5',unrealizedPnl:'0',leverage:{type:'cross',value:2}}}))},wallet=buildNativeWalletRouting({accounts:[{address,state,http_receipt:{http_status:200,received_ts:T,sha256:'a'.repeat(64)}}],run_id:'CONTROLLED_PRIOR_WALLET',now:T});
function service({denial=null}={}){const calls=[],grants=[],s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,clock:()=>T,candidate_slots:2,max_http_per_run:5,native_wallet_routing:wallet,dydx_enabled:true,dydx_crypto_assets:assets,dydx_routing:routing,provider_admit:async r=>{grants.push(r);return denial&&r.requests.DYDX_RPC?denial:{allowed:true,new_reservation:true};},fetch_impl:async(url,init)=>{const q=JSON.parse(init.body);calls.push({url:String(url),body:q});let p;if(String(url).includes('dydx-rpc'))p=q.method==='status'?raw.raw[0].payload:q[0].id===3?raw.raw[2].payload:raw.raw[1].payload;else{assert.equal(String(url),'https://api.hyperliquid.xyz/info');p=q.type==='metaAndAssetCtxs'?[{universe:[{name:'WIF'},{name:'ETH'}]},[{markPx:'1'},{markPx:'1'}]]:state;}return new Response(JSON.stringify(p));}});return{s,calls,grants};}
const params=contract=>({contract,native_symbol:contract.replace(/-USDT$/,''),run_id,deep_started_ts:T,max_http_for_candidate:5,allowed_source_ids:['HYPERLIQUID_NATIVE','DYDX_PINNED_NATIVE'],dydx_position_batch_contracts:['WIF-USDT','ETH-USDT']});
test('one exact dYdX snapshot for both selected assets fits after1 native Hyperliquid read within4 total and both original consumers retain it',async()=>{const f=service(),first=await f.s.collect(params('WIF-USDT'));assert.ok(first?.hyperliquid);assert.equal(first?.scoped?.length,1);const second=await f.s.collect(params('ETH-USDT'));assert.equal(second?.hyperliquid??null,null);assert.equal(second?.scoped?.length,1);assert.equal(f.calls.length,4);assert.equal(f.calls.filter(c=>c.url.includes('dydx-rpc')).length,3);assert.equal(f.calls.filter(c=>c.url.includes('hyperliquid')).length,1);assert.equal(f.s.summary().shared_budget.actual_http,4);assert.equal(f.s.summary().shared_budget.reserved_http,4);for(const [a,contract] of [[first,'WIF-USDT'],[second,'ETH-USDT']]){const bound=bindScopedProviderAcquisition(a.scoped[0],{contract,run_id,snapshot_id:'CONTROLLED:'+contract,observed_ts:T});assert.equal(bound.status,'USABLE_SCOPED_NATIVE_CONTEXT');assert.equal(bound.source_ts,1791377363911);assert.equal(bound.entry_eligible,false);}assert.deepEqual(f.s.summary().routed.filter(r=>r.lane==='DYDX_PINNED_NATIVE').map(r=>r.source_outcome.attempted_http_count),[3,0]);});
test('missing, duplicated or foreign second asset hint cannot borrow the following candidate envelope',async()=>{for(const batch of [['WIF-USDT'],['WIF-USDT','WIF-USDT'],['WIF-USDT','UNKNOWN-USDT']]){const f=service(),first=await f.s.collect({...params('WIF-USDT'),dydx_position_batch_contracts:batch});assert.ok(first);assert.equal(first.scoped?.length??0,0);assert.equal(f.calls.filter(c=>c.url.includes('dydx-rpc')).length,0);assert.equal(f.calls.length,1);}});
test('an explicit smaller candidate cap remains binding even for a valid shared batch',async()=>{const f=service(),first=await f.s.collect({...params('WIF-USDT'),max_http_for_candidate:3});assert.ok(first);assert.equal(first.scoped?.length??0,0);assert.equal(f.calls.length,1);});
test('unspent denial and unknown ACK create no dYdX state; unknown durable reservation is not refunded or retried',async()=>{for(const denial of [{allowed:false,new_reservation:false,reservation_not_created:true,reason:'DYDX_RPC_FREE_QUOTA_EXHAUSTED'},{allowed:false,new_reservation:false,reason:'ACK_UNKNOWN'}]){const f=service({denial}),a=await f.s.collect(params('WIF-USDT'));assert.ok(a);assert.equal(a.scoped?.length??0,0);assert.equal(f.calls.length,1);assert.equal(f.s.summary().shared_budget.reserved_http,denial.reservation_not_created?1:4);assert.equal(f.s.summary().shared_budget.actual_http,1);}});
