import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync,deflateSync} from 'node:zlib';
import {discoverDydxBlockAccounts,discoverDydxRecentBlockAccounts} from '../files/src/liquidation-extension/dydx-block-account-discovery.mjs';
import {permittedDydxReadOnlyBody,decodeDydxPinnedSnapshot,dydxAccountQueryBody} from '../files/src/liquidation-extension/dydx-pinned-conditional-levels.mjs';
import {createDydxRuntimeCollector,buildDydxRouting,saveDydxRouting} from '../files/src/liquidation-extension/dydx-runtime-collector.mjs';
const raw=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/source-inputs/dydx-pinned-native-37612540426.json.gz'))),T=1791371575827,original=decodeDydxPinnedSnapshot({raw,now:T}),source={chain_id:original.chain_id,height:original.height,source_ts:original.source_ts,block_hash:original.block_hash},crypto_assets=new Set(['WIF','ETH','ATOM']),accounts=original.subaccounts.filter(a=>a.positions.length).map(({owner,number})=>({owner,number}));
const vi=n=>{const out=[];do{const b=n&127;n=Math.floor(n/128);out.push(b|(n?128:0));}while(n);return Buffer.from(out);},f=(id,b)=>Buffer.concat([vi(id*8+2),vi(b.length),b]),u=(id,n)=>Buffer.concat([vi(id*8),vi(n)]),id=a=>Buffer.concat([f(1,Buffer.from(a.owner)),u(2,a.number)]),order=a=>f(1,f(1,id(a))),any=(type,value)=>Buffer.concat([f(1,Buffer.from(type)),f(2,value)]),tx=messages=>f(1,Buffer.concat(messages.map(m=>f(1,m))));
function block(txs=[tx([any('/dydxprotocol.clob.MsgPlaceOrder',f(1,order(accounts[0])))]),tx([any('/dydxprotocol.clob.MsgProposedOperations',f(1,f(1,f(1,Buffer.concat([f(1,f(1,id(accounts[1]))),f(2,Buffer.concat([u(1,10),f(2,f(1,id(accounts[0])))]))])))))])]){return{jsonrpc:'2.0',id:7,result:{block_id:{hash:source.block_hash},block:{header:{chain_id:source.chain_id,height:source.height,time:new Date(source.source_ts).toISOString()},data:{txs:txs.map(x=>x.toString('base64'))}}}};}
const discover=payload=>discoverDydxBlockAccounts({payload,...source});
function records(){const b=Buffer.from(raw.raw[1].payload.result.response.value,'base64');let i=0;const out=[],uint=()=>{let n=0,s=0;for(;;){const x=b[i++];n+=(x&127)*2**s;if(x<128)return n;s+=7;}};while(i<b.length){const start=i,k=uint(),n=uint();i+=n;if(k===10)out.push(b.subarray(start,i));}return out;}
function recentBlocks(payload){const rows=Array.from({length:4},(_,i)=>{const b=i?block([]):structuredClone(payload);b.id=7+i;b.result.block.header.height=String(BigInt(source.height)-BigInt(i));b.result.block.header.time=new Date(source.source_ts-i*500).toISOString();if(i)b.result.block_id.hash=String(i).repeat(64);return b;});for(let i=0;i<3;i++)rows[i].result.block.header.last_block_id={hash:rows[i+1].result.block_id.hash};return rows;}
function transport(payload=block()){const rows=records(),calls=[];return{calls,fetch_impl:async(url,init)=>{const body=JSON.parse(init.body);calls.push(body);let data;if(body.method==='status')data=raw.raw[0].payload;else if(body?.[0]?.id===3)data=[...raw.raw[2].payload,...recentBlocks(payload)];else if(body.method==='abci_query')data=raw.raw[1].payload;else data=body.map(q=>{const i=original.subaccounts.findIndex(a=>q.params.data.includes(Buffer.from(a.owner).toString('hex').toUpperCase()));assert.ok(i>=0);return{jsonrpc:'2.0',id:q.id,result:{response:{height:source.height,code:0,value:rows[i].toString('base64')}}};});return new Response(JSON.stringify(data),{status:200});}};}
test('native order and proposed match bytes discover exact public subaccounts without treating order price/side as a position',()=>{const d=discover(block());assert.equal(d.unique_observed_accounts,2);assert.equal(d.selected_accounts.length,2);assert.equal(d.open_positions_claimed,false);assert.equal(d.trade_side_is_position_side,false);assert.equal(d.levels_produced,0);assert.equal(d.independent_upstream_added,false);assert.deepEqual(d.selected_accounts.map(a=>a.owner).sort(),accounts.map(a=>a.owner).sort());for(const a of d.selected_accounts)assert.match(a.original_tx_sha256,/^[a-f0-9]{64}$/);});
test('nested signed short-term placement is parsed by the pinned Cosmos/dYdX schema without recursive scanning arbitrary address text',()=>{const placement=tx([any('/dydxprotocol.clob.MsgPlaceOrder',f(1,order(accounts[0])))]),b=block([tx([any('/dydxprotocol.clob.MsgProposedOperations',f(1,f(2,placement)))])]);assert.equal(discover(b).selected_accounts.length,1);const fake=block([tx([any('/unrelated.Message',f(1,Buffer.from(accounts[0].owner)))])]);assert.equal(discover(fake).selected_accounts.length,0);});
test('foreign native block hash, height, chain or original clock fails before account discovery',()=>{for(const changed of ['hash','height','chain_id','time']){const b=block();if(changed==='hash')b.result.block_id.hash='0'.repeat(64);else b.result.block.header[changed]='wrong';assert.throws(()=>discover(b),/MISMATCH/);}});
test('malformed native protobuf, excessive sample limit, invalid base64 and duplicated match variants are denied',()=>{assert.throws(()=>discover(block([Buffer.from([10,255])])));assert.throws(()=>discoverDydxBlockAccounts({payload:block(),...source,max_accounts:9}));const b=block();b.result.block.data.txs=['!!!'];assert.throws(()=>discover(b),/BASE64/);const bad=block([tx([any('/dydxprotocol.clob.MsgProposedOperations',f(1,Buffer.concat([f(1,Buffer.alloc(0)),f(2,Buffer.alloc(0))])))])]);assert.throws(()=>discover(bad),/ONEOF/);});
test('additional native block request is read-only, explicit-height and allowed only with the exact four catalog queries',()=>{const body=[...raw.raw[2].receipt.request_body,{jsonrpc:'2.0',id:7,method:'block',params:{height:source.height}}];assert.equal(permittedDydxReadOnlyBody(body),true);for(const replacement of [{...body[4],params:{height:'latest'}},{...body[4],method:'broadcast_tx_sync'},{...body[4],id:6}])assert.equal(permittedDydxReadOnlyBody([...body.slice(0,4),replacement]),false);assert.equal(permittedDydxReadOnlyBody(body[4]),false);});
test('activity account discovery rereads full exact accounts in3 HTTP and retains original chain clock and the untouched native page cursor',async()=>{const io=transport(),prior=buildDydxRouting({snapshot:original,crypto_assets,now:T}),collector=createDydxRuntimeCollector({fetch_impl:io.fetch_impl,clock:()=>T,crypto_assets,routing:prior}),r=await collector({run_id:'CONTROLLED_ACTIVITY',discovery:true,activity_discovery:true});assert.equal(r.status,'DYDX_BOUNDED_NATIVE_DISCOVERY_CLOSED');assert.equal(io.calls.length,3);assert.equal(io.calls[1].length,8);assert.equal(io.calls[2].length,2);assert.equal(r.snapshot.source_ts,source.source_ts);assert.equal(r.snapshot.activity_discovery.unique_observed_accounts,2);assert.equal(r.routing.next_page_key_hex,prior.next_page_key_hex);assert.equal(r.routing.last_discovery_kind,'CURRENT_BLOCK_ACTIVE_ACCOUNTS');assert.equal(r.routing.accounts.length,2);});
test('empty activity block falls back to one bounded native page in the same3 requests and produces no invented activity hints',async()=>{const io=transport(block([])),collector=createDydxRuntimeCollector({fetch_impl:io.fetch_impl,clock:()=>T,crypto_assets}),r=await collector({run_id:'CONTROLLED_EMPTY_ACTIVITY',discovery:true,activity_discovery:true});assert.equal(r.status,'DYDX_BOUNDED_NATIVE_DISCOVERY_CLOSED');assert.equal(io.calls.length,3);assert.equal(io.calls[2].params.path,'/dydxprotocol.subaccounts.Query/SubaccountAll');assert.equal(r.snapshot.activity_discovery.unique_observed_accounts,0);assert.equal(r.snapshot.subaccounts.length,20);});
test('a source block identity failure spends no third read and cannot save structural account hints',async()=>{const b=block();b.result.block_id.hash='0'.repeat(64);const io=transport(b);let saved=0;const c=createDydxRuntimeCollector({fetch_impl:io.fetch_impl,clock:()=>T,crypto_assets,on_snapshot:()=>saved++}),r=await c({run_id:'CONTROLLED_BAD_HASH',discovery:true,activity_discovery:true});assert.equal(r.status,'DYDX_NATIVE_NOT_CLOSED');assert.equal(io.calls.length,2);assert.equal(saved,0);});
test('actual two-row cache write is admitted conservatively; one remaining row cannot authorize a structural save',async()=>{let writes=0;const db={prepare:()=>({bind:()=>({run:async()=>{writes++;return{success:true,meta:{changes:1}}}})})},r=await saveDydxRouting({db,snapshot:original,crypto_assets,now:T,db_admit:extra=>({allowed:extra.rows_written<=1})});assert.equal(r.status,'D1_WRITE_NOT_ADMITTED');assert.equal(writes,0);});

test('retained actual native block handles the index0 Slinky zlib commit and absent Any value without inventing trading accounts',()=>{const actual=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/source-inputs/dydx-native-activity-37621191104.json.gz'))),sync=actual.raw[0].payload.result.sync_info,payload=actual.raw[1].payload.find(r=>r.id===7),identity={chain_id:'dydx-mainnet-1',height:sync.latest_block_height,source_ts:Date.parse(sync.latest_block_time),block_hash:sync.latest_block_hash},d=discoverDydxBlockAccounts({payload,...identity});assert.equal(d.consensus_records,1);assert.equal(d.block_transaction_count,5);assert.equal(d.recognized_clob_messages,1);assert.equal(d.unique_observed_accounts,0);assert.deepEqual(d.selected_accounts,[]);assert.equal(discoverDydxRecentBlockAccounts({payload:[payload],...identity}).block_count,1);const misplaced=structuredClone(payload);misplaced.result.block.data.txs.push(misplaced.result.block.data.txs[0]);assert.throws(()=>discoverDydxBlockAccounts({payload:misplaced,...identity}),/CONSENSUS_RECORD_INDEX/);});
test('only valid consensus schema can be skipped; empty known default message and unrelated bytes yield no position claims',()=>{assert.throws(()=>discover(block([deflateSync(Buffer.from('not consensus'))])));const b=block([tx([f(1,Buffer.from('/dydxprotocol.clob.MsgProposedOperations'))])]);assert.equal(discover(b).unique_observed_accounts,0);});
test('five exact subaccount queries remain allowed and four adjacent block reads preserve the eight-message ceiling',()=>{const ids=Array.from({length:5},(_,i)=>({...accounts[0],number:i}));assert.equal(permittedDydxReadOnlyBody(dydxAccountQueryBody(ids,source.height)),true);const body=[...raw.raw[2].receipt.request_body,...Array.from({length:4},(_,i)=>({jsonrpc:'2.0',id:7+i,method:'block',params:{height:String(BigInt(source.height)-BigInt(i))}}))];assert.equal(permittedDydxReadOnlyBody(body),true);assert.equal(permittedDydxReadOnlyBody([...body,{...body[7],id:11}]),false);const bad=structuredClone(body);bad[6].params.height=source.height;assert.equal(permittedDydxReadOnlyBody(bad),false);});
test('recent native account hints require adjacent parent hashes and original monotone block clocks, and deduplicate accounts',()=>{const bs=recentBlocks(block()),opts={...source,payload:bs},d=discoverDydxRecentBlockAccounts(opts);assert.equal(d.block_count,4);assert.equal(d.unique_observed_accounts,2);for(const mutate of [b=>b[0].result.block.header.last_block_id.hash='0'.repeat(64),b=>b[1].result.block.header.time=new Date(source.source_ts+1).toISOString(),b=>b[3].result.block.header.height=source.height]){const b=structuredClone(bs);mutate(b);assert.throws(()=>discoverDydxRecentBlockAccounts({...source,payload:b}));}});

test('exact QueryGetSubaccountRequest is the official flat owner1/number2 protobuf and the previous nested request is rejected',()=>{for(const number of [0,127,128,127999]){const a={...accounts[0],number},q=dydxAccountQueryBody([a],source.height)[0],expected=Buffer.concat([f(1,Buffer.from(a.owner)),u(2,number)]).toString('hex').toUpperCase();assert.equal(q.params.data,expected);const nested={...q,params:{...q.params,data:f(1,Buffer.from(expected,'hex')).toString('hex').toUpperCase()}};assert.equal(permittedDydxReadOnlyBody([nested]),false);} });
