import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {permittedDydxReadOnlyBody,dydxAccountPageBody,decodeDydxPinnedSnapshot,calculateDydxConditionalLevels} from '../files/src/liquidation-extension/dydx-pinned-conditional-levels.mjs';
import {createDydxRuntimeCollector,buildDydxRouting,normalizeDydxPinnedLevels} from '../files/src/liquidation-extension/dydx-runtime-collector.mjs';
const raw=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/source-inputs/dydx-pinned-native-37612540426.json.gz'))),T=1791371575827,s=decodeDydxPinnedSnapshot({raw,now:T}),assets=new Set(['WIF','ETH','ATOM']),sha=b=>createHash('sha256').update(b).digest('hex');
const vi=n=>{const a=[];do{const b=n%128;n=Math.floor(n/128);a.push(b|(n?128:0));}while(n);return Buffer.from(a);},f=(id,b)=>Buffer.concat([vi(id*8+2),vi(b.length),b]);
// Controlled empty accounts extend a retained page only to test parser bounds.
// Their addresses/positions are never claimed as newly observed native state.
function dense(count=200){const r=structuredClone(raw),row=r.raw[1],b=Buffer.from(row.payload.result.response.value,'base64'),xs=[b];for(let number=1;number<=count-20;number++){const id=Buffer.concat([f(1,Buffer.from(s.subaccounts[0].owner)),vi(16),vi(number)]);xs.push(f(1,f(1,id)));}row.receipt.request_body=dydxAccountPageBody({height:s.height,limit:200});row.payload.result.response.value=Buffer.concat(xs).toString('base64');row.raw_body_utf8=JSON.stringify(row.payload);row.receipt.bytes=Buffer.byteLength(row.raw_body_utf8);row.receipt.sha256=sha(row.raw_body_utf8);return r;}
test('explicit native discovery allows only20 or200 complete-account pages; arbitrary/future default limits are denied',()=>{const q=dydxAccountPageBody({height:s.height,limit:200});assert.equal(q.params.data,'0A0318C801');assert.equal(permittedDydxReadOnlyBody(q),true);for(const limit of [0,1,100,199,201,500,Infinity])assert.throws(()=>dydxAccountPageBody({height:s.height,limit}));const bad=structuredClone(q);bad.params.data='0A0318C901';assert.equal(permittedDydxReadOnlyBody(bad),false);});
test('controlled200-account page keeps full retained positions, original height and clocks; hints remain capped32 and prices are not stored',()=>{const d=decodeDydxPinnedSnapshot({raw:dense(),now:T});assert.equal(d.subaccounts.length,200);assert.equal(d.account_page_limit,200);assert.equal(d.source_ts,s.source_ts);assert.equal(d.height,s.height);assert.equal(calculateDydxConditionalLevels(d,{crypto_assets:assets}).levels.length,2);const route=buildDydxRouting({snapshot:d,crypto_assets:assets,now:T});assert.equal(route.accounts.length,2);assert.ok(route.accounts.length<=32);assert.equal(JSON.stringify(route).includes('liquidation_price'),false);});
test('native page response count is bound to its exact requested limit;201 records cannot be accepted under200',()=>{assert.throws(()=>decodeDydxPinnedSnapshot({raw:dense(201),now:T}),/NATIVE_RECORD_BOUND/);const r=dense();r.raw[1].receipt.request_body=dydxAccountPageBody({height:s.height,limit:20});assert.throws(()=>decodeDydxPinnedSnapshot({raw:r,now:T}),/NATIVE_RECORD_BOUND/);});
test('denser discovery shares the existing three explicit-height HTTP and stores only verified source-derived structural hints',async()=>{const fixture=dense(),calls=[],collect=createDydxRuntimeCollector({clock:()=>T,crypto_assets:assets,fetch_impl:async(url,init)=>{const q=JSON.parse(init.body);assert.equal(permittedDydxReadOnlyBody(q),true);calls.push(q);const row=q.method==='status'?fixture.raw[0]:q.method==='abci_query'?fixture.raw[1]:fixture.raw[2];return new Response(row.raw_body_utf8,{status:200});}}),r=await collect({run_id:'CONTROLLED_DENSE_NATIVE_PAGE',discovery:true,discovery_page_size:200});assert.equal(r.status,'DYDX_BOUNDED_NATIVE_DISCOVERY_CLOSED');assert.equal(r.requests,3);assert.equal(calls.length,3);assert.equal(calls[1].params.data,'0A0318C801');assert.equal(calls[2].length,4);assert.equal(r.snapshot.subaccounts.length,200);assert.equal(r.snapshot.activity_discovery,null);});
test('unapproved discovery limit cannot spend even the initial status HTTP',async()=>{let calls=0;const collect=createDydxRuntimeCollector({clock:()=>T,crypto_assets:assets,fetch_impl:async()=>{calls++;throw Error('NO_TRANSPORT')}}),r=await collect({run_id:'CONTROLLED_INVALID_LIMIT',discovery:true,discovery_page_size:201});assert.equal(r.requests,0);assert.equal(calls,0);assert.equal(r.status,'DYDX_DISCOVERY_PAGE_LIMIT_NOT_ADMITTED');});
test('retained actual flat exact-query response independently proves current-height full state and conditional labels at its original receipt clock',()=>{const a=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/source-inputs/dydx-native-exact-37623708779.json.gz'))),now=Math.max(...a.raw.map(r=>r.receipt.received_ts)),d=decodeDydxPinnedSnapshot({raw:a,now}),q=a.raw[1].receipt.request_body;assert.equal(d.height,'108443885');assert.equal(d.subaccounts.length,2);assert.equal(d.account_request_kind,'EXACT_SUBACCOUNT_BATCH');assert.equal(q.length,2);for(let i=0;i<q.length;i++){const account=d.subaccounts[i],expected=Buffer.concat([f(1,Buffer.from(account.owner)),vi(16),vi(account.number)]).toString('hex').toUpperCase();assert.equal(q[i].params.data,expected);}const model=calculateDydxConditionalLevels(d,{crypto_assets:assets});assert.equal(model.levels.length,2);for(const asset of ['WIF','ETH']){const p=normalizeDydxPinnedLevels({snapshot:d,contract:asset+'-USDT',run_id:a.run_id,observed_ts:now,crypto_assets:assets});assert.ok(p);assert.equal(p.execution_target_eligible,false);assert.equal(p.source_ts,1791377363911);assert.equal(p.zones[0].decision_target_eligible,false);}assert.throws(()=>decodeDydxPinnedSnapshot({raw:a,now:now+120001}),/RECEIPT|CLOCK/);});
