import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'runtime'),load=n=>import(pathToFileURL(path.join(root,'src',n)));
const [{createCombinedLiquidationService},{addDydxCollectionPermission,buildDydxRouting,createDydxRuntimeCollector},{decodeDydxPinnedSnapshot,dydxAccountPageBody,calculateDydxConditionalLevels},{buildRuntimeCanonicalBundle}]=await Promise.all([load('liquidation-extension/combined-runner-service.mjs'),load('liquidation-extension/dydx-runtime-collector.mjs'),load('liquidation-extension/dydx-pinned-conditional-levels.mjs'),load('canonical-runtime-adapter.mjs')]);
const bytes=fs.readFileSync('checkpoints/source-inputs/dydx-native-dense-37625020734.json.gz'),raw=JSON.parse(gunzipSync(bytes)),T=Math.max(...raw.raw.map(r=>r.receipt.received_ts)),snapshot=decodeDydxPinnedSnapshot({raw,now:T}),universe=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'))),assets=new Set(universe.assets.map(a=>a.symbol)),levels=calculateDydxConditionalLevels(snapshot,{crypto_assets:assets}).levels,covered=[...new Set(levels.map(l=>l.asset))].sort(),selected=covered.slice(0,2).map(a=>a+'-USDT'),base={eligible:false,source_ids:[],proven_level_source_ids:[],status:'NO_VERIFIED_REAL_LEVEL_SOURCE'};
assert.equal(assets.size,102);assert.equal(covered.length,18);assert.equal(levels.length,33);
function replay({denial=null,routing=null,universe=assets}={}){const calls=[],grants=[],s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,dydx_enabled:true,dydx_automatic_discovery_enabled:true,dydx_crypto_assets:universe,dydx_routing:routing,candidate_slots:2,max_http_per_run:5,clock:()=>T,provider_admit:async r=>{grants.push(r);return denial??{allowed:true,new_reservation:true};},fetch_impl:async(url,init)=>{assert.equal(String(url),'https://dydx-rpc.publicnode.com/');const q=JSON.parse(init.body);calls.push(q);const row=q.method==='status'?raw.raw[0]:q.method==='abci_query'?raw.raw[1]:raw.raw[2];return new Response(row.raw_body_utf8);}});return{s,calls,grants};}
const params=(contract,contracts=selected)=>({contract,native_symbol:contract.replace(/-USDT$/,''),run_id:'CONTROLLED_AUTOMATIC_REPORT_SEARCH',deep_started_ts:T,max_http_for_candidate:5,allowed_source_ids:['DYDX_PINNED_NATIVE'],dydx_position_batch_contracts:contracts});
test('automatic search admission is generic over the verified asset universe and grants no current market, level, entry or leader replacement claim',()=>{
 for(const symbol of assets){const p=addDydxCollectionPermission(base,{contract:symbol+'-USDT',crypto_assets:assets,routing:null,now:T,automatic_discovery_enabled:true});assert.equal(p.eligible,true);assert.equal(p.structural_hint_available,false);assert.deepEqual(p.source_ids,['DYDX_PINNED_NATIVE']);assert.deepEqual(p.proven_level_source_ids,[]);assert.equal(p.fresh_live_levels_confirmed,false);assert.equal(p.leaders_may_be_replaced,false);assert.equal(p.calculated_fallback_allowed,false);}
 for(const contract of ['NOT_IN_FROZEN_UNIVERSE-USDT','BTC-USD','BTC-USDT-extra',' BTC-USDT'])assert.equal(addDydxCollectionPermission(base,{contract,crypto_assets:assets,routing:null,automatic_discovery_enabled:true,now:T}),base);
 assert.equal(addDydxCollectionPermission(base,{contract:selected[0],crypto_assets:assets,routing:null,now:T}),base);
});
test('the assembled report service discovers positions without any per-coin hint and both dynamically selected assets reach canonical reports in one3HTTP snapshot',async()=>{
 const f=replay(),proof=[];
 for(const contract of selected){const a=await f.s.collect(params(contract));assert.equal(a.scoped.length,1);const asset=contract.replace(/-USDT$/,''),expected=levels.filter(l=>l.asset===asset),reference=expected[0].reference_price;
  const b=buildRuntimeCanonicalBundle({contract,run_id:params(contract).run_id,snapshot_id:'CONTROLLED_AUTO:'+contract,observed_ts:T,discovery_row:{contract,mark_price:reference},publication_shadow:{entry_signal:{state:'REJECTED',direction:null},scenario_plan:{execution_reference_price:reference}},native_liquidation_acquisition:a,internal_market_context:{internal_only:true,liquidation_coverage_admission:addDydxCollectionPermission(base,{contract,crypto_assets:assets,routing:null,now:T,automatic_discovery_enabled:true})}});
  assert.equal(b.canonical.state,'REJECTED');assert.equal(b.canonical.direction,null);assert.equal(b.canonical.metadata.validated_signal,false);assert.equal(b.canonical.targets?.length??0,0);assert.ok(b.manual.text.includes('dYdX'));assert.ok(b.manual.text.includes('расч'));assert.ok(JSON.stringify(b.canonical.liquidations).includes('CALCULATED_CONDITIONAL'));
  const prices=[...a.scoped[0].above,...a.scoped[0].below].map(z=>z.native_price).sort((a,b)=>a-b);assert.deepEqual(prices,expected.slice(0,8).map(l=>l.price).sort((a,b)=>a-b));
  proof.push({contract,source_ts:snapshot.source_ts,actual_retained_expected_levels:expected.length,acquisition:a,canonical:b.canonical,manual_text:b.manual.text});
 }
 assert.equal(f.calls.length,3);assert.deepEqual(f.calls[1],dydxAccountPageBody({height:snapshot.height,limit:200}));assert.deepEqual(f.s.summary().routed.map(r=>r.source_outcome.attempted_http_count),[3,0]);assert.equal(f.s.summary().shared_budget.actual_http,3);assert.equal(f.s.summary().shared_budget.reserved_http,3);assert.equal(f.s.summary().dydx.automatic_position_search,true);
 fs.writeFileSync('audit-output/dydx-automatic-report-search-proof.json',JSON.stringify({schema:'DYDX_AUTOMATIC_REPORT_POSITION_SEARCH_RETAINED_PROOF_V1',source_cloud_run:37625020734,source_gzip_sha256:createHash('sha256').update(bytes).digest('hex'),scope:'CONTROLLED_TRANSPORT_AND_REPORT_CONSUMER_REPLAY_AT_ORIGINAL_CLOCK_NOT_FRESH_HTX_MAIN',asset_selection:'DYNAMIC_FROM_RETAINED_NATIVE_MODEL_NO_PER_COIN_CONFIGURATION',structural_hints_at_start:0,controlled_transport_calls:3,sourceHTTP:0,D1:0,MAIN:0,Telegram:0,source_clocks_refreshed:false,new_fresh_SENT:false,proof},null,2)+'\n');
});
test('a current complete page with no selected asset yields no invented level and uses the saved continuation cursor without extra requests',async()=>{
 const absent='NOTINPAGE',universe=new Set([...assets,absent]),routing=buildDydxRouting({snapshot,crypto_assets:universe,now:T}),calls=[];
 const collect=createDydxRuntimeCollector({clock:()=>T,crypto_assets:universe,routing,automatic_discovery_enabled:true,fetch_impl:async(url,init)=>{const q=JSON.parse(init.body);calls.push(q);const row=q.method==='status'?raw.raw[0]:q.method==='abci_query'?raw.raw[1]:raw.raw[2];return new Response(row.raw_body_utf8);}});
 // Deliberately controlled replay of the retained response under a continuation request:
 // it verifies scheduling and absence, and is not a new native continuation-page proof.
 const p={contract:absent+'-USDT',run_id:'CONTROLLED_CURSOR_ABSENCE',position_batch_contracts:[absent+'-USDT']},a=await collect(p);assert.equal(a.status,'DYDX_NO_ELIGIBLE_SAMPLE_LEVEL');assert.equal(a.acquisition,null);assert.equal(a.requests,3);assert.deepEqual(calls[1],dydxAccountPageBody({height:snapshot.height,key:routing.next_page_key_hex,limit:200}));assert.equal(a.position_search.full_market_census,false);assert.equal(a.position_search.source_clock_refreshed,false);const b=await collect(p);assert.equal(b.requests,0);assert.equal(b.source_ts,a.source_ts);assert.equal(calls.length,3);
});
test('automatic search respects exact selected identities, smaller envelopes and durable quota/unknown ACK without transport, refund or fabricated result',async()=>{
 for(const denial of [{allowed:false,new_reservation:false,reservation_not_created:true,reason:'FREE_QUOTA_EXHAUSTED'},{allowed:false,new_reservation:false,reason:'ACK_UNKNOWN'}]){const f=replay({denial});assert.equal(await f.s.collect(params(selected[0])),null);assert.equal(f.calls.length,0);assert.equal(f.s.summary().shared_budget.actual_http,0);assert.equal(f.s.summary().shared_budget.reserved_http,denial.reservation_not_created?0:3);}
 const small=replay();assert.equal(await small.s.collect({...params(selected[0]),max_http_for_candidate:2}),null);assert.equal(small.calls.length,0);
 const collect=createDydxRuntimeCollector({crypto_assets:assets,clock:()=>T,automatic_discovery_enabled:true,fetch_impl:()=>{throw Error('TRANSPORT_FORBIDDEN')}});
 for(const position_batch_contracts of [[selected[0],selected[0]],[selected[0],'NOT_IN_FROZEN_UNIVERSE-USDT'],selected.concat(covered[2]+'-USDT')]){const a=await collect({contract:selected[0],run_id:'INVALID',position_batch_contracts});assert.equal(a.requests,0);assert.equal(a.status,'DYDX_EXACT_SELECTED_CONTRACT_REQUIRED');}
});