import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {decodeDydxPinnedSnapshot,permittedDydxReadOnlyBody,dydxAccountQueryBody,dydxAccountPageBody} from '../files/src/liquidation-extension/dydx-pinned-conditional-levels.mjs';
import {buildDydxRouting,validateDydxRouting,selectDydxRouting,normalizeDydxPinnedLevels,addDydxCollectionPermission,saveDydxRouting,loadDydxRouting,createDydxRuntimeCollector} from '../files/src/liquidation-extension/dydx-runtime-collector.mjs';
import {createCombinedLiquidationService} from '../files/src/liquidation-extension/combined-runner-service.mjs';
import {createSharedSourceBudget} from '../files/src/liquidation-extension/run-source-budget.mjs';
import {bindScopedProviderAcquisition} from '../files/src/liquidation-extension/scoped-provider-runtime-bridge.mjs';
import {installSourceAllowances} from '../files/src/liquidation-extension/install-source-allowances.mjs';
import {buildPumpLiquidationZones} from '../files/src/pump-liquidation-zones.mjs';
const raw=JSON.parse(gunzipSync(fs.readFileSync(new URL('../../checkpoints/source-inputs/dydx-pinned-native-37612540426.json.gz',import.meta.url)))),T=1791371575827,crypto_assets=new Set(['WIF','ETH','ATOM']),snapshot=()=>decodeDydxPinnedSnapshot({raw:structuredClone(raw),now:T}),routing=()=>buildDydxRouting({snapshot:snapshot(),crypto_assets,now:T});
const grant=async request=>({allowed:true,new_reservation:true,reservation_id:request.reservation_id});
// Controlled transport replay; no new native source receipt or current-run proof is claimed.
function transport(){let calls=0;const bytes=Buffer.from(raw.raw[1].payload.result.response.value,'base64'),records=[];let i=0;const uint=()=>{let n=0,s=0;while(true){const b=bytes[i++];n|=(b&127)<<s;if(b<128)return n;s+=7;}};while(i<bytes.length){const start=i,k=uint(),n=uint();i+=n;if(k===10)records.push(bytes.subarray(start,i));}
 const fixtureAccounts=snapshot().subaccounts;
 const fetch_impl=async(url,init)=>{calls++;assert.equal(String(url),'https://dydx-rpc.publicnode.com/');const body=JSON.parse(init.body);let payload;if(body.method==='status')payload=raw.raw[0].payload;else if(body.method==='abci_query')payload=raw.raw[1].payload;else if(body[0].id===3)payload=raw.raw[2].payload;else payload=body.map(q=>{const a=fixtureAccounts.findIndex(a=>q.params.data.includes(Buffer.from(a.owner).toString('hex').toUpperCase())&&q.params.data.endsWith('10'+a.number.toString(16).padStart(2,'0').toUpperCase()));assert.ok(a>=0);return{jsonrpc:'2.0',id:q.id,result:{response:{height:'108434861',code:0,value:records[a].toString('base64')}}};});return new Response(JSON.stringify(payload),{status:200});};return{fetch_impl,calls:()=>calls};}
test('dYdX transport allows exact status, bounded pages and explicit account/query batches only',()=>{assert.equal(permittedDydxReadOnlyBody(raw.raw[0].receipt.request_body),true);assert.equal(permittedDydxReadOnlyBody(dydxAccountPageBody({height:'108434861',offset:20})),true);assert.equal(permittedDydxReadOnlyBody(dydxAccountQueryBody(selectDydxRouting(routing(),{symbol:'WIF',now:T}),'108434861')),true);for(const b of [{jsonrpc:'2.0',id:1,method:'broadcast_tx_sync',params:{}},{...raw.raw[0].receipt.request_body,params:{height:'1'}},{...raw.raw[1].receipt.request_body,params:{...raw.raw[1].receipt.request_body.params,height:'latest'}},{...raw.raw[1].receipt.request_body,params:{...raw.raw[1].receipt.request_body.params,prove:true}}])assert.equal(permittedDydxReadOnlyBody(b),false);assert.throws(()=>dydxAccountQueryBody([{owner:raw.raw[1].payload.result.response.value,number:0}],'1'));assert.throws(()=>dydxAccountQueryBody([{owner:snapshot().subaccounts[0].owner,number:-1}],'1'));assert.throws(()=>dydxAccountPageBody({height:'1',offset:3000}));});
test('real native account sample derives only structural hints for eligible assets without price/size/level state',()=>{const r=routing();assert.equal(r.accounts.length,2);assert.deepEqual(r.accounts.map(a=>a.coins),[['WIF'],['ATOM','ETH']]);for(const a of r.accounts)assert.equal(Object.keys(a).sort().join(','),'coins,number,original_account_response_sha256,owner,verified_receipt_ts,verified_source_ts');assert.ok(r.next_page_key_hex);assert.ok(validateDydxRouting(r,{now:T}));assert.equal(selectDydxRouting(r,{symbol:'APE',now:T}).length,0);assert.equal(selectDydxRouting(r,{symbol:'WIF',now:T+7*86400000+1}).length,0);});
test('structural hints grant a bounded additional check without upgrading historical capability to current coverage',()=>{const base={eligible:false,source_ids:[],status:'NO_VERIFIED_REAL_LEVEL_SOURCE'},p=addDydxCollectionPermission(base,{contract:'WIF-USDT',crypto_assets,routing:routing(),now:T});assert.equal(p.eligible,true);assert.deepEqual(p.source_ids,['DYDX_PINNED_NATIVE']);assert.deepEqual(p.proven_level_source_ids,[]);assert.equal(p.fresh_live_levels_confirmed,false);assert.equal(p.calculated_fallback_allowed,false);assert.equal(addDydxCollectionPermission(base,{contract:'WTI-USDT',crypto_assets,routing:routing(),now:T}),base);});
test('mutated or fabricated native snapshot cannot produce normalized receipts or saved hints',()=>{const s=snapshot();s.subaccounts.find(a=>a.positions.length===2).positions[0].quantums=1n;assert.equal(buildDydxRouting({snapshot:s,crypto_assets,now:T}),null);assert.equal(normalizeDydxPinnedLevels({snapshot:s,contract:'WIF-USDT',run_id:s.run_id,observed_ts:T,crypto_assets}),null);});
test('real estimates pass the scoped display producer with source time, estimate label and no HTX target',()=>{const s=snapshot(),r=normalizeDydxPinnedLevels({snapshot:s,contract:'WIF-USDT',run_id:s.run_id,observed_ts:T,crypto_assets});assert.equal(r.zones.length,1);assert.ok(Math.abs(r.zones[0].notional-249.208801992)<1e-9);assert.equal(r.source_ts,1791371573962);const p=buildPumpLiquidationZones({contract:'WIF-USDT',current_price:r.zones[0].native_reference_price,provider_maps:[r],observed_ts:T});assert.equal(p.above.length,1);assert.equal(p.above[0].estimated,true);assert.equal(p.above[0].decision_target_eligible,false);assert.equal(p.above[0].source,'dYdX pinned protocol model');});
test('combined production factory serves both exact eligible assets in3 admitted HTTP and then0-clock-preserving reuse',async()=>{const io=transport(),s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,clock:()=>T,fetch_impl:io.fetch_impl,provider_admit:grant,candidate_slots:2,max_http_per_run:5,dydx_enabled:true,dydx_crypto_assets:crypto_assets,dydx_routing:routing()});const base={run_id:'CONTROLLED_DYDX_REPLAY',deep_started_ts:T,max_deep_ms:45000,allowed_source_ids:['DYDX_PINNED_NATIVE'],dydx_position_batch_contracts:['WIF-USDT','ETH-USDT']};const a=await s.collect({...base,contract:'WIF-USDT',native_symbol:'WIF'}),b=await s.collect({...base,contract:'ETH-USDT',native_symbol:'ETH'});assert.ok(a?.scoped?.[0]);assert.ok(b?.scoped?.[0]);assert.equal(io.calls(),3);assert.equal(s.summary().shared_budget.reserved_http,3);assert.equal(s.summary().shared_budget.actual_http,3);assert.deepEqual(s.summary().routed.map(x=>x.source_outcome.attempted_http_count),[3,0]);for(const [acq,contract] of [[a,'WIF-USDT'],[b,'ETH-USDT']]){const bound=bindScopedProviderAcquisition(acq.scoped[0],{contract,run_id:base.run_id,snapshot_id:'CONTROLLED:'+contract,observed_ts:T,direction:'LONG'});assert.equal(bound.status,'USABLE_SCOPED_NATIVE_CONTEXT');assert.equal(bound.source_ts,1791371573962);assert.equal(bound.entry_eligible,false);assert.equal(bound.freshness_max_age_ms,120000);assert.equal(bindScopedProviderAcquisition(acq.scoped[0],{contract,run_id:base.run_id,snapshot_id:'CONTROLLED:'+contract,observed_ts:T+120000}).status,'NOT_CLOSED');}});
test('disabled producer or absent structural hints makes no extra source HTTP or admission',async()=>{for(const opt of [{dydx_enabled:false,dydx_routing:routing()},{dydx_enabled:true,dydx_routing:null}]){let calls=0,admissions=0;const s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,clock:()=>T,fetch_impl:async()=>{calls++;throw Error('forbidden')},provider_admit:async()=>{admissions++;return grant({})},dydx_crypto_assets:crypto_assets,...opt});assert.equal(await s.collect({contract:'WIF-USDT',native_symbol:'WIF',run_id:'CONTROLLED_OFF',deep_started_ts:T,allowed_source_ids:['DYDX_PINNED_NATIVE']}),null);assert.equal(calls,0);assert.equal(admissions,0);}});
test('unspent or unknown source allowance denial never performs native reads or creates levels',async()=>{for(const denial of [{allowed:false,new_reservation:false,reservation_not_created:true,reason:'FREE_QUOTA_EXHAUSTED'},{allowed:false,new_reservation:false,reason:'ACK_UNKNOWN'}]){let calls=0;const s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,clock:()=>T,fetch_impl:async()=>{calls++;throw Error('forbidden')},provider_admit:async()=>denial,dydx_enabled:true,dydx_crypto_assets:crypto_assets,dydx_routing:routing()});assert.equal(await s.collect({contract:'WIF-USDT',native_symbol:'WIF',run_id:'CONTROLLED_DENIAL',deep_started_ts:T,allowed_source_ids:['DYDX_PINNED_NATIVE']}),null);assert.equal(calls,0);assert.equal(s.summary().shared_budget.reserved_http,denial.reservation_not_created?0:3);}});
test('read-only operation allowlist fails before any transport and never refunds the durable source reservation',async()=>{let calls=0;const b=createSharedSourceBudget({clock:()=>T,provider_admit:grant,fetch_impl:async()=>{calls++;return new Response('{}')},max_requests:5});await b.admit({reservation_id:'READONLY',run_id:'R',contract:'WIF-USDT',requests:{DYDX_RPC:3},max_requests:3,deadline_ts:T+10000});await assert.rejects(()=>b.fetch('https://dydx-rpc.publicnode.com/',{method:'POST',body:JSON.stringify({jsonrpc:'2.0',id:1,method:'broadcast_tx_sync',params:{}})}),/READ_ONLY/);assert.equal(calls,0);assert.equal(b.summary().reserved_http,3);});
test('bounded page records retain the original continuation cursor without storing level state',()=>{const s=snapshot(),prior=routing();const page=s.next_page_key_hex;assert.ok(page);const r=buildDydxRouting({previous:prior,snapshot:s,crypto_assets,now:T});assert.equal(r.next_page_key_hex,page);assert.ok(!JSON.stringify(r).includes('liquidation_price'));});
test('durable structural save requires an acknowledged D1 write and never accepts unknown/newer competing ACK',async()=>{for(const ack of [{success:true,meta:{changes:1}},{success:true,meta:{changes:0}},{}]){let writes=0;const db={prepare:()=>({bind:()=>({run:async()=>{writes++;return ack}})})},prior=routing(),out=await saveDydxRouting({db,previous:prior,snapshot:snapshot(),crypto_assets,now:T,db_admit:()=>({allowed:true})});assert.equal(writes,1);assert.equal(out.status,ack.meta?.changes===1?'DYDX_STRUCTURAL_ROUTING_SAVED':ack.meta?.changes===0?'NEWER_ROUTING_RETAINED':'D1_WRITE_ACK_UNKNOWN');if(ack.meta?.changes!==1)assert.equal(out.routing,prior);}});
test('new dYdX request scope is opt-in1000 and reconciles all earlier research reservations without resetting other providers',async()=>{class DB{constructor(){this.statements=[]}prepare(sql){const db=this;return{bind(...args){db.statements.push({sql,args});return this;}}}async batch(xs){return xs.map(()=>({success:true,meta:{changes:1}}))}}const db=new DB(),on=await installSourceAllowances({db,now:T,enable_dydx_native:true});assert.equal(on.provider_operational_caps.DYDX_RPC,1000);assert.equal(on.provider_operational_caps.HYPERLIQUID,10000);assert.equal(on.provider_operational_caps.GTRADE,4000);assert.equal(on.combined_run_http_cap,5);assert.equal(on.automatic_topup,false);assert.ok(db.statements.some(x=>x.sql.includes('SUM(reserved_units)')&&x.args[1]==='DYDX_RPC'));assert.equal((await installSourceAllowances({db:new DB(),now:T})).bindings.DYDX_RPC,undefined);});

function withAccountPage(value){const r=structuredClone(raw),row=r.raw[1];row.payload.result.response.value=value.toString('base64');row.raw_body_utf8=JSON.stringify(row.payload);row.receipt.bytes=Buffer.byteLength(row.raw_body_utf8);row.receipt.sha256=createHash('sha256').update(row.raw_body_utf8).digest('hex');return decodeDydxPinnedSnapshot({raw:r,now:T});}
function chunks(b){let i=0;const out=[];function u(){let v=0,shift=0;for(;;){const n=b[i++];v+=(n&127)*2**shift;if(n<128)return v;shift+=7;}}while(i<b.length){const start=i,k=u(),n=u(),value=b.subarray(i,i+n);i+=n;out.push({k,value,bytes:b.subarray(start,i)});}return out;}
function field1(b){let n=b.length,vs=[];do{const x=n&127;n=Math.floor(n/128);vs.push(x|(n?128:0));}while(n);return Buffer.concat([Buffer.from([10,...vs]),b]);}
// These controlled protobuf mutations verify cleanup only; they are not live source evidence.
test('fresh complete native account removes a closed position hint and EOF resets the discovery cursor',()=>{const s=snapshot(),i=s.subaccounts.findIndex(a=>a.positions.length===2),parts=chunks(Buffer.from(raw.raw[1].payload.result.response.value,'base64')).filter(p=>p.k===10),emptyAccount=chunks(parts[i].value).find(p=>p.k===10).bytes;parts[i]={bytes:field1(emptyAccount)};const fresh=withAccountPage(Buffer.concat(parts.map(p=>p.bytes))),updated=buildDydxRouting({previous:routing(),snapshot:fresh,crypto_assets,now:T});assert.equal(updated.accounts.length,1);assert.deepEqual(updated.accounts[0].coins,['ATOM','ETH']);assert.equal(updated.next_page_key_hex,null);assert.ok(validateDydxRouting(updated,{now:T}));});
test('empty terminal native page retains unseen hints without claiming it closed their positions',()=>{const s=withAccountPage(Buffer.from('1200','hex')),updated=buildDydxRouting({previous:routing(),snapshot:s,crypto_assets,now:T});assert.equal(s.subaccounts.length,0);assert.equal(updated.next_page_key_hex,null);assert.equal(updated.accounts.length,2);});
test('pagination metadata survives a weekly boundary while old account hints cannot grant fresh collection permission',()=>{const r=routing(),v=validateDydxRouting(r,{now:T+8*86400000});assert.ok(v);assert.equal(v.accounts.length,0);assert.equal(v.next_page_key_hex,r.next_page_key_hex);assert.equal(selectDydxRouting(r,{symbol:'WIF',now:T+8*86400000}).length,0);assert.equal(validateDydxRouting(r,{now:T+29*86400000}),null);});
test('manual and weekly routing-only read is D1 admitted and performs no provider fetch',async()=>{let reads=0;const r=routing(),db={prepare:()=>({bind:()=>({first:async()=>{reads++;return{payload_json:JSON.stringify(r)}}})})};assert.equal(await loadDydxRouting({db,now:T,db_admit:()=>({allowed:false})}),null);assert.equal(reads,0);assert.deepEqual(await loadDydxRouting({db,now:T,db_admit:()=>({allowed:true})}),r);assert.equal(reads,1);});
