import test from 'node:test';import assert from 'node:assert/strict';import {qualifyEarlyDirectionReceipt} from '../files/src/early-direction-receipt.mjs';
const T=1791225015208,contract='ZEC-USDT',wave='EDW:ZEC-USDT:1791187242450:G3';
const actualSummary={contract,early_candidate_bridge:true,early_candidate_wave_id:wave,early_candidate_receipt:{status:'CLOSED',contract,wave_id:wave,source_ts:1791224965870,available_at:1791224965870,direction_hint:'LONG',direction_state:'DIRECTION_NOT_CLOSED',evidence_ids:[`${wave}:RELATIVE_STRENGTH:LONG`,`${wave}:RELATIVE_STRENGTH:SHORT`,`${wave}:VOLUME_ACCELERATION_PROXY:BOTH`]}};
// Evidence rows are a reproduction fixture; summary and original cutoff are from exact run 1791224954306-1791224965631.
const rows=['LONG','SHORT','BOTH'].map((side,i)=>({status:'CLOSED',side,evidence_id:actualSummary.early_candidate_receipt.evidence_ids[i]}));
const fixture=()=>({...actualSummary,early_candidate_receipt:{...actualSummary.early_candidate_receipt,evidence:rows}});
test('actual explicit DIRECTION_NOT_CLOSED cannot become canonical LONG',()=>{const r=qualifyEarlyDirectionReceipt(fixture(),T);assert.equal(r.closed,false);assert.equal(r.direction,null);assert.equal(r.direction_state_closed,false);assert.equal(r.reason,'EARLY_DIRECTION_STATE_NOT_CLOSED');});
test('only assigned directional facts are listed; opposite and BOTH remain unassigned',()=>{const d=fixture();d.early_candidate_receipt.direction_state='LONG_WATCH';const r=qualifyEarlyDirectionReceipt(d,T);assert.equal(r.closed,true);assert.deepEqual(r.evidence_ids,[rows[0].evidence_id]);assert.deepEqual(r.unassigned_evidence_ids,[rows[1].evidence_id,rows[2].evidence_id]);});
test('neutral BOTH evidence cannot establish a direction',()=>{const d=fixture();d.early_candidate_receipt.direction_state='CONFIRMED';d.early_candidate_receipt.evidence=[rows[2]];assert.equal(qualifyEarlyDirectionReceipt(d,T).closed,false);});
test('freshness, exact wave and matching directional state are required',()=>{for(const change of [d=>d.early_candidate_receipt.direction_state='SHORT_WATCH',d=>d.early_candidate_receipt.wave_id='OTHER',d=>d.early_candidate_receipt.source_ts=T-900001,d=>d.early_candidate_receipt.available_at=T+1,d=>d.early_candidate_receipt.contract='FOREIGN-USDT']){const d=fixture();d.early_candidate_receipt.direction_state='LONG_WATCH';change(d);assert.equal(qualifyEarlyDirectionReceipt(d,T).closed,false);}});
test('closed SHORT observation and confirmed LONG retain their existing valid paths',()=>{for(const [side,state] of [['SHORT','SHORT_WATCH'],['LONG','CONFIRMED']]){const d=fixture();d.early_candidate_receipt.direction_hint=side;d.early_candidate_receipt.direction_state=state;assert.equal(qualifyEarlyDirectionReceipt(d,T).direction,side);}});
