import test from 'node:test';import assert from 'node:assert/strict';import {collectEvidenceRouteBlock} from '../files/src/candidate-evidence-v2-runtime.mjs';
test('complementary role collectors share a fixed envelope and reuse valid caches when it is exhausted',async()=>{const routes=['A','B','CACHE','C'].map(name=>({name})),calls=[];const make=(id,n)=>async({request_admit,fetch_impl})=>{const grant=request_admit({logical_request_id:id,attempts:n});if(!grant.allowed)return{status:grant.status,network_calls:0};calls.push(id);for(let i=0;i<n;i++)await fetch_impl('https://source.example');return{status:'CLOSED',network_calls:n};};const out=await collectEvidenceRouteBlock({routes,max_requests:5,params:{request_admit:()=>({allowed:true}),fetch_impl:async()=>new Response('{}')},collectors:{A:make('A',3),B:make('B',2),CACHE:async()=>({status:'CLOSED',cache_status:'HIT',network_calls:0,evidence:[{block_id:'N07'}]}),C:make('C',1)}});assert.equal(out.network_calls,5);assert.deepEqual(calls,['A','B']);assert.equal(out.results.CACHE.evidence.length,1);assert.equal(out.results.C.status,'DEFERRED_SHARED_REQUEST_ENVELOPE');});
test('known provider quota denial leaves the local envelope for another useful role',async()=>{const out=await collectEvidenceRouteBlock({routes:[{name:'DENIED'},{name:'NEXT'}],max_requests:3,params:{request_admit:()=>({allowed:true}),fetch_impl:async()=>new Response('{}')},collectors:{DENIED:async({request_admit})=>{request_admit({attempts:3});return{status:'DAILY_CAP_OR_DUPLICATE',network_calls:0,admission:{allowed:false}};},NEXT:async({request_admit,fetch_impl})=>{const grant=request_admit({attempts:2});if(grant.allowed){await fetch_impl('https://source.example');await fetch_impl('https://source.example');}return{status:grant.allowed?'CLOSED':'BLOCKED',network_calls:grant.allowed?2:0};}}});assert.equal(out.results.NEXT.status,'CLOSED');assert.equal(out.reserved_requests,2);assert.equal(out.network_calls,2);});

test('unknown durable reservation after an exception cannot free capacity',async()=>{
 const out=await collectEvidenceRouteBlock({routes:[{name:'UNKNOWN'},{name:'NEXT'}],max_requests:3,params:{request_admit:()=>({allowed:true})},collectors:{UNKNOWN:async({request_admit})=>{request_admit({attempts:3});throw Error('ACK_UNKNOWN');},NEXT:async({request_admit})=>({status:request_admit({attempts:1}).status,network_calls:0})}});
 assert.equal(out.results.UNKNOWN.status,'CODE_OR_STORE_ERROR');assert.equal(out.reserved_requests,3);assert.equal(out.results.NEXT.status,'DEFERRED_SHARED_REQUEST_ENVELOPE');
});
test('transport counts attempts even when a collector throws after a failed request',async()=>{
 let attempted=0;const out=await collectEvidenceRouteBlock({routes:[{name:'FAIL'}],max_requests:1,params:{request_admit:()=>({allowed:true}),fetch_impl:async()=>{attempted++;throw Error('TIMEOUT');}},collectors:{FAIL:async({request_admit,fetch_impl})=>{request_admit({attempts:1});await fetch_impl('https://source.example');}}});
 assert.equal(attempted,1);assert.equal(out.network_calls,1);assert.equal(out.results.FAIL.network_calls,1);assert.equal(out.reserved_requests,1);
});
test('a later collector cannot spend an earlier unknown reservation',async()=>{
 let calls=0;const out=await collectEvidenceRouteBlock({routes:[{name:'UNKNOWN'},{name:'UNADMITTED'},{name:'OWN'}],max_requests:4,params:{request_admit:()=>({allowed:true}),fetch_impl:async()=>{calls++;return new Response('{}');}},collectors:{UNKNOWN:async({request_admit})=>{request_admit({attempts:3});throw Error('ACK_UNKNOWN');},UNADMITTED:async({fetch_impl})=>{await fetch_impl('https://source.example');return{status:'CLOSED'};},OWN:async({request_admit,fetch_impl})=>{request_admit({attempts:1});await fetch_impl('https://source.example');return{status:'CLOSED'};}}});
 assert.equal(calls,1);assert.equal(out.reserved_requests,4);assert.equal(out.results.UNADMITTED.status,'CODE_OR_STORE_ERROR');assert.equal(out.results.OWN.status,'CLOSED');
});
