import test from 'node:test';
import assert from 'node:assert/strict';
import {SOURCE_POLICIES,planEvidenceSourceRequest,normalizeOfficialEvent,normalizeChainTransfer,normalizeAttentionSample,normalizeCalendarEvent} from '../files/src/evidence-source-adapters.mjs';
import {validateEvidenceV2,consumeEvidenceV2} from '../files/src/evidence-v2.mjs';

test('K16 adapters: every selected free source has a fixed cap and concrete block role',()=>{for(const [id,row] of Object.entries(SOURCE_POLICIES)){assert.ok(row.daily_cap>0,id);assert.ok(row.ttl_ms>0,id);assert.ok(row.blocks.length,id);}});
test('K16 adapters: exact identity and free-key/cost gates fail closed before transport',()=>{
 assert.equal(planEvidenceSourceRequest({source:'CHAIN_RPC',htx_contract:'SOL-USDT',asset_id:'sol',registry_verified:false}).status,'EXACT_ASSET_IDENTITY_REQUIRED');
 assert.equal(planEvidenceSourceRequest({source:'CHAIN_RPC',htx_contract:'SOL-USDT',asset_id:'sol',registry_verified:true,methods:5}).status,'RPC_METHODS_PER_REFRESH_EXCEEDED');
 assert.equal(planEvidenceSourceRequest({source:'BLOCKSCOUT_INDEX',htx_contract:'SOL-USDT',asset_id:'sol',registry_verified:true}).status,'WAITING_FREE_KEY');
 assert.equal(planEvidenceSourceRequest({source:'BLOCKSCOUT_INDEX',htx_contract:'SOL-USDT',asset_id:'sol',registry_verified:true,secret_present:true,credit_cost:null}).status,'VERIFIED_CREDIT_COST_REQUIRED');
});
test('K16 adapters: official adverse event is risk, not an invented Short vote',()=>{const row=normalizeOfficialEvent({asset_id:'sol',htx_contract:'SOL-USDT',event_id:'halt',event_type:'PROTOCOL_HALT',effective_at:1500,source_ts:1000,observed_ts:1100,confirmed:true});assert.equal(row.directional_strength,null);assert.equal(row.risk_strength,1);assert.ok(consumeEvidenceV2([row],{base_interest:70,decision_ts:1200}).adjustment<0);});
test('K16 adapters: provisional chain event is explicit and cannot affect a decision',()=>{const row=normalizeChainTransfer({asset_id:'asset',htx_contract:'ABC-USDT',chain:'eip155:1',token_address:'0xabc',tx_hash:'0x1',log_index:2,from:'0x0',to:'0xa',zero_address:'0x0',amount_token:10,source_ts:1000,observed_ts:1100,finalized:false});assert.equal(row.block_id,'N02');assert.equal(validateEvidenceV2(row,{decision_ts:1200}).usable,false);assert.equal(row.finality_status,'PROVISIONAL');});
test('K16 adapters: social attention is zero-coverage until 30 windows over seven days',()=>{const cold=normalizeAttentionSample({provider_id:'BLUESKY_PUBLIC',asset_id:'sol',htx_contract:'SOL-USDT',window_start:0,window_end:1000,unique_authors:50,history_windows:29,history_days:7,observed_ts:1100}),warm=normalizeAttentionSample({provider_id:'BLUESKY_PUBLIC',asset_id:'sol',htx_contract:'SOL-USDT',window_start:0,window_end:1000,unique_authors:50,history_windows:30,history_days:7,observed_ts:1100});assert.equal(cold.coverage_fraction,0);assert.equal(warm.coverage_fraction,1);assert.equal(warm.directional_strength,null);});
test('K16 adapters: calendar schedules recheck and has no market direction',()=>{const row=normalizeCalendarEvent({provider_id:'BLS',event_id:'CPI',event_type:'CPI',effective_at:2000,source_ts:1000,observed_ts:1100});assert.equal(row.block_id,'N13');assert.equal(row.directional_strength,null);assert.equal(row.risk_strength,null);});
