import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {deliverExactSavedRunTelegram,validateExactSavedRunTelegram} from '../files/src/exact-saved-run-telegram.mjs';

class Stmt{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new Stmt(this.db,this.sql,args);}async run(){return this.db.raw.prepare(this.sql).run(...this.args);}async first(){return this.db.raw.prepare(this.sql).get(...this.args)||null;}}
class DB{constructor(){this.raw=new DatabaseSync(':memory:');this.raw.exec(`CREATE TABLE telegram_output_dispatch_journal_v2(dispatch_key TEXT PRIMARY KEY,category TEXT,source_ref TEXT,status TEXT,reserved_ts INTEGER,updated_ts INTEGER,message_hash TEXT,telegram_message_id TEXT,telegram_http_status INTEGER,error_text TEXT)`);}prepare(sql){return new Stmt(this,sql);}}
const NOW=1_800_000_000_000,RUN='1791163034769-1791163043488';
function candidate(contract,state,score){return{publication_id:`PUB:${contract}`,contract,run_id:RUN,snapshot_id:`S:${contract}`,observed_ts:NOW-1000,valid_until_ts:NOW+600000,block_coverage:{status:'CLOSED_ALL_15_CHECKED',all_blocks_checked:true,coverage_count:15,checked_block_count:15},canonical:{contract,status:'CLOSED',state,direction:state==='REJECTED'?null:'LONG',scores:{coin_interest_0_100:score,overall_0_100:null,entry_readiness_0_100:null,is_probability:false},reasons:[{label:'Качество раннего сигнала',value:score,unit:'из 100',source:'V3 early'}],trigger:{expires_ts:NOW+600000},data_quality:{owner_deferred_exact_signed_raw24h:true},liquidations:{future_only:true,calculated_fallback_enabled:false,calculated_zone_count:0,all_zones:[],above:[],below:[]},observed_ts:NOW-1000,snapshot_id:`S:${contract}`,run_id:RUN}};}
function saved(){return{run_id:RUN,status:'CLOSED',reason:null,secrets_included:false,alternative_manual_recalculation:false,market_scan_audit:{complete:true,universe_total:102,scanned:102,errors:0,stale:0},candidate_selection_audit:{top_two_contracts:['ADA-USDT','MUBARAK-USDT'],deep_check_selected:['ADA-USDT','MUBARAK-USDT'],registry_did_not_change_rank:true},candidates:[candidate('ADA-USDT','OBSERVE',73),candidate('MUBARAK-USDT','REJECTED',null)]};}

test('exact accepted saved run renders one approved non-entry observation',()=>{const r=validateExactSavedRunTelegram({saved_output:saved(),requested_run_id:RUN,now_ts:NOW});assert.equal(r.ok,true);assert.equal(r.candidate.contract,'ADA-USDT');assert.match(r.rendered.message,/ADA — ⚪️ НАБЛЮДЕНИЕ/u);assert.doesNotMatch(r.rendered.message,/ВХОД ОДОБРЕН/u);});
test('top-two drift, missing all15, or calculated liquidation fails closed',()=>{for(const mutate of [x=>x.candidate_selection_audit.deep_check_selected.reverse(),x=>x.candidates[0].block_coverage.checked_block_count=14,x=>x.candidates[0].canonical.liquidations.calculated_zone_count=1]){const x=saved();mutate(x);assert.equal(validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW}).ok,false);}});
test('network delivery requires positive message id and is idempotent on exact run and snapshot',async()=>{const db=new DB();let calls=0;const fetch_impl=async()=>{calls++;return{ok:true,status:200,async json(){return{ok:true,status:'SENT',message_id:321};}}};const args={db,saved_output:saved(),requested_run_id:RUN,enabled:true,relay_url:'https://relay.invalid',relay_key:'k',now_ts:NOW,fetch_impl};const first=await deliverExactSavedRunTelegram(args),second=await deliverExactSavedRunTelegram(args);assert.equal(first.status,'SENT');assert.equal(first.message_id,'321');assert.equal(second.status,'SENT');assert.equal(second.reused,true);assert.equal(calls,1);});
