import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {deliverExactSavedRunTelegram,validateExactSavedRunTelegram,acceptedJointForTelegramRetrieval} from '../files/src/exact-saved-run-telegram.mjs';
import {renderCanonicalTelegram,CANONICAL_PUBLICATION_VERSION} from '../files/src/canonical-publication.mjs';
import {formatManualReport} from '../files/src/manual-report-formatter.mjs';

class Stmt{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new Stmt(this.db,this.sql,args);}async run(){const result=this.db.raw.prepare(this.sql).run(...this.args);return this.db.rowsWrittenOnly?{meta:{rows_written:Number(result.changes)}}:result;}async first(){return this.db.raw.prepare(this.sql).get(...this.args)||null;}async all(){return{results:this.db.raw.prepare(this.sql).all(...this.args)};}}
class DB{constructor({rowsWrittenOnly=false}={}){this.rowsWrittenOnly=rowsWrittenOnly;this.raw=new DatabaseSync(':memory:');this.raw.exec(`CREATE TABLE telegram_output_dispatch_journal_v2(dispatch_key TEXT PRIMARY KEY,category TEXT NOT NULL CHECK(category IN ('MORNING_REPORT','SHADOW_FINAL_DECISION','WATCH70_CANDIDATE')),source_ref TEXT,status TEXT,reserved_ts INTEGER,updated_ts INTEGER,message_hash TEXT,telegram_message_id TEXT,telegram_http_status INTEGER,error_text TEXT)`);}prepare(sql){return new Stmt(this,sql);}}
const NOW=1_800_000_000_000,RUN='1791163034769-1791163043488';
function candidate(contract,state,score){return{publication_id:`PUB:${contract}`,contract,run_id:RUN,snapshot_id:`S:${contract}`,observed_ts:NOW-1000,valid_until_ts:NOW+600000,block_coverage:{status:'CLOSED_ALL_15_CHECKED',all_blocks_checked:true,coverage_count:15,checked_block_count:15},canonical:{contract,status:'CLOSED',state,direction:state==='REJECTED'?null:'LONG',scores:{coin_interest_0_100:score,overall_0_100:null,entry_readiness_0_100:null,is_probability:false},reasons:[{label:'Качество раннего сигнала',value:score,unit:'из 100',source:'V3 early'}],trigger:{metric:'price',operator:'>=',value:1,unit:'USDT',timeframe:'5m',expires_ts:NOW+600000,cancel_condition:'цена ниже 0,9 USDT',next_recheck_ts:NOW+300000},data_quality:{owner_deferred_exact_signed_raw24h:true},liquidations:{future_only:true,calculated_fallback_enabled:false,calculated_zone_count:0,all_zones:[],above:[],below:[]},observed_ts:NOW-1000,snapshot_id:`S:${contract}`,run_id:RUN}};}
function saved(){return{run_id:RUN,status:'CLOSED',reason:null,secrets_included:false,alternative_manual_recalculation:false,market_scan_audit:{complete:true,universe_total:102,scanned:102,errors:0,stale:0},candidate_selection_audit:{top_two_contracts:['ADA-USDT','MUBARAK-USDT'],deep_check_selected:['ADA-USDT','MUBARAK-USDT'],registry_did_not_change_rank:true},candidates:[candidate('ADA-USDT','OBSERVE',73),candidate('MUBARAK-USDT','REJECTED',null)]};}

function approvedView(c){return{...c.canonical,snapshot_time_utc:new Date(c.observed_ts).toISOString(),candidates:[{contract:c.contract,ticker:c.contract}],metadata:{...(c.canonical.metadata||{}),contract:c.contract}};}
test('exact accepted saved run preserves the established approved non-entry layout',()=>{const x=saved(),before=JSON.stringify(x),r=validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW});assert.equal(r.ok,true);assert.equal(r.candidate.contract,'ADA-USDT');assert.equal(r.rendered.formatter,CANONICAL_PUBLICATION_VERSION);assert.equal(r.rendered.message,renderCanonicalTelegram({canonical:approvedView(x.candidates[0]),lifecycle_event:'OBSERVE'}).text);assert.match(r.rendered.message,/^ADA\n🟢 РОСТ\n⚪️ РАННЕЕ НАБЛЮДЕНИЕ\nОценка: 73 из 100\./u);assert.match(r.rendered.message,/Для входа ждём:/u);assert.doesNotMatch(r.rendered.message,/Следующая проверка:|Снимок рынка:/u);assert.doesNotMatch(r.rendered.message,/ВХОД ОДОБРЕН|ADA — ⚪️ НАБЛЮДЕНИЕ/u);assert.equal(JSON.stringify(x),before);});
test('missing levels are explicit in approved Telegram and manual forms',()=>{const x=saved(),r=validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW}),m=formatManualReport(approvedView(x.candidates[0]));assert.equal(r.ok,true);assert.equal(m.ok,true);for(const output of [r.rendered.message,m.text]){assert.match(output,/Сильные ликвидации выше: уровни будущих ликвидаций не получены\./u);assert.match(output,/Сильные ликвидации ниже: уровни будущих ликвидаций не получены\./u);}});
test('numeric future levels supplement the same established layout and reach both forms',()=>{const empty=saved(),x=saved(),liq=x.candidates[0].canonical.liquidations;liq.above=[{kind:'NATIVE_FUTURE_LEVEL',side:'ABOVE',price:1.25,distance_pct:25,notional:25000,notional_unit:'USDC',price_quote:'USD',source:'Hyperliquid',source_ts:NOW-1000,estimated:false}];liq.below=[{...liq.above[0],side:'BELOW',price:0.75,distance_pct:-25}];liq.all_zones=[...liq.above,...liq.below];const out=validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW}),base=validateExactSavedRunTelegram({saved_output:empty,requested_run_id:RUN,now_ts:NOW}),manual=formatManualReport(approvedView(x.candidates[0]));assert.equal(out.ok,true);assert.equal(manual.ok,true);assert.equal(out.rendered.message.split('Сильные ликвидации выше:')[0],base.rendered.message.split('Сильные ликвидации выше:')[0]);for(const body of [out.rendered.message,manual.text]){assert.match(body,/1,25 USD/u);assert.match(body,/0,75 USD/u);assert.match(body,/25000 USDC/u);}assert.doesNotMatch(out.rendered.message,/уровни будущих ликвидаций не получены/u);});
test('short Unicode asset preserves approved header and expired snapshots never render',()=>{const x=saved();x.candidates[0]=candidate('龙虾-USDT','OBSERVE',83);x.candidates[0].canonical.direction='SHORT';x.candidate_selection_audit.top_two_contracts[0]='龙虾-USDT';x.candidate_selection_audit.deep_check_selected[0]='龙虾-USDT';assert.match(validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW}).rendered.message,/^龙虾\n🔴 СНИЖЕНИЕ\n⚪️ РАННЕЕ НАБЛЮДЕНИЕ/u);assert.equal(validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW+600001}).reason,'SAVED_OBSERVATION_EXPIRED');});
test('top-two drift, missing all15, or calculated liquidation fails closed',()=>{for(const mutate of [x=>x.candidate_selection_audit.deep_check_selected.reverse(),x=>x.candidates[0].block_coverage.checked_block_count=14,x=>x.candidates[0].canonical.liquidations.calculated_zone_count=1]){const x=saved();mutate(x);assert.equal(validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW}).ok,false);}});
test('network delivery sends exactly approved text and is idempotent on exact run and snapshot',async()=>{const db=new DB(),x=saved();let calls=0;const fetch_impl=async(url,options)=>{calls++;assert.equal(JSON.parse(options.body).text,renderCanonicalTelegram({canonical:approvedView(x.candidates[0]),lifecycle_event:'OBSERVE'}).text);return{ok:true,status:200,async json(){return{ok:true,status:'SENT',message_id:321};}}};const args={db,saved_output:x,requested_run_id:RUN,enabled:true,relay_url:'https://relay.invalid',relay_key:'k',now_ts:NOW,fetch_impl};const first=await deliverExactSavedRunTelegram(args),second=await deliverExactSavedRunTelegram(args);assert.equal(first.status,'SENT');assert.equal(first.validated_signal,true);assert.equal(first.message_id,'321');assert.equal(first.formatter,CANONICAL_PUBLICATION_VERSION);assert.equal(second.status,'SENT');assert.equal(second.validated_signal,true);assert.equal(second.reused,true);assert.equal(calls,1);});
test('D1 rows_written acknowledgement is accepted and still requires readback',async()=>{const db=new DB({rowsWrittenOnly:true}),fetch_impl=async()=>({ok:true,status:200,async json(){return{ok:true,status:'SENT',message_id:654};}});const out=await deliverExactSavedRunTelegram({db,saved_output:saved(),requested_run_id:RUN,enabled:true,relay_url:'https://relay.invalid',relay_key:'k',now_ts:NOW,fetch_impl});assert.equal(out.status,'SENT');assert.equal(out.message_id,'654');});
test('legacy pre-network reservation with no owner token is reclaimed once under the analytics lease',async()=>{const db=new DB(),gate=validateExactSavedRunTelegram({saved_output:saved(),requested_run_id:RUN,now_ts:NOW}),c=gate.candidate,key=`canonical-saved-run:${RUN}:${c.snapshot_id}:${gate.rendered.message_hash}`;db.raw.prepare(`INSERT INTO telegram_output_dispatch_journal_v2(dispatch_key,category,source_ref,status,reserved_ts,updated_ts,message_hash,telegram_message_id,telegram_http_status,error_text) VALUES (?1,'WATCH70_CANDIDATE',?2,'RESERVED',?3,?3,?4,NULL,NULL,NULL)`).run(key,`${RUN}|${c.snapshot_id}|${c.publication_id}`,NOW-1000,gate.rendered.message_hash);let calls=0;const fetch_impl=async()=>{calls++;return{ok:true,status:200,async json(){return{ok:true,status:'SENT',message_id:987};}}};const out=await deliverExactSavedRunTelegram({db,saved_output:saved(),requested_run_id:RUN,enabled:true,relay_url:'https://relay.invalid',relay_key:'k',now_ts:NOW,fetch_impl});assert.equal(out.status,'SENT');assert.equal(out.message_id,'987');assert.equal(calls,1);});
test('honestly accounted optional gaps permit the same approved renderer, while foreign or inflated use counts cannot',()=>{
 const x=saved(),ids=['N01','N02','N03','N04','N05','N06','N07','N08','N09','N10','N11','N12','N14','N15','N16'];
 for(const c of x.candidates){
  c.block_coverage={status:'PARTIAL_BLOCK_CHECK',all_blocks_checked:false,coverage_count:15,checked_block_count:6,blocks:Object.fromEntries(ids.map(id=>[id,{status:'NOT_CHECKED',source_statuses:{PRIMARY:'NO_EXACT_ROUTE'},source_checks:{PRIMARY:{checked:false}}}]))};
  c.block_decision_use={schema:'report2-block-decision-use-audit-v2-same-run-assessments',run_id:c.run_id,snapshot_id:c.snapshot_id,contract:c.contract,decision_ts:c.observed_ts,participating_block_ids:['N10'],participating_block_count:1,blocks:{N10:{participating:true}}};
 }
 assert.equal(validateExactSavedRunTelegram({saved_output:x,requested_run_id:RUN,now_ts:NOW}).ok,true);
 for(const mutate of [c=>c.block_decision_use.run_id='FOREIGN',c=>c.block_decision_use.participating_block_count=15,c=>delete c.block_coverage.blocks.N01]){const y=structuredClone(x);mutate(y.candidates[0]);assert.equal(validateExactSavedRunTelegram({saved_output:y,requested_run_id:RUN,now_ts:NOW}).ok,false);}
});

test('runner retrieval follows the bound owner scope and still requires actual joint, Top2 and real-only liquidation acceptance',()=>{
 const proof={status:'CLOSED',actual_evidence_verified:true,canonical_run_id:RUN,canonical_status:'CLOSED',actual_top_two_verified:true,block_acceptance:{all_candidates_fully_checked:false,all_block_outcomes_accounted:true,same_run_participation_verified:true,maximum_available_blocks_live_verified:true},owner_maximum_useful_amendment_sha256:'c7519f06133c9069231d5673dbdc631e51df7df8cf1de925cfa6137a31cd1fd9',liquidation_acceptance:{calculated_fallback_enabled:false,calculated_zone_count:0}};
 assert.equal(acceptedJointForTelegramRetrieval(proof,RUN),true);
 for(const mutate of [x=>x.canonical_run_id='OLD',x=>x.actual_top_two_verified=false,x=>x.actual_evidence_verified=false,x=>x.block_acceptance.same_run_participation_verified=false,x=>x.owner_maximum_useful_amendment_sha256='unknown',x=>x.liquidation_acceptance.calculated_zone_count=1]){const x=structuredClone(proof);mutate(x);assert.equal(acceptedJointForTelegramRetrieval(x,RUN),false);}
});
