import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_MAINTENANCE_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_MAINTENANCE_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url);
const {maintainExpiredProviderCache,CACHE_MAINTENANCE_SOURCES,CACHE_MAINTENANCE_BUDGET}=await import(new URL('expired-provider-cache-maintenance.mjs',root));
const NOW=1791236789811;
const source=CACHE_MAINTENANCE_SOURCES[Math.floor(NOW/2400000)%CACHE_MAINTENANCE_SOURCES.length];
function database(hook=()=>{}){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(`CREATE TABLE report2_evidence_source_cache(source TEXT,asset_key TEXT,observed_ts INTEGER,expires_ts INTEGER,payload_json TEXT,PRIMARY KEY(source,asset_key));CREATE TABLE report2_evidence_source_reservation(reservation_id TEXT PRIMARY KEY,attempts INTEGER);INSERT INTO report2_evidence_source_reservation VALUES('KEEP',7);CREATE TABLE full_evidence_snapshot_shadow(proof TEXT);INSERT INTO full_evidence_snapshot_shadow VALUES('immutable-original');`);
 let queries=0;
 return{sqlite,get queries(){return queries;},prepare(sql){queries++;return{args:[],bind(...args){this.args=args;return this;},async run(){hook(sql,this.args,sqlite);return sqlite.prepare(sql).run(...this.args);},async first(){hook(sql,this.args,sqlite);return sqlite.prepare(sql).get(...this.args)||null;},async all(){hook(sql,this.args,sqlite);return{results:sqlite.prepare(sql).all(...this.args)};}};}};
}
const seed=(db,n,{owner=source,expiry=NOW-1}={})=>{for(let i=0;i<n;i++)db.sqlite.prepare('INSERT INTO report2_evidence_source_cache VALUES(?,?,?,?,?)').run(owner,String(i).padStart(4,'0'),NOW-10000,expiry,'{"original":true}');};
const run=db=>maintainExpiredProviderCache({db,now:NOW,admit:b=>{assert.deepEqual(b,CACHE_MAINTENANCE_BUDGET);return{allowed:true};}});
test('no D1 work without preadmission; fixed read and write headroom',async()=>{const db=database();seed(db,12);const r=await maintainExpiredProviderCache({db,now:NOW,admit:()=>({allowed:false,status:'RUN_WRITE_RESERVATION_EXCEEDED'})});assert.equal(r.status,'RUN_WRITE_RESERVATION_EXCEEDED');assert.equal(db.queries,0);assert.equal(r.deleted,0);db.sqlite.close();});
test('one primary-key page deletes at most eight expired entries; history and source reservations preserved',async()=>{const db=database();seed(db,40);seed(db,2,{owner:'OTHER'});db.sqlite.prepare('UPDATE report2_evidence_source_cache SET expires_ts=? WHERE source=? AND asset_key=?').run(NOW+1,source,'0000');
const r=await run(db);assert.equal(r.scanned,32);assert.equal(r.deleted,8);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM report2_evidence_source_cache WHERE source=?').get(source).n,32);assert.equal(db.sqlite.prepare('SELECT payload_json FROM report2_evidence_source_cache WHERE source=? AND asset_key=?').get(source,'0000').payload_json,'{"original":true}');assert.equal(db.sqlite.prepare('SELECT attempts FROM report2_evidence_source_reservation').get().attempts,7);assert.equal(db.sqlite.prepare('SELECT proof FROM full_evidence_snapshot_shadow').get().proof,'immutable-original');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM report2_evidence_source_cache WHERE source=?').get('OTHER').n,2);
const plan=db.sqlite.prepare('EXPLAIN QUERY PLAN SELECT asset_key,observed_ts,expires_ts FROM report2_evidence_source_cache WHERE source=? AND asset_key>? ORDER BY asset_key LIMIT 32').all(source,'');assert(plan.every(r=>!r.detail.includes('SCAN ')));db.sqlite.close();});
test('cursor reaches expired pages beyond a fresh prefix and wraps without scanning other providers',async()=>{const db=database();seed(db,32,{expiry:NOW+3600000});for(let i=32;i<40;i++)db.sqlite.prepare('INSERT INTO report2_evidence_source_cache VALUES(?,?,?,?,?)').run(source,String(i).padStart(4,'0'),NOW-10000,NOW-1,'old');
assert.equal((await run(db)).deleted,0);const r=await run(db);assert.equal(r.scanned,8);assert.equal(r.deleted,8);assert.equal(r.page_complete,true);assert.equal((await run(db)).scanned,32);db.sqlite.close();});
test('concurrently refreshed clock or same-clock changed body survives conditional delete',async()=>{for(const change of ['clock','body']){let changed=false;const db=database((sql,args,s)=>{if(sql.startsWith('DELETE FROM')&&!changed){changed=true;if(change==='clock')s.prepare('UPDATE report2_evidence_source_cache SET observed_ts=?,expires_ts=? WHERE source=? AND asset_key=?').run(NOW,NOW+60000,args[0],args[1]);else s.prepare('UPDATE report2_evidence_source_cache SET payload_json=? WHERE source=? AND asset_key=?').run('new-body',args[0],args[1]);}});seed(db,1);const r=await run(db);assert.equal(r.deleted,0);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM report2_evidence_source_cache WHERE source=?').get(source).n,1);db.sqlite.close();}});
test('failed cursor persistence honestly records any preceding deletion',async()=>{const db=database(sql=>{if(sql.startsWith('INSERT INTO report2_evidence_source_cache'))throw Error('simulated storage failure');});seed(db,1);const r=await run(db);assert.equal(r.status,'CACHE_MAINTENANCE_ERROR');assert.equal(r.deleted,1);db.sqlite.close();});
