import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
const root=process.env.REPORT2_RECEIPT_RUNTIME?path.resolve(process.env.REPORT2_RECEIPT_RUNTIME,'src'):path.resolve('current-generation/files/src');
const load=rel=>import(pathToFileURL(path.join(root,rel)));
const tape=await load('htx-signed-tape.mjs'),{parseHtxMarketJson}=await load('htx-trade-json.mjs'),{buildHtxFlowClosureDiagnostic}=await load('source-closure-diagnostics.mjs'),{completeRecheck}=await load('recheck-scheduler.mjs');
const T=1791537994409,contract='ZEC-USDT',url=`https://api.hbdm.com/linear-swap-ex/market/history/trade?contract_code=${contract}`;
const source=fs.readFileSync(path.join(root,'worker.js'),'utf8');
const worker=source.slice(source.indexOf('async function fetchJson(url) {'),source.indexOf('function createPerDeepCheckFetchCache('));
const fetcher=fetch=>{const context=vm.createContext({fetch,AbortController,setTimeout:()=>1,clearTimeout:()=>{},Date:{now:()=>T},parseHtxMarketJson,observeHtxAcquisitionAttempt:tape.observeHtxAcquisitionAttempt});return vm.runInContext(worker+';fetchJson',context);};
async function diagnostic(){await tape.persistCapturedHtxSignedTape({contract,now:T,db_admit:()=>{throw Error('NO_D1_ON_MISSING_CAPTURE');}});const flow=tape.capturedSignedTapeFourHourFlow({contract,now:T});assert.equal(flow.check_completed,false);assert.equal(flow.evidence.length,0);return {flow,receipt:buildHtxFlowClosureDiagnostic({contract,now:T,signed_flow:flow})};}
test('actual worker failures retain only safe stage/status while missing source remains missing',async()=>{
 const cases=[['TIMEOUT','ABORT_ERROR',null,()=>{throw Object.assign(new Error('SECRET_TOKEN'),{name:'AbortError'});}],['TRANSPORT_FAILED','TRANSPORT_EXCEPTION',null,()=>{throw Error('SECRET_TOKEN');}],['BODY_READ_FAILED','TRANSPORT_EXCEPTION',200,()=>({ok:true,status:200,text:async()=>{throw Error('SECRET_TOKEN');}})],['JSON_PARSE_FAILED','INVALID_JSON',200,()=>({ok:true,status:200,text:async()=>'{broken SECRET_TOKEN'})],['JSON_PARSE_FAILED','CHANNEL_MISMATCH',200,()=>({ok:true,status:200,text:async()=>JSON.stringify({status:'ok',ch:'market.BTC-USDT.trade.detail',ts:T,data:[]})})],['API_REJECTED','HTTP_REJECTED',429,()=>({ok:false,status:429,text:async()=>'{"status":"error","err-msg":"SECRET_TOKEN"}'})],['API_REJECTED','API_REJECTED',200,()=>({ok:true,status:200,text:async()=>'{"status":"error","err-msg":"SECRET_TOKEN"}'})]];
 for(const [stage,code,status,response] of cases){tape.clearHtxSignedTapeSnapshots();let calls=0;const result=await fetcher(async()=>{calls++;return response();})(url);assert.equal(result.ok,false);assert.equal(calls,1);const {flow,receipt}=await diagnostic(),r=receipt.acquisition.source_request_failure;assert.equal(r.stage,stage);assert.equal(r.error_code,code);assert.equal(r.http_status,status);assert.equal(r.started_ts,T);assert.equal(flow.raw_acquisition_diagnostic.source_clocks.trades.status,'MISSING_CAPTURE');assert.equal(flow.raw_acquisition_diagnostic.source_clocks.trades.source_ts,null);assert.ok(!JSON.stringify(receipt).includes('SECRET_TOKEN'));assert.ok(Buffer.byteLength(JSON.stringify(receipt))<=2048);}
});
test('failed response cannot refresh an earlier source capture and foreign routes cannot explain it',async()=>{
 tape.clearHtxSignedTapeSnapshots();tape.observeHtxSignedTape({status:'ok',ch:`market.${contract}.trade.detail`,ts:T-120001,data:[]},url,T-120000);
 await fetcher(async()=>{throw Error('private');})(url);const {flow,receipt}=await diagnostic();assert.equal(flow.raw_acquisition_diagnostic.source_clocks.trades.source_ts,T-120001);assert.equal(flow.raw_acquisition_diagnostic.source_clocks.trades.status,'SOURCE_CAPTURE_NOT_FRESH');assert.equal(receipt.acquisition.source_request_failure.stage,'TRANSPORT_FAILED');
 tape.clearHtxSignedTapeSnapshots();for(const u of [url.replace('api.hbdm.com','foreign.test'),url.replace(contract,'BTC-USDT')])await fetcher(async()=>{throw Error('private');})(u);assert.equal((await diagnostic()).receipt.acquisition.source_request_failure,undefined);
});
test('valid sample retains exact identifier and source clock but does not prove full four hours',async()=>{
 tape.clearHtxSignedTapeSnapshots();const r=await fetcher(async()=>({ok:true,status:200,text:async()=>`{"status":"ok","ch":"market.${contract}.trade.detail","ts":${T-100},"data":[{"data":[{"id":123456789012345678901}]}]}`}))(url);assert.equal(r.ok,true);assert.equal(r.data.data[0].data[0].id,'123456789012345678901');const {flow,receipt}=await diagnostic();assert.equal(flow.raw_acquisition_diagnostic.source_clocks.trades.source_ts,T-100);assert.equal(receipt.acquisition.source_request_failure,undefined);
});
class DB{constructor(){this.sql=new DatabaseSync(':memory:');this.writes=0;this.sql.exec(`CREATE TABLE v3_recheck_task_shadow(task_id TEXT PRIMARY KEY,publication_id TEXT,contract_code TEXT,direction TEXT,run_id TEXT,state TEXT,last_result TEXT,lease_owner TEXT,lease_started_ts INTEGER,lease_expires_ts INTEGER,updated_ts INTEGER,expires_ts INTEGER);CREATE TABLE canonical_publication_shadow(publication_id TEXT,contract_code TEXT,direction TEXT,run_id TEXT,observed_ts INTEGER);`);}prepare(sql){const self=this;return{bind(...args){const order=[],q=sql.replace(/\?(\d+)/g,(_,n)=>{order.push(Number(n)-1);return '?';});return{async run(){self.writes++;const r=self.sql.prepare(q).run(...order.map(i=>args[i]));return{meta:{changes:Number(r.changes)}};}};}};}}
const light={schema:'LIGHT_PRICE_RECHECK_V1',status:'TRIGGER_PRICE_REACHED_FULL_ANALYSIS_REQUIRED',task_id:'TASK',publication_id:'OLD',run_id:'ORIGINAL',snapshot_id:'S1',analytical_fingerprint:'abc',telegram_message_id:'169',checked_ts:T-1000,source_ts:T-1200,observed_ts:T-1200,price:0.240388,entry_authorized:false};
function database(){const d=new DB();d.sql.prepare('INSERT INTO v3_recheck_task_shadow VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('TASK','OLD',contract,'LONG','ORIGINAL','CLAIMED',JSON.stringify(light),'GITHUB_ACTIONS',T-500,T+5000,T-500,T+6000);d.sql.prepare('INSERT INTO canonical_publication_shadow VALUES(?,?,?,?,?)').run('NEW',contract,'LONG','FRESH',T-100);return d;}
const finish=d=>completeRecheck(d,{task_id:'TASK',actor:'GITHUB_ACTIONS',lease_started_ts:T-500,result:'DONE',new_publication_id:'NEW',now_ts:T});
test('full analysis completion preserves exact collector price identity and clocks in the same one write',async()=>{const d=database(),before=d.sql.prepare('SELECT * FROM v3_recheck_task_shadow').get();assert.equal((await finish(d)).completed,true);assert.equal(d.writes,1);const row=d.sql.prepare('SELECT * FROM v3_recheck_task_shadow').get(),receipt=JSON.parse(row.last_result);assert.deepEqual(receipt.original_light_price_receipt,light);assert.equal(receipt.publication_id,'NEW');assert.equal(receipt.completed_ts,T);assert.equal(row.expires_ts,before.expires_ts);assert.equal(row.state,'DONE');assert.equal(row.lease_owner,null);assert.equal((await finish(d)).completed,false);assert.equal(d.sql.prepare('SELECT last_result FROM v3_recheck_task_shadow').get().last_result,row.last_result);});
test('foreign or stale completion cannot erase the original trigger receipt',async()=>{for(const change of ["UPDATE canonical_publication_shadow SET contract_code='BTC-USDT'","UPDATE canonical_publication_shadow SET run_id='ORIGINAL'",`UPDATE canonical_publication_shadow SET observed_ts=${T-501}`,"UPDATE v3_recheck_task_shadow SET lease_owner='FOREIGN'",`UPDATE v3_recheck_task_shadow SET lease_expires_ts=${T-1}`]){const d=database();d.sql.exec(change);assert.equal((await finish(d)).completed,false);assert.equal(d.sql.prepare('SELECT last_result FROM v3_recheck_task_shadow').get().last_result,JSON.stringify(light));}});
