import test from 'node:test';
import assert from 'node:assert/strict';
import {captureBykFutureMap,capturedFutureMap,collectStandaloneFutureMap,normalizeCoinLobsterFutureHint,collectCoinLobsterFutureHint,captureNativeFutureMap,capturedNativeFutureMaps} from '../files/src/future-liquidation-map-source.mjs';
import {seal} from '../files/src/liquidation-extension/core.mjs';
import {buildPumpLiquidationZones} from '../files/src/pump-liquidation-zones.mjs';
const T=1800000000000;
test('full source position map retains unselected huge distant levels and cannot cross runs or store account addresses',()=>{
 const receipt=seal({provider:'Hyperliquid official',native_symbol:'SUI',run_id:'FULL-NATIVE',source_ts:T,status:'USABLE_SCOPED_CONTEXT',usable_for_context:true,evidence_class:'NATIVE_ACCOUNT_LIQUIDATION_PRICES',zones:Array.from({length:10},(_,i)=>({native_price:101+i*100,liquidated_side:'SHORT',notional:1000000+i*1000,notional_unit:'USDC',native_reference_price:100,source_ts:T,account:'private-account-address'}))});
 assert.equal(captureNativeFutureMap(receipt,{contract:'SUI-USDT',run_id:'OTHER',price_quote:'USDC'}),false);
 assert.equal(captureNativeFutureMap({...receipt,zones:[]},{contract:'SUI-USDT',run_id:'FULL-NATIVE',price_quote:'USDC'}),false);
 assert.equal(captureNativeFutureMap(receipt,{contract:'SUI-USDT',run_id:'FULL-NATIVE',price_quote:'USDC'}),true);
 assert.deepEqual(capturedNativeFutureMaps({contract:'SUI-USDT',run_id:'OTHER'}),[]);
 const maps=capturedNativeFutureMaps({contract:'SUI-USDT',run_id:'FULL-NATIVE'});assert.doesNotMatch(JSON.stringify(maps),/private-account-address/);
 const out=buildPumpLiquidationZones({contract:'SUI-USDT',current_price:100,observed_ts:T,provider_maps:maps});assert.equal(out.all_zones.length,10);assert.equal(out.above[0].price,1001);assert.equal(out.above[0].price_quote,'USDC');assert.equal(out.above[0].notional,1009000);assert.equal(out.above[0].estimated,false);
});
test('protected structured map capture is exact-symbol and source-clock bound without another request',()=>{
 const p={symbol:'SUI',as_of:new Date(T).toISOString(),real_levels:{model_version:'real_v1_multi',reference_price:100,sources:['gate','htx'],levels:[{price:110,notional_usd:2000000,side:'short'}]}};
 captureBykFutureMap({url:'https://bykaranteli.com/api/liqmap/public?symbol=SUI',payload:p,received_ts:T});
 const r=capturedFutureMap({contract:'SUI-USDT',run_id:'R',snapshot_id:'S',observed_ts:T});assert.equal(r.data_available,true);assert.equal(r.maps[0].zones.length,1);assert.equal(r.maps[0].native_symbol,'SUI');assert.equal(capturedFutureMap({contract:'OTHER-USDT',run_id:'R',snapshot_id:'S',observed_ts:T}).data_available,false);assert.equal(capturedFutureMap({contract:'SUI-USDT',run_id:'R',snapshot_id:'S',observed_ts:T+300001}).status,'STALE_RESPONSE');
});
test('unsupported exact coin is retained as coverage failure, never zero future liquidations',()=>{captureBykFutureMap({url:'https://bykaranteli.com/api/liqmap/public?symbol=BTW',payload:{error:{code:'INVALID_SYMBOL'}},received_ts:T,http_status:400});const r=capturedFutureMap({contract:'BTW-USDT',run_id:'R',snapshot_id:'S',observed_ts:T});assert.equal(r.status,'EXACT_SYMBOL_UNSUPPORTED');assert.equal(r.maps.length,0);assert.equal(r.data_available,false);});
test('standalone map needs both HTTP and monthly admission before network, with exactly one attempt',async()=>{let calls=0,quotaCalls=0;const opts={contract:'SUI-USDT',run_id:'R',fetch_impl:async()=>{calls++;return new Response(JSON.stringify({error:{code:'INVALID_SYMBOL'}}),{status:400});},quota_reserve:async()=>{quotaCalls++;return{allowed:true};}};await collectStandaloneFutureMap({...opts,request_admit:()=>({allowed:false})});assert.equal(calls,0);assert.equal(quotaCalls,0);await collectStandaloneFutureMap({...opts,request_admit:()=>({allowed:true,duplicate:false}),quota_reserve:async()=>({allowed:false,status:'EXHAUSTED'})});assert.equal(calls,0);const r=await collectStandaloneFutureMap({...opts,request_admit:()=>({allowed:true,duplicate:false})});assert.equal(calls,1);assert.equal(quotaCalls,1);assert.equal(r.status,'EXACT_SYMBOL_UNSUPPORTED');});
test('partial future hint retains its age and access limits without a price or amount',()=>{const r=normalizeCoinLobsterFutureHint({available:true,coin:'BTW',headline:{coin:'BTW',nearest_liquidation_zone:'below'},as_of_ms:T-1800000,delayed:{minutes:30},detail:'headline',access_note:'Rows withheld.'},{contract:'BTW-USDT',received_ts:T});assert.equal(r.status,'PARTIAL_HINT_ONLY');assert.equal(r.source_age_ms,1800000);assert.equal(r.direction,'below');assert.equal(r.level_price,null);assert.equal(r.notional,null);assert.equal(r.score_eligible,false);assert.equal(r.access_note,'Rows withheld.');assert.equal(normalizeCoinLobsterFutureHint({...r,coin:'OTHER'},{contract:'BTW-USDT',received_ts:T}).data_available,false);});
test('cloud keyless MCP is a single read-only tool call and supports streamed responses',async()=>{let calls=0;const result=await collectCoinLobsterFutureHint({contract:'BTW-USDT',fetch_impl:async(url,init)=>{calls++;assert.equal(url,'https://coinlobster.com/mcp');assert.equal(init.method,'POST');const body=JSON.parse(init.body);assert.equal(body.method,'tools/call');assert.equal(body.params.name,'liq_zones');assert.equal(body.params.arguments.pair,'BTW/USD');return new Response('data: '+JSON.stringify({id:1,result:{structuredContent:{available:true,coin:'BTW',headline:{coin:'BTW',nearest_liquidation_zone:'below'},as_of_ms:Date.now(),detail:'headline'}}})+'\n\n');}});assert.equal(calls,1);assert.equal(result.status,'PARTIAL_HINT_ONLY');assert.equal(result.network_calls,1);});
