import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {normalizeGdeltOfficialDiscovery,collectGdeltOfficialDiscovery} from '../files/src/gdelt-official-discovery.mjs';

class Statement{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new Statement(this.db,this.sql,args);}async run(){return this.db.sqlite.prepare(this.sql).run(...this.args);}async first(){return this.db.sqlite.prepare(this.sql).get(...this.args)||null;}}
class DB{constructor(){this.sqlite=new DatabaseSync(':memory:');}prepare(sql){return new Statement(this,sql);}async batch(rows){this.sqlite.exec('BEGIN');try{const out=[];for(const row of rows)out.push(await row.run());this.sqlite.exec('COMMIT');return out;}catch(error){this.sqlite.exec('ROLLBACK');throw error;}}}
const NOW=Date.parse('2026-09-28T03:00:00Z'),META={official_name:'ABC Protocol',official_domains:['abc.example']},payload={articles:[{url:'https://abc.example/news/1',title:'ABC update',seendate:'20260928T023000Z',sourcecountry:'US',language:'English'},{url:'https://fake.example/news/2',title:'ABC rumor',seendate:'20260928T023000Z'}]};

test('K16 GDELT retains only exact official-domain URLs and never creates market evidence',()=>{const out=normalizeGdeltOfficialDiscovery({payload,asset_metadata:META,observed_ts:NOW});assert.equal(out.status,'CLOSED');assert.equal(out.discoveries.length,1);assert.equal(out.discoveries[0].host,'abc.example');assert.equal(out.evidence.length,0);assert.match(out.direction_policy,/NO_MARKET_VOTE/);});
test('K16 GDELT requires exact name and domain instead of ticker guessing',()=>{assert.equal(normalizeGdeltOfficialDiscovery({payload,asset_metadata:{official_name:'ABC'},observed_ts:NOW}).status,'EXACT_OFFICIAL_IDENTITY_REQUIRED');assert.equal(normalizeGdeltOfficialDiscovery({payload,asset_metadata:{official_domains:['abc.example']},observed_ts:NOW}).status,'EXACT_OFFICIAL_IDENTITY_REQUIRED');});
test('K16 GDELT uses one admitted cached discovery request',async()=>{const db=new DB(),urls=[],fetch_impl=async url=>{urls.push(String(url));return{ok:true,status:200,json:async()=>payload};},base={db,fetch_impl,request_admit:()=>({allowed:true,status:'RESERVED'}),contract:'ABC-USDT',run_id:'R',asset_metadata:META,now:NOW};const first=await collectGdeltOfficialDiscovery(base),second=await collectGdeltOfficialDiscovery({...base,run_id:'R2',now:NOW+1});assert.equal(first.status,'CLOSED');assert.equal(first.network_calls,1);assert.equal(second.network_calls,0);assert.equal(urls.length,1);const decoded=decodeURIComponent(urls[0]);assert.match(decoded,/domain:abc\.example/);assert.match(decoded,/maxrecords=50/);assert.match(decoded,/timespan=24h/);});
test('K16 GDELT fails closed before network without whole-job admission',async()=>{let calls=0;const out=await collectGdeltOfficialDiscovery({db:new DB(),fetch_impl:async()=>{calls++;throw Error('no');},contract:'ABC-USDT',run_id:'R',asset_metadata:META,now:NOW});assert.equal(out.status,'WHOLE_JOB_HTTP_ADMISSION_REQUIRED');assert.equal(calls,0);});
test('K16 GDELT respects Retry-After and performs zero calls during global 429 backoff',async()=>{const db=new DB();let calls=0,fetch_impl=async()=>{calls++;return{ok:false,status:429,headers:{get:name=>name==='retry-after'?'120':null},json:async()=>({})};},base={db,fetch_impl,request_admit:()=>({allowed:true,status:'RESERVED'}),contract:'ABC-USDT',run_id:'R429',asset_metadata:META,now:NOW};const first=await collectGdeltOfficialDiscovery(base),second=await collectGdeltOfficialDiscovery({...base,run_id:'R429-2',now:NOW+1});assert.equal(first.status,'RATE_LIMITED_429');assert.equal(first.retry_after_ms,120000);assert.equal(second.status,'RATE_LIMITED_429');assert.equal(second.network_calls,0);assert.equal(second.cache_status,'GLOBAL_RATE_BACKOFF');assert.equal(calls,1);});
