import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import {gunzipSync} from 'node:zlib';import test from 'node:test';import assert from 'node:assert/strict';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'runtime'),load=n=>import(pathToFileURL(path.join(root,'src',n))),require=createRequire(path.join(root,'src/liquidation-extension/package.json')),sdk=require('@gainsnetwork/sdk'),{ethers}=require('ethers'),iface=new ethers.utils.Interface([...JSON.parse(fs.readFileSync('tools/gtrade-chain-abi.json')),...JSON.parse(fs.readFileSync('tools/gtrade-exact-selected-read-abi.json')).abi]),hash=b=>createHash('sha256').update(b).digest('hex');
const [pin,routing,collectors,gtrade,bridge,combined,canonical,wallet]=await Promise.all(['liquidation-extension/gtrade-pinned-position-snapshot.mjs','liquidation-extension/gtrade-position-routing.mjs','liquidation-extension/gtrade-runtime-collector.mjs','liquidation-extension/gtrade.mjs','liquidation-extension/gtrade-runtime-bridge.mjs','liquidation-extension/combined-runner-service.mjs','canonical-runtime-adapter.mjs','liquidation-extension/native-wallet-routing.mjs'].map(load));
const bytes=fs.readFileSync('gtrade-current-source/gtrade-actual-rpc-raw.json.gz'),raw=JSON.parse(gunzipSync(bytes)),proof=JSON.parse(fs.readFileSync('gtrade-current-source/gtrade-actual-rpc-proof.json'));assert.equal(hash(bytes),proof.raw_gzip_sha256);assert.equal(raw.head,'567726d9d67c40bb4a5e8c01a1437868dee3db55');assert.equal(proof.status,'ACTUAL_CURRENT_PINNED_RAY_NATIVE_AND_SCOPED_CONTEXT_VERIFIED');
const T=proof.observed_ts,variables=raw.raw.find(r=>r.url.endsWith('/trading-variables')).payload,prices=raw.raw.find(r=>r.url.endsWith('/charts')).payload,rpc=raw.raw.find(r=>r.method==='POST'),answers=new Map(rpc.payload.map(r=>[r.id,r.result])),fn=['getAllTradesForTraders','getAllTradeInfosForTraders','getAllTradesLiquidationParamsForTraders'],plain=(row,name)=>Object.fromEntries(iface.getFunction(name).outputs[0].components.map((p,i)=>[p.name,p.type==='bool'?row[i]:p.type==='address'?String(row[i]):row[i].toString()])),tradeArray=iface.decodeFunctionResult(fn[0],answers.get(3))[0].map(row=>plain(row,fn[0])),args=iface.decodeFunctionData('getTradeFeesDataArray',rpc.request_body.find(r=>r.id===6).params[0].data),selected=args[0].map((user,i)=>({trade:tradeArray.find(t=>t.user.toLowerCase()===user.toLowerCase()&&t.index===args[1][i].toString())})),receipt={http_status:rpc.http_status,sha256:rpc.sha256,received_ts:rpc.received_ts},decoded=pin.decodeGTradePinnedRpcSnapshot({body:rpc.request_body,response:rpc.payload,selected,current_block:variables.currentBlock,pair_index:299,receipt,as_of_ms:T}),assets=new Set(JSON.parse(gunzipSync(fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'))).assets.map(a=>a.symbol)),hints=routing.buildGTradePositionRouting({observation:decoded.routing_observation,variables,crypto_assets:assets,now:T}),id=t=>t.user.toLowerCase()+':'+t.index,feeMap=new Map(selected.map((s,i)=>[id(s.trade),iface.decodeFunctionResult('getTradeFeesDataArray',answers.get(6))[0][i]])),initialMap=new Map(selected.map((s,i)=>[id(s.trade),answers.get(i+7)]));
function replayRPC(body,{closed=false,error=false,foreign=false,omitted=false,allOmitted=false}={}){const feeRequest=body.find(r=>r.method==='eth_call'&&iface.parseTransaction({data:r.params[0].data}).name==='getTradeFeesDataArray'),requested=iface.decodeFunctionData('getTradeFeesDataArray',feeRequest.params[0].data),keys=requested[0].map((a,i)=>a.toLowerCase()+':'+requested[1][i].toString()),out=rpc.payload.filter(r=>r.id<=5).map(r=>({...r}));if(iface.parseTransaction({data:body.find(r=>r.id===3).params[0].data}).name==='getTrade'){const make=(id,result)=>({jsonrpc:'2.0',id,result}),point=rpc.payload.filter(r=>r.id<=2).map(r=>({...r}));for(const req of body.filter(r=>r.method==='eth_call')){const decodedCall=iface.parseTransaction({data:req.params[0].data}),name=decodedCall.name;let result;if(['getTrade','getTradeInfo','getTradeLiquidationParams'].includes(name)){const k=decodedCall.args[0].toLowerCase()+':'+decodedCall.args[1].toString(),row=decoded.trades.find(r=>id(r.trade)===k),value=row[name==='getTrade'?'trade':name==='getTradeInfo'?'tradeInfo':'liquidationParams'];const values=iface.getFunction(name).outputs[0].components.map(p=>closed?p.type==='bool'?false:p.type==='address'?'0x'+'0'.repeat(40):'0':foreign&&p.name==='user'?'0x'+'f'.repeat(40):value[p.name]);result=iface.encodeFunctionResult(name,[values]);}else if(name==='getTradeFeesDataArray')result=iface.encodeFunctionResult(name,[keys.map(k=>feeMap.get(k))]);else result=initialMap.get(decodedCall.args[1].toLowerCase()+':'+decodedCall.args[2].toString());point.push(make(req.id,result));}if(error)point[2]={jsonrpc:'2.0',id:3,error:{code:-32000,message:'CONTROLLED_EXACT_GETTER_ERROR'}};return point;}if(omitted||allOmitted){for(const [i,f]of fn.entries()){const original=iface.decodeFunctionResult(f,answers.get(i+3))[0],kept=original.filter((_,i)=>allOmitted?!keys.includes(id(tradeArray[i])):id(tradeArray[i])!==id(selected[0].trade));out.find(r=>r.id===i+3).result=iface.encodeFunctionResult(f,[kept]);}}if(closed||foreign){const tuples=tradeArray.map(t=>({...t,...(closed?{isOpen:false}:{}),...(foreign?{user:'0x'+'f'.repeat(40)}:{})})).map(t=>iface.getFunction(fn[0]).outputs[0].components.map(p=>t[p.name]));out.find(r=>r.id===3).result=iface.encodeFunctionResult(fn[0],[tuples]);}out.push({jsonrpc:'2.0',id:6,result:iface.encodeFunctionResult('getTradeFeesDataArray',[keys.map(k=>feeMap.get(k))])},...keys.map((k,i)=>({jsonrpc:'2.0',id:i+7,result:initialMap.get(k)})));if(error)out[2]={jsonrpc:'2.0',id:3,error:{code:-32000,message:'CONTROLLED_RPC_FAILURE'}};return out;}
const transport=(calls,options={})=>async(url,init={})=>{calls.push(String(url));if(String(url).endsWith('/open-trades'))throw Error('REPEATED_TRADE_DISCOVERY_FORBIDDEN');const value=String(url).endsWith('/trading-variables')?variables:String(url).endsWith('/charts')?prices:replayRPC(JSON.parse(init.body),options);return new Response(JSON.stringify(value));};
const params={contract:'RAY-USDT',native_symbol:'RAY',run_id:'RETAINED_RAY_3READ',acquisition_id:'RETAINED_RAY_3READ:A',deadline_ts:T+20000,snapshot_admitted:true,admit_position_snapshot:async()=>({allowed:true,new_reservation:true}),position_batch_contracts:['RAY-USDT']};
let retainedProof;
test('actual full native returned array yields11 structural IDs across7 exact crypto assets, only4 RAY fee-complete levels',()=>{assert.equal(tradeArray.length,128);assert.equal(hints.positions.length,11);assert.deepEqual([...new Set(hints.positions.map(p=>p.symbol))].sort(),['BNB','BTC','ETH','HYPE','PONS','RAY','ZEC']);assert.equal(decoded.trades.length,4);assert.equal(decoded.evidence.complete_position_census,false);assert.equal(decoded.routing_observation.complete_position_census,false);assert.ok(hints.positions.every(p=>!('long' in p)&&!('liquidationPrice' in p)));});
test('three controlled HTTP replays of original actual state preserve4 exact RAY estimates through scoped and canonical consumers',async()=>{const calls=[],collect=collectors.createGTradeRuntimeCollector({sdk,clock:()=>T,position_routing:hints,crypto_assets:assets,fetch_impl:transport(calls),reserve_rpc_enabled:true}),a=await collect(params);assert.equal(a.requests,3);assert.equal(calls.length,3);assert.equal(a.position_source_clock_known,true);assert.equal(a.acquisition.position_discovery_basis,'VERIFIED_STRUCTURAL_IDS_FRESH_NATIVE_REREAD');const b=await collect({...params,acquisition_id:'SECOND'});assert.equal(b.requests,0);assert.equal(b.source_ts,a.source_ts);const bound=bridge.bindGTradeAcquisition(a.acquisition,{contract:'RAY-USDT',run_id:params.run_id,snapshot_id:'SCOPED:RAY',observed_ts:T});assert.equal(bound.status,'USABLE_SCOPED_NATIVE_CONTEXT');const levels=[...bound.above,...bound.below].map(l=>[l.side??l.liquidated_side,l.native_price,l.notional,l.source_ts]).sort(),original=[...proof.scoped_consumer.above,...proof.scoped_consumer.below].map(l=>[l.side??l.liquidated_side,l.native_price,l.notional,l.source_ts]).sort();assert.deepEqual(levels,original);const bundle=canonical.buildRuntimeCanonicalBundle({contract:'RAY-USDT',run_id:params.run_id,snapshot_id:'RETAINED_REFERENCE:RAY',observed_ts:T,discovery_row:{contract:'RAY-USDT',mark_price:2.5191333},publication_shadow:{entry_signal:{state:'REJECTED',direction:'LONG'},scenario_plan:{execution_reference_price:2.5191333}},native_liquidation_acquisition:bridge.createMultiLiquidationAcquisition({contract:'RAY-USDT',run_id:params.run_id,gtrade:a.acquisition}),internal_market_context:{internal_only:true,liquidation_coverage_admission:{contract:'RAY-USDT',eligible:true,source_ids:['GTRADE_NATIVE'],proven_level_source_ids:[],fresh_live_levels_confirmed:false}}});assert.equal(bundle.canonical.state,'REJECTED');assert.equal(bundle.canonical.metadata.validated_signal,false);assert.equal(bundle.canonical.targets?.length??0,0);assert.ok(bundle.manual.text.includes('gTrade'));assert.ok(bundle.manual.text.includes('расч'));retainedProof={scope:'CONTROLLED_THREE_REQUEST_TRANSPORT_REPLAY_OF_RETAINED_ACTUAL_NATIVE_STATE_NOT_FRESH_HTX_MAIN',source_cloud_run:37630677111,original_run_id:raw.run_id,source_gzip_sha256:hash(bytes),source_ts:a.source_ts,source_clock_refreshed:false,original_asof:T,structural_ids:hints,levels,consumer:bound,canonical:bundle.canonical,manual_text:bundle.manual.text,controlled_transport_calls:3,new_sourceHTTP:0,D1:0,MAIN:0,Telegram:0,new_fresh_SENT:false};});
test('closed positions and invalid RPC never reuse the hint as a level; closed selected IDs are removed',async()=>{for(const options of [{closed:true},{error:true},{foreign:true}]){let saved=null;const calls=[],collect=collectors.createGTradeRuntimeCollector({sdk,clock:()=>T,position_routing:hints,crypto_assets:assets,fetch_impl:transport(calls,options),on_position_routing:p=>{saved=routing.buildGTradePositionRouting({previous:hints,...p});}}),a=await collect(params);assert.equal(a.position_source_clock_known??false,false);assert.equal(a.acquisition??null,null);await collect(params);assert.equal(calls.length,3);if(options.closed){assert.ok(saved);assert.equal(routing.selectGTradePositionRouting(saved,{symbol:'RAY',now:T}).length,0);}else assert.equal(saved,null);}});
test('omission from a bounded native returned array is not a closed position and cannot remove its structural hint',async()=>{let saved=null;const calls=[],collect=collectors.createGTradeRuntimeCollector({sdk,clock:()=>T,position_routing:hints,crypto_assets:assets,fetch_impl:transport(calls,{omitted:true}),on_position_routing:p=>{saved=routing.buildGTradePositionRouting({previous:hints,...p});}}),a=await collect(params);assert.equal(a.position_source_clock_known,true);assert.equal(a.acquisition.above.length+a.acquisition.below.length,3);const checked=saved??hints;assert.ok(checked.positions.some(p=>id(p)===id(selected[0].trade)));assert.equal(checked.positions.find(p=>id(p)===id(selected[0].trade)).verified_source_ts,hints.positions.find(p=>id(p)===id(selected[0].trade)).verified_source_ts);assert.equal(calls.length,3);});
test('sparse source-derived selections use bounded exact native getters and retain fee-aware actual source estimates',async()=>{const {routing_fingerprint,...material}=hints;material.positions=material.positions.filter(p=>p.symbol==='RAY').slice(0,2);const subset={...material,routing_fingerprint:(await load('liquidation-extension/core.mjs')).fingerprint(material)},calls=[],collect=collectors.createGTradeRuntimeCollector({sdk,clock:()=>T,position_routing:subset,crypto_assets:assets,fetch_impl:transport(calls)}),a=await collect(params);assert.equal(a.requests,3);assert.equal(a.position_source_clock_known,true);assert.equal(a.acquisition.position_query_basis,'EXACT_SELECTED_NATIVE_GETTERS');assert.equal(a.acquisition.above.length+a.acquisition.below.length,2);const body=pin.buildGTradePinnedRpcBatch({current_block:variables.currentBlock,selected:routing.selectGTradePositionRouting(subset,{symbol:'RAY',now:T}),exact_selected:true});assert.equal(body.length,11);assert.equal(body.some(r=>r.method==='eth_call'&&iface.parseTransaction({data:r.params[0].data}).name.startsWith('getAll')),false);assert.ok(pin.permittedGTradePinnedRpcBatch(body));const keys=new Set(subset.positions.map(id));for(const l of [...a.acquisition.above,...a.acquisition.below])assert.equal(l.native_price,[...proof.scoped_consumer.above,...proof.scoped_consumer.below].find(p=>p.position_key===l.position_key).native_price);assert.throws(()=>pin.buildGTradePinnedRpcBatch({current_block:variables.currentBlock,selected,exact_selected:true}),/EXACT_SELECTED_NATIVE_BOUND/);});
test('an explicit native closed/default tuple removes its exact selected IDs while foreign open IDs fail closed',async()=>{const {routing_fingerprint,...material}=hints;material.positions=material.positions.filter(p=>p.symbol==='RAY').slice(0,2);const subset={...material,routing_fingerprint:(await load('liquidation-extension/core.mjs')).fingerprint(material)};for(const options of [{closed:true},{foreign:true}]){let saved=null;const calls=[],collect=collectors.createGTradeRuntimeCollector({sdk,clock:()=>T,position_routing:subset,crypto_assets:assets,fetch_impl:transport(calls,options),on_position_routing:p=>{saved=routing.buildGTradePositionRouting({previous:subset,...p});}}),a=await collect(params);assert.equal(a.acquisition??null,null);assert.equal(calls.length,3);if(options.closed){assert.ok(saved);assert.equal(saved.positions.length,0);}else assert.equal(saved,null);}});
test('three transport receipts alone cannot convert unpinned or old discovery proof into a fresh reduced route',()=>{const c={symbol:'RAY',run_id:'NO_FAKE_REDUCED_ROUTE',snapshot_id:'S',as_of_ms:T,received_at_ms:T,max_age_ms:300000},rs=[raw.raw[0],raw.raw.find(r=>r.url.endsWith('/charts')),rpc].map(r=>({http_status:200,received_ts:r.received_ts,sha256:r.sha256}));const n=gtrade.normalizeGTrade({variables,trades:decoded.trades,prices,receipts:rs,pinned_positions:decoded.evidence},c,sdk);assert.equal(n.usable_for_context,false);assert.equal(n.status,'GTRADE_RECEIPT_WINDOW_NOT_CLOSED');});
const readOld=f=>JSON.parse(gunzipSync(fs.readFileSync('original-source/'+f))),oldRows=readOld('verified-pinned-trades.json.gz'),oldVars=readOld('rest-1.json.gz').payload,oldPrices=readOld('rest-3.json.gz').payload,oldProof=JSON.parse(fs.readFileSync('original-source/gtrade-pinned-source-proof.json')),OT=1791273618880,oldSelected=['QNT','ZEC'].flatMap(s=>oldRows.filter(r=>Number(r.trade.pairIndex)===gtrade.resolveGTradeCryptoMarket(oldVars,s).pair_index)),tuple=(v,f)=>iface.getFunction(f).outputs[0].components.map(p=>v[p.name]);
const oldResponse=selection=>[{jsonrpc:'2.0',id:1,result:'0xa4b1'},{jsonrpc:'2.0',id:2,result:{number:ethers.utils.hexValue(oldVars.currentBlock),timestamp:ethers.utils.hexValue(oldProof.source_clock.block_source_ts/1000),hash:oldProof.source_clock.block_hash}},...fn.map((f,i)=>({jsonrpc:'2.0',id:i+3,result:iface.encodeFunctionResult(f,[oldSelected.map(r=>tuple(r[i===0?'trade':i===1?'tradeInfo':'liquidationParams'],f))])})),{jsonrpc:'2.0',id:6,result:iface.encodeFunctionResult('getTradeFeesDataArray',[selection.map(r=>tuple(r.tradeFeesData,'getTradeFeesDataArray'))])},...selection.map((r,i)=>({jsonrpc:'2.0',id:i+7,result:iface.encodeFunctionResult('getBorrowingInitialAccFees',[tuple(r.initialAccFees,'getBorrowingInitialAccFees')])}))];
const oldBody=pin.buildGTradePinnedRpcBatch({current_block:oldVars.currentBlock,selected:oldSelected}),oldDecoded=pin.decodeGTradePinnedRpcSnapshot({body:oldBody,response:oldResponse(oldSelected),selected:oldSelected,current_block:oldVars.currentBlock,pair_index:gtrade.resolveGTradeCryptoMarket(oldVars,'QNT').pair_index,receipt:{http_status:200,received_ts:OT,sha256:hash(JSON.stringify(oldResponse(oldSelected)))},as_of_ms:OT}),oldRouting=routing.buildGTradePositionRouting({observation:oldDecoded.routing_observation,variables:oldVars,crypto_assets:assets,now:OT}),address='0x'+'1'.repeat(40),state={time:OT,marginSummary:{accountValue:'10',totalNtlPos:'20',totalMarginUsed:'5'},assetPositions:['QNT','ZEC'].map(coin=>({position:{coin,szi:'10',entryPx:'1',positionValue:'10',liquidationPx:'.7',marginUsed:'2.5',unrealizedPnl:'0',leverage:{type:'cross',value:2}}}))},nativeRouting=wallet.buildNativeWalletRouting({accounts:[{address,state,http_receipt:{http_status:200,received_ts:OT,sha256:'a'.repeat(64)}}],run_id:'CONTROLLED_HL_HINT',now:OT});
function makeCombined(denial=null){const calls=[],service=combined.createCombinedLiquidationService({mode:'SHADOW_ONLY',clock:()=>OT,candidate_slots:2,max_http_per_run:5,gtrade_position_routing:oldRouting,gtrade_crypto_assets:assets,native_wallet_routing:nativeRouting,sdk_loader:()=>({version:'1.8.10',sdk}),provider_admit:async r=>r.requests.GTRADE&&denial?denial:{allowed:true,new_reservation:true},fetch_impl:async(url,init={})=>{calls.push(String(url));let p;if(String(url).endsWith('/trading-variables'))p=oldVars;else if(String(url).endsWith('/charts'))p=oldPrices;else if(String(url).endsWith('/open-trades'))throw Error('NO_OLD_DISCOVERY');else if(String(url).includes('hyperliquid'))p=JSON.parse(init.body).type==='metaAndAssetCtxs'?[{universe:[{name:'QNT'},{name:'ZEC'}]},[{markPx:'1'},{markPx:'1'}]]:state;else{const body=JSON.parse(init.body),a=iface.decodeFunctionData('getTradeFeesDataArray',body.find(r=>r.id===6).params[0].data),selection=a[0].map((user,i)=>oldSelected.find(r=>id(r.trade)===user.toLowerCase()+':'+a[1][i].toString()));p=oldResponse(selection);}return new Response(JSON.stringify(p));}});return{service,calls};}
const combinedParams=contract=>({contract,native_symbol:contract.replace(/-USDT$/,''),run_id:'CONTROLLED_SHARED_HINT_PAIR',deep_started_ts:OT,max_http_for_candidate:5,allowed_source_ids:['HYPERLIQUID_NATIVE','GTRADE_NATIVE'],position_batch_contracts:['QNT-USDT','ZEC-USDT']});
test('two native HL reads plus three retained gTrade reads fit global5 and both selected assets retain calculated levels',async()=>{const f=makeCombined(),a=await f.service.collect(combinedParams('QNT-USDT')),b=await f.service.collect(combinedParams('ZEC-USDT'));assert.ok(a.hyperliquid);assert.ok(a.gtrade);assert.ok(b.gtrade);console.log('DIAG_SHARED_PAIR',JSON.stringify({calls:f.calls,summary:f.service.summary()}));assert.equal(f.calls.length,5);assert.equal(f.calls.filter(u=>u.includes('hyperliquid')).length,2);assert.equal(f.calls.filter(u=>!u.includes('hyperliquid')).length,3);assert.equal(f.service.summary().shared_budget.reserved_http,5);for(const [r,contract]of [[a,'QNT-USDT'],[b,'ZEC-USDT']])assert.equal(bridge.bindGTradeAcquisition(r.gtrade,{contract,run_id:'CONTROLLED_SHARED_HINT_PAIR',snapshot_id:contract,observed_ts:OT}).status,'USABLE_SCOPED_NATIVE_CONTEXT');assert.deepEqual(f.service.summary().routed.filter(r=>r.lane==='GTRADE_NATIVE').map(r=>r.source_outcome.attempted_http_count),[3,0]);});
test('explicit smaller candidate envelope and malformed second asset batch cannot borrow global budget',async()=>{for(const p of [{max_http_for_candidate:3},{position_batch_contracts:['QNT-USDT','QNT-USDT']},{position_batch_contracts:['QNT-USDT','UNKNOWN-USDT']}]){const f=makeCombined(),a=await f.service.collect({...combinedParams('QNT-USDT'),...p});assert.ok(a);console.log('DIAG_SMALL_PAIR',JSON.stringify({params:p,calls:f.calls,summary:f.service.summary()}));assert.equal(a.gtrade??null,null);assert.ok(f.calls.length<=3);assert.equal(f.calls.some(u=>u.endsWith('/charts')),false);}});
test('unknown gTrade admission ACK is charged without retries or artificial levels',async()=>{const f=makeCombined({allowed:false,new_reservation:false,reason:'ACK_UNKNOWN'}),a=await f.service.collect(combinedParams('QNT-USDT'));assert.ok(a);console.log('DIAG_UNKNOWN_ACK',JSON.stringify({calls:f.calls,summary:f.service.summary()}));assert.equal(a.gtrade??null,null);assert.equal(f.calls.length,2);assert.equal(f.service.summary().shared_budget.reserved_http,3);});
test('an unsupported first candidate cannot make the following one-request hinted snapshot reuse a spent catalog reservation',async()=>{const calls=[],ids=new Set(),admissions=[],service=combined.createCombinedLiquidationService({mode:'SHADOW_ONLY',clock:()=>T,candidate_slots:2,max_http_per_run:5,gtrade_position_routing:hints,gtrade_crypto_assets:assets,sdk_loader:()=>({version:'1.8.10',sdk}),provider_admit:async r=>{admissions.push(r.reservation_id);if(ids.has(r.reservation_id))return{allowed:true,new_reservation:false};ids.add(r.reservation_id);return{allowed:true,new_reservation:true};},fetch_impl:transport(calls)}),p={run_id:'UNSUPPORTED_THEN_HINTED_RAY',deep_started_ts:T,max_http_for_candidate:5,allowed_source_ids:['GTRADE_NATIVE']};assert.equal(await service.collect({...p,contract:'龙虾-USDT',native_symbol:'龙虾'}),null);const a=await service.collect({...p,contract:'RAY-USDT',native_symbol:'RAY',position_batch_contracts:['RAY-USDT']});assert.ok(a.gtrade);assert.equal(calls.length,3);assert.equal(service.summary().shared_budget.reserved_http,3);assert.equal(new Set(admissions).size,3);assert.ok(admissions.some(id=>id.includes('GTRADE_CATALOG:')));assert.ok(admissions.some(id=>id.includes('GTRADE_SNAPSHOT:')));});

test('all selected IDs missing from a bounded sample remain unknown through the combined lane and do not delete original hints',async()=>{
 let saved=null;const calls=[],service=combined.createCombinedLiquidationService({mode:'SHADOW_ONLY',clock:()=>T,candidate_slots:2,max_http_per_run:5,gtrade_position_routing:hints,gtrade_crypto_assets:assets,on_gtrade_position_routing:p=>{saved=routing.buildGTradePositionRouting({previous:hints,...p});},sdk_loader:()=>({version:'1.8.10',sdk}),provider_admit:async()=>({allowed:true,new_reservation:true}),fetch_impl:transport(calls,{allOmitted:true})});
 const p={contract:'RAY-USDT',native_symbol:'RAY',run_id:'BOUNDED_ALL_OMITTED',deep_started_ts:T,max_http_for_candidate:5,allowed_source_ids:['GTRADE_NATIVE'],position_batch_contracts:['RAY-USDT']};
 assert.equal(await service.collect(p),null);const r=service.summary().routed.find(r=>r.lane==='GTRADE_NATIVE');
 assert.equal(r.position_proof.status,'GTRADE_PINNED_SELECTED_POSITION_STATE_UNKNOWN');assert.equal(r.position_proof.diagnostic.excluded_reason_counts.SELECTED_ID_NOT_RETURNED_BY_BOUNDED_NATIVE_SAMPLE,4);assert.equal(r.position_proof.diagnostic.verified_open_positions,0);assert.equal(r.usable,false);assert.equal(calls.length,3);
 const next=saved??hints;for(const row of hints.positions.filter(p=>p.symbol==='RAY')){const current=next.positions.find(p=>id(p)===id(row));assert.ok(current);assert.equal(current.verified_source_ts,row.verified_source_ts);}
 await service.collect(p);assert.equal(calls.length,3);
});
test('a native RPC error retains its bounded code and method in combined diagnostics without retry, levels or clock promotion',async()=>{
 const calls=[],service=combined.createCombinedLiquidationService({mode:'SHADOW_ONLY',clock:()=>T,candidate_slots:2,max_http_per_run:5,gtrade_position_routing:hints,gtrade_crypto_assets:assets,sdk_loader:()=>({version:'1.8.10',sdk}),provider_admit:async()=>({allowed:true,new_reservation:true}),fetch_impl:transport(calls,{error:true})});
 const p={contract:'RAY-USDT',native_symbol:'RAY',run_id:'RPC_REASON_RETAINED',deep_started_ts:T,max_http_for_candidate:5,allowed_source_ids:['GTRADE_NATIVE'],position_batch_contracts:['RAY-USDT']};
 assert.equal(await service.collect(p),null);const r=service.summary().routed.find(r=>r.lane==='GTRADE_NATIVE');assert.equal(r.position_proof.reason,'GTRADE_PINNED_RPC_RESPONSE_INVALID');assert.equal(r.position_proof.source_clock_closed,false);assert.equal(r.position_proof.diagnostic.rpc_errors.length,1);const e=r.position_proof.diagnostic.rpc_errors[0];assert.equal(e.code,-32000);assert.equal(e.message,'CONTROLLED_RPC_FAILURE');assert.equal(e.method,'eth_call');assert.match(e.selector,/^0x[0-9a-f]{8}$/);assert.ok(Buffer.byteLength(JSON.stringify(r.position_proof.diagnostic))<2048);await service.collect(p);assert.equal(calls.length,3);
});

function mixedSelectedFixture({protect=false,denyPin=false}={}){
 const calls=[],grants=[],run='CONTROLLED_RETAINED_MIXED_SELECTED_PAIR',pair=['QNT-USDT','BR-USDT'],plan={schema:'SELECTED_NATIVE_SOURCE_PLAN_V1',run_id:run,entries:pair.map(contract=>({contract,eligible:true,source_ids:contract==='BR-USDT'&&protect?['GTRADE_NATIVE','DYDX_PINNED_NATIVE','HYPERLIQUID_NATIVE']:['GTRADE_NATIVE','DYDX_PINNED_NATIVE']}))};
 const service=combined.createCombinedLiquidationService({mode:'SHADOW_ONLY',clock:()=>OT,candidate_slots:2,max_http_per_run:5,gtrade_crypto_assets:assets,sdk_loader:()=>({version:'1.8.10',sdk}),provider_admit:async r=>{grants.push(r);return denyPin&&r.reservation_id.includes('GTRADE_PINNED_POSITION')?{allowed:false,new_reservation:false,reason:'ACK_UNKNOWN'}:{allowed:true,new_reservation:true};},fetch_impl:async(url,init={})=>{
  calls.push(String(url));let payload;
  if(String(url).endsWith('/trading-variables'))payload=oldVars;
  else if(String(url).endsWith('/charts'))payload=oldPrices;
  else if(String(url).endsWith('/open-trades'))payload=oldSelected;
  else{const body=JSON.parse(init.body),args=iface.decodeFunctionData('getTradeFeesDataArray',body.find(r=>r.id===6).params[0].data),selected=args[0].map((user,i)=>oldSelected.find(r=>id(r.trade)===user.toLowerCase()+':'+args[1][i].toString()));assert.ok(selected.every(Boolean));payload=oldResponse(selected);}
  return new Response(JSON.stringify(payload));
 }});
 const params={contract:pair[0],native_symbol:'QNT',run_id:run,deep_started_ts:OT,max_http_for_candidate:5,allowed_source_ids:plan.entries[0].source_ids,position_batch_contracts:pair,selected_native_source_plan:plan};
 return{service,calls,grants,params,plan,pair};
}
test('one otherwise unusable following reserve request completes retained QNT position time with four HTTP and keeps BR unsupported at zero HTTP',async()=>{
 const f=mixedSelectedFixture(),a=await f.service.collect(f.params);assert.ok(a.gtrade);console.log('DIAG_MIXED_PAIR',JSON.stringify({calls:f.calls,summary:f.service.summary(),acquisition:a.gtrade}));assert.equal(a.gtrade.source_clock_closed,true);assert.equal(f.calls.length,4);assert.equal(f.calls.filter(u=>u.endsWith('/open-trades')).length,1);assert.equal(f.service.summary().shared_budget.reserved_http,4);
 const route=f.service.summary().routed.find(r=>r.lane==='GTRADE_NATIVE');assert.equal(route.position_proof.status,'GTRADE_PINNED_OPEN_POSITIONS_CLOSED');assert.equal(route.source_outcome.role_usable,true);assert.equal(route.pair_reserve_finish.borrowed_http,1);
 const bound=bridge.bindGTradeAcquisition(a.gtrade,{contract:'QNT-USDT',run_id:f.params.run_id,snapshot_id:'CONTROLLED_MIXED_QNT',observed_ts:OT});assert.equal(bound.status,'USABLE_SCOPED_NATIVE_CONTEXT');assert.equal(bound.source_clock_closed,true);assert.equal(bound.entry_eligible,false);assert.equal(bound.prices_converted_to_htx,false);assert.equal(bound.positions_source_ts,oldProof.source_clock.block_source_ts);
 const count=f.calls.length;assert.equal(await f.service.collect({...f.params,contract:'BR-USDT',native_symbol:'BR',allowed_source_ids:f.plan.entries[1].source_ids,max_http_for_candidate:2}),null);assert.equal(f.calls.length,count);assert.equal(f.service.summary().shared_budget.reserved_http,4);assert.equal(f.service.summary().routed.at(-1).source_outcome.coverage_status,'UNSUPPORTED');
 fs.mkdirSync('audit-output',{recursive:true});fs.writeFileSync('audit-output/unused-native-pair-reserve-proof.json',JSON.stringify({schema:'UNUSED_NATIVE_PAIR_RESERVE_RETAINED_CONTROL_V1',scope:'CONTROLLED_MIXED_SELECTED_PAIR_FROM_ORIGINAL_PINNED_QNT_INPUTS_NOT_CURRENT_HTX_MAIN',original_asof:OT,original_pinned_head:oldProof.head,original_source_ts:bound.positions_source_ts,source_clock_refreshed:false,controlled_transport_calls:4,summary:f.service.summary(),context:bound,sourceHTTP:0,D1:0,MAIN:0,Telegram:0,actual_ENTRY:false,new_fresh_SENT:false},null,2)+'\n');
});
test('viable following routes, missing or foreign plan, and the explicit smaller caller envelope retain the original first-candidate cap',async()=>{
 for(const change of ['PROTECT','NO_PLAN','FOREIGN_PLAN','SMALL_CALLER']){const f=mixedSelectedFixture({protect:change==='PROTECT'});if(change==='NO_PLAN')delete f.params.selected_native_source_plan;if(change==='FOREIGN_PLAN')f.plan.run_id='FOREIGN';if(change==='SMALL_CALLER')f.params.max_http_for_candidate=3;const a=await f.service.collect(f.params);assert.ok(a.gtrade);assert.equal(a.gtrade.source_clock_closed,false);assert.equal(f.calls.length,3);assert.ok(f.calls.every(u=>u.includes('gains.trade')));assert.equal(f.service.summary().shared_budget.reserved_http,3);}
});
test('unknown pinned admission is charged once and never retries or promotes the backend receipt clock',async()=>{
 const f=mixedSelectedFixture({denyPin:true}),a=await f.service.collect(f.params);assert.ok(a.gtrade);assert.equal(a.gtrade.source_clock_closed,false);assert.equal(f.calls.length,3);assert.equal(f.service.summary().shared_budget.reserved_http,4);assert.equal(f.grants.filter(g=>g.reservation_id.includes('GTRADE_PINNED_POSITION')).length,1);await f.service.collect(f.params);assert.equal(f.calls.length,3);assert.equal(f.grants.filter(g=>g.reservation_id.includes('GTRADE_PINNED_POSITION')).length,1);
});
test('retained source proof is written only after producer and canonical verification',()=>{assert.ok(retainedProof);fs.mkdirSync('audit-output',{recursive:true});fs.writeFileSync('audit-output/gtrade-three-read-retained-proof.json',JSON.stringify(retainedProof,null,2)+'\n');});

