import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
const root=process.env.REPORT2_NATIVE_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_NATIVE_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url),load=n=>import(new URL(n,root));
const [{normalizeHederaPublishedSupply:normalize,hederaConsensusMilliseconds:milliseconds,HEDERA_SUPPLY_TTL:TTL,HEDERA_SUPPLY_URL:SUPPLY_URL},{normalizeHtxAssetReferences},{parseSupplementalIdentityRegistry},{collectChainSupplyEvidence},{consumeBlockResultContext},{consumeEvidenceV2},{SOURCE_POLICIES},{installEvidenceSourceStore}]=await Promise.all(['hedera-primary-supply.mjs','htx-asset-identity.mjs','supplemental-candidate-context.mjs','chain-supply-evidence.mjs','block-result-context.mjs','evidence-v2.mjs','evidence-source-adapters.mjs','evidence-source-store.mjs'].map(load));
const T=1791490000000,identity={chain:'hedera',asset_kind:'NATIVE',native_asset_id:'hedera:mainnet',contract_or_mint:null},payload={timestamp:'1791489999.999999999',released_supply:'3999999999999999949',total_supply:'5000000000000000000'},params={contract:'HBAR-USDT',identity,payload,observed_ts:T};
function memoryDB(){const s=new DatabaseSync(':memory:');return{sqlite:s,prepare(sql){return{args:[],bind(...args){this.args=args;return this;},async run(){return s.prepare(sql).run(...this.args);},async first(){return s.prepare(sql).get(...this.args)||null;}};},async batch(rows){return Promise.all(rows.map(r=>r.run()));}};}
test('HTX native chain identity survives supplemental parsing while an issued or wrapped Hedera asset does not become native',()=>{
 const reference=normalizeHtxAssetReferences({code:200,data:[{currency:'hbar',chains:[{chain:'hbar',chainType:0,baseChain:'HBAR',contractAddress:''}]}]});assert.equal(reference.entries.HBAR.status,'CLOSED');assert.deepEqual(reference.entries.HBAR.identities[0],identity);assert.deepEqual(parseSupplementalIdentityRegistry({HBAR:identity}).entries.HBAR.identity,identity);
 for(const patch of [{chainType:1,baseChain:''},{contractAddress:'0x'+'1'.repeat(40),baseChain:'ETH'}]){const x=normalizeHtxAssetReferences({code:200,data:[{currency:'hbar',chains:[{chain:'hbar',chainType:0,baseChain:'',contractAddress:'',...patch}]}]});assert.notDeepEqual(x.entries.HBAR.identities[0],identity);}
 assert.equal(normalize({...params,identity:{...identity,contract_or_mint:'0.0.123'}}).evidence.length,0);assert.equal(normalize({...params,contract:'OTHER-USDT'}).evidence.length,0);
});
test('primary tinybar strings retain integer precision, eight decimals and the original consensus nanosecond timestamp',()=>{
 assert.equal(milliseconds(payload.timestamp),T-1);assert.equal(milliseconds('1791489999'),T-1000);for(const x of [null,1791489999,'1e9','1791489999.1234567890','1791489999.-1'])assert.equal(milliseconds(x),null);
 const r=normalize(params),e=r.evidence[0];assert.equal(r.status,'CLOSED');assert.equal(e.decimals,8);assert.equal(e.source_ts,T-1);assert.equal(e.expires_at,T-1+TTL);assert.equal(e.supply_values_base_units.unreleased_supply,'1000000000000000051');assert.equal(e.chain_finalized_block_verified,false);assert.equal(e.circulating_supply_verified,false);assert.equal(e.future_unlocks_checked,false);assert.equal(r.summary.finalized,false);
});
test('unknown, future and expired clocks, wrong total or released units and numeric approximation fail closed',()=>{
 for(const patch of [{timestamp:'1791490000.001'},{timestamp:String((T-TTL-1)/1000)},{timestamp:null},{total_supply:'5000000000000000001'},{released_supply:'5000000000000000001'},{released_supply:3999999999999999949},{released_supply:'-1'},{released_supply:'4e18'}])assert.equal(normalize({...params,payload:{...payload,...patch}}).evidence.length,0);
});
test('the report recomputes the primary metric and renders neutral N02 without a supply-change, unlock, circulating or directional claim',()=>{
 const r=normalize({...params,payload:{...payload,released_supply:'4000000000000000000'}}),facts=consumeBlockResultContext({evidence:r.evidence,contract:params.contract,now:T}).facts;assert.equal(facts.length,1);assert.equal(facts[0].block_id,'N02');assert.match(facts[0].value,/40[\s\u00a0]000[\s\u00a0]000[\s\u00a0]000/);assert.equal(facts[0].directional_vote,false);assert.equal(facts[0].score_contribution,0);assert.equal(consumeEvidenceV2(r.evidence,{decision_ts:T,base_interest:70}).adjustment,0);
 for(const patch of [{provider_id:'OTHER'},{unit:'HBAR'},{decimals:5},{source_ts:T},{consensus_timestamp:'FORGED'},{circulating_supply_verified:true},{supply_values_base_units:{...r.evidence[0].supply_values_base_units,released_supply:'1'}},{primary_payload:{...payload,released_supply:'1'}}])assert.equal(consumeBlockResultContext({evidence:[{...r.evidence[0],...patch}],contract:params.contract,now:T}).facts.length,0);
 assert.equal(consumeBlockResultContext({evidence:r.evidence,contract:params.contract,now:T+TTL}).facts.length,0);
});
test('an already persisted Stellar cache overhang cannot keep an expired primary fact until the later receipt-based cache deadline',async()=>{
 const db=memoryDB(),times={now:T},calls=[],stellar={chain:'stellar',asset_kind:'NATIVE',native_asset_id:'stellar:mainnet',contract_or_mint:null},base={originalSupply:'100000000000',inflationLumens:'0.0000000',burnedLumens:'50000000000',totalSupply:'50000000000',upgradeReserve:'0',feePool:'0',sdfMandate:'10000000000',circulatingSupply:'40000000000'},p={db,fetch_impl:async()=>{calls.push(times.now);return new Response(JSON.stringify({...base,updatedAt:new Date(times.now===T?T-TTL+1000:T).toISOString()}));},request_admit:()=>({allowed:true}),contract:'XLM-USDT',run_id:'CONTROLLED_STELLAR_ORIGINAL1',asset_identity:stellar,now:T,clock:()=>times.now};
 const first=await collectChainSupplyEvidence(p);assert.equal(first.status,'CLOSED');assert.equal(first.evidence[0].expires_at,T+1000);db.sqlite.prepare('UPDATE report2_evidence_source_cache SET expires_ts=? WHERE source=?').run(T+TTL,'STELLAR_NATIVE_SUPPLY');
 times.now=T+1001;const next=await collectChainSupplyEvidence({...p,now:times.now,run_id:'CONTROLLED_STELLAR_ORIGINAL2'});assert.equal(next.status,'CLOSED');assert.equal(calls.length,2);assert.equal(next.evidence[0].source_ts,T);assert.notEqual(first.evidence[0].source_ts,next.evidence[0].source_ts);assert.equal(next.summary.finalized,false);assert.equal(next.evidence[0].chain_finalized_block_verified,false);
});
test('one current native source request also reserves the existing parent budget, and cached evidence has zero new HTTP with unchanged original clocks',async()=>{
 const db=memoryDB(),grants=[],calls=[],request_admit=x=>{grants.push(x);return{allowed:true};},fetch_impl=async(url,init)=>{calls.push({url,init});assert.equal(url,SUPPLY_URL);assert.equal(init.redirect,'error');return new Response(JSON.stringify(payload));},p={db,fetch_impl,request_admit,contract:'HBAR-USDT',run_id:'CONTROLLED_PRIMARY_HEDERA',asset_identity:identity,now:T,clock:()=>T};
 const r=await collectChainSupplyEvidence(p),cached=await collectChainSupplyEvidence({...p,run_id:'CONTROLLED_CACHED_HEDERA'});assert.equal(r.status,'CLOSED');assert.equal(r.network_calls,1);assert.equal(cached.network_calls,0);assert.equal(cached.cache_status,'HIT');assert.deepEqual(cached.evidence,r.evidence);assert.equal(calls.length,1);assert.equal(grants.length,1);assert.equal(grants[0].attempts,1);
 const counts=db.sqlite.prepare('SELECT source,COUNT(*) AS n FROM report2_evidence_source_reservation GROUP BY source').all();assert.ok(counts.some(x=>x.source==='HEDERA_NATIVE_SUPPLY'));assert.ok(counts.some(x=>x.source==='CHAIN_RPC'));assert.equal(SOURCE_POLICIES.HEDERA_NATIVE_SUPPLY.daily_cap,4);assert.equal(SOURCE_POLICIES.CHAIN_RPC.daily_cap,720);
 const expiry=db.sqlite.prepare('SELECT expires_ts FROM report2_evidence_source_cache WHERE source=?').get('HEDERA_NATIVE_SUPPLY').expires_ts;assert.equal(expiry,r.evidence[0].expires_at);
});
test('published data expiring before its query receipt refreshes after the original expiry, while provider failure and parent denial never create evidence',async()=>{
 const db=memoryDB(),old={...payload,timestamp:String((T-TTL+1000)/1000)},times={now:T},calls=[],p={db,fetch_impl:async()=>{calls.push(times.now);return new Response(JSON.stringify(times.now===T?old:payload));},request_admit:()=>({allowed:true}),contract:'HBAR-USDT',run_id:'CONTROLLED_ORIGINAL_EXPIRY1',asset_identity:identity,now:T,clock:()=>times.now};
 const first=await collectChainSupplyEvidence(p);assert.equal(first.status,'CLOSED');times.now=T+1001;const next=await collectChainSupplyEvidence({...p,now:times.now,run_id:'CONTROLLED_ORIGINAL_EXPIRY2'});assert.equal(next.status,'CLOSED');assert.equal(calls.length,2);assert.notEqual(first.evidence[0].source_ts,next.evidence[0].source_ts);
 const deniedDB=memoryDB();await installEvidenceSourceStore(deniedDB);deniedDB.sqlite.prepare('INSERT INTO report2_evidence_source_daily VALUES (?,?,?,?,?)').run('CHAIN_RPC',new Date(T).toISOString().slice(0,10),720,'PARENT_FULL',T);let deniedCalls=0;const denied=await collectChainSupplyEvidence({...p,db:deniedDB,run_id:'CONTROLLED_PARENT_DENIED',fetch_impl:async()=>{deniedCalls++;throw Error('FORBIDDEN');}});assert.equal(denied.evidence.length,0);assert.equal(deniedCalls,0);
 const failed=await collectChainSupplyEvidence({...p,db:memoryDB(),run_id:'CONTROLLED_TRANSPORT_ERROR',fetch_impl:async()=>new Response('unavailable',{status:503})});assert.equal(failed.evidence.length,0);
});

