import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(process.argv[2]||'runtime'),workerPath=path.join(runtime,'src/worker.js');
const source=fs.readFileSync(workerPath,'utf8').replace(/from (['"])\.\/([^'"\n]+)\1/g,(_,quote,name)=>`from ${JSON.stringify(pathToFileURL(path.join(runtime,'src',name)).href)}`);
const expose='fetchJson,rawTradeRecordIntegrity,cvdDeltaQuality,factualMinuteTradeCount';
const api=await import('data:text/javascript;base64,'+Buffer.from(source+`\nexport {${expose}};\n`).toString('base64'));
const NOW=1790761200000,raw=`{"status":"ok","ch":"market.SOL-USDT.trade.detail","ts":${NOW},"data":[{"data":[{"id":123456789012345678901,"price":100,"amount":1,"quantity":1,"ts":${NOW-60000},"direction":"buy"},{"id":123456789012345678902,"price":100,"amount":1,"quantity":1,"ts":${NOW-59000},"direction":"sell"}]}]}`;
let calls=0;globalThis.fetch=async()=>{calls++;return new Response(raw,{status:200});};
const result=await api.fetchJson('https://api.hbdm.com/linear-swap-ex/market/history/trade?contract_code=SOL-USDT&size=2000');
assert.equal(result.ok,true);assert.equal(calls,1);
const rows=result.data.data[0].data,integrity=api.rawTradeRecordIntegrity(rows,{market:'futures',contract_size:1});
assert.equal(integrity.complete,true);assert.equal(integrity.unique_trade_ids,2);
assert.equal(api.rawTradeRecordIntegrity(JSON.parse(raw).data[0].data,{market:'futures',contract_size:1}).complete,false);
const factual=api.factualMinuteTradeCount([{ts:NOW-60000,trade_count:2}],NOW-60000,NOW);
assert.equal(api.cvdDeltaQuality(2,factual,integrity).reliable,true);
assert.equal(api.cvdDeltaQuality(1,factual,integrity).reliable,false);
assert.equal(api.cvdDeltaQuality(2,{...factual,status:'INCOMPLETE'},integrity).reliable,false);
assert.equal(api.rawTradeRecordIntegrity([rows[0],rows[0]],{market:'futures',contract_size:1}).complete,false);
const wrong=await api.fetchJson('https://api.hbdm.com/linear-swap-ex/market/history/trade?contract_code=LINK-USDT');
assert.equal(wrong.ok,false);assert.equal(wrong.error,'HTX_TRADE_CHANNEL_MISMATCH');
console.log(JSON.stringify({status:'EXACT_ASSEMBLED_HTX_TRADE_IDS_PASS',before_unique_ids:1,after_unique_ids:2,complete_window_rule_unchanged:true,unknown_coverage_still_rejected:true,network_calls:0,telegram_calls:0,trades:0}));
