import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_SIGNED_TAPE_MODULE_ROOT;
const load=rel=>import(root?pathToFileURL(root+'/'+rel):new URL('../files/src/'+rel,import.meta.url));
const {HTX_SIGNED_TAPE_VERSION,verifiedSignedMinutes,mergeSignedTape,signedTape24hEvidence,observeHtxSignedTape,clearHtxSignedTapeSnapshots,persistCapturedHtxSignedTape,mergeHtxSignedHistoryTrades,capturedSignedTapeFourHourFlow}=await load('htx-signed-tape.mjs');
const {consumeBlockResultContext}=await load('block-result-context.mjs');
const {consumeEvidenceV2}=await load('evidence-v2.mjs');
const MIN=60000,now=1791141000000,contract='测试1000-USDT',size=1,hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const snapshot=()=>({metadata:{observed_ts:now,payload:{status:'ok',ts:now,data:[{contract_code:contract,contract_status:1,business_type:'swap',trade_partition:'USDT',contract_size:size}]}},trades:{observed_ts:now,payload:{status:'ok',ts:now,ch:`market.${contract}.trade.detail`,data:[{data:[{id:'123456789012345678901',ts:now-3*MIN+1000,direction:'buy',price:2,amount:3,trade_turnover:6}]}]}},minutes:{observed_ts:now,payload:{status:'ok',ts:now,ch:`market.${contract}.kline.1min`,data:Array.from({length:45},(_,i)=>({id:(now-46*MIN+i*MIN)/1000,count:i===43?1:0}))}}});
class Statement{constructor(db,sql,args=[]){Object.assign(this,{db,sql,args});}bind(...args){return new Statement(this.db,this.sql,args);}async run(){return this.db.sqlite.prepare(this.sql).run(...this.args);}async first(){return this.db.sqlite.prepare(this.sql).get(...this.args)||null;}}
class DB{constructor(){this.sqlite=new DatabaseSync(':memory:');}prepare(sql){return new Statement(this,sql);}async batch(rows){return Promise.all(rows.map(s=>s.run()));}}
test('only individual raw minute/count matches persist; a bounded recent sample never proves 24 hours',()=>{const a=verifiedSignedMinutes({snapshot:snapshot(),contract,now});assert.equal(a.minutes.length,45);assert.equal(a.minutes.find(m=>m.factual_count===1).fills[0].id,'123456789012345678901');const m=mergeSignedTape({acquisition:a,now});assert.equal(m.status,'DURABLE_RAW_TAPE_WARMING');assert.equal(signedTape24hEvidence({ring:m.ring,now}).status,'WARMING_OR_GAPPED_RAW_24H');assert.equal(signedTape24hEvidence({ring:m.ring,now}).evidence.length,0);});
test('compensating minute count errors, unsafe IDs, stale and foreign metadata never green the tape',()=>{
 const moved=snapshot();moved.minutes.payload.data[43].count=0;moved.minutes.payload.data[42].count=1;const a=verifiedSignedMinutes({snapshot:moved,contract,now});assert.equal(a.minutes.length,43);assert.equal(a.gaps.length,2);
 for(const alter of [s=>s.trades.payload.data[0].data[0].id=Number.MAX_SAFE_INTEGER+5,s=>s.metadata.payload.data[0].contract_code='BTC-USDT',s=>s.trades.payload.ts=now-120001,s=>s.metadata.payload.data[0].contract_size=100]){const s=snapshot();alter(s);const out=verifiedSignedMinutes({snapshot:s,contract,now});assert.ok(!out.minutes.length||!out.minutes.some(m=>m.factual_count===1));}
 const dup=snapshot();dup.trades.payload.data[0].data.push({...dup.trades.payload.data[0].data[0],price:4});assert.equal(verifiedSignedMinutes({snapshot:dup,contract,now}).status,'RAW_FILL_ID_INTEGRITY_NOT_CLOSED');
});
test('changed complete minute and corrupt saved source bytes do not replace a verified ring',()=>{const a=verifiedSignedMinutes({snapshot:snapshot(),contract,now}),m=mergeSignedTape({acquisition:a,now});const changed=structuredClone(a);let minute=changed.minutes.find(m=>m.factual_count);minute.fills[0].contracts=4;minute.fills[0].quote_usdt=8;minute.raw_sha256=hash(minute.fills);assert.equal(mergeSignedTape({previous:m.ring,acquisition:changed,now}).status,'CONFLICTING_COMPLETE_RAW_MINUTE');const corrupt=structuredClone(m.ring);corrupt.minutes.find(m=>m.factual_count).fills[0].contracts=4;assert.equal(mergeSignedTape({previous:corrupt,acquisition:a,now}).status,'SAVED_RAW_TAPE_INTEGRITY_NOT_CLOSED');});
// A clearly controlled 24h fixture tests admission; it is never a live acceptance.
function controlledRing(){const end=now-MIN;return{version:HTX_SIGNED_TAPE_VERSION,contract,contract_size:1,observed_ts:now,minutes:Array.from({length:1440},(_,i)=>{const start_ts=end-1440*MIN+i*MIN,fills=[{id:String(100000+i),ts:start_ts+1000,side:i%2?'buy':'sell',price:2,contracts:3,quote_usdt:6}];return{contract,contract_size:1,start_ts,factual_count:1,fills,raw_sha256:hash(fills),source_ts:now,observed_ts:now};})};}
test('only a complete 1440-minute ring with exact unique fills supplies a neutral signed fact to the report',()=>{const out=signedTape24hEvidence({ring:controlledRing(),now});assert.equal(out.status,'CLOSED_EXACT_SIGNED_RAW_24H');assert.equal(out.evidence[0].raw_trade_count,1440);assert.equal(out.evidence[0].value,0);const context=consumeBlockResultContext({evidence:out.evidence,contract,now});assert.equal(context.facts.length,1);assert.equal(context.facts[0].score_contribution,0);assert.match(context.facts[0].value,/1440 минут/u);assert.equal(consumeEvidenceV2(out.evidence,{base_interest:70,decision_ts:now}).adjustment,0);
 for(const alter of [r=>r.minutes.splice(12,1),r=>{r.minutes[12].fills[0].id=r.minutes[11].fills[0].id;r.minutes[12].raw_sha256=hash(r.minutes[12].fills);},r=>r.minutes[12].observed_ts=now+1,r=>r.minutes[12].fills[0].quote_usdt=999]){const r=controlledRing();alter(r);assert.equal(signedTape24hEvidence({ring:r,now}).evidence.length,0);}
});
test('durable raw ring respects DB admission and readback without network requests or new tables',async()=>{clearHtxSignedTapeSnapshots();const s=snapshot();for(const [k,url] of [['metadata','/linear-swap-api/v1/swap_contract_info'],['trades','/linear-swap-ex/market/history/trade'],['minutes','/linear-swap-ex/market/history/kline']])observeHtxSignedTape(s[k].payload,'https://api.hbdm.com'+url+'?contract_code='+encodeURIComponent(contract)+'&period=1min',now);const db=new DB();assert.equal((await persistCapturedHtxSignedTape({db,contract,now,db_admit:()=>({allowed:false,status:'NO_HEADROOM'})})).status,'NO_HEADROOM');let grants=0;const out=await persistCapturedHtxSignedTape({db,contract,now,db_admit:e=>{grants++;assert.equal(e.rows_written,4);return{allowed:true};}});assert.equal(grants,1);assert.equal(out.persisted_minutes,45);assert.equal(out.network_calls,0);assert.equal(out.evidence.length,0);assert.ok(db.sqlite.prepare("SELECT payload_json FROM report2_evidence_source_cache WHERE source='HTX_SIGNED_RAW_TAPE'").get());});

test('injected corrupt acquisitions and duplicate saved minute keys are rejected before persistence',()=>{const a=verifiedSignedMinutes({snapshot:snapshot(),contract,now}),m=mergeSignedTape({acquisition:a,now});const bad=structuredClone(a);bad.minutes[0].raw_sha256='0'.repeat(64);assert.equal(mergeSignedTape({acquisition:bad,now}).status,'ACQUIRED_RAW_TAPE_INTEGRITY_NOT_CLOSED');const duplicate=structuredClone(m.ring);duplicate.minutes.push(duplicate.minutes[0]);assert.equal(mergeSignedTape({previous:duplicate,acquisition:a,now}).status,'SAVED_RAW_TAPE_INTEGRITY_NOT_CLOSED');assert.equal(signedTape24hEvidence({ring:duplicate,now}).evidence.length,0);});

test('the shared raw accumulator retains factual minutes older than 45 minutes already present in the same response',()=>{
 const s=snapshot();s.minutes.payload.data=Array.from({length:300},(_,i)=>({id:(now-301*MIN+i*MIN)/1000,count:i===298?1:0}));
 const a=verifiedSignedMinutes({snapshot:s,contract,now});assert.equal(a.minutes.length,300);assert.equal(a.network_calls,0);assert.equal(mergeSignedTape({acquisition:a,now}).ring.minutes.length,300);
});
test('validated immutable raw history extends the same contract sample; foreign, corrupt or conflicting fills never do',()=>{
 const ring=controlledRing(),current=ring.minutes.at(-1).fills.map(f=>({id:f.id,ts:f.ts,direction:f.side,price:f.price,amount:f.contracts,trade_turnover:f.quote_usdt}));
 const params={ring,current_trades:current,contract,contract_size:1,now};const good=mergeHtxSignedHistoryTrades(params);
 assert.equal(good.trades.length,1440);assert.equal(good.reused_fills,1439);assert.equal(good.source_http,0);assert.equal(good.full_window_completion_claimed,false);
 for(const mutate of [r=>r.contract='FOREIGN-USDT',r=>r.contract_size=2,r=>r.minutes[0].raw_sha256='foreign',r=>r.minutes[0].observed_ts=now+1,r=>r.minutes.push(r.minutes[0])]){const r=structuredClone(ring);mutate(r);assert.deepEqual(mergeHtxSignedHistoryTrades({...params,ring:r}).trades,current);}
 const conflict=structuredClone(current);conflict[0].amount+=1;assert.equal(mergeHtxSignedHistoryTrades({...params,current_trades:conflict}).status,'CONFLICTING_SAVED_AND_CURRENT_FILL');
});

test('saved history does not erase truncation or dropped-row provenance from the current transport',()=>{
 for(const flag of ['_source_truncated','_source_rows_dropped']){const current=[];Object.defineProperty(current,flag,{value:flag==='_source_truncated'?true:1});const result=mergeHtxSignedHistoryTrades({ring:controlledRing(),current_trades:current,contract,contract_size:1,now});assert.equal(result.status,'CURRENT_RAW_TRANSPORT_NOT_COMPLETE');assert.equal(result.trades,current);}
});

test('persistence exceptions retain the exact admitted failure stage and source clocks without evidence, retry or extra writes',async()=>{
 for(const failure of ['D1_ADMISSION','INSTALL_EVIDENCE_SOURCE_STORE','READ_PREVIOUS_RING','WRITE_MERGED_RING','READBACK_MERGED_RING']){
  clearHtxSignedTapeSnapshots();const snap=snapshot();for(const [type,route] of [['metadata','/linear-swap-api/v1/swap_contract_info'],['trades','/linear-swap-ex/market/history/trade'],['minutes','/linear-swap-ex/market/history/kline']])observeHtxSignedTape(snap[type].payload,'https://api.hbdm.com'+route+'?contract_code='+encodeURIComponent(contract)+(type==='minutes'?'&period=1min':''),now);
  const ops=[];let reads=0;const boom=()=>{const e=new Error('DO_NOT_EXPORT_SECRET');e.code='D1_TEST_DENIAL';throw e;};const db={prepare(sql){return{bind(){return this;},async first(){ops.push('READ');reads++;if(failure==='READ_PREVIOUS_RING'||failure==='READBACK_MERGED_RING'&&reads===2)boom();return null;},async run(){ops.push('WRITE');if(failure==='WRITE_MERGED_RING')boom();return{success:true};}};},async batch(){ops.push('INSTALL');if(failure==='INSTALL_EVIDENCE_SOURCE_STORE')boom();}};
  const result=await persistCapturedHtxSignedTape({db,contract,now,db_admit:()=>{ops.push('ADMISSION');if(failure==='D1_ADMISSION')boom();return{allowed:true};}});
  assert.equal(result.status,'RAW_TAPE_PERSISTENCE_NOT_CLOSED');assert.equal(result.failure_stage,failure);assert.equal(result.error_code,'D1_TEST_DENIAL');assert.deepEqual(result.evidence,[]);assert.equal(result.network_calls,0);
  const flow=capturedSignedTapeFourHourFlow({contract,now});assert.equal(flow.check_completed,false);assert.equal(flow.evidence.length,0);assert.equal(flow.raw_acquisition_diagnostic.failure_stage,failure);assert.equal(flow.raw_acquisition_diagnostic.source_clocks.trades.source_ts,now);assert.equal(flow.raw_acquisition_diagnostic.source_clocks.minutes.source_ts,now);assert.equal(flow.raw_acquisition_diagnostic.new_verified_minutes,45);assert.ok(!JSON.stringify(flow).includes('DO_NOT_EXPORT_SECRET'));assert.ok(ops.filter(o=>o==='WRITE').length<=1);
 }
 clearHtxSignedTapeSnapshots();
});
