import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_SIGNED_TAPE_MODULE_ROOT;
const load=rel=>import(root?pathToFileURL(root+'/'+rel):new URL('../files/src/'+rel,import.meta.url));
const {HTX_SIGNED_TAPE_VERSION,verifiedSignedMinutes,mergeSignedTape,signedTape24hEvidence,observeHtxSignedTape,clearHtxSignedTapeSnapshots,persistCapturedHtxSignedTape}=await load('htx-signed-tape.mjs');
const {consumeBlockResultContext}=await load('block-result-context.mjs');
const {consumeEvidenceV2}=await load('evidence-v2.mjs');
const MIN=60000,now=1791141000000,contract='测试1000-USDT',size=1,hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const snapshot=()=>({metadata:{observed_ts:now,payload:{status:'ok',ts:now,data:[{contract_code:contract,contract_status:1,business_type:'swap',trade_partition:'USDT',contract_size:size}]}},trades:{observed_ts:now,payload:{status:'ok',ts:now,ch:`market.${contract}.trade.detail`,data:[{data:[{id:'123456789012345678901',ts:now-3*MIN+1000,direction:'buy',price:2,amount:3,trade_turnover:6}]}]}},minutes:{observed_ts:now,payload:{status:'ok',ts:now,ch:`market.${contract}.kline.1min`,data:Array.from({length:45},(_,i)=>({id:(now-46*MIN+i*MIN)/1000,count:i===43?1:0}))}}});
class Statement{constructor(db,sql,args=[]){Object.assign(this,{db,sql,args});}bind(...args){return new Statement(this.db,this.sql,args);}async run(){return this.db.sqlite.prepare(this.sql).run(...this.args);}async first(){return this.db.sqlite.prepare(this.sql).get(...this.args)||null;}}
class DB{constructor(){this.sqlite=new DatabaseSync(':memory:');}prepare(sql){return new Statement(this,sql);}async batch(rows){return Promise.all(rows.map(s=>s.run()));}}
test('only individual raw minute/count matches persist; a bounded recent sample never proves 24 hours',()=>{const a=verifiedSignedMinutes({snapshot:snapshot(),contract,now});assert.equal(a.minutes.length,45);assert.equal(a.minutes.find(m=>m.factual_count===1).fills[0].id,'123456789012345678901');const m=mergeSignedTape({acquisition:a,now});assert.equal(m.status,'DURABLE_RAW_TAPE_WARMING');assert.equal(signedTape24hEvidence({ring:m.ring,now}).status,'WARMING_OR_GAPPED_RAW_24H');assert.equal(signedTape24hEvidence({ring:m.ring,now}).evidence.length,0);});
test('compensating minute count errors, unsafe IDs, stale and foreign metadata never green the tape',()=>{
 const moved=snapshot();moved.minutes.payload.data[43].count=0;moved.minutes.payload.data[42].count=1;const a=verifiedSignedMinutes({snapshot:moved,contract,now});assert.equal(a.minutes.length,43);assert.equal(a.gaps.length,2);
 for(const alter of [s=>s.trades.payload.data[0].data[0].id=Number.MAX_SAFE_INTEGER+5,s=>s.metadata.payload.data[0].contract_code='BTC-USDT',s=>s.trades.payload.ts=now-120001,s=>s.metadata.payload.data[0].contract_size=100]){const s=snapshot();alter(s);const out=verifiedSignedMinutes({snapshot:s,contract,now});assert.ok(!out.minutes.length||!out.minutes.some(m=>m.factual_count===1));}
 const dup=snapshot();dup.trades.payload.data[0].data.push({...dup.trades.payload.data[0].data[0],price:4});assert.equal(verifiedSignedMinutes({snapshot:dup,contract,now}).status,'RAW_FILL_ID_INTEGRITY_NOT_CLOSED');
});
test('changed complete minute and corrupt saved source bytes do not replace a verified ring',()=>{const a=verifiedSignedMinutes({snapshot:snapshot(),contract,now}),m=mergeSignedTape({acquisition:a,now});const changed=structuredClone(a);let minute=changed.minutes.find(m=>m.factual_count);minute.fills[0].contracts=4;minute.fills[0].quote_usdt=8;minute.raw_sha256=hash(minute.fills);assert.equal(mergeSignedTape({previous:m.ring,acquisition:changed,now}).status,'CONFLICTING_COMPLETE_RAW_MINUTE');const corrupt=structuredClone(m.ring);corrupt.minutes.find(m=>m.factual_count).fills[0].contracts=4;assert.equal(mergeSignedTape({previous:corrupt,acquisition:a,now}).status,'SAVED_RAW_TAPE_INTEGRITY_NOT_CLOSED');});
// A clearly controlled 24h fixture tests admission; it is never a live acceptance.
function controlledRing(){const end=now-MIN;return{version:HTX_SIGNED_TAPE_VERSION,contract,contract_size:1,observed_ts:now,minutes:Array.from({length:1440},(_,i)=>{const start_ts=end-1440*MIN+i*MIN,fills=[{id:String(100000+i),ts:start_ts+1000,side:i%2?'buy':'sell',price:2,contracts:3,quote_usdt:6}];return{contract,contract_size:1,start_ts,factual_count:1,fills,raw_sha256:hash(fills),source_ts:now,observed_ts:now};})};}
test('only a complete 1440-minute ring with exact unique fills supplies a neutral signed fact to the report',()=>{const out=signedTape24hEvidence({ring:controlledRing(),now});assert.equal(out.status,'CLOSED_EXACT_SIGNED_RAW_24H');assert.equal(out.evidence[0].raw_trade_count,1440);assert.equal(out.evidence[0].value,0);const context=consumeBlockResultContext({evidence:out.evidence,contract,now});assert.equal(context.facts.length,1);assert.equal(context.facts[0].score_contribution,0);assert.match(context.facts[0].value,/1440 минут/u);assert.equal(consumeEvidenceV2(out.evidence,{base_interest:70,decision_ts:now}).adjustment,0);
 for(const alter of [r=>r.minutes.splice(12,1),r=>{r.minutes[12].fills[0].id=r.minutes[11].fills[0].id;r.minutes[12].raw_sha256=hash(r.minutes[12].fills);},r=>r.minutes[12].observed_ts=now+1,r=>r.minutes[12].fills[0].quote_usdt=999]){const r=controlledRing();alter(r);assert.equal(signedTape24hEvidence({ring:r,now}).evidence.length,0);}
});
test('durable raw ring respects DB admission and readback without network requests or new tables',async()=>{clearHtxSignedTapeSnapshots();const s=snapshot();for(const [k,url] of [['metadata','/linear-swap-api/v1/swap_contract_info'],['trades','/linear-swap-ex/market/history/trade'],['minutes','/linear-swap-ex/market/history/kline']])observeHtxSignedTape(s[k].payload,'https://api.hbdm.com'+url+'?contract_code='+encodeURIComponent(contract)+'&period=1min',now);const db=new DB();assert.equal((await persistCapturedHtxSignedTape({db,contract,now,db_admit:()=>({allowed:false,status:'NO_HEADROOM'})})).status,'NO_HEADROOM');let grants=0;const out=await persistCapturedHtxSignedTape({db,contract,now,db_admit:e=>{grants++;assert.equal(e.rows_written,4);return{allowed:true};}});assert.equal(grants,1);assert.equal(out.persisted_minutes,45);assert.equal(out.network_calls,0);assert.equal(out.evidence.length,0);assert.ok(db.sqlite.prepare("SELECT payload_json FROM report2_evidence_source_cache WHERE source='HTX_SIGNED_RAW_TAPE'").get());});

test('injected corrupt acquisitions and duplicate saved minute keys are rejected before persistence',()=>{const a=verifiedSignedMinutes({snapshot:snapshot(),contract,now}),m=mergeSignedTape({acquisition:a,now});const bad=structuredClone(a);bad.minutes[0].raw_sha256='0'.repeat(64);assert.equal(mergeSignedTape({acquisition:bad,now}).status,'ACQUIRED_RAW_TAPE_INTEGRITY_NOT_CLOSED');const duplicate=structuredClone(m.ring);duplicate.minutes.push(duplicate.minutes[0]);assert.equal(mergeSignedTape({previous:duplicate,acquisition:a,now}).status,'SAVED_RAW_TAPE_INTEGRITY_NOT_CLOSED');assert.equal(signedTape24hEvidence({ring:duplicate,now}).evidence.length,0);});
