import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {realInput,wireFixture} from './volume-profile-fixture.mjs';
import {buildHtxVolumeProfile,volumeProfileSignal,readReadyHtxVolumeProfile,clearVolumeProfileSnapshots,observeHtxVolumeSnapshot,applyVolumeProfileToLiquidationPanel} from '../files/src/htx-volume-profile.mjs';
import {collectReadyHtxVolumeProfile} from '../files/src/htx-volume-profile-collector.mjs';
import {normalizeVenueVolumeProfiles,compareVolumeProfiles,collectCrossVenueVolumeProfiles} from '../files/src/cross-venue-volume-profile.mjs';
import {buildSupplementalScoreEvidence,applySupplementalScoreAdjustment} from '../files/src/supplemental-score-evidence.mjs';
import {createUnifiedHttpBudget} from '../files/src/unified-budget.mjs';
import {installProviderMinuteLedger} from '../files/src/provider-minute-ledger.mjs';
const urls=['https://api.hbdm.com/linear-swap-api/v1/swap_contract_info?contract_code=QNT-USDT','https://api.hbdm.com/linear-swap-ex/market/history/kline?contract_code=QNT-USDT&period=1min','https://api.hbdm.com/linear-swap-ex/market/history/trade?contract_code=QNT-USDT'];
export class DB {
 constructor(){this.sql=new DatabaseSync(':memory:');}
 prepare(sql){const db=this.sql;return {
  async run(){return db.prepare(sql).run();},
  bind(...xs){return {
   async first(){return db.prepare(sql).get(...xs)||null;},
   async run(){return db.prepare(sql).run(...xs);},
   async all(){return {results:db.prepare(sql).all(...xs)};}
  };}
 };}
}
test('retained real wire reconciles every minute, volume and long identifiers in 4h',()=>{const p=buildHtxVolumeProfile(realInput());assert.equal(p.status,'CLOSED');assert.equal(p.window_minutes,240);assert.equal(p.unique_trades,1257);assert.ok(Math.abs(p.total_base_volume-967.36)<1e-8);assert.equal(p.poc,284.9975);assert.ok(p.value_area_fraction>=.7);assert.ok(Math.abs(p.volume_by_price_bin.reduce((a,b)=>a+b,0)-p.total_base_volume)<1e-8);});
test('wrong units, duplicates, gaps, wrong contract and stale or future times fail closed',()=>{for(const mutate of [x=>x.trades.data=[],x=>{for(const b of x.trades.data)for(const r of b.data)r.id='1';},x=>{for(const b of x.trades.data)for(const r of b.data)r.quantity*=2;},x=>x.candles.data=x.candles.data.filter(r=>r.id%120===0),x=>x.trades.ch='market.SOL-USDT.trade.detail',x=>x.now+=181000,x=>x.trades.ts=x.now+1]){const x=realInput();mutate(x);assert.equal(buildHtxVolumeProfile(x).status,'NOT_CLOSED');}});
test('shorter complete fallback is disclosed and a replacement sample never accumulates prior trades',()=>{clearVolumeProfileSnapshots();const x=realInput(),end=Math.floor(Math.min(x.trades.ts,x.candles.ts)/60000)*60000;[x.info,x.candles,x.trades].forEach((p,i)=>observeHtxVolumeSnapshot(p,urls[i],x.now));assert.equal(readReadyHtxVolumeProfile(x).window_minutes,240);for(const b of x.trades.data)b.data=b.data.filter(r=>r.ts>=end-15*60000);observeHtxVolumeSnapshot(x.trades,urls[2],x.now);const p=readReadyHtxVolumeProfile(x);assert.equal(p.window_minutes,15);assert.equal(p.maximum_score_points,.5);observeHtxVolumeSnapshot({...x.trades,data:[]},urls[2],x.now);assert.equal(readReadyHtxVolumeProfile(x).status,'NOT_CLOSED');clearVolumeProfileSnapshots();});
test('single venue, agreement, conflict and missing peers produce one bounded score family',()=>{const x=realInput(),p=buildHtxVolumeProfile({...x,window_end:Math.floor(x.trades.ts/60000)*60000-120000}),price=p.last_closed_bars.at(-1).close,options={contract:x.contract,now:x.now,reference_price:price,direction:'LONG'};const peer=source=>({...p,source,market:`${source}_LINEAR_USDT_PERPETUAL`});const single=compareVolumeProfiles({primary:p,...options}),one=compareVolumeProfiles({primary:p,peers:[peer('BINANCE')],...options}),two=compareVolumeProfiles({primary:p,peers:[peer('BINANCE'),peer('BYBIT')],...options}),conflict=compareVolumeProfiles({primary:p,peers:[{...peer('BINANCE'),poc:p.poc*1.03,val:p.val*1.03,vah:p.vah*1.03}],...options});assert.equal(single.factor,.5);assert.equal(one.factor,.8);assert.equal(two.factor,1);assert.equal(conflict.factor,0);for(const [consensus,points] of [[single,.75],[one,1.2],[two,1.5],[conflict,0]]){const rows=buildSupplementalScoreEvidence({direction:'LONG',volume_profile:p,volume_consensus:consensus,contract:x.contract,observed_ts:x.now,reference_price:price});const out=applySupplementalScoreAdjustment(70,[...rows,...rows]);assert.equal(out.adjustment,points);assert.ok(out.receipts.length<=1);}assert.equal(volumeProfileSignal(p,{...options,now:x.now+181000}).status,'NOT_CLOSED');assert.equal(volumeProfileSignal({...p,expires_at:undefined},options).status,'NOT_CLOSED');assert.equal(volumeProfileSignal(p,{...options,reference_price:price*1.1}).status,'NOT_CLOSED');assert.equal(compareVolumeProfiles({primary:p,peers:[{...peer('BINANCE'),window_end:p.window_end-60000}],...options}).factor,.5);});
test('foreign venue adapter reconciles ready trades against its own candles, never HTX candles',()=>{const x=realInput(),end=Math.floor(x.trades.ts/60000)*60000,rows=x.trades.data.flatMap(b=>b.data),bars=x.candles.data;const args={venue:'BYBIT',contract:x.contract,symbol:'QNTUSDT',catalog_entry:{base:'QNT',bybit:'QNTUSDT'},now:x.now,window_end:end,trades:{retCode:0,time:x.trades.ts,result:{category:'linear',list:rows.map(r=>({execId:r.id,symbol:'QNTUSDT',time:String(r.ts),price:String(r.price),size:String(r.quantity)}))}},candles:{retCode:0,time:x.candles.ts,result:{category:'linear',symbol:'QNTUSDT',list:bars.map(b=>[String(b.id*1000),b.open,b.high,b.low,b.close,b.amount,b.trade_turnover].map(String))}}};const valid=normalizeVenueVolumeProfiles(args);assert.equal(valid.status,'CLOSED');assert.equal(valid.profiles[0].poc,284.9975);const broken=structuredClone(args);broken.trades.result.list.pop();broken.trades.result.list=broken.trades.result.list.filter(r=>Number(r.time)<end-60000);assert.equal(normalizeVenueVolumeProfiles(broken).status,'NOT_CLOSED');assert.equal(normalizeVenueVolumeProfiles({...args,symbol:'1000QNTUSDT'}).status,'NOT_CLOSED');const binance={...args,venue:'BINANCE',catalog_entry:{base:'QNT',binance:'QNTUSDT'},trades:rows.map((r,i)=>({a:i+1,T:r.ts,p:String(r.price),q:String(r.quantity)})),candles:bars.map(b=>[b.id*1000,b.open,b.high,b.low,b.close,b.amount,b.id*1000+59999,b.trade_turnover])};assert.equal(normalizeVenueVolumeProfiles(binance).status,'CLOSED');});
test('liquidation ranking gets confluence but unchanged price, notional, eligibility and directional score',()=>{const x=realInput(),p=buildHtxVolumeProfile(x),panel={status:'CLOSED',score_evidence:{bullish_strength:.2},clusters:[{center_price:300,distance_pct:1,largest_provider_position_usd:50,decision_target_eligible:false},{center_price:p.poc,distance_pct:-4,largest_provider_position_usd:60,decision_target_eligible:false}]};const out=applyVolumeProfileToLiquidationPanel(panel,p,{contract:x.contract,now:x.now,reference_price:p.last_closed_bars.at(-1).close});assert.equal(out.clusters[0].center_price,p.poc);assert.equal(out.clusters[0].decision_target_eligible,false);assert.deepEqual(out.score_evidence,panel.score_evidence);assert.ok(out.clusters.every(c=>c.volume_profile_additional_score_points===0));});
test('standalone collector admits three calls once, does not wait or retry 429',async()=>{clearVolumeProfileSnapshots();const f=wireFixture(),budget=createUnifiedHttpBudget();let calls=0;const args={contract:'QNT-USDT',run_id:'T',request_admit:budget.reserve,fetch_impl:async url=>{calls++;return new Response(f[url.includes('contract_info')?'1':url.includes('history/kline')?'2':'10']);},clock:()=>f.provenance.now};assert.equal((await collectReadyHtxVolumeProfile(args)).status,'CLOSED');assert.equal(calls,3);assert.equal((await collectReadyHtxVolumeProfile(args)).network_calls,0);clearVolumeProfileSnapshots();assert.equal((await collectReadyHtxVolumeProfile(args)).network_calls,0);const r=await collectReadyHtxVolumeProfile({...args,run_id:'429',fetch_impl:async()=>new Response('',{status:429})});assert.equal(r.network_calls,3);assert.ok(r.receipts.every(x=>x.status==='TEMPORARY_RATE_LIMIT'));clearVolumeProfileSnapshots();});
test('cross-venue provider cooldown survives another asset and independent provider remains eligible',async()=>{const db=new DB(),now=realInput().now;await installProviderMinuteLedger(db);db.sql.exec('CREATE TABLE report2_cross_exchange_catalog(catalog_id TEXT,expires_ts INTEGER,payload_json TEXT)');db.sql.prepare('INSERT INTO report2_cross_exchange_catalog VALUES(?,?,?)').run('CEX_V3',now+86400000,JSON.stringify({entries:{QNT:{base:'QNT',binance:'QNTUSDT',bybit:'QNTUSDT'},SOL:{base:'SOL',binance:'SOLUSDT',bybit:'SOLUSDT'}}}));const seen=[];const options={db,request_admit:createUnifiedHttpBudget().reserve,clock:()=>now,fetch_impl:async url=>{seen.push(url);return new Response('{}',{status:url.includes('binance')?429:503});}};let r=await collectCrossVenueVolumeProfiles({...options,contract:'QNT-USDT',run_id:'A'});assert.equal(r.network_calls,4);r=await collectCrossVenueVolumeProfiles({...options,contract:'SOL-USDT',run_id:'B'});assert.equal(r.network_calls,2);assert.equal(r.sources.BINANCE.reason,'TEMPORARY_RATE_LIMIT');assert.equal(seen.filter(x=>x.includes('binance')).length,2);db.sql.close();});

test('OKX native contract sizes are converted once and its closed candles prove completeness',()=>{const x=realInput(),rows=x.trades.data.flatMap(b=>b.data),bars=x.candles.data,end=Math.floor(x.trades.ts/60000)*60000,entry={base:'QNT',okx:'QNT-USDT-SWAP',okx_asset_category:'1',okx_contract_value:.01,okx_contract_multiplier:1,okx_contract_value_currency:'QNT'};const args={venue:'OKX',contract:x.contract,symbol:entry.okx,catalog_entry:entry,now:x.now,window_end:end,trades:{code:'0',data:rows.map(r=>({instId:entry.okx,tradeId:r.id,ts:String(r.ts),px:String(r.price),sz:String(r.amount)}))},candles:{code:'0',data:bars.map(b=>[b.id*1000,b.open,b.high,b.low,b.close,b.vol,b.amount,b.trade_turnover,'1'].map(String))}};const p=normalizeVenueVolumeProfiles(args);assert.equal(p.status,'CLOSED');assert.equal(p.profiles[0].poc,284.9975);assert.ok(Math.abs(p.profiles[0].total_base_volume-967.36)<1e-8);assert.equal(normalizeVenueVolumeProfiles({...args,catalog_entry:{...entry,okx_contract_value_currency:'USDT'}}).status,'NOT_CLOSED');assert.equal(normalizeVenueVolumeProfiles({...args,catalog_entry:{...entry,okx_contract_value:1}}).status,'NOT_CLOSED');});

test('an independently fresh peer with a large price discrepancy neutralizes the profile, not silently drops to single venue',()=>{const x=realInput(),p=buildHtxVolumeProfile(x),peer={...p,source:'OKX',okx_asset_category:'1',poc:p.poc/6,val:p.val/6,vah:p.vah/6,last_closed_bars:p.last_closed_bars.map(b=>({...b,open:b.open/6,high:b.high/6,low:b.low/6,close:b.close/6}))};const c=compareVolumeProfiles({primary:p,peers:[peer],contract:x.contract,now:x.now,reference_price:p.last_closed_bars.at(-1).close,direction:'LONG'});assert.equal(c.status,'CONFLICT');assert.equal(c.factor,0);assert.equal(c.conflicts[0].reason,'PRICE_OR_ASSET_IDENTITY_CONFLICT');});
