import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_UNIFIED_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_UNIFIED_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url);
const [{jointSpotFuturesFlow,validateJointFlowEvidence},{consumeBlockResultContext,auditRenderedBlockResults},{consumeEvidenceV2},{finalizeCandidateBlockCoverage},{BITGET_FLOW_VERSION},{canonicalFingerprint,renderCanonicalTelegram,loadExactManual,sha256},{formatManualReport}]=await Promise.all(['joint-spot-futures-flow.mjs','block-result-context.mjs','evidence-v2.mjs','candidate-evidence-v2-runtime.mjs','bitget-four-hour-flow.mjs','canonical-publication.mjs','manual-report-formatter.mjs'].map(n=>import(new URL(n,root))));
const end=1791633600000,now=end+1000;
const args=()=>({now,primary:{check_completed:true,evidence:[{block_id:'N05',metric_family:'EXACT_FUTURES_TAKER_FLOW_4H',provider_id:'HTX_FUTURES_RAW_FLOW',upstream_id:'HTX_OFFICIAL_RAW_FILLS',source_clock_policy:'IMMUTABLE_EXACT_RAW_MINUTES',score_contribution:0,entry_authorized:false,factual_1m_trade_count:240,raw_trade_count:240,window_start_ts:end-14400000,window_end_ts:end,buy_quote_turnover_usdt:60,sell_quote_turnover_usdt:40,htx_contract:'LINK-USDT',asset_id:'HTX:USDT_M_PERPETUAL:LINK-USDT'}]},external:{components:[{version:BITGET_FLOW_VERSION,status:'CLOSED_VOLUME_RECONCILED_FOUR_HOURS',check_completed:true,exact_asset_binding:true,contract:'LINK-USDT',window_start_ts:end-14400000,window_end_ts:end,observed_ts:now,verified_minutes:240,venue:'BITGET',physical_root:'BITGET_OFFICIAL_PUBLIC_TRADES',market:'SPOT',quote:'USDT',buy_quote:62,sell_quote:38}]}});
test('controlled multi-venue spot and futures agreement yields one unscored fact for both report chains',()=>{const a=args(),r=jointSpotFuturesFlow(a),row=r.evidence[0];assert.equal(r.check_completed,true);assert.equal(validateJointFlowEvidence(row,now),true);const c=consumeBlockResultContext({contract:'LINK-USDT',now,evidence:r.evidence});assert.equal(c.facts.length,1);assert.match(c.facts[0].value,/спот/);assert.match(c.facts[0].value,/фьючерсы/);assert.equal(consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:now}).final_interest,70);const f=finalizeCandidateBlockCoverage({decision_ts:now,evidence_result:{evidence:[],sources:{BITGET_FOUR_HOUR_FLOW:a.external}},primary_sources:{PRIMARY_HTX_FUTURES_FLOW:a.primary}});assert.equal(f.block_coverage.blocks.N05.checked,true);assert.equal(f.block_coverage.blocks.N05.usable_facts,0);assert.equal(f.evidence.length,1);});
test('single venue, opposite direction, weak imbalance, large strength spread and old window do not confirm N05',()=>{for(const mutate of [a=>a.external.components=[],a=>{a.external.components[0].buy_quote=38;a.external.components[0].sell_quote=62;},a=>{a.external.components[0].buy_quote=51;a.external.components[0].sell_quote=49;},a=>{a.external.components[0].buy_quote=90;a.external.components[0].sell_quote=10;},a=>a.now=end+300001,a=>a.external.components[0].verified_minutes=239,a=>a.external.components[0].contract='OTHER-USDT',a=>a.external.components.push({...a.external.components[0]})]){const a=args();mutate(a);assert.equal(jointSpotFuturesFlow(a).evidence.length,0);}});
test('tampered report rows cannot bypass the shared recomputed agreement checks',()=>{const row=jointSpotFuturesFlow(args()).evidence[0];for(const mutate of [r=>r.components[1].buy_quote=0,r=>r.components[1].contract='OTHER-USDT',r=>r.agreed_direction='SELL',r=>r.value+=.01,r=>r.score_contribution=1,r=>r.agreement_policy.maximum_imbalance_spread=1]){const bad=structuredClone(row);mutate(bad);assert.equal(validateJointFlowEvidence(bad,now),false);assert.equal(consumeBlockResultContext({contract:'LINK-USDT',now,evidence:[bad]}).facts.length,0);}});
test('legacy single-market or Nansen rows cannot award points in the current N05 strategy',()=>{const r=jointSpotFuturesFlow(args()).evidence[0];const old={...r,metric_family:'CEX_NET_FLOW_TWO_COMPLETE_HOURS',coverage_fraction:1,directional_strength:1};assert.equal(consumeEvidenceV2([old],{base_interest:70,decision_ts:now}).final_interest,70);assert.equal(consumeBlockResultContext({contract:'LINK-USDT',now,evidence:[old]}).facts.length,0);});

test('same controlled canonical joint flow is actually printed in manual and both approved Telegram forms',()=>{const c=structuredClone(JSON.parse(fs.readFileSync(new URL('../../checkpoints/btw-preserved-block-result-input-20261004.json',import.meta.url))).canonical),a=args(),T=c.observed_ts,E=Math.floor(T/60000)*60000,contract=c.metadata.contract,h=a.primary.evidence[0],b=a.external.components[0];a.now=T;Object.assign(h,{htx_contract:contract,asset_id:'HTX:USDT_M_PERPETUAL:'+contract,window_start_ts:E-14400000,window_end_ts:E});Object.assign(b,{contract,window_start_ts:E-14400000,window_end_ts:E,observed_ts:T});const r=jointSpotFuturesFlow(a);assert.equal(r.check_completed,true);c.metadata.internal_market_context.evidence_v2.evidence=r.evidence;c.metadata.supporting_context={facts:consumeBlockResultContext({contract,now:T,evidence:r.evidence}).facts};c.direction='LONG';c.state='OBSERVE';c.trigger={metric:'price',operator:'>=',value:1,unit:'USDT',timeframe:'5m',expires_ts:T+600000,next_recheck_ts:T+60000,cancel_condition:'price<1'};c.analytical_fingerprint=canonicalFingerprint(c);const before=JSON.stringify(c),manual=formatManualReport(c);assert.equal(manual.ok,true);for(const context_policy of ['ORIGINAL_V5_20261006','ORIGINAL_BRIEF_20261007']){const tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'OBSERVE',context_policy});assert.equal(tg.ok,true,tg.status);assert.match(manual.text,/Согласованный поток спота и фьючерсов/);assert.match(tg.text,/Согласованный поток спота и фьючерсов/);const audit=auditRenderedBlockResults({canonical:c,manual,telegram:tg});assert.deepEqual(audit.used_context_block_ids,['N05']);assert.deepEqual(audit.telegram_used_context_block_ids,['N05']);assert.equal(audit.telegram_delivery_proven,false);}assert.equal(JSON.stringify(c),before);});
test('stored manual presentation hash is checked before legacy N05 text is suppressed',async()=>{const c=structuredClone(JSON.parse(fs.readFileSync(new URL('../../checkpoints/btw-preserved-block-result-input-20261004.json',import.meta.url))).canonical);c.direction='LONG';c.state='OBSERVE';c.metadata.supporting_context={facts:[{block_id:'N05',field:'CEX_NET_FLOW_TWO_COMPLETE_HOURS',label:'Старый поток',value:'LEGACY-N05-MARKER'}]};c.analytical_fingerprint=canonicalFingerprint(c);const p={publication_id:'ARCHIVE',contract_code:c.metadata.contract,direction:c.direction,run_id:c.run_id,snapshot_id:c.snapshot_id,observed_ts:c.observed_ts,canonical_json:JSON.stringify(c),analytical_fingerprint:c.analytical_fingerprint,manual_text:'Old LEGACY-N05-MARKER',telegram_text:'Old Telegram'};p.presentation_hash=sha256({manual_text:p.manual_text,telegram_text:p.telegram_text,analytical_fingerprint:c.analytical_fingerprint});const before=JSON.stringify(p),db={prepare(){return{bind(){return this;},async first(){return p;}};}};const r=await loadExactManual(db,{publication_id:'ARCHIVE'});assert.equal(r.ok,true,r.status);assert.equal(r.legacy_N05_facts_suppressed,true);assert.doesNotMatch(r.text,/LEGACY-N05-MARKER/);assert.equal(JSON.stringify(p),before);p.manual_text+=' changed';assert.equal((await loadExactManual(db,{publication_id:'ARCHIVE'})).ok,false);});

test('qualified Binance native taker window participates in the same shared joint gate and reports',async()=>{const {normalizeBinanceNativeFlow}=await import(new URL('binance-native-four-hour-flow.mjs',root)),a=args(),contract='APT-USDT';Object.assign(a.primary.evidence[0],{htx_contract:contract,asset_id:'HTX:USDT_M_PERPETUAL:'+contract});const component=normalizeBinanceNativeFlow({contract,identity:{chain:'aptos',asset_kind:'NATIVE',native_asset_id:'aptos:mainnet',contract_or_mint:null},catalog:{symbols:[{symbol:'APTUSDT',baseAsset:'APT',quoteAsset:'USDT',status:'TRADING',isSpotTradingAllowed:true}]},window_end_ts:end,observed_ts:now,candles:Array.from({length:240},(_,i)=>[end-14400000+i*60000,'1','1','1','1','100',end-14400000+i*60000+59999,'100',2,'62','62','0'])});a.external.components=[component];const r=jointSpotFuturesFlow(a);assert.equal(r.check_completed,true,r.reason);assert.equal(validateJointFlowEvidence(r.evidence[0],now),true);const facts=consumeBlockResultContext({contract,now,evidence:r.evidence}).facts;assert.equal(facts.length,1);assert.match(facts[0].source,/Binance/);assert.equal(consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:now}).final_interest,70);const f=finalizeCandidateBlockCoverage({decision_ts:now,evidence_result:{evidence:[],sources:{EXTERNAL_N05_FLOW:a.external}},primary_sources:{PRIMARY_HTX_FUTURES_FLOW:a.primary}});assert.equal(f.block_coverage.blocks.N05.checked,true);for(const change of [c=>c.venue='GATE',c=>c.physical_root='OTHER',c=>c.direction_semantics='BUY_OR_SELL_ORDER',c=>c.identity.native_asset_id='other:mainnet',c=>c.observed_ts=now+1,c=>c.window_end_ts+=60000,c=>c.verified_minutes=239]){const bad=structuredClone(a);change(bad.external.components[0]);assert.equal(jointSpotFuturesFlow(bad).evidence.length,0);}});

test('qualified Gate exact token window survives shared validation and both report chains without score',async()=>{
 const [{normalizeGateSpotFlow},{GATE_PUBLIC_TAKER_REFERENCE}]=await Promise.all(['gate-four-hour-flow.mjs','gate-public-taker-reference.mjs'].map(n=>import(new URL(n,root))));
 const c=structuredClone(JSON.parse(fs.readFileSync(new URL('../../checkpoints/btw-preserved-block-result-input-20261004.json',import.meta.url))).canonical),T=c.observed_ts,E=Math.floor(T/60000)*60000,S=E-14400000,contract=c.metadata.contract,base=contract.slice(0,-5),identity={chain:'ethereum',asset_kind:'TOKEN',contract_or_mint:'0x'+'a'.repeat(40)};
 const component=normalizeGateSpotFlow({contract,identity,currencies:[{currency:base,chains:[{name:'ETH',addr:identity.contract_or_mint}]}],spot:[{id:base+'_USDT',base,quote:'USDT',trade_status:'tradable'}],window_end_ts:E,observed_ts:T,direction_reference:GATE_PUBLIC_TAKER_REFERENCE,candles:Array.from({length:240},(_,i)=>[String((S+i*60000)/1000),'2','1','1','1','1','2','true']),pages:[Array.from({length:240},(_,i)=>({id:String(240-i),currency_pair:base+'_USDT',create_time_ms:String(S+(239-i)*60000+1000)+'.001',price:'1',amount:'2',side:i%3?'buy':'sell'}))]});
 assert.equal(component.check_completed,true,component.reason);const a=args();a.now=T;Object.assign(a.primary.evidence[0],{htx_contract:contract,asset_id:'HTX:USDT_M_PERPETUAL:'+contract,window_start_ts:S,window_end_ts:E,buy_quote_turnover_usdt:66,sell_quote_turnover_usdt:34});a.external.components=[component];const r=jointSpotFuturesFlow(a);assert.equal(r.check_completed,true,r.reason);assert.equal(validateJointFlowEvidence(r.evidence[0],T),true);assert.equal(consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:T}).final_interest,70);
 c.metadata.internal_market_context.evidence_v2.evidence=r.evidence;c.metadata.supporting_context={facts:consumeBlockResultContext({contract,now:T,evidence:r.evidence}).facts};c.direction='LONG';c.state='OBSERVE';c.trigger={metric:'price',operator:'>=',value:1,unit:'USDT',timeframe:'5m',expires_ts:T+600000,next_recheck_ts:T+60000,cancel_condition:'price<1'};c.analytical_fingerprint=canonicalFingerprint(c);const manual=formatManualReport(c);assert.equal(manual.ok,true);assert.match(manual.text,/GATE/);for(const context_policy of ['ORIGINAL_V5_20261006','ORIGINAL_BRIEF_20261007']){const tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'OBSERVE',context_policy});assert.equal(tg.ok,true,tg.status);assert.match(tg.text,/GATE/);assert.deepEqual(auditRenderedBlockResults({canonical:c,manual,telegram:tg}).telegram_used_context_block_ids,['N05']);}
 for(const patch of [{direction_reference_id:'UNPROVEN'},{physical_root:'OTHER'},{observed_ts:T+1},{contract:'OTHER-USDT'},{identity:{...identity,asset_kind:'NATIVE'}},{score_contribution:1}])assert.equal(jointSpotFuturesFlow({...a,external:{components:[{...component,...patch}]}}).check_completed,false);
});


test('Backpack USDC flow appears in unchanged manual and both Telegram forms using only relative imbalance',async()=>{
 const {normalizeBackpackSpotFlow}=await import(new URL('backpack-four-hour-flow.mjs',root)),c=structuredClone(JSON.parse(fs.readFileSync(new URL('../../checkpoints/btw-preserved-block-result-input-20261004.json',import.meta.url))).canonical),T=c.observed_ts,E=Math.floor(T/60000)*60000,S=E-14400000,contract=c.metadata.contract,base=contract.slice(0,-5),identity={chain:'solana',contract_or_mint:'a'.repeat(32)};
 const candles=Array.from({length:240},(_,i)=>({start:new Date(S+i*60000).toISOString(),end:new Date(S+(i+1)*60000).toISOString(),open:'1',high:'1',low:'1',close:'1',volume:'2',quoteVolume:'2',trades:'1'})),pages=[Array.from({length:240},(_,i)=>({id:240-i,timestamp:S+(239-i)*60000+1000,price:'1',quantity:'2',quoteQuantity:'2',isBuyerMaker:i%3===0}))];
 const component=normalizeBackpackSpotFlow({contract,identity,assets:[{symbol:base,tokens:[{blockchain:'Solana',contractAddress:identity.contract_or_mint}]}],markets:[{symbol:base+'_USDC',baseSymbol:base,quoteSymbol:'USDC',marketType:'SPOT',orderBookState:'Open',visible:true}],quote:'USDC',candles,pages,window_end_ts:E,observed_ts:T});assert.equal(component.check_completed,true,component.reason);
 const a=args();a.now=T;Object.assign(a.primary.evidence[0],{htx_contract:contract,asset_id:'HTX:USDT_M_PERPETUAL:'+contract,window_start_ts:S,window_end_ts:E,buy_quote_turnover_usdt:66,sell_quote_turnover_usdt:34});a.external.components=[component];const r=jointSpotFuturesFlow(a);assert.equal(r.check_completed,true,r.reason);assert.equal(consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:T}).final_interest,70);
 c.metadata.internal_market_context.evidence_v2.evidence=r.evidence;c.metadata.supporting_context={facts:consumeBlockResultContext({contract,now:T,evidence:r.evidence}).facts};c.direction='LONG';c.state='OBSERVE';c.trigger={metric:'price',operator:'>=',value:1,unit:'USDT',timeframe:'5m',expires_ts:T+600000,next_recheck_ts:T+60000,cancel_condition:'price<1'};c.analytical_fingerprint=canonicalFingerprint(c);const manual=formatManualReport(c);assert.equal(manual.ok,true);assert.match(manual.text,/BACKPACK/);for(const context_policy of ['ORIGINAL_V5_20261006','ORIGINAL_BRIEF_20261007']){const tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'OBSERVE',context_policy});assert.equal(tg.ok,true,tg.status);assert.match(tg.text,/BACKPACK/);assert.deepEqual(auditRenderedBlockResults({canonical:c,manual,telegram:tg}).telegram_used_context_block_ids,['N05']);}
});
