import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_NATIVE_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_NATIVE_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url);
const [{consumeEvidenceV2,ACTIVE_BLOCK_IDS,PAUSED_BLOCKS},{resolveBlockCap},{consumeBlockResultContext},{buildSupplementalScoreEvidence,applySupplementalScoreAdjustment},{collectEvidenceRouteBlock,planCandidateEvidenceRoutes,auditCandidateBlocks,finalizeCandidateBlockCoverage,BLOCK_SOURCE_REQUIREMENTS},{enforceManualBlockCoverage,formatManualRunSummary}]=await Promise.all(['evidence-v2.mjs','block-score-policy.mjs','block-result-context.mjs','supplemental-score-evidence.mjs','candidate-evidence-v2-runtime.mjs','manual-run-summary.mjs'].map(n=>import(new URL(n,root))));
const T=Date.UTC(2026,9,10,12),row={evidence_id:'PAUSE-TEST',asset_id:'asset:apt',htx_contract:'APT-USDT',block_id:'N01',metric_family:'TOKEN_UNLOCK',provider_id:'OFFICIAL_EVENTS',upstream_id:'OFFICIAL_PRIMARY',dependency_group:'RELEASE',origin_event_id:'RELEASE',source_ts:T-1000,observed_ts:T,first_known_ts:T,expires_at:T+600000,coverage_status:'COMPLETE',coverage_fraction:1,schema_version:'EvidenceV2.1',validation_status:'VALID',identity_status:'EXACT',finality_status:'FINAL',directional_strength:null,risk_strength:1,reliability:1};
test('paused N01 cannot add, subtract, penalize absence or redistribute remaining weights',()=>{
 assert.ok(PAUSED_BLOCKS.N01);assert.equal(ACTIVE_BLOCK_IDS.length,13);assert.equal(ACTIVE_BLOCK_IDS.includes('N01'),false);
 for(const patch of [{},{directional_strength:1,risk_strength:null},{directional_strength:-1},{risk_strength:0}]){const r=consumeEvidenceV2([{...row,...patch}],{base_interest:70,decision_ts:T});assert.equal(r.adjustment,0);assert.equal(r.final_interest,70);assert.equal(r.threshold_unchanged,70);assert.equal(r.receipts[0].reason,'BLOCK_PAUSED_BY_OWNER');assert.equal(r.receipts[0].block_weight.cap,0);assert.deepEqual(r.block_contributions,{});}
 const other={...row,block_id:'N07',evidence_id:'OTHER',origin_event_id:'OTHER',dependency_group:'OTHER'};const alone=consumeEvidenceV2([other],{base_interest:70,decision_ts:T});const mixed=consumeEvidenceV2([row,other],{base_interest:70,decision_ts:T});assert.equal(alone.adjustment,mixed.adjustment);assert.equal(resolveBlockCap(row,{decision_ts:T}).cap,0);
 for(const direction of ['LONG','SHORT',null]){const r=applySupplementalScoreAdjustment(70,buildSupplementalScoreEvidence({direction,internal_market_context:{decision_ts:T,evidence_v2:{evidence:[row]}}}));assert.equal(r.adjustment,0);assert.equal(r.final_score,70);}
});
test('no native calendar routes are planned, and explicit calendar dispatch cannot spend HTTP',async()=>{
 for(const [symbol,chain] of [['APT','aptos'],['SUI','sui'],['ADA','cardano'],['NEAR','near']])assert.equal(planCandidateEvidenceRoutes({contract:symbol+'-USDT',asset_identity:{chain,asset_kind:'NATIVE',native_asset_id:chain+':mainnet',contract_or_mint:null}}).routes.some(r=>['TOKEN_CALENDAR','TOKEN_SCHEDULE'].includes(r.name)),false);
 let other=0;const forbidden=()=>{throw Error('PAUSED_N01_MUST_NOT_CALL_OR_ADMIT');};const r=await collectEvidenceRouteBlock({routes:[{name:'TOKEN_CALENDAR'},{name:'OTHER'},{name:'TOKEN_SCHEDULE'}],params:{request_admit:forbidden,fetch_impl:forbidden},max_requests:5,collectors:{TOKEN_CALENDAR:forbidden,TOKEN_SCHEDULE:forbidden,OTHER:async()=>{other++;return{status:'CLOSED',evidence:[],network_calls:0};}}});assert.equal(other,1);assert.equal(r.network_calls,0);assert.equal(r.reserved_requests,0);assert.equal(r.results.TOKEN_CALENDAR.status,'BLOCK_PAUSED_BY_OWNER');assert.equal(r.results.TOKEN_SCHEDULE.status,'BLOCK_PAUSED_BY_OWNER');
});
test('cached, externally supplied and formerly rendered N01 rows stay excluded',()=>{
 assert.equal(consumeBlockResultContext({evidence:[row],contract:'APT-USDT',now:T}).facts.length,0);const r=finalizeCandidateBlockCoverage({evidence_result:{evidence:[row]},primary_sources:{EXTERNAL:{evidence:[row],check_completed:true}},decision_ts:T});assert.equal(r.evidence.length,0);assert.equal(r.block_coverage.blocks.N01.checked,false);assert.equal(r.block_coverage.blocks.N01.maximum_score_points,0);
});
test('paused N01 is not a missing requirement or an active denominator',()=>{
 const names=new Set(ACTIVE_BLOCK_IDS.flatMap(id=>[...(BLOCK_SOURCE_REQUIREMENTS[id].all||[]),...(BLOCK_SOURCE_REQUIREMENTS[id].any||[])])),sources=Object.fromEntries([...names].map(name=>[name,{status:'VALID_RESPONSE_NO_EVENT',network_calls:1}]));const a=auditCandidateBlocks({evidence:[row],sources,decision_ts:T});assert.equal(a.coverage_count,13);assert.equal(a.checked_block_count,13);assert.equal(a.all_blocks_checked,true);assert.equal(a.blocks.N01.status,'BLOCK_PAUSED_BY_OWNER');assert.deepEqual(a.blocks.N01.missing_required,[]);assert.equal(a.blocked_required_source_block_count,0);
 const r=enforceManualBlockCoverage({status:'CLOSED',source:'manual',candidates:[{block_coverage:a,canonical:{state:'REJECTED',data_quality:{sufficient:false}}}]});assert.equal(r.status,'CLOSED');assert.equal(r.block_audit.required_block_count,13);assert.match(formatManualRunSummary(r),/13 из 13/);
});
