import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';import {pathToFileURL} from 'node:url';import {DatabaseSync} from 'node:sqlite';
const root=process.env.REPORT2_UNIFIED_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_UNIFIED_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url);
const [{matchGatePublicRestDirection,exactGateTokenBinding,normalizeGateSpotFlow,qualifiedGateSpotComponent},{normalizeTurnoverBaseline},{collectGateFlow},{collectTurnoverBaseline},{installEvidenceSourceStore},{installProviderMinuteLedger}]=await Promise.all(['gate-four-hour-flow.mjs','flow-turnover-baseline.mjs','gate-flow-collector.mjs','flow-turnover-collector.mjs','evidence-source-store.mjs','provider-minute-ledger.mjs'].map(n=>import(new URL(n,root))));
const clone=x=>JSON.parse(JSON.stringify(x)),end=1791640800000,start=end-14400000,historyEnd=Math.floor(start/3600000)*3600000;
const identity={asset_kind:'TOKEN',chain:'ethereum',contract_or_mint:'0x'+'a'.repeat(40)},currencies=[{currency:'TEST',chains:[{name:'ETH',addr:identity.contract_or_mint}]}],spot=[{id:'TEST_USDT',base:'TEST',quote:'USDT',trade_status:'tradable'}];
const rest=Array.from({length:12},(_,i)=>({id:String(i+1),sequence_id:String(i+1),currency_pair:'BTC_USDT',create_time_ms:String(end+i)+'.125',price:'1.50',amount:'2',side:i%2?'buy':'sell'}));
const messages=rest.map(r=>({channel:'spot.trades',event:'update',result:{...r,id:String(10000+Number(r.id)),id_market:r.id,stock:'BTC',money:'USDT',trade_mode:0,range:r.id+'-'+r.id}}));
const proof={...matchGatePublicRestDirection({messages,rest,pair:'BTC_USDT'}),reference_id:'CONTROLLED_TEST_ONLY'};
test('Gate pairs market IDs and both sides without treating global IDs as market IDs',()=>{assert.equal(proof.verified,true);assert.equal(proof.matched_count,12);const x=clone(rest);x[0].side='buy';assert.equal(matchGatePublicRestDirection({messages,rest:x,pair:'BTC_USDT'}).reason,'SAME_TRADE_DIRECTION_OR_FIELDS_MISMATCH');});
test('Gate rejects ambiguous, missing, aggregated and foreign public proof',()=>{for(const mutate of [x=>x.push(x[0]),x=>x.splice(0,4),x=>x.forEach(r=>r.side='sell')]){const x=clone(rest);mutate(x);assert.equal(matchGatePublicRestDirection({messages,rest:x,pair:'BTC_USDT'}).verified,false);}for(const field of ['money','stock','range']){const m=clone(messages);m.forEach(r=>r.result[field]='FOREIGN');assert.equal(matchGatePublicRestDirection({messages:m,rest,pair:'BTC_USDT'}).verified,false);}});
test('Gate identity requires exact chain, address, unique tradable USDT pair',()=>{const p={contract:'TEST-USDT',identity,currencies,spot};assert.equal(exactGateTokenBinding(p),true);for(const patch of [{identity:{...identity,chain:'bsc'}},{identity:{...identity,asset_kind:'NATIVE'}},{spot:[...spot,...spot]},{currencies:[{...currencies[0],trade_disabled:true}]},{currencies:[{...currencies[0],chains:[{name:'ETH',addr:'0x'+'b'.repeat(40)}]}]}])assert.equal(exactGateTokenBinding({...p,...patch}),false);});
const gateCandles=Array.from({length:240},(_,i)=>[String((start+i*60000)/1000),'2','1','1','1','1','2','true']);
const gateTrades=Array.from({length:240},(_,i)=>({id:String(240-i),currency_pair:'TEST_USDT',create_time_ms:String(start+(239-i)*60000+1000)+'.001',price:'1',amount:'2',side:i%2?'buy':'sell'}));
const gp={contract:'TEST-USDT',identity,currencies,spot,pages:[gateTrades],candles:gateCandles,window_end_ts:end,observed_ts:end+1000,direction_reference:proof};
test('Gate full native grid reconciles both quote and base without adding score',()=>{const f=normalizeGateSpotFlow(gp);assert.equal(f.check_completed,true,JSON.stringify(f));assert.equal(f.buy_quote,240);assert.equal(f.sell_quote,240);assert.equal(qualifiedGateSpotComponent(f,proof),true);assert.equal(f.score_contribution,0);assert.equal(f.raw_trade_counter_independently_verified,false);assert.equal(f.recent_windows.length,2);});
test('Gate missing minutes, volume mismatch, unified quote and unproven side fail closed',()=>{const wrong=clone(gateTrades);wrong[0].amount='3';const foreign=clone(gateTrades);foreign[0].trade_quote='USDC';for(const patch of [{candles:gateCandles.slice(1)},{pages:[wrong]},{pages:[foreign]},{direction_reference:{...proof,verified:false}}])assert.equal(normalizeGateSpotFlow({...gp,...patch}).check_completed,false);});
const flow={check_completed:true,exact_asset_binding:true,contract:'TEST-USDT',venue:'BINANCE',market:'SPOT',quote:'USDT',window_start_ts:start,window_end_ts:end,observed_ts:end,buy_quote:400,sell_quote:400};
const hours=Array.from({length:720},(_,i)=>{const t=historyEnd-30*86400000+i*3600000;return[t,'1','1','1','1','100',t+3599999,'100',10,'50','50','0'];});
const hp={contract:'TEST-USDT',venue:'BINANCE',candles:hours,history_end_ts:historyEnd,observed_ts:end+1000,current_flow:flow};
test('prior 30-day turnover forms 180 independent windows, excludes current period and never calibrates holders or outcomes',()=>{const b=normalizeTurnoverBaseline(hp);assert.equal(b.check_completed,true,JSON.stringify(b));assert.equal(b.complete_nonoverlapping_four_hour_samples,180);assert.equal(b.ratio_to_median,2);assert.equal(b.median_four_hour_quote,400);assert.equal(b.individual_trade_size_calibration,false);assert.equal(b.price_impact_calibration,false);assert.equal(b.score_contribution,0);});
test('history gaps duplicates future leakage venue mismatch and invalid native counts are rejected',()=>{const duplicate=clone(hours);duplicate[1]=duplicate[0];const bad=clone(hours);bad[0][8]=0;for(const patch of [{candles:hours.slice(1)},{candles:duplicate},{candles:bad},{history_end_ts:historyEnd+3600000},{venue:'GATE'},{current_flow:{...flow,quote:'USDC'}}])assert.equal(normalizeTurnoverBaseline({...hp,...patch}).check_completed,false);});

const db=()=>{const native=new DatabaseSync(':memory:');return{prepare(sql){const st=native.prepare(sql);return{bind(...p){this.p=Object.fromEntries(p.map((v,i)=>[String(i+1),v]));return this;},async first(){return st.get(this.p||{});},async all(){return{results:st.all(this.p||{})};},async run(){return st.run(this.p||{});}};},async batch(ss){native.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());native.exec('COMMIT');return r;}catch(e){native.exec('ROLLBACK');throw e;}},close(){native.close();}};};

const params=d=>({db:d,contract:'TEST-USDT',asset_identity:identity,identity_method:'HTX_OFFICIAL_CURRENCY_CHAIN_ADDRESS',run_id:'LARGE_TEST',now:end+1000,clock:()=>end+1000,request_admit:()=>({allowed:true}),source_health_admit:()=>({allowed:true})});
test('Gate cold/cache calls keep actual SQL roles and clocks; exhausted cap never sends HTTP',async()=>{const d=db();await installEvidenceSourceStore(d);await installProviderMinuteLedger(d);let calls=0;const p={...params(d),fetch_impl:async url=>{calls++;return new Response(JSON.stringify(url.endsWith('/currencies')?currencies:url.endsWith('/currency_pairs')?spot:url.includes('candlesticks')?gateCandles:gateTrades));}};const r=await collectGateFlow(p);assert.equal(r.check_completed,true,r.reason||r.status);assert.equal(calls,4);assert.equal(r.network_calls,4);const cache=await collectGateFlow({...p,run_id:'LARGE_TEST_CACHE'});assert.equal(cache.check_completed,true);assert.equal(calls,4);assert.equal(cache.components[0].observed_ts,end+1000);d.close();const denied=db();await installEvidenceSourceStore(denied);await installProviderMinuteLedger(denied);await denied.prepare('INSERT INTO report2_evidence_source_daily VALUES(?1,?2,8,NULL,?3)').bind('GATE_ASSET_REFERENCE','2026-10-10',end).run();const x=await collectGateFlow({...params(denied),fetch_impl:async()=>{throw Error('UNEXPECTED_HTTP');}});assert.equal(x.network_calls,0);assert.equal(x.check_completed,false);denied.close();});
test('turnover uses existing role and one HTTP; cache preserves original history clock and cap denies fresh request',async()=>{const d=db();await installEvidenceSourceStore(d);await installProviderMinuteLedger(d);let calls=0;const p={...params(d),fetch_impl:async()=>{calls++;return new Response(JSON.stringify(hours));}};const r=await collectTurnoverBaseline(p,flow);assert.equal(r.check_completed,true,r.reason||r.status);assert.equal(calls,1);const cache=await collectTurnoverBaseline({...p,run_id:'LARGE_TEST_CACHE',now:end+2000,clock:()=>end+2000},{...flow,observed_ts:end+2000});assert.equal(cache.check_completed,true,cache.reason);assert.equal(cache.observed_ts,end+1000);assert.equal(calls,1);const row=await d.prepare('SELECT source,attempts FROM report2_evidence_source_daily').first();assert.equal(row.source,'N05_OFFICIAL_FLOW:BINANCE');assert.equal(row.attempts,1);d.close();});
