import test from 'node:test';
import assert from 'node:assert/strict';
import {clearHtxTechnicalSnapshots,observeHtxTechnicalSnapshot,buildHtxPrimaryTechnicalReceipt} from '../files/src/htx-technical-structure.mjs';
const now=1791149000000,contract='哈基米-USDT',end=Math.floor(now/60000)*60000;
function input(){
 clearHtxTechnicalSnapshots();
 observeHtxTechnicalSnapshot({status:'ok',ts:now,ch:`market.${contract}.kline.1min`,data:Array.from({length:20},(_,i)=>({id:(end-20*60000+i*60000)/1000,open:10,high:11,low:9,close:10}))},`https://api.hbdm.com/linear-swap-ex/market/history/kline?contract_code=${encodeURIComponent(contract)}&period=1min`,now);
 const p={usable:true,coverage:'closed',exact_1m_bars:true,expected_1m_bars:15,received_1m_bars:15,window_start_ts:end-900000,window_end_ts:end,open:10,high:11,low:9,close:10};
 return {contract,now,futures:{execution_status:'FULFILLED',data:{contract,health:{info:true,depth:true},contract_info:{contract_code:contract,contract_status:1,contract_size:1},bbo:{best_bid:9.99,best_ask:10.01},liquidity:{depth_timestamp:new Date(now-1000).toISOString()}}},trajectory:{execution_status:'FULFILLED',data:{contract,contract_info:{contract_code:contract},health:{info:true,price_1m:true},provider_source_ts:end,windows:{'15m':{synchronized_window_start_ts:end-900000,synchronized_window_end_ts:end,price:p}}}},reference_price:{status:'CLOSED',type:'MID_OBSERVATION',contract,venue:'HTX',value:10,source_ts:now-1000,received_ts:now},route_state:'REJECTED'};
}
test('same Unicode crypto future has useful primary receipt only with actual healthy snapshot and exact closed trajectory',()=>{const r=buildHtxPrimaryTechnicalReceipt(input());assert.equal(r.check_completed,true);assert.equal(r.evidence[0].htx_contract,contract);assert.equal(r.network_calls,0);assert.equal(r.receipts[0].entry_authorized_by_context,false);assert.equal(r.receipts[0].signed_raw_24h_verified,false);});
test('fulfilled HTTP wrappers and a price alone never close the primary pipeline',()=>{const x=input();x.futures.data.health={};x.trajectory.data.health={};assert.equal(buildHtxPrimaryTechnicalReceipt(x).check_completed,false);});
test('neutral rolling price range alone cannot replace primary closed-candle trajectory',()=>{const x=input();clearHtxTechnicalSnapshots();observeHtxTechnicalSnapshot({status:'ok',ts:now,ticks:[{contract_code:contract,business_type:'swap',trade_partition:'USDT',ts:now,low:9,high:11,open:10,close:10}]},'https://api.hbdm.com/linear-swap-ex/market/detail/batch_merged',now);const r=buildHtxPrimaryTechnicalReceipt(x);assert.equal(r.check_completed,false);assert.ok(r.receipts[0].failures.includes('VALIDATED_CLOSED_CANDLE_CONTEXT_REQUIRED'));});
test('missing/stale/foreign/impossible/partial-price components remain unaccepted',()=>{
 for(const change of [x=>x.futures.execution_status='REJECTED',x=>x.trajectory.data.contract='BTC-USDT',x=>x.reference_price.source_ts=now-180001,x=>x.reference_price.source_ts=now+1,x=>x.reference_price.venue='OTHER',x=>x.reference_price.value=20,x=>x.futures.data.contract_info.contract_status=0,x=>x.trajectory.data.health.price_1m=false,x=>x.trajectory.data.provider_source_ts=now-180001,x=>x.trajectory.data.windows['15m'].price.exact_1m_bars=false,x=>x.trajectory.data.windows['15m'].price.received_1m_bars=14,x=>x.trajectory.data.windows['15m'].price.close=12,x=>x.trajectory.data.windows['15m'].price.window_end_ts=end-60000]){const x=input();change(x);assert.equal(buildHtxPrimaryTechnicalReceipt(x).check_completed,false);}
});
test('owner-deferred signed raw24h stays independent from real price trajectory and never becomes verified',()=>{const x=input();x.trajectory.data.coverage={flow_24h:'not_closed'};x.futures.data.order_flow={usable:false,cvd_delta_reliable:false};const r=buildHtxPrimaryTechnicalReceipt(x);assert.equal(r.check_completed,true);assert.equal(r.receipts[0].signed_raw_24h_verified,false);assert.equal(r.entry_rules_changed,false);});
