import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs';import {pathToFileURL} from 'node:url';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'current-generation/files'),load=n=>import(pathToFileURL(root+'/src/'+n));
const [{createCombinedLiquidationService,acquisitionHasFreshLevels},{buildNativeWalletRouting},{bindNativeAcquisition},{createFuturesCoverageDatabase,applyFuturesCoverageChecks,runtimeLiquidationCollectionAdmission,WEEK},{seal}]=await Promise.all([load('liquidation-extension/combined-runner-service.mjs'),load('liquidation-extension/native-wallet-routing.mjs'),load('liquidation-extension/runtime-bridge.mjs'),load('liquidation-futures-coverage.mjs'),load('liquidation-extension/core.mjs')]);
const T=Date.parse('2026-10-08T02:24:00Z'),old='0x'+'1'.repeat(40),fresh='0x'+'2'.repeat(40),sha='a'.repeat(64);
const state=(time,{far=false}={})=>({time,assetPositions:[{position:{coin:'NEAR',szi:far?'-10':'10',positionValue:'50',liquidationPx:far?'15':'4',leverage:{type:'cross',value:2}}}]});
const priorAccount={address:old,state:state(T-1000),http_receipt:{http_status:200,received_ts:T-1000,sha256:sha}},routing=buildNativeWalletRouting({accounts:[priorAccount],run_id:'CONTROLLED:prior',now:T-1000});
const universe={status:'CLOSED',observed_ts:T-2000,contracts:[{family:'linear_swap',contract_code:'NEAR-USDT',asset_symbol:'NEAR'}],assets:[{symbol:'NEAR',asset_analysis_contract:'NEAR-USDT',contracts:[{family:'linear_swap',contract_code:'NEAR-USDT'}]}]};
function coverage(status='NO_REAL_NUMERIC_LEVELS'){return applyFuturesCoverageChecks(createFuturesCoverageDatabase({universe,universe_sha256:sha,now:T-2000}),[{contract:'NEAR-USDT',source_id:'HYPERLIQUID_NATIVE',status,source_proof_sha256:sha,now:T-1500}]);}
function fixture({hint=true,cap=5,now=T}={}){const calls=[],saved=[];let current=hint?routing:null;const s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,candidate_slots:1,max_http_per_run:5,clock:()=>now,native_wallet_routing:current,on_native_accounts:async p=>{current=buildNativeWalletRouting({previous:current,...p})||current;saved.push(current);},provider_admit:async()=>({allowed:true,new_reservation:true}),fetch_impl:async(url,init)=>{const q=init?.body?JSON.parse(init.body):null;calls.push(q||String(url));if(q?.type==='clearinghouseState')return new Response(JSON.stringify(state(now,{far:q.user===old})));if(q?.type==='metaAndAssetCtxs')throw Error('EXACT_STRUCTURAL_ROUTE_MUST_NOT_SPEND_A_CATALOG_REQUEST');return new Response(JSON.stringify({coin:'NEAR',positions:[{address:fresh,size:10,liq_price:4}]}));}});const admission=runtimeLiquidationCollectionAdmission(coverage(),{contract:'NEAR-USDT',now});return{s,calls,saved,admission,current:()=>current,collect:()=>s.collect({contract:'NEAR-USDT',native_symbol:'NEAR',run_id:'CONTROLLED:search:'+now,deep_started_ts:now,max_http_for_candidate:cap,allowed_source_ids:admission.source_ids,structural_market_source_ids:admission.structural_market_source_ids})};}
test('a supported empty weekly sample permits new account discovery without claiming level coverage',()=>{const a=runtimeLiquidationCollectionAdmission(coverage(),{contract:'NEAR-USDT',now:T});assert.equal(a.eligible,true);assert.deepEqual(a.source_ids,['HYPERLIQUID_NATIVE']);assert.deepEqual(a.structural_market_source_ids,['HYPERLIQUID_NATIVE']);assert.deepEqual(a.proven_level_source_ids,[]);assert.equal(a.fresh_live_levels_confirmed,false);assert.equal(a.receipt_only_context_score_eligible,false);for(const status of ['EXACT_SOURCE_MARKET_UNSUPPORTED','ACCESS_BLOCKED','SOURCE_ERROR','QUOTA_DEFERRED'])assert.equal(runtimeLiquidationCollectionAdmission(coverage(status),{contract:'NEAR-USDT',now:T}).eligible,false);assert.equal(runtimeLiquidationCollectionAdmission(coverage(),{contract:'NEAR-USDT',now:T+WEEK}).eligible,false);});
test('an irrelevant freshly reread hint cannot stop discovery while the original source cap has capacity',async()=>{const f=fixture(),raw=await f.collect();assert.ok(raw);assert.equal(f.calls.length,3);assert.equal(f.calls[0].user,old);assert.equal(f.calls[2].user,fresh);assert.ok(f.s.summary().primary.records.some(r=>r.status==='HINT_ONLY_IRRELEVANT_NATIVE_LEVELS_CONTINUE_SEARCH'));assert.ok(f.s.summary().shared_budget.actual_http<=5);const b=bindNativeAcquisition(raw,{contract:'NEAR-USDT',run_id:raw.run_id,snapshot_id:'CONTROLLED:new',observed_ts:T,direction:null});assert.equal(b.below[0].native_price,4);assert.equal(b.above.length,0);assert.equal(b.source_ts,T);assert.equal(acquisitionHasFreshLevels(raw,{contract:'NEAR-USDT',run_id:raw.run_id,observed_ts:T}),true);});
test('when the hint exhausts useful capacity its invalidated coin capability cannot starve the next independent search',async()=>{const first=fixture({cap:2});assert.equal(await first.collect(),null);assert.equal(first.calls.length,1);assert.equal(first.current().accounts.length,0);const second=fixture({hint:false,cap:2,now:T+60000}),raw=await second.collect();assert.ok(raw);assert.equal(second.calls.length,2);assert.equal(second.calls[1].user,fresh);assert.equal(raw.accounts[0].state.time,T+60000);assert.equal(raw.provenance.raw_model_prices_used,false);assert.equal(raw.provenance.hyperliquid_market_context,null);});
test('same original source clock does not make an irrelevant native threshold useful role evidence',()=>{const p=seal({schema:'NATIVE_LIQUIDATION_ACQUISITION_V1',contract:'NEAR-USDT',native_symbol:'NEAR',run_id:'CONTROLLED:far',acquisition_id:'CONTROLLED:far',collection_started_ts:T,collection_completed_ts:T,mode:'SHADOW_ONLY',accounts:[{address:old,state:state(T,{far:true}),http_receipt:{http_status:200,received_ts:T,sha256:sha}}],provenance:null});const {fingerprint,...body}=p;const raw={...body,acquisition_fingerprint:fingerprint};assert.equal(bindNativeAcquisition(raw,{contract:'NEAR-USDT',run_id:raw.run_id,snapshot_id:'CONTROLLED:far',observed_ts:T,direction:null}).above[0].native_price,15);assert.equal(acquisitionHasFreshLevels(raw,{contract:'NEAR-USDT',run_id:raw.run_id,observed_ts:T}),false);});
test.after(()=>{fs.mkdirSync('audit-output',{recursive:true});fs.writeFileSync('audit-output/native-relevant-search-proof.json',JSON.stringify({schema:'NATIVE_RELEVANT_SEARCH_CONTROL_V1',control_clock:T,controlled_positions_not_actual_market_levels:true,sourceHTTP:0,D1:0,Telegram:0,original_0524_source_not_refreshed:true,native_http_cap:5,old_levels_promoted:false,fresh_SENT:false,actual_ENTRY:false,full_project_complete:false},null,2)+'\n');});
