import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'runtime'),load=n=>import(pathToFileURL(path.join(root,'src',n)));
const [{createCombinedLiquidationService,classifyOperationalSourceOutcome},{createDydxRuntimeCollector,verifyDydxSourceState},{decodeDydxPinnedSnapshot,calculateDydxConditionalLevels},{buildLiquidationSourceAcquisitionAudit}]=await Promise.all([load('liquidation-extension/combined-runner-service.mjs'),load('liquidation-extension/dydx-runtime-collector.mjs'),load('liquidation-extension/dydx-pinned-conditional-levels.mjs'),load('liquidation-source-acquisition-audit.mjs')]);
const bytes=fs.readFileSync('checkpoints/source-inputs/dydx-native-dense-37625020734.json.gz'),raw=JSON.parse(gunzipSync(bytes)),T=Math.max(...raw.raw.map(r=>r.receipt.received_ts)),snapshot=decodeDydxPinnedSnapshot({raw,now:T}),universe=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'))),assets=new Set(universe.assets.map(a=>a.symbol)),covered=new Set(calculateDydxConditionalLevels(snapshot,{crypto_assets:assets}).levels.map(l=>l.asset)),selected=[...assets].filter(a=>!covered.has(a)).sort().slice(0,2).map(a=>a+'-USDT'),run='CONTROLLED_NATIVE_EMPTY_HEALTH';
function transport(calls){return async(url,init)=>{assert.equal(String(url),'https://dydx-rpc.publicnode.com/');const q=JSON.parse(init.body);calls.push(q);return new Response((q.method==='status'?raw.raw[0]:q.method==='abci_query'?raw.raw[1]:raw.raw[2]).raw_body_utf8);};}
test('retained complete empty selected sample is healthy transport but zero role evidence, and the second asset reuses exact original clocks with zero HTTP',async()=>{
 const calls=[],updates=[],roles=[],grants=[];const service=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,dydx_enabled:true,dydx_automatic_discovery_enabled:true,dydx_crypto_assets:assets,candidate_slots:2,max_http_per_run:5,clock:()=>T,fetch_impl:transport(calls),provider_admit:async r=>{grants.push(r);return{allowed:true,new_reservation:true};},source_weight_store:{load:async()=>[],record:async r=>{updates.push(r);return{recorded:true};},recordRole:async r=>{roles.push(r);return{recorded:true};}}});
 for(const contract of selected)assert.equal(await service.collect({contract,native_symbol:contract.replace(/-USDT$/,''),run_id:run,deep_started_ts:T,max_http_for_candidate:5,allowed_source_ids:['DYDX_PINNED_NATIVE'],dydx_position_batch_contracts:selected}),null);
 const summary=service.summary();assert.equal(calls.length,3);assert.equal(grants.length,1);assert.deepEqual(summary.routed.map(r=>r.source_outcome.attempted_http_count),[3,0]);assert.equal(summary.shared_budget.actual_http,3);assert.equal(summary.shared_budget.reserved_http,3);
 for(const r of summary.routed){assert.equal(r.status,'DYDX_NO_ELIGIBLE_SAMPLE_LEVEL');assert.equal(r.source_outcome.operational_success,true);assert.equal(r.source_outcome.transport_status,'CLOSED');assert.equal(r.source_outcome.schema_status,'CLOSED');assert.equal(r.source_outcome.coverage_status,'EMPTY_BOUNDED_SAMPLE');assert.equal(r.source_outcome.role_usable,false);assert.equal(r.usable,false);assert.equal(r.position_proof.source_ts,snapshot.source_ts);assert.equal(r.position_proof.height,snapshot.height);assert.equal(r.position_proof.position_search.complete_accounts_read,200);assert.equal(r.position_proof.position_search.full_market_census,false);assert.equal(verifyDydxSourceState(r.position_proof,{contract:r.contract,run_id:run,now:T}),true);}
 assert.ok(updates.every(r=>r.usable===true));assert.ok(roles.every(r=>r.role_usable===false));assert.equal(roles.length,2);
 const audit=buildLiquidationSourceAcquisitionAudit({summary,run_id:run,candidates:selected,evaluated_ts:T});assert.equal(audit.routes.length,2);assert.deepEqual(audit.routes.map(r=>r.source_outcome.actual_http),[3,0]);assert.deepEqual(audit.routes.map(r=>r.position_proof.receipt_sha256),[snapshot.receipts.map(r=>r.sha256),snapshot.receipts.map(r=>r.sha256)]);assert.equal(audit.network_calls,0);assert.equal(audit.db_calls,0);assert.equal(audit.entry_authorized,false);assert.ok(Buffer.byteLength(JSON.stringify(audit))<=16384);
 fs.writeFileSync('audit-output/native-empty-source-health-proof.json',JSON.stringify({schema:'NATIVE_EMPTY_SOURCE_HEALTH_RETAINED_PROOF_V1',source_cloud_run:37625020734,source_gzip_sha256:createHash('sha256').update(bytes).digest('hex'),scope:'CONTROLLED_TRANSPORT_AT_ORIGINAL_CLOCK_NOT_FRESH_PRODUCTION_READ',audit,availability_updates:updates,role_updates:roles,sourceHTTP:0,D1:0,MAIN:0,Telegram:0,new_fresh_SENT:false},null,2)+'\n');
});
test('bare status, a forged or serialized proof, changed proof, wrong identity and stale clocks cannot close operational source state',async()=>{
 const calls=[],collect=createDydxRuntimeCollector({clock:()=>T,crypto_assets:assets,automatic_discovery_enabled:true,fetch_impl:transport(calls)}),result=await collect({contract:selected[0],run_id:run,position_batch_contracts:selected}),state=result.source_state;
 assert.equal(verifyDydxSourceState(state,{now:T}),true);assert.equal(classifyOperationalSourceOutcome({status:result.status,source_state:state,actual_http:3,now:T}).operational_success,true);
 for(const proof of [null,JSON.parse(JSON.stringify(state)),{source_clock_closed:true,native_snapshot_verified:true}])assert.equal(classifyOperationalSourceOutcome({status:result.status,source_state:proof,now:T}).operational_success,false);
 assert.equal(verifyDydxSourceState(state,{contract:selected[1],now:T}),false);assert.equal(verifyDydxSourceState(state,{run_id:'OTHER',now:T}),false);assert.equal(verifyDydxSourceState(state,{now:state.source_ts+120001}),false);assert.equal(verifyDydxSourceState(state,{now:state.observed_ts-1}),false);state.source_ts++;assert.equal(verifyDydxSourceState(state,{now:T}),false);
});
test('HTTP, schema and quota errors retain their actual failure and create no verified source state',async()=>{
 const collect=createDydxRuntimeCollector({clock:()=>T,crypto_assets:assets,automatic_discovery_enabled:true,fetch_impl:async()=>new Response('{"error":"denied"}',{status:403})}),r=await collect({contract:selected[0],run_id:'DENIED',position_batch_contracts:selected});assert.equal(r.status,'DYDX_NATIVE_NOT_CLOSED');assert.equal(r.requests,1);assert.equal(r.source_state,undefined);assert.equal(classifyOperationalSourceOutcome({status:r.status,now:T}).operational_success,false);
 assert.equal(classifyOperationalSourceOutcome({status:'HTTP_429',actual_http:1,now:T}).failure_origin,'PROVIDER_QUOTA');
});
test('artifact audit bounds run, asset and original proof fields and omits arbitrary raw state',()=>{
 const summary={routed:[{contract:selected[0],run_id:run,lane:'DYDX_PINNED_NATIVE',position_proof:{secret:'DO_NOT_EXPORT',payload:{secret:'DO_NOT_EXPORT'}}},{contract:selected[0],run_id:'OLD',lane:'DYDX_PINNED_NATIVE'}],shared_budget:{reserved_http:3,actual_http:3},total_http_cap:5};
 const a=buildLiquidationSourceAcquisitionAudit({summary,run_id:run,candidates:selected,evaluated_ts:T});assert.equal(a.routes.length,1);assert.ok(!JSON.stringify(a).includes('DO_NOT_EXPORT'));assert.equal(buildLiquidationSourceAcquisitionAudit({summary,run_id:run,candidates:[...selected,selected[0]],evaluated_ts:T}),null);assert.equal(buildLiquidationSourceAcquisitionAudit({summary,run_id:run,candidates:['FOREIGN-USD'],evaluated_ts:T}),null);
});
