import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {normalizeSolana,normalizeDefiLlama,normalizeCoinbase} from '../files/src/supplemental-candidate-context.mjs';
import {collectChainSupplyEvidence} from '../files/src/chain-supply-evidence.mjs';
import {decodeFinalizedChainEvent,collectFinalizedChainEvents,TRANSFER_TOPIC,AAVE_TOPIC,AAVE_POOL} from '../files/src/finalized-chain-events.mjs';
import {rotateEvidenceRoleRoutes,EVIDENCE_ROUTE_PRIORITY,collectEvidenceRouteBlock} from '../files/src/candidate-evidence-v2-runtime.mjs';
import {loadVenueCatalog} from '../files/src/cross-exchange-risk-context.mjs';
import {collectSupplementalCandidateContext} from '../files/src/supplemental-candidate-context.mjs';
import {consumeEvidenceV2} from '../files/src/evidence-v2.mjs';
import {compileOfficialSourceRegistry,mergeOfficialAndConfiguredRegistries} from '../files/src/official-source-registry.mjs';
import fs from 'node:fs';
const NOW=Date.parse('2026-09-30T08:00:00Z'),asset='0x0000000000000000000000000000000000000001',identity={chain:'ethereum',contract_or_mint:asset},mint='JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',word=x=>'0x'+BigInt(x).toString(16).padStart(64,'0'),hash='0x'+'1'.repeat(64),block={hash,number:'0x100',timestamp:'0x'+Math.floor((NOW-60000)/1000).toString(16)},log={address:asset,removed:false,transactionHash:hash,blockHash:hash,blockNumber:'0x100',logIndex:'0x0',topics:[TRANSFER_TOPIC,word(0),word(2)],data:word(1000000000000000000000001n)};
function db(){const sqlite=new DatabaseSync(':memory:');return{sqlite,prepare(sql){return{args:[],bind(...a){this.args=a;return this;},async run(){return sqlite.prepare(sql).run(...this.args);},async first(){return sqlite.prepare(sql).get(...this.args)||null;},async all(){return{results:sqlite.prepare(sql).all(...this.args)};}};},async batch(rows){return Promise.all(rows.map(r=>r.run()));}};}
test('finalized event caches preserve exact HTX market across shared token aliases',async()=>{
 const database=db();let calls=0;const p={db:database,asset_identity:identity,run_id:'CACHE_SCOPE',now:NOW,request_admit:()=>({allowed:true}),fetch_impl:async(u,i)=>{calls++;const b=JSON.parse(i.body);return new Response(JSON.stringify(Array.isArray(b)?[{id:1,result:'0x1'},{id:2,result:block}]:{id:b.id,result:b.method==='eth_getLogs'?[log]:block}));}};
 const a=await collectFinalizedChainEvents({...p,contract:'ABC-USDT'}),b=await collectFinalizedChainEvents({...p,contract:'OTHER-USDT'}),again=await collectFinalizedChainEvents({...p,contract:'ABC-USDT'});
 assert.equal(a.evidence[0].htx_contract,'ABC-USDT');assert.equal(b.evidence[0].htx_contract,'OTHER-USDT');assert.equal(again.evidence[0].htx_contract,'ABC-USDT');assert.equal(again.network_calls,0);assert.equal(calls,6);database.sqlite.close();
});
test('all eligible roles reach first place over distinct report rotations',()=>{const routes=['CHAIN','OFFICIAL','SNAPSHOT','SOURCIFY','DERIBIT'].map(name=>({name})),seen=new Set();for(let i=0;i<100;i++){const rotated=rotateEvidenceRoleRoutes(routes,'REPORT:'+i);assert.deepEqual(new Set(rotated.map(r=>r.name)),new Set(routes.map(r=>r.name)));seen.add(rotated[0].name);}assert.equal(seen.size,5);});
test('useful primary roles get more scheduling opportunities without removing complementary routes',()=>{
 const routes=Object.keys(EVIDENCE_ROUTE_PRIORITY).map(name=>({name})),counts={};
 for(let i=0;i<4096;i++){const ordered=rotateEvidenceRoleRoutes(routes,`UTILITY:${i}`);assert.equal(ordered.length,routes.length);assert.equal(new Set(ordered.map(r=>r.name)).size,routes.length);counts[ordered[0].name]=(counts[ordered[0].name]||0)+1;}
 assert.ok(counts.LARGE_TRADES>counts.DERIBIT*2);assert.ok(counts.OFFICIAL>counts.GDELT*2);assert.ok(counts.CHAIN>counts.SOURCIFY*1.5);
 assert.deepEqual(rotateEvidenceRoleRoutes([], 'EMPTY'),[]);assert.deepEqual(rotateEvidenceRoleRoutes([{name:'CHAIN'}],'ONLY'),[{name:'CHAIN'}]);
});
test('quota-exhausted primary does not block the next route or cached complements',async()=>{
 const called=[];let http=0;
 const result=await collectEvidenceRouteBlock({routes:[{name:'PRIMARY'},{name:'RESERVE'},{name:'CACHE'}],max_requests:1,params:{request_admit:()=>({allowed:true}),fetch_impl:async()=>{http++;return new Response('{}');}},collectors:{
  PRIMARY:async p=>{called.push('PRIMARY');p.request_admit({attempts:1});return{status:'PROVIDER_QUOTA_EXHAUSTED',admission:{allowed:false},evidence:[]};},
  RESERVE:async p=>{called.push('RESERVE');assert.equal(p.request_admit({attempts:1}).allowed,true);await p.fetch_impl('https://synthetic.invalid');return{status:'CLOSED',evidence:[]};},
  CACHE:async()=>{called.push('CACHE');return{status:'CLOSED',cache_status:'HIT',evidence:[]};},
 }});
 assert.deepEqual(called,['PRIMARY','RESERVE','CACHE']);assert.equal(http,1);assert.equal(result.network_calls,1);assert.equal(result.reserved_requests,1);
});
test('Solana excludes failed and future signatures and cannot compare a saturated short sample',()=>{const out=normalizeSolana({result:[...Array(98).fill({err:null,blockTime:NOW/1000-10}),{err:{InstructionError:1},blockTime:NOW/1000-20},{err:null,blockTime:NOW/1000+1}]},{contract_or_mint:mint},NOW);assert.equal(out.recent_signature_count_1h,98);assert.equal(out.source_ts,NOW-10000);assert.equal(out.comparable_windows,false);assert.equal(out.coverage_fraction,0);});
test('TVL requires exact token, actual source freshness and a relative seven day baseline',()=>{const payload={address:asset,symbol:'ABC',tvl:[{date:NOW/1000-7*86400,totalLiquidityUSD:100},{date:NOW/1000,totalLiquidityUSD:120}]};const run=p=>normalizeDefiLlama(p,'abc',NOW,{identity,expected_symbol:'ABC'});assert.equal(run(payload).status,'CLOSED');assert.ok(Math.abs(run(payload).tvl_change_7d_pct-20)<1e-10);assert.equal(run({...payload,address:word(2)}).tvl_change_7d_pct,null);assert.equal(run({...payload,tvl:payload.tvl.map(x=>({...x,date:x.date-3*86400}))}).status,'NOT_CLOSED');assert.equal(run({...payload,tvl:[payload.tvl[1]]}).tvl_change_7d_pct,null);});
test('Coinbase self-consistent wrong market cannot satisfy the requested identity',()=>{const product={id:'XYZ-USD',base_currency:'XYZ',quote_currency:'USD'};assert.equal(normalizeCoinbase(product,{price:1},NOW,1,'ABC-USD').status,'NOT_CLOSED');assert.equal(normalizeCoinbase(product,{price:1},NOW,1,'XYZ-USD').status,'CLOSED');});
test('case-only Solana registry conflict is rejected; verified protocol survives empty configured metadata',()=>{const official=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(new URL('../files/official-event-sources.json',import.meta.url))));assert.throws(()=>mergeOfficialAndConfiguredRegistries({official,configured:{JUP:{chain:'solana',contract_or_mint:'j'+mint.slice(1)}}}),/CONFLICT/);assert.equal(mergeOfficialAndConfiguredRegistries({official,configured:{LDO:{official_name:'Lido'}}}).registry.LDO.protocol_slug,'lido');});
test('finalized mint retains exact units and physical event identity without score or target permission',()=>{const row=decodeFinalizedChainEvent({log,mode:'TOKEN_TRANSFER',asset,block,observed_ts:NOW,contract:'ABC-USDT'});assert.equal(row.amount_base_units,'1000000000000000000000001');assert.equal(row.block_id,'N02');assert.equal(row.source_ts,NOW-60000);assert.equal(consumeEvidenceV2([row,row],{base_interest:70,decision_ts:NOW}).adjustment,0);assert.equal(decodeFinalizedChainEvent({log:{...log,removed:true},asset,block,observed_ts:NOW}),null);assert.equal(decodeFinalizedChainEvent({log,asset,block:{...block,hash:word(3)},observed_ts:NOW}),null);});
test('Aave liquidation binds exact borrower and collateral; never authorizes HTX entry',()=>{const credit={...log,address:AAVE_POOL,topics:[AAVE_TOPIC,word(1),word(2),word(3)],data:'0x'+[100n,200n,4n,1n].map(x=>word(x).slice(2)).join('')};const row=decodeFinalizedChainEvent({log:credit,mode:'AAVE_CREDIT',asset,block,observed_ts:NOW,contract:'ABC-USDT'});assert.equal(row.block_id,'N04');assert.equal(row.debt_to_cover_base_units,'100');assert.equal(row.market_kind,'DEFI_CREDIT');assert.equal(row.entry_eligible,false);assert.equal(row.is_htx_price,false);assert.equal(decodeFinalizedChainEvent({log:credit,mode:'AAVE_CREDIT',asset:'0x'+'9'.repeat(40),block,observed_ts:NOW}),null);});
test('Solana supply clock comes from its exact finalized slot, missing clock fails closed',async()=>{for(const clock of [NOW/1000-60,null]){const database=db(),calls=[];const out=await collectChainSupplyEvidence({db:database,asset_identity:{chain:'solana',contract_or_mint:mint},contract:'JUP-USDT',run_id:'R',now:NOW,request_admit:r=>{assert.equal(r.attempts,2);return{allowed:true};},fetch_impl:async(u,i)=>{const b=JSON.parse(i.body);calls.push(b);return new Response(JSON.stringify({id:1,result:b.method==='getTokenSupply'?{context:{slot:123},value:{amount:'100',decimals:6}}:clock}));}});assert.equal(calls.length,2);assert.deepEqual(calls[1].params,[123]);assert.equal(out.evidence[0].source_ts,clock===null?null:clock*1000);assert.equal(out.status,clock===null?'SOURCE_CLOCK_NOT_CLOSED':'CLOSED');database.sqlite.close();}});
test('event acquisition uses bounded finalized logs and exact block clock within three HTTP; invalid logs do not close',async()=>{for(const removed of [false,true]){const database=db();let calls=0;const out=await collectFinalizedChainEvents({db:database,asset_identity:identity,contract:'ABC-USDT',run_id:'R',now:NOW,request_admit:r=>{assert.equal(r.attempts,3);return{allowed:true};},fetch_impl:async(u,i)=>{calls++;const b=JSON.parse(i.body);if(Array.isArray(b))return new Response(JSON.stringify([{id:2,result:block},{id:1,result:'0x1'}]));return new Response(JSON.stringify({id:b.id,result:b.method==='eth_getLogs'?[{...log,removed}]:block}));}});assert.equal(calls,3);assert.equal(out.network_calls,3);assert.equal(out.status,removed?'EVENT_VALIDATION_NOT_CLOSED':'CLOSED');assert.equal(out.evidence.length,removed?0:1);database.sqlite.close();}});

test('CEX partial catalog retains failures across cache reuse and does not call an unavailable venue unsupported',async()=>{const database=db();let calls=0;const fetch_impl=async url=>{calls++;if(url.includes('okx'))return new Response(JSON.stringify({code:'0',data:[{state:'live',instType:'SWAP',instCategory:'1',settleCcy:'USDT',ctValCcy:'SOL',instId:'SOL-USDT-SWAP',ctVal:'1'}]}));return new Response('{}',{status:403});};const fresh=await loadVenueCatalog({db:database,fetch_impl,now:NOW}),cached=await loadVenueCatalog({db:database,fetch_impl,now:NOW+1000});assert.equal(calls,3);assert.equal(cached.network_calls,0);assert.equal(cached.entries.SOL.okx,'SOL-USDT-SWAP');assert.deepEqual(cached.receipts,fresh.receipts);assert.equal(cached.receipts[0].status,'HTTP_403');assert.equal(cached.receipts[0].catalog_complete,false);database.sqlite.close();});
test('Solana pool identity preserves case through real supplemental normalization and failed cached sources do not close',async()=>{const database=db();const pool='So11111111111111111111111111111111111111112';const out=await collectSupplementalCandidateContext({db:database,registry:{JUP:{chain:'solana',contract_or_mint:mint}},contract:'JUP-USDT',run_id:'SEED0',derivatives_venues:2,critical_conflict:false,now:NOW,fetch_impl:async url=>{if(url.includes('dexscreener'))return new Response(JSON.stringify([{chainId:'solana',pairAddress:pool,baseToken:{address:mint},quoteToken:{address:pool}}]));if(url.includes('geckoterminal'))return new Response(JSON.stringify({data:[{relationships:{base_token:{data:{id:'solana_'+mint}}},attributes:{address:pool}}]}));return new Response(JSON.stringify({result:[]}));}});assert.equal(out.lane,'DEX_RISK');assert.equal(out.sources.DEX_SCREENER.pools[0].pool_key,'solana|'+pool);assert.equal(out.sources.GECKOTERMINAL.pools[0].pool_key,'solana|'+pool);database.sqlite.close();});
