import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {runOxArchiveCostProbe,loadOxArchiveReadiness,reserveOxArchiveCredits,createOxArchiveCollector} from '../files/src/oxarchive-cost-probe.mjs';

class DB{
 constructor(){this.probes=new Map();this.ledger=new Map();}
 prepare(sql){const self=this;const statement={
  bind(...a){return{
   async first(){if(sql.includes('report2_oxarchive_cost_probe'))return self.probes.get(a[0])||null;if(sql.includes('report2_oxarchive_credit_ledger'))return self.ledger.get(a[0])||null;return null;},
   async run(){
    if(sql.includes('INSERT INTO report2_oxarchive_cost_probe'))self.probes.set(a[0],{probe_key:a[0],symbol:a[1],requested_ts:a[2],http_status:a[3],response_headers_json:a[4],request_id:a[5],success:a[6],route_cost_closed:a[7],credit_cost:a[8],error_text:a[9]});
    if(sql.includes('INSERT INTO report2_oxarchive_credit_ledger')){const used=[...self.ledger.values()].filter(x=>x.window_start_ts===a[1]).reduce((n,x)=>n+x.credits,0);if(used+a[3]<=a[6])self.ledger.set(a[0],{reservation_id:a[0],window_start_ts:a[1],window_end_ts:a[2],credits:a[3],created_ts:a[4],route:a[5]});}
    return{};
   }
  };},async first(){return null;},async run(){return{};}
 };return statement;}
}

test('probe is impossible without key and spends zero calls',async()=>{const r=await runOxArchiveCostProbe({db:new DB(),symbol:'SOL'});assert.equal(r.network_calls,0);assert.equal(r.reason,'API_KEY_REQUIRED');});
test('one authenticated production-route probe is idempotent and the official 100-row route costs one credit',async()=>{const db=new DB();let calls=0;const fetch_impl=async url=>{calls++;assert.match(String(url),/range_pct=50&buckets=100/);return{ok:true,status:200,headers:new Headers({'x-request-id':'r1'}),json:async()=>({success:true,meta:{request_id:'r1'},data:{levels:[]}})}};const a=await runOxArchiveCostProbe({db,fetch_impl,api_key:'secret',symbol:'SOL'});const b=await runOxArchiveCostProbe({db,fetch_impl,api_key:'secret',symbol:'SOL'});assert.equal(a.status,'AUTH_AND_ROUTE_CLOSED');assert.equal(a.credit_cost,1);assert.equal(a.production_enable_allowed,true);assert.equal(b.status,'ALREADY_PROBED');assert.equal(b.production_enable_allowed,true);assert.equal(calls,1);});
test('configured key enables a 5000-credit ledger without requiring an extra paid cost probe',async()=>{const ready=await loadOxArchiveReadiness({db:new DB(),api_key:'secret'});assert.equal(ready.enabled,true);assert.equal(ready.credit_cost,1);assert.equal(ready.max_monthly_calls,5000);assert.equal(ready.auth_probe_optional,true);});
test('monthly credit ledger is idempotent and fails closed at its exact cap',async()=>{const db=new DB(),now=Date.UTC(2026,8,27);const one=await reserveOxArchiveCredits({db,reservation_id:'a',credit_cost:4999,now});const same=await reserveOxArchiveCredits({db,reservation_id:'a',credit_cost:4999,now});const last=await reserveOxArchiveCredits({db,reservation_id:'b',credit_cost:1,now});const blocked=await reserveOxArchiveCredits({db,reservation_id:'c',credit_cost:1,now});assert.equal(one.allowed,true);assert.equal(same.idempotent,true);assert.equal(last.allowed,true);assert.equal(blocked.reason,'MONTHLY_MODULE_CREDIT_CAP_EXHAUSTED');});
test('collector turns a strict fresh 0xArchive payload into the same scoped liquidation acquisition used by the report block',async()=>{const db=new DB(),base=Date.parse('2026-09-27T20:00:00Z');let tick=0;const payload={success:true,data:{mid_price:100,snapshot_ts:'2026-09-27 19:59:00.000',block_number:123,total_long:1000,total_short:2000,flagged_notional:0,source:'raw',levels:[{price:90,long_notional:500,short_notional:0,long_count:2,short_count:0},{price:110,long_notional:0,short_notional:800,long_count:0,short_count:3}]},meta:{count:2,request_id:'r'}};const fetch_impl=async()=>new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json','x-request-id':'r'}});const collector=createOxArchiveCollector({db,fetch_impl,api_key:'secret',readiness:{enabled:true,credit_cost:1},clock:()=>base+tick++});const result=await collector({contract:'ABC-USDT',native_symbol:'ABC',run_id:'run'});assert.equal(result.schema,'MULTI_LIQUIDATION_ACQUISITION_V1');assert.equal(result.scoped[0].provider,'0xArchive');assert.equal(result.scoped[0].above[0].native_price,110);assert.equal(result.scoped[0].below[0].native_price,90);assert.equal(db.ledger.size,1);});
test('GitHub manual dispatch can execute the optional auth probe while schedule cannot',()=>{const runner=fs.readFileSync(new URL('../files/runner-main.mjs',import.meta.url),'utf8');assert.match(runner,/source!==['"]schedule['"].*REPORT2_OXARCHIVE_COST_PROBE/);assert.doesNotMatch(runner,/source===['"]manual['"].*REPORT2_OXARCHIVE_COST_PROBE/);});
