import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_UNIFIED_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_UNIFIED_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url);
const [{consumeEvidenceV2,PAUSED_BLOCKS,ACTIVE_BLOCK_IDS,evidenceDedupKey},{consumeBlockResultContext,confirmedBlockContextFacts,auditRenderedBlockResults},{canonicalFingerprint,renderCanonicalTelegram},{formatManualReport},{buildSupplementalScoreEvidence,applySupplementalScoreAdjustment},{auditCanonicalBlockDecisionUse},{collectEvidenceRouteBlock,planCandidateEvidenceRoutes}]=await Promise.all(['evidence-v2.mjs','block-result-context.mjs','canonical-publication.mjs','manual-report-formatter.mjs','supplemental-score-evidence.mjs','block-decision-use-audit.mjs','candidate-evidence-v2-runtime.mjs'].map(n=>import(new URL(n,root))));
const saved=JSON.parse(fs.readFileSync(new URL('../../checkpoints/btw-preserved-block-result-input-20261004.json',import.meta.url))).canonical;
test('N01 and N02 are inactive and cannot score either direction or claim the physical root',()=>{
 assert.deepEqual(Object.keys(PAUSED_BLOCKS),['N01','N02']);assert.equal(ACTIVE_BLOCK_IDS.length,13);
 const original=saved.metadata.internal_market_context.evidence_v2.evidence.find(r=>r.block_id==='N02'),T=saved.observed_ts;
 for(const block_id of ['N01','N02'])for(const direction of ['LONG','SHORT',null]){const rows=[{...original,block_id,coverage_fraction:1,reliability:1,directional_strength:1,risk_strength:1}],market={decision_ts:T,evidence_v2:{evidence:rows}};const score=consumeEvidenceV2(rows,{base_interest:70,decision_ts:T});assert.equal(score.adjustment,0);assert.equal(score.final_interest,70);assert.equal(score.receipts[0].block_weight.cap,0);assert.equal(score.receipts[0].reason,'BLOCK_PAUSED_BY_OWNER');assert.equal(applySupplementalScoreAdjustment(70,buildSupplementalScoreEvidence({direction,internal_market_context:market})).final_score,70);}
});
test('sole supply/calendar routes are blocked while a shared source preserves active N03 evidence',async()=>{
 const original=saved.metadata.internal_market_context.evidence_v2.evidence.find(r=>r.block_id==='N02'),active={...original,block_id:'N03',evidence_id:'ACTIVE-N03'};
 const forbidden=()=>{throw Error('PAUSED_ROUTE_MUST_NOT_COLLECT_OR_SPEND_HTTP');};let shared=0;
 const r=await collectEvidenceRouteBlock({routes:[{name:'TOKEN_CALENDAR'},{name:'TOKEN_SCHEDULE'},{name:'COINMETRICS'},{name:'CHAIN_SUPPLY'}],params:{contract:original.htx_contract,request_admit:forbidden,fetch_impl:forbidden},collectors:{TOKEN_CALENDAR:forbidden,TOKEN_SCHEDULE:forbidden,COINMETRICS:forbidden,CHAIN_SUPPLY:async()=>{shared++;return{status:'CLOSED',network_calls:0,evidence:[original,active]};}},max_requests:5});
 assert.equal(shared,1);assert.equal(r.network_calls,0);assert.equal(r.reserved_requests,0);assert.deepEqual(r.results.CHAIN_SUPPLY.evidence.map(x=>x.block_id),['N03']);assert.equal(r.results.CHAIN_SUPPLY.market_binding.status,'CLOSED');assert.equal(r.results.COINMETRICS.status,'BLOCK_PAUSED_BY_OWNER');
 const p=planCandidateEvidenceRoutes({contract:'SOL-USDT',asset_identity:{chain:'solana',asset_kind:'NATIVE',native_asset_id:'solana:mainnet',contract_or_mint:null}});assert.equal(p.routes.some(x=>['TOKEN_CALENDAR','TOKEN_SCHEDULE','COINMETRICS'].includes(x.name)),false);assert.ok(p.routes.some(x=>x.name==='CHAIN_SUPPLY'));
});
test('manual and Telegram exclude paused facts, including previously stored facts, on the same retained snapshot',()=>{
 const c=structuredClone(saved),T=c.observed_ts,contract=c.metadata.contract;c.direction='LONG';c.state='OBSERVE';c.trigger={metric:'price',operator:'>=',value:1,unit:'USDT',timeframe:'5m',expires_ts:T+600000,next_recheck_ts:T+60000,cancel_condition:'price<1'};
 const row=c.metadata.internal_market_context.evidence_v2.evidence.find(r=>r.block_id==='N02');c.metadata.internal_market_context.evidence_v2.evidence.push({...row,block_id:'N01',evidence_id:'PAUSED-N01'});
 const permitted=consumeBlockResultContext({evidence:c.metadata.internal_market_context.evidence_v2.evidence,contract,now:T}).facts;
 c.metadata.supporting_context={facts:[...permitted,...['N01','N02'].map(block_id=>({label:'Запрещённый факт '+block_id,value:'PAUSED-BLOCK-MARKER',block_id,evidence_id:block_id==='N02'?row.evidence_id:'PAUSED-N01',physical_root_key:evidenceDedupKey(row),source_ts:row.source_ts,observed_ts:row.observed_ts}))]};c.analytical_fingerprint=canonicalFingerprint(c);
 const before=JSON.stringify(c),manual=formatManualReport(c);assert.equal(manual.ok,true);
 for(const context_policy of ['ORIGINAL_V5_20261006','ORIGINAL_BRIEF_20261007']){const telegram=renderCanonicalTelegram({canonical:c,lifecycle_event:'OBSERVE',context_policy});assert.equal(telegram.ok,true,telegram.status);assert.doesNotMatch(manual.text,/PAUSED-BLOCK-MARKER|Запрещённый факт|Наблюдение предложения токена/);assert.doesNotMatch(telegram.text,/PAUSED-BLOCK-MARKER|Запрещённый факт|Наблюдение предложения токена/);const audit=auditRenderedBlockResults({canonical:c,manual,telegram});for(const ids of [audit.used_context_block_ids,audit.telegram_used_context_block_ids])assert.equal(ids.some(id=>PAUSED_BLOCKS[id]),false);}
 assert.equal(confirmedBlockContextFacts(c).some(f=>PAUSED_BLOCKS[f.block_id]),false);const use=auditCanonicalBlockDecisionUse(c,{manual});for(const id of ['N01','N02']){assert.equal(use.blocks[id].participating,false);assert.equal(use.blocks[id].participation_status,'BLOCK_PAUSED_BY_OWNER');}assert.equal(use.required_block_count,13);assert.equal(JSON.stringify(c),before);
});
