import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_TEST_RUNTIME;
const moduleURL=root?pathToFileURL(path.resolve(root,'src/pre-analysis-failure-receipt.mjs')):new URL('../files/src/pre-analysis-failure-receipt.mjs',import.meta.url);
const {schedulerReadFailure,enforcePeriodicOwnership}=await import(moduleURL);
const context={generation:'MY_REPORT_2_CURRENT_20260929_CURRENT_CYCLE_V13_20M',head:'211e3eb0df6adc9fa889efc33d787aadfac8a0a9',source_run_id:'37931650060',task_id:'RCHK:493dd8a27079e267c97e2fa638fee498babc3bb4',trigger_only:true,started_ts:1791549690264,failed_ts:1791549692035};
test('exact GRAM failure bindings persist without claiming a market decision',async()=>{
 let output;await assert.rejects(enforcePeriodicOwnership({ownership:{allowed:false,status:'READ_FAILED',owner:null,actor:'GITHUB_ACTIONS',error:'D1_BRIDGE_TIMEOUT'},context,write_result:async v=>{output=v;}}),e=>{assert.equal(e.pre_analysis_failure.artifact_persisted,true);return /:READ_FAILED$/.test(e.message);});
 assert.equal(output.pre_analysis_failure.task_id,context.task_id);assert.equal(output.pre_analysis_failure.source_run_id,'37931650060');assert.equal(output.pre_analysis_failure.read_failure.family,'D1_BRIDGE_TIMEOUT');assert.equal(output.pre_analysis_failure.market_conditions_evaluated,false);assert.equal(output.pre_analysis_failure.task_writes,0);assert.equal(output.pre_analysis_failure.entry_authorized,false);assert.deepEqual(output.candidates,[]);assert.equal(output.status,'NOT_CLOSED');
});
test('native bridge codes and HTTP status stay distinct from an unknown native SQL error',()=>{
 assert.equal(schedulerReadFailure('D1_BRIDGE_FAILURE:UNAUTHORIZED').bridge_code,'UNAUTHORIZED');assert.equal(schedulerReadFailure('D1_BRIDGE_FAILURE:HTTP_503').http_status,503);assert.equal(schedulerReadFailure('D1_BRIDGE_INVALID_JSON_HTTP_502').http_status,502);const secret='D1_BRIDGE_FAILURE:DO_NOT_EXPORT_SECRET';assert.equal(schedulerReadFailure(secret).bridge_code,null);assert.equal(JSON.stringify(schedulerReadFailure(secret)).includes('DO_NOT_EXPORT_SECRET'),false);assert.match(schedulerReadFailure(secret).error_fingerprint,/^[a-f0-9]{64}$/);
});
test('allowed owner proceeds without a diagnostic write',async()=>{let writes=0;await enforcePeriodicOwnership({ownership:{allowed:true,status:'CLOSED',owner:'GITHUB_ACTIONS'},context,write_result:()=>{writes++;}});assert.equal(writes,0);});
test('migration or other owner remains a refusal rather than read-failure evidence',async()=>{for(const ownership of [{allowed:false,status:'MIGRATION_REQUIRED'},{allowed:false,status:'CLOSED',owner:'CLOUDFLARE'}]){let output;await assert.rejects(enforcePeriodicOwnership({ownership,context,write_result:v=>{output=v;}}));assert.equal(output.pre_analysis_failure.read_failure,null);assert.equal(output.pre_analysis_failure.entry_authorized,false);assert.notEqual(output.pre_analysis_failure.reason,'SCHEDULER_OWNER_READ_FAILED');}});
test('artifact-write failure preserves the ownership refusal',async()=>{await assert.rejects(enforcePeriodicOwnership({ownership:{allowed:false,status:'READ_FAILED'},context,write_result:()=>{throw Error('disk unavailable');}}),e=>e.pre_analysis_failure.artifact_persisted===false&&e.message.endsWith(':READ_FAILED'));});
test('unknown identities and arbitrary error strings do not become bound facts',async()=>{let output;await assert.rejects(enforcePeriodicOwnership({ownership:{allowed:false,status:'arbitrary status',error:'SECRET'},context:{task_id:'SECRET',head:'SECRET',source_run_id:'SECRET'},write_result:v=>{output=v;}}));assert.equal(output.pre_analysis_failure.task_id,null);assert.equal(output.pre_analysis_failure.head,null);assert.equal(output.pre_analysis_failure.source_run_id,null);assert.equal(output.pre_analysis_failure.read_failure,null);assert.equal(JSON.stringify(output).includes('SECRET'),false);});
const source=fs.readFileSync(root?path.resolve(root,'runner-main.mjs'):new URL('../files/runner-main.mjs',import.meta.url),'utf8');
const calls=source.match(/await enforcePeriodicOwnership\([^\n]+\);/g)||[];
test('assembled runner captures refusal in both ownership checks before further work',async()=>{
 assert.equal(calls.length,2);for(const call of calls){let writes=0,saved;const run=new (Object.getPrototypeOf(async function(){}).constructor)('ownership','enforcePeriodicOwnership','generation','process','triggerKickTaskId','triggerOnly','started','Date','fs',call);await assert.rejects(run({allowed:false,status:'READ_FAILED',error:'D1_BRIDGE_FAILURE:HTTP_503'},enforcePeriodicOwnership,context.generation,{env:{GITHUB_SHA:context.head,GITHUB_RUN_ID:context.source_run_id}},context.task_id,true,context.started_ts,{now:()=>context.failed_ts},{writeFile:async(file,body)=>{assert.equal(file,'report2-run-result.json');writes++;saved=JSON.parse(body);}}));assert.equal(writes,1);assert.equal(saved.pre_analysis_failure.task_id,context.task_id);assert.equal(saved.pre_analysis_failure.read_failure.http_status,503);}
});
test('both current runner checks allow the real scheduler owner without diagnostic writes',async()=>{for(const call of calls){let writes=0;const run=new (Object.getPrototypeOf(async function(){}).constructor)('ownership','enforcePeriodicOwnership','generation','process','triggerKickTaskId','triggerOnly','started','Date','fs',call);await run({allowed:true,status:'CLOSED',owner:'GITHUB_ACTIONS'},enforcePeriodicOwnership,context.generation,{env:{}},context.task_id,true,context.started_ts,{now:()=>context.failed_ts},{writeFile:()=>{writes++;}});assert.equal(writes,0);}});
