import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_TEST_RUNTIME;
const moduleURL=root?pathToFileURL(path.resolve(root,'src/pre-analysis-failure-receipt.mjs')):new URL('../files/src/pre-analysis-failure-receipt.mjs',import.meta.url);
const {schedulerReadFailure,enforcePeriodicOwnership,summarizeD1AttemptUsage,enforceDailyAnalysisAdmission}=await import(moduleURL);
const context={generation:'MY_REPORT_2_CURRENT_20260929_CURRENT_CYCLE_V13_20M',head:'211e3eb0df6adc9fa889efc33d787aadfac8a0a9',source_run_id:'37931650060',task_id:'RCHK:493dd8a27079e267c97e2fa638fee498babc3bb4',trigger_only:true,started_ts:1791549690264,failed_ts:1791549692035};
test('exact GRAM failure bindings persist without claiming a market decision',async()=>{
 let output;await assert.rejects(enforcePeriodicOwnership({ownership:{allowed:false,status:'READ_FAILED',owner:null,actor:'GITHUB_ACTIONS',error:'D1_BRIDGE_TIMEOUT'},context,write_result:async v=>{output=v;}}),e=>{assert.equal(e.pre_analysis_failure.artifact_persisted,true);return /:READ_FAILED$/.test(e.message);});
 assert.equal(output.pre_analysis_failure.task_id,context.task_id);assert.equal(output.pre_analysis_failure.source_run_id,'37931650060');assert.equal(output.pre_analysis_failure.read_failure.family,'D1_BRIDGE_TIMEOUT');assert.equal(output.pre_analysis_failure.market_conditions_evaluated,false);assert.equal(output.pre_analysis_failure.task_writes,0);assert.equal(output.pre_analysis_failure.entry_authorized,false);assert.deepEqual(output.candidates,[]);assert.equal(output.status,'NOT_CLOSED');
});
test('native bridge codes and HTTP status stay distinct from an unknown native SQL error',()=>{
 assert.equal(schedulerReadFailure('D1_BRIDGE_FAILURE:UNAUTHORIZED').bridge_code,'UNAUTHORIZED');assert.equal(schedulerReadFailure('D1_BRIDGE_FAILURE:HTTP_503').http_status,503);assert.equal(schedulerReadFailure('D1_BRIDGE_INVALID_JSON_HTTP_502').http_status,502);const secret='D1_BRIDGE_FAILURE:DO_NOT_EXPORT_SECRET';assert.equal(schedulerReadFailure(secret).bridge_code,null);assert.equal(JSON.stringify(schedulerReadFailure(secret)).includes('DO_NOT_EXPORT_SECRET'),false);assert.match(schedulerReadFailure(secret).error_fingerprint,/^[a-f0-9]{64}$/);
});
test('allowed owner proceeds without a diagnostic write',async()=>{let writes=0;await enforcePeriodicOwnership({ownership:{allowed:true,status:'CLOSED',owner:'GITHUB_ACTIONS'},context,write_result:()=>{writes++;}});assert.equal(writes,0);});
test('migration or other owner remains a refusal rather than read-failure evidence',async()=>{for(const ownership of [{allowed:false,status:'MIGRATION_REQUIRED'},{allowed:false,status:'CLOSED',owner:'CLOUDFLARE'}]){let output;await assert.rejects(enforcePeriodicOwnership({ownership,context,write_result:v=>{output=v;}}));assert.equal(output.pre_analysis_failure.read_failure,null);assert.equal(output.pre_analysis_failure.entry_authorized,false);assert.notEqual(output.pre_analysis_failure.reason,'SCHEDULER_OWNER_READ_FAILED');}});
test('artifact-write failure preserves the ownership refusal',async()=>{await assert.rejects(enforcePeriodicOwnership({ownership:{allowed:false,status:'READ_FAILED'},context,write_result:()=>{throw Error('disk unavailable');}}),e=>e.pre_analysis_failure.artifact_persisted===false&&e.message.endsWith(':READ_FAILED'));});
test('unknown identities and arbitrary error strings do not become bound facts',async()=>{let output;await assert.rejects(enforcePeriodicOwnership({ownership:{allowed:false,status:'arbitrary status',error:'SECRET'},context:{task_id:'SECRET',head:'SECRET',source_run_id:'SECRET'},write_result:v=>{output=v;}}));assert.equal(output.pre_analysis_failure.task_id,null);assert.equal(output.pre_analysis_failure.head,null);assert.equal(output.pre_analysis_failure.source_run_id,null);assert.equal(output.pre_analysis_failure.read_failure,null);assert.equal(JSON.stringify(output).includes('SECRET'),false);});
const source=fs.readFileSync(root?path.resolve(root,'runner-main.mjs'):new URL('../files/runner-main.mjs',import.meta.url),'utf8');
const calls=source.match(/await enforcePeriodicOwnership\([^\n]+\);/g)||[];
test('assembled runner captures refusal in both ownership checks before further work',async()=>{
 assert.equal(calls.length,2);for(const call of calls){let writes=0,saved;const run=new (Object.getPrototypeOf(async function(){}).constructor)('ownership','enforcePeriodicOwnership','generation','process','triggerKickTaskId','triggerOnly','started','Date','fs','env',call);await assert.rejects(run({allowed:false,status:'READ_FAILED',error:'D1_BRIDGE_FAILURE:HTTP_503'},enforcePeriodicOwnership,context.generation,{env:{GITHUB_SHA:context.head,GITHUB_RUN_ID:context.source_run_id}},context.task_id,true,context.started_ts,{now:()=>context.failed_ts},{writeFile:async(file,body)=>{assert.equal(file,'report2-run-result.json');writes++;saved=JSON.parse(body);}},{DATA_DB:{usageSnapshot:()=>({requests:1,rows_read:0,rows_written:0,unknown_ops:1})}}));assert.equal(writes,1);assert.equal(saved.pre_analysis_failure.task_id,context.task_id);assert.equal(saved.pre_analysis_failure.read_failure.http_status,503);}
});
test('both current runner checks allow the real scheduler owner without diagnostic writes',async()=>{for(const call of calls){let writes=0;const run=new (Object.getPrototypeOf(async function(){}).constructor)('ownership','enforcePeriodicOwnership','generation','process','triggerKickTaskId','triggerOnly','started','Date','fs','env',call);await run({allowed:true,status:'CLOSED',owner:'GITHUB_ACTIONS'},enforcePeriodicOwnership,context.generation,{env:{}},context.task_id,true,context.started_ts,{now:()=>context.failed_ts},{writeFile:()=>{writes++;}},{DATA_DB:{usageSnapshot:()=>({requests:1,rows_read:1,rows_written:0,unknown_ops:0})}});assert.equal(writes,0);}});

test('unknown operation records measured subtotals without inventing total row cost',()=>{
 const r=summarizeD1AttemptUsage({requests:10,rows_read:75,rows_written:4,unknown_ops:1});assert.equal(r.attempted_statements,10);assert.equal(r.measured_rows_read_subtotal,75);assert.equal(r.unknown_operations,1);assert.equal(r.total_rows_read,null);assert.equal(r.total_rows_written,null);assert.equal(r.row_totals_closed,false);
 assert.equal(summarizeD1AttemptUsage({requests:1,rows_read:2,rows_written:0,unknown_ops:0}).total_rows_read,2);
});
test('missing or invalid native counters remain absent rather than guessed',()=>{for(const usage of [null,{}, {requests:1,rows_read:'2',rows_written:0,unknown_ops:0},{requests:1,rows_read:2,rows_written:-1,unknown_ops:0}])assert.equal(summarizeD1AttemptUsage(usage),null);});
test('actual unchanged daily guard preserves unknown usage and emits exact infrastructure refusal',async()=>{
 const {evaluateDailyReservationBudget}=await import('../../runner/d1-preaction-budget-guard.mjs');
 const admission=evaluateDailyReservationBudget({daily:{ok:true,status:'DAY_USAGE_CLOSED',unknown_ops:1,reserved_rows_read:1000,reserved_rows_written:16,unfinished_count:0},nextReservation:{rows_read:54000,rows_written:840}});assert.equal(admission.allowed,false);assert.equal(admission.status,'UNMEASURED_FINALIZED_USAGE');let output;
 await assert.rejects(enforceDailyAnalysisAdmission({admission,context:{...context,source:'schedule',d1_usage:{requests:1,rows_read:1,rows_written:0,unknown_ops:0}},write_result:x=>{output=x;}}),/D1_DAY_PREACTION_BUDGET_BLOCKED:UNMEASURED_FINALIZED_USAGE/);assert.equal(output.pre_analysis_failure.stage,'D1_DAY_PREACTION_ADMISSION');assert.equal(output.pre_analysis_failure.daily.unknown_operations,1);assert.equal(output.pre_analysis_failure.daily.reserved_rows_read,1000);assert.equal(output.pre_analysis_failure.market_conditions_evaluated,false);assert.equal(output.pre_analysis_failure.entry_authorized,false);assert.equal(output.pre_analysis_failure.task_writes,0);assert.deepEqual(output.candidates,[]);
});
test('allowed daily admission proceeds without diagnostic writes or changes to the guard',async()=>{let writes=0;await enforceDailyAnalysisAdmission({admission:{allowed:true,status:'CLOSED'},context,write_result:()=>{writes++;}});assert.equal(writes,0);});
test('daily diagnostic persistence failure cannot turn refusal into admission',async()=>{await assert.rejects(enforceDailyAnalysisAdmission({admission:{allowed:false,status:'UNMEASURED_FINALIZED_USAGE',daily:{unknown_ops:1}},context,write_result:()=>{throw Error('CONTROLLED_WRITE_FAILURE');}}),e=>e.pre_analysis_failure.artifact_persisted===false&&e.pre_analysis_failure.entry_authorized===false);});

test('trigger-only quota refusal stays bound to its exact task without evaluating market conditions',async()=>{let output;await assert.rejects(enforceDailyAnalysisAdmission({admission:{allowed:false,status:'UNMEASURED_FINALIZED_USAGE',daily:{unknown_ops:1}},context:{...context,trigger_admission:true},write_result:x=>{output=x;}}));assert.equal(output.pre_analysis_failure.stage,'D1_TRIGGER_RECHECK_ADMISSION');assert.equal(output.pre_analysis_failure.reason,'D1_TRIGGER_BUDGET_NOT_CLOSED');assert.equal(output.pre_analysis_failure.task_id,context.task_id);assert.equal(output.pre_analysis_failure.full_analysis_completed,false);assert.equal(output.pre_analysis_failure.task_writes,0);assert.equal(output.pre_analysis_failure.source_clock_refreshed,false);});

test('both actual runner quota checks persist a refusal before later work',async()=>{
 const budgetCalls=source.match(/await enforceDailyAnalysisAdmission\([^\n]+?\);/g)||[];assert.equal(budgetCalls.length,2);
 for(const call of budgetCalls){let output;const fn=new (Object.getPrototypeOf(async function(){}).constructor)('admissionBudget','d1DayAdmission','enforceDailyAnalysisAdmission','generation','process','source','triggerKickTaskId','triggerOnly','started','Date','fs','env','d1DailyBeforeReservationRaw',call),admission={allowed:false,status:'UNMEASURED_FINALIZED_USAGE',daily:{unknown_ops:1}};
 await assert.rejects(fn(admission,admission,enforceDailyAnalysisAdmission,context.generation,{env:{GITHUB_SHA:context.head,GITHUB_RUN_ID:context.source_run_id}},'schedule',context.task_id,true,context.started_ts,{now:()=>context.failed_ts},{writeFile:async(_,v)=>{output=JSON.parse(v);}},{DATA_DB:{usageSnapshot:()=>({requests:10,rows_read:75,rows_written:4,unknown_ops:1})}},admission.daily));assert.equal(output.pre_analysis_failure.daily.unknown_operations,1);assert.equal(output.pre_analysis_failure.d1_attempt_usage.total_rows_read,null);assert.equal(output.pre_analysis_failure.entry_authorized,false);assert.equal(output.pre_analysis_failure.task_id,context.task_id);}
});
test('native reservations and measured subtotals remain distinct from adaptive admission inputs',async()=>{
 let output;const raw={status:'DAY_USAGE_CLOSED',day_utc:'2026-10-09',run_count:69,reserved_rows_read:993000,reserved_rows_written:17664,measured_rows_read:595632,measured_rows_written:8023,unknown_ops:1,unfinished_count:0};
 await assert.rejects(enforceDailyAnalysisAdmission({admission:{allowed:false,status:'UNMEASURED_FINALIZED_USAGE',daily:{unknown_ops:1,reserved_rows_read:595632,reserved_rows_written:8023,unfinished_count:0}},context:{...context,daily_usage_scope:'ADAPTIVE_ADMISSION_POLICY_INPUTS',native_d1_daily:raw},write_result:x=>{output=x;}}));
 const r=output.pre_analysis_failure;assert.equal(r.daily_usage_scope,'ADAPTIVE_ADMISSION_POLICY_INPUTS');assert.equal(r.daily.reserved_rows_read,595632);assert.equal(r.native_daily_aggregate.reserved_rows_read,993000);assert.equal(r.native_daily_aggregate.measured_rows_read,595632);assert.equal(r.native_daily_aggregate.unknown_operations,1);assert.equal(r.native_daily_aggregate.day_utc,'2026-10-09');assert.equal(r.entry_authorized,false);
});
test('missing or arbitrary daily provenance is never silently marked native or given zero usage',async()=>{
 let output;await assert.rejects(enforceDailyAnalysisAdmission({admission:{allowed:false,status:'NOT_CLOSED'},context:{...context,daily_usage_scope:'SECRET',native_d1_daily:{reserved_rows_read:'100',reserved_rows_written:-1,day_utc:'SECRET',secret:'SECRET'}},write_result:x=>{output=x;}}));
 const r=output.pre_analysis_failure;assert.equal(r.daily_usage_scope,'UNSPECIFIED');assert.equal(r.native_daily_aggregate.reserved_rows_read,null);assert.equal(r.native_daily_aggregate.reserved_rows_written,null);assert.equal(r.native_daily_aggregate.unknown_operations,null);assert.equal(r.native_daily_aggregate.day_utc,null);assert.equal(JSON.stringify(output).includes('SECRET'),false);
 await assert.rejects(enforceDailyAnalysisAdmission({admission:{allowed:false,status:'NOT_CLOSED'},context,write_result:x=>{output=x;}}));assert.equal(output.pre_analysis_failure.native_daily_aggregate,null);
});
