import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'current-generation/files');
const {createCombinedLiquidationService}=await import(pathToFileURL(root+'/src/liquidation-extension/combined-runner-service.mjs'));
const {bindNativeAcquisition}=await import(pathToFileURL(root+'/src/liquidation-extension/runtime-bridge.mjs'));
const {buildNativeWalletRouting}=await import(pathToFileURL(root+'/src/liquidation-extension/native-wallet-routing.mjs'));
const {selectLiquidationDisplayZones,RELEVANT_LIQUIDATION_PRESENTATION}=await import(pathToFileURL(root+'/src/canonical-display.mjs'));
const retained=JSON.parse(fs.readFileSync('checkpoints/source-inputs/swole-native-sample-37596747832.json')).raw[0],T=retained.receipt.received_ts;
const address='0x'+'2'.repeat(40);
const state={time:T,assetPositions:[{position:{coin:'NEAR',szi:'10',positionValue:'50',liquidationPx:'4',leverage:{type:'cross',value:2}}}]};
function fixture({proven=true,stale=false,wrong=false,denied=false,hint=false}={}){
 const calls=[],s=createCombinedLiquidationService({mode:'SHADOW_ONLY',secondary_enabled:false,candidate_slots:1,max_http_per_run:5,clock:()=>T,native_wallet_routing:hint?buildNativeWalletRouting({accounts:[{address:retained.address,state:retained.payload,http_receipt:retained.receipt}],run_id:'ORIGINAL_RETAINED',now:T}):null,provider_admit:async()=>denied?{allowed:false,new_reservation:false,reservation_not_created:true}:{allowed:true,new_reservation:true},fetch_impl:async(url,init)=>{const b=init?.body?JSON.parse(init.body):null;calls.push({url:String(url),body:b});if(b?.type==='clearinghouseState')return new Response(JSON.stringify(hint?retained.payload:{...state,time:stale?T-120001:T,assetPositions:wrong?[]:state.assetPositions}));if(b?.type==='metaAndAssetCtxs')return new Response(JSON.stringify([{universe:[{name:'NEAR'}]},[{markPx:'5'}]]));return new Response(JSON.stringify({coin:'NEAR',positions:[{address,size:10,liq_price:4}]}));}});
 return {s,calls,collect:()=>s.collect({contract:'NEAR-USDT',native_symbol:'NEAR',run_id:'CONTROLLED_PROVEN_ROUTE',deep_started_ts:T,max_http_for_candidate:2,allowed_source_ids:['HYPERLIQUID_NATIVE'],proven_level_source_ids:proven?['HYPERLIQUID_NATIVE']:[]})};
}
test('exact proven route fits discovery and new account verification in the following candidate two-call envelope',async()=>{const f=fixture(),raw=await f.collect();assert.ok(raw);assert.equal(f.calls.length,2);assert.equal(f.calls.some(x=>x.body?.type==='metaAndAssetCtxs'),false);const bound=bindNativeAcquisition(raw,{contract:'NEAR-USDT',run_id:raw.run_id,snapshot_id:'CONTROLLED:new',observed_ts:T,direction:'LONG'});assert.equal(bound.status,'USABLE_NATIVE_SAMPLE');assert.equal(bound.below[0].native_price,4);assert.equal(bound.market_context,null);assert.equal(bound.entry_eligible,false);assert.equal(f.s.summary().shared_budget.actual_http,2);});
test('absence of a structural route still requires catalog and never promotes model hint prices',async()=>{const f=fixture({proven:false});assert.equal(await f.collect(),null);assert.equal(f.calls.length,1);assert.equal(f.calls[0].body.type,'metaAndAssetCtxs');});
test('stale or absent current exact coin state cannot become a fresh level and denied quota makes zero calls',async()=>{for(const opt of [{stale:true},{wrong:true}]){const f=fixture(opt),raw=await f.collect();const b=bindNativeAcquisition(raw,{contract:'NEAR-USDT',run_id:raw.run_id,snapshot_id:'CONTROLLED:new',observed_ts:T,direction:null});assert.equal(b.above.length+b.below.length,0);if(opt.stale)assert.equal(b.status,'NOT_CLOSED');assert.equal(f.calls.length,2);}const f=fixture({denied:true});assert.equal(await f.collect(),null);assert.equal(f.calls.length,0);});
test('real retained NEAR account is read through the composed native producer at its original clock without advertising an irrelevant threshold',async()=>{const f=fixture({hint:true}),raw=await f.collect();assert.ok(raw);assert.equal(f.calls.length,1);assert.equal(JSON.stringify(raw.accounts[0].state),JSON.stringify(retained.payload));assert.equal(raw.accounts[0].state.time,retained.payload.time);const b=bindNativeAcquisition(raw,{contract:'NEAR-USDT',run_id:raw.run_id,snapshot_id:'CONTROLLED:original-clock',observed_ts:T,direction:null});assert.equal(b.status,'USABLE_NATIVE_SAMPLE');assert.equal(b.above[0].native_price,15.0281326363);const z={price:b.above[0].native_price,...b.above[0],kind:'NATIVE_FUTURE_LEVEL',distance_reference_price:b.above[0].native_reference_price,distance_reference_basis:'ORIGINAL_SOURCE_REFERENCE_SAME_QUOTE',source:b.provider};assert.equal(selectLiquidationDisplayZones({above:[z],below:[],display_source_zones:[z]},'ABOVE',{policy:RELEVANT_LIQUIDATION_PRESENTATION}).length,0);});
