import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.env.REPORT2_MARKET_CONTEXT_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_MARKET_CONTEXT_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url);
const {normalizeCoinpaprikaProviderReference,verifyCoinpaprikaProviderReference,normalizeCoinpaprikaHtxIdentity}=await import(new URL('coinpaprika-htx-identity.mjs',root));
const {normalizeCoinpaprikaMarketSupply}=await import(new URL('coinpaprika-market-supply.mjs',root));
const {normalizeCoinpaprikaSector,collectCoinpaprikaSectorEvidence}=await import(new URL('coinpaprika-sector-evidence.mjs',root));
const {consumeSectorContext}=await import(new URL('sector-context.mjs',root));
const {consumeBlockResultContext}=await import(new URL('block-result-context.mjs',root));
const {createProviderReferenceReader}=await import(new URL('provider-reference-cache.mjs',root));
const {installEvidenceSourceStore}=await import(new URL('evidence-source-store.mjs',root));
const {planCandidateEvidenceRoutes}=await import(new URL('candidate-evidence-v2-runtime.mjs',root));
const NOW=Date.now(),contract='ABC-USDT',metadata={id:'abc-example',symbol:'ABC',is_active:true,type:'coin',name:'Example',contracts:[],tags:[{id:'storage'}]},markets=[{pair:'ABC/USDT',base_currency_id:'abc-example',quote_currency_id:'usdt-tether',category:'spot',market_url:'https://www.htx.com/trade/abc_usdt'}];
const ref=()=>({...normalizeCoinpaprikaProviderReference({markets,metadata,contract}),reference_observed_ts:NOW-1000});
const quote=(id,symbol,change=1)=>({id,symbol,last_updated:new Date(NOW-60000).toISOString(),total_supply:1000,max_supply:2000,quotes:{USD:{price:1,volume_24h:300000,percent_change_24h:change}}});
function db(){const sqlite=new DatabaseSync(':memory:');return{sqlite,prepare(sql){return{args:[],bind(...a){this.args=a;return this;},async run(){return sqlite.prepare(sql).run(...this.args);},async first(){return sqlite.prepare(sql).get(...this.args)||null;},async all(){return{results:sqlite.prepare(sql).all(...this.args)};}};},async batch(rows){return Promise.all(rows.map(r=>r.run()));}};}
test('strict provider market binding allows market context without inventing native/chain identity',()=>{const r=ref();assert.equal(verifyCoinpaprikaProviderReference(r,contract,NOW),true);assert.equal(r.chain_route_authorized,false);assert.equal(normalizeCoinpaprikaHtxIdentity({markets,metadata,contract}).identity,null);assert(planCandidateEvidenceRoutes({contract}).routes.some(r=>r.name==='SECTOR'));});
test('ambiguous market, foreign venue, inactive and wrapped-symbol substitutes cannot acquire provider identity',()=>{for(const changes of [{markets:[...markets,{...markets[0],base_currency_id:'abc-other'}]},{markets:[{...markets[0],market_url:'https://example.com/trade'}]},{metadata:{...metadata,symbol:'WABC'}},{metadata:{...metadata,is_active:false}},{metadata:{...metadata,id:'br-bohr'}}])assert.notEqual(normalizeCoinpaprikaProviderReference({markets,metadata,contract,...changes}).status,'CLOSED_PROVIDER_MARKET_REFERENCE');for(const changes of [{reference_observed_ts:NOW+1},{reference_observed_ts:NOW-21600001},{contract:'OTHER-USDT'}])assert.equal(verifyCoinpaprikaProviderReference({...ref(),...changes},contract,NOW),false);});
test('real response fields only: missing circulating and zero maximum stay unknown, no inferred unlock or score',()=>{const ticker={...quote('abc-example','ABC'),max_supply:0},r=normalizeCoinpaprikaMarketSupply({reference:ref(),ticker,contract,observed_ts:NOW});assert.equal(r.status,'CLOSED_AGGREGATED_SUPPLY_CONTEXT');assert.deepEqual(r.summary,{total_supply:1000});const row=r.evidence[0],used=consumeBlockResultContext({evidence:[row],contract,now:NOW});assert.deepEqual(used.facts,[]);assert.equal(row.chain_finality_verified,false);assert.equal(row.entry_authorized,false);for(const ticker2 of [{...ticker,last_updated:new Date(NOW+1).toISOString()},{...ticker,id:'foreign'},{...ticker,total_supply:0},{...ticker,total_supply:2000,max_supply:1000}])assert.equal(normalizeCoinpaprikaMarketSupply({reference:ref(),ticker:ticker2,contract,observed_ts:NOW}).evidence.length,0);assert.equal(consumeBlockResultContext({evidence:[{...row,supply_values:{total_supply:99999}}],contract,now:NOW}).facts.length,0);});
test('provider declared functional sector consumes exact matched peer basket without chain route; membership tampering fails',()=>{const tag={id:'storage',name:'Storage',type:'functional',coins:['abc-example','p1','p2','p3']},tickers=[quote('abc-example','ABC',5),quote('p1','P1',-2),quote('p2','P2',0),quote('p3','P3',2)],r=normalizeCoinpaprikaSector({metadata,tag,tickers,provider_reference:ref(),contract,coin_id:'abc-example',tag_id:'storage',observed_ts:NOW});assert.equal(r.status,'CLOSED');assert.equal(r.summary.relative_strength_pct_points,5);const used=consumeSectorContext({evidence:r.evidence,contract,now:NOW});assert.equal(used.facts.length,1);assert.equal(used.facts[0].score_contribution,0);const row=r.evidence[0];assert.equal(consumeSectorContext({evidence:[{...row,provider_tag:{...row.provider_tag,coins:['abc-example']}}],contract,now:NOW}).facts.length,0);assert.equal(consumeSectorContext({evidence:[{...row,provider_reference:{...ref(),contract:'OTHER-USDT'}}],contract,now:NOW}).facts.length,0);});
test('large shared quote body stays in bounded same-run memory and consumes one source reservation',async()=>{const database=db();await installEvidenceSourceStore(database);let calls=0;const opts={db:database,source:'COINPAPRIKA_SECTOR',run_id:'same-run',now:Date.now()+1000,daily_cap:48,request_admit:()=>({allowed:true}),fetch_impl:async()=>{calls++;return new Response(JSON.stringify([{id:'actual-returned',padding:'x'.repeat(5000)}]));}};const url='https://api.coinpaprika.com/v1/tickers?quotes=USD',config={ttl_ms:60000,max_bytes:10000,max_cache_bytes:1000,shape:Array.isArray},a=createProviderReferenceReader(opts),first=await a.get('FREE_AGGREGATED_QUOTES',url,config),b=createProviderReferenceReader(opts),second=await b.get('FREE_AGGREGATED_QUOTES',url,config);assert.deepEqual(second,first);assert.equal(calls,1);assert.equal(b.summary().network_calls,0);assert.equal(b.summary().receipts[0].received_ts,a.summary().receipts[0].received_ts);assert.equal(database.sqlite.prepare('SELECT COUNT(*) n FROM report2_evidence_source_cache').get().n,0);assert.equal(database.sqlite.prepare('SELECT COUNT(*) n FROM report2_evidence_source_reservation').get().n,1);database.sqlite.close();});
test('generic market collector uses reported supply even when functional category has no basket, and keeps primary chain missing',async()=>{const database=db();let calls=0;const r=await collectCoinpaprikaSectorEvidence({db:database,contract,run_id:'generic',now:NOW,request_admit:()=>({allowed:true}),fetch_impl:async url=>{calls++;return new Response(JSON.stringify(url.includes('/exchanges/')?markets:url.includes('/coins/')?metadata:url.endsWith('/tags')?[]:quote('abc-example','ABC')));}});assert.equal(calls,4);assert.equal(r.status,'CLOSED');assert.equal(r.supply_status,'CLOSED_AGGREGATED_SUPPLY_CONTEXT');assert.equal(r.sector_status,'EXACT_FUNCTIONAL_SECTOR_NOT_FOUND');assert.deepEqual(r.evidence.map(r=>r.block_id),['N02']);assert.equal(r.chain_route_authorized,false);database.sqlite.close();});

test('actual provider misclassification of regulatory/investor/consensus themes cannot become a sector',async()=>{
 const {selectCoinpaprikaFunctionalSector,comparableCoinpaprikaFunctionalTag}=await import(new URL('coinpaprika-sector-evidence.mjs',root));
 const ids=['alleged-sec-securities','ftx-holdings','multicoin-capital-portfolio','made-in-usa','pos','open-source','wrapped-token'];
 for(const id of ids)assert.equal(comparableCoinpaprikaFunctionalTag({id,type:'functional'}),false);
 const tags=[...ids.map(id=>({id,type:'functional'})),{id:'big-data-data-storage',type:'functional'}],m={tags:tags.map(t=>({id:t.id}))};
 assert.equal(selectCoinpaprikaFunctionalSector(m,tags).id,'big-data-data-storage');
 const r=normalizeCoinpaprikaSector({metadata,tag:{id:'alleged-sec-securities',type:'functional',coins:['abc-example','p1','p2','p3']},tickers:[quote('abc-example','ABC'),quote('p1','P1'),quote('p2','P2'),quote('p3','P3')],provider_reference:ref(),contract,coin_id:'abc-example',tag_id:'alleged-sec-securities',observed_ts:NOW});assert.equal(r.evidence.length,0);
});
