import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
const root=process.env.REPORT2_NATIVE_MODULE_ROOT?pathToFileURL(path.resolve(process.env.REPORT2_NATIVE_MODULE_ROOT)+'/'):new URL('../files/src/',import.meta.url),load=n=>import(new URL(n,root));
const [{normalizePublishedMonthlySchedule:normalize,derivePublishedMonthlySchedule:derive,collectPublishedMonthlySchedule:collect,PUBLISHED_MONTHLY_SCHEDULE_TTL:TTL,SUI_MONTHLY_SCHEDULE_ROUTE:route},{normalizeHtxAssetReferences},{collectOfficialTokenSchedule,exactTokenScheduleRoute},{consumeBlockResultContext},{consumeEvidenceV2},{planCandidateEvidenceRoutes},{writeEvidenceSourceCache}]=await Promise.all(['published-monthly-supply-schedule.mjs','htx-asset-identity.mjs','official-token-schedule.mjs','block-result-context.mjs','evidence-v2.mjs','candidate-evidence-v2-runtime.mjs','evidence-source-store.mjs'].map(load));
const rawPath=new URL('../../checkpoints/sui-monthly-schedule-qualification-37859105684/sui-monthly-api.json.gz',import.meta.url),raw=fs.readFileSync(rawPath);assert.equal(createHash('sha256').update(raw).digest('hex'),'5e7bea11652d2ac775de70fed65f3d8bbd3a851a97eab17b6b1e845a65803bae');
const payload=JSON.parse(gunzipSync(raw)),T=1791501784800,identity={chain:'sui',asset_kind:'NATIVE',native_asset_id:'sui:mainnet',contract_or_mint:null},params={contract:'SUI-USDT',asset_identity:identity,payload,source_url:route.url,observed_ts:T},facts=(rows,now=T)=>consumeBlockResultContext({evidence:rows,contract:'SUI-USDT',now}).facts;
function memoryDB(){const sql=new DatabaseSync(':memory:');return{sql,prepare(query){return{args:[],bind(...args){this.args=args;return this;},async run(){return sql.prepare(query).run(...this.args);},async first(){return sql.prepare(query).get(...this.args)||null;}};},async batch(rows){return Promise.all(rows.map(r=>r.run()));}};}
test('actual retained API and exact HTX native binding produce two internal month-end projections, not a matched N01 release',()=>{
 const refs=normalizeHtxAssetReferences(JSON.parse(gunzipSync(fs.readFileSync(new URL('../../checkpoints/primary-native-supply-tests-37854297470/primary-source/htx-currencies.json.gz',import.meta.url)))));assert.deepEqual(refs.entries.SUI.identities,[identity]);const result=normalize(params);assert.equal(result.status,'CLOSED');assert.equal(result.schedule.published_months,85);assert.deepEqual(result.schedule.projections.map(p=>p.month),['2026-10','2026-11']);assert.equal(result.schedule.projections[0].planned_month_end_circulation_tokens,4118270447.6403894);assert.ok(Math.abs(result.schedule.projections[0].planned_increase_over_previous_month_tokens-21733301.09943)<0.00001);assert.equal(facts(result.evidence).length,0);assert.equal(consumeEvidenceV2(result.evidence,{decision_ts:T,base_interest:70}).adjustment,0);assert.equal(result.evidence[0].coverage_fraction,0);assert.equal(result.evidence[0].actual_unlock_transfer_verified,false);assert.equal(result.evidence[0].current_finalized_supply_verified,false);assert.equal(result.evidence[0].exact_unlock_time_verified,false);assert.equal(result.evidence[0].source_ts,T);assert.equal(result.evidence[0].expires_at,T+TTL);
});
test('existing generic candidate route and collector dispatch include the exact native asset',async()=>{
 assert.equal(exactTokenScheduleRoute({contract:'SUI-USDT',asset_identity:identity}).url,route.url);assert.equal(planCandidateEvidenceRoutes({contract:'SUI-USDT',asset_identity:identity}).routes.some(r=>r.name==='TOKEN_SCHEDULE'),false);const db=memoryDB();let calls=0;const r=await collectOfficialTokenSchedule({db,contract:'SUI-USDT',asset_identity:identity,run_id:'route',now:T,clock:()=>T,request_admit:()=>({allowed:true}),fetch_impl:async url=>{assert.equal(url,route.url);calls++;return new Response(JSON.stringify(payload));}});assert.equal(r.status,'CLOSED');assert.equal(calls,1);assert.equal(facts(r.evidence).length,0);
});
for(const patch of [{contract:'SUI-USD'},{asset_identity:{...identity,chain:'ethereum'}},{asset_identity:{...identity,asset_kind:'TOKEN'}},{asset_identity:{...identity,native_asset_id:'wrong'}},{asset_identity:{...identity,contract_or_mint:'0x'+'1'.repeat(40)}},{source_url:'https://evil.example/sui'},{observed_ts:T+0.5}])test('rejects foreign exact binding or clock '+JSON.stringify(patch),()=>assert.equal(normalize({...params,...patch}).evidence.length,0));
for(const [name,change]of [['duplicate month',p=>p.splice(3,0,structuredClone(p[2]))],['missing month',p=>p.splice(5,1)],['descending supply',p=>p[3].circulatingSupplyValue=1],['wrong fraction',p=>p[3].circulatingSupplyPercentage=0.99],['above fixed maximum',p=>p[3].circulatingSupplyValue=11000000000],['string unit',p=>p[3].circulatingSupplyValue=String(p[3].circulatingSupplyValue)],['invalid month',p=>p[3].month=13]])test('rejects whole-series '+name,()=>{const p=structuredClone(payload);change(p);assert.equal(derive(p,{observed_ts:T}),null);});
test('each altered consumer field is rejected and expired query clock is not renewed',()=>{
 const row=normalize(params).evidence[0];for(const patch of [{source_ts:T-1},{expires_at:T+TTL+1},{provider_id:'UNKNOWN'},{coverage_fraction:1},{directional_strength:0.1},{actual_unlock_transfer_verified:true},{exact_unlock_time_verified:true},{schedule_context:{...row.schedule_context,projections:[{...row.schedule_context.projections[0],planned_increase_over_previous_month_tokens:999}]}}])assert.equal(facts([{...row,...patch}]).length,0,JSON.stringify(patch));assert.equal(facts([row],T+TTL).length,0);assert.equal(facts([row],T-1).length,0);
});
test('past schedule is not a future event and monthly boundary remains a period',()=>{
 assert.equal(derive(payload,{observed_ts:Date.UTC(2030,5,1)}),null);const p=normalize(params).schedule.projections[0];assert.equal(p.period_start_ts,Date.UTC(2026,9,1));assert.equal(p.period_end_exclusive_ts,Date.UTC(2026,10,1));assert.equal(normalize(params).schedule.period_precision,'MONTH;END_OF_MONTH_VALUE_NOT_UNLOCK_TIME');
});
test('valid cache preserves original inner clock, costs zero provider HTTP and cannot use an outer expiry extension',async()=>{
 const db=memoryDB();let calls=0;const options={db,contract:'SUI-USDT',asset_identity:identity,run_id:'cache',now:T,clock:()=>T,request_admit:()=>({allowed:true}),fetch_impl:async()=>{calls++;return new Response(JSON.stringify(payload));}},a=await collect(options),b=await collect({...options,now:T+60000});assert.equal(calls,1);assert.equal(b.network_calls,0);assert.equal(b.evidence[0].source_ts,T);assert.equal(b.evidence[0].expires_at,T+TTL);db.sql.prepare('UPDATE report2_evidence_source_cache SET expires_ts=?').run(T+2*TTL);const stale=await collect({...options,now:T+TTL,request_admit:()=>({allowed:false,status:'CONTROL_BUDGET_DENIED'})});assert.equal(stale.evidence.length,0);assert.equal(stale.network_calls,0);assert.equal(calls,1);
});
test('source cap stops a fifth fresh attempt without retries or provider calls',async()=>{
 const db=memoryDB();let calls=0;for(let i=0;i<5;i++){const r=await collect({db,contract:'SUI-USDT',asset_identity:identity,run_id:'cap'+i,now:T,clock:()=>T,strict_fresh_manual:true,request_admit:()=>({allowed:true}),fetch_impl:async()=>{calls++;return new Response('{}',{status:503});}});if(i<4){assert.equal(r.network_calls,1);assert.equal(r.evidence.length,0);}else assert.equal(r.network_calls,0);}assert.equal(calls,4);assert.equal(db.sql.prepare("SELECT attempts FROM report2_evidence_source_daily WHERE source='SUI_PUBLISHED_MONTHLY_SCHEDULE'").get().attempts,4);
});
