import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
import {buildSameRunDeliveryProof,verifySameRunDeliveryProof} from '../files/src/same-run-delivery-proof.mjs';
const H='a'.repeat(40),F='b'.repeat(64),P='c'.repeat(64),T=1791565000000;
function fixture(event='OBSERVE'){
 const a={run_id:'R1',snapshot_id:'S1',observed_ts:T,analytical_fingerprint:F,state:event==='ENTRY'?'ENTRY_NOW_ANALYTICAL':'OBSERVE',trigger:{next_recheck_ts:T+300000,expires_ts:T+1800000}};
 const c={publication_id:'PUB1',contract:'NEAR-USDT',direction:'LONG',run_id:'R1',snapshot_id:'S1',wave_id:'W1',observed_ts:T,lifecycle_event:event,canonical:a};
 const output={status:'CLOSED',head:H,generation:'G1',run_id:'R1',source:'schedule',candidates:[c]};
 const b={schema:'BOUND_DELIVERY_RECEIPT_V1',...c,canonical:undefined,analytical_fingerprint:F,presentation_hash:P,source_run_id:'R1',network_result:'CONFIRMED_SENT',dispatch_finalized:true,finalization_status:'SENT',dispatch_state:'SENT',task_at_delivery:{state:'PENDING',run_id:'R1',snapshot_id:'S1',due_ts:a.trigger.next_recheck_ts,expires_ts:a.trigger.expires_ts},secret:'MUST_NOT_COPY'};
 const delivery={status:'CLOSED',lifecycle:[{status:'SENT',sent:true,message_id:'123',bound_receipt:b}],secret:'MUST_NOT_COPY'};return {output,delivery};
}
test('exact current ack and successful dispatch write capture OBSERVE and already-read task, no secret or added calls',()=>{const f=fixture(),p=buildSameRunDeliveryProof({...f,recorded_at:T+1000});assert.equal(p.cases[0].exact_SENT,true);assert.equal(p.cases[0].task_at_delivery_verified,true);assert.equal(p.cases[0].actual_ENTRY,false);assert.equal(JSON.stringify(p).includes('MUST_NOT_COPY'),false);assert.equal(verifySameRunDeliveryProof({output:f.output,proof:p,expected_head:H}).exact_SENT,1);assert.equal(p.D1_added,0);});
test('ENTRY accepted only with exact canonical ENTRY and actual bound delivery',()=>{const f=fixture('ENTRY'),p=buildSameRunDeliveryProof(f);assert.equal(verifySameRunDeliveryProof({output:f.output,proof:p,expected_head:H}).actual_ENTRY,1);p.cases[0].lifecycle_event='OBSERVE';assert.throws(()=>verifySameRunDeliveryProof({output:f.output,proof:p,expected_head:H}));});
test('masked ID, missing ack, write failure, old run and foreign snapshot are never exact SENT',()=>{for(const mutate of [f=>f.delivery.lifecycle[0].message_id='***',f=>f.delivery.lifecycle[0].bound_receipt.network_result='UNKNOWN',f=>f.delivery.lifecycle[0].bound_receipt.dispatch_finalized=false,f=>f.delivery.lifecycle[0].bound_receipt.source_run_id='OLD',f=>f.delivery.lifecycle[0].bound_receipt.snapshot_id='FOREIGN',f=>f.delivery.lifecycle[0].bound_receipt.presentation_hash='',f=>f.output.status='NOT_CLOSED']){const f=fixture();mutate(f);const p=buildSameRunDeliveryProof(f);assert.equal(p.cases[0].exact_SENT,false);assert.equal(p.cases[0].telegram_message_id,null);}});
test('missing or stale original task is not recreated or extended',()=>{const f=fixture();f.delivery.lifecycle[0].bound_receipt.task_at_delivery.expires_ts++;const p=buildSameRunDeliveryProof(f);assert.equal(p.cases[0].exact_SENT,true);assert.equal(p.cases[0].task_at_delivery_verified,false);assert.equal(p.cases[0].task_at_delivery,null);});
test('artifact mismatches and duplicate positive claims refuse',()=>{const f=fixture(),p=buildSameRunDeliveryProof(f);assert.throws(()=>verifySameRunDeliveryProof({output:f.output,proof:p,expected_head:'d'.repeat(40)}));p.cases.push(p.cases[0]);assert.throws(()=>verifySameRunDeliveryProof({output:f.output,proof:p,expected_head:H}));});
test('actual retained TIA artifact without exact delivery receipt remains unproven',()=>{const output=JSON.parse(execFileSync('unzip',['-p','checkpoints/post261-natural-37944444674.zip','report2-run-result.json']));const p=buildSameRunDeliveryProof({output,delivery:{status:'CLOSED',sent:1,lifecycle:[{status:'SENT',message_id:'***'}]}});assert.equal(p.cases.length,0);assert.equal(verifySameRunDeliveryProof({output,proof:p,expected_head:output.head}).exact_SENT,0);});
