import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {gunzipSync} from 'node:zlib';
import {pathToFileURL} from 'node:url';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'runtime');
const {consumeSectorContext}=await import(pathToFileURL(path.join(root,'src/sector-context.mjs')));
const {formatManualReport}=await import(pathToFileURL(path.join(root,'src/manual-report-formatter.mjs')));
const {formatManualRunSummary}=await import(pathToFileURL(path.join(root,'src/manual-run-summary.mjs')));
const {auditRenderedBlockResults}=await import(pathToFileURL(path.join(root,'src/block-result-context.mjs')));
const fixture=JSON.parse(gunzipSync(fs.readFileSync(new URL('./fixtures/actual-ZEC-role-handoff-0931.json.gz',import.meta.url))));
const original=fixture.canonical;
const args={evidence:original.metadata.internal_market_context.evidence_v2.evidence,contract:original.metadata.contract,asset_identity:original.metadata.internal_market_context.candidate_context.asset_identity,now:original.observed_ts};
test('both actual ZEC provider comparisons reach the existing manual context consumer at their original clock',()=>{
 assert.equal(fixture.source_cloud_run,37423984921);
 const context=consumeSectorContext(args);
 assert.equal(context.facts.length,2);
 assert.deepEqual(context.facts.map(f=>f.source),['CoinGecko','CoinPaprika']);
 assert.equal(new Set(context.facts.map(f=>f.physical_root_key)).size,2);
 assert.ok(context.facts[0].label!==context.facts[1].label);
 assert.equal(context.score_contribution,0);assert.equal(context.directional_vote,false);
 const canonical=structuredClone(original);
 canonical.metadata.supporting_context.facts=[...canonical.metadata.supporting_context.facts.filter(f=>f.block_id!=='N15'),...context.facts];
 const manual=formatManualReport(canonical);
 assert.equal(manual.ok,true);
 const audit=auditRenderedBlockResults({canonical,manual});
 const receipts=audit.context_receipts.filter(r=>r.block_id==='N15');
 assert.equal(receipts.length,2);
 assert.deepEqual(new Set(receipts.map(r=>r.source)),new Set(['CoinGecko','CoinPaprika']));
 assert.ok(receipts.every(r=>r.observed_ts<=original.observed_ts&&r.score_contribution===0));
 const summary=formatManualRunSummary({status:'PARTIAL_DATA_UNAVAILABLE',run_id:original.run_id,candidates:[{contract:args.contract,run_id:original.run_id,snapshot_id:original.snapshot_id,observed_ts:original.observed_ts,canonical,manual_text:manual.text,block_rendered_results:audit}]});
 for(const fact of context.facts)assert.ok(summary.includes(fact.value));
 assert.deepEqual(canonical.scores,original.scores);assert.equal(canonical.state,original.state);assert.equal(canonical.direction,original.direction);
});
test('same-source repeats, wrong-market and future-known evidence do not add a second source or defeat the original cutoff',()=>{
 const rows=args.evidence.filter(r=>r.block_id==='N15');
 const first=rows.find(r=>r.provider_id==='COINGECKO_SECTOR');
 assert.equal(consumeSectorContext({...args,evidence:[first,structuredClone(first)]}).facts.length,1);
 const wrong=structuredClone(rows);for(const r of wrong)r.htx_contract='BTC-USDT';
 assert.equal(consumeSectorContext({...args,evidence:wrong}).facts.length,0);
 const future=structuredClone(rows);for(const r of future)r.observed_ts=original.observed_ts+1;
 assert.equal(consumeSectorContext({...args,evidence:future}).facts.length,0);
 assert.equal(consumeSectorContext({...args,now:original.observed_ts+900001}).facts.length,0);
});
