import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'current-generation/files'),load=n=>import(pathToFileURL(path.join(root,'src',n)));
const {readSavedHtxSignedTape,capturedSignedTapeFourHourFlow,clearHtxSignedTapeSnapshots}=await load('htx-signed-tape.mjs'),{buildHtxFuturesFlowPrimary,finalizeCandidateBlockCoverage}=await load('candidate-evidence-v2-runtime.mjs'),{buildRuntimeCanonicalBundle}=await load('canonical-runtime-adapter.mjs');
const bytes=fs.readFileSync('current-generation/tests/fixtures/exact-current-37395903856.json.gz');assert.equal(createHash('sha256').update(bytes).digest('hex'),'d3e6ac9394f57739a1ea7ffe89a4aade9ff52a52fd271f5612fdf17f575dc50f');const fixture=JSON.parse(gunzipSync(bytes)),row=fixture.rows.find(r=>r.contract_code==='LSK-USDT'),ring=row.tape.ring,contract=row.contract_code,T=row.canonical.observed_ts;
function database(payload,ops,{error}={}){return{prepare(sql){ops.push({sql});return{bind(...args){ops.at(-1).args=args;return this;},async first(){if(error)throw error;return payload===null?null:{observed_ts:ring.observed_ts,expires_ts:T+1,payload_json:JSON.stringify(payload)};}};}};}
test('fallback budget denial and exception are retained without D1, transport, fabricated clock or fact',async()=>{
 for(const throws of [false,true]){clearHtxSignedTapeSnapshots();const ops=[],error=Object.assign(new Error('DO_NOT_EXPORT_SECRET'),{code:'D1_DENIED'}),db=database(ring,ops);assert.equal(await readSavedHtxSignedTape({db,contract,now:T,db_admit:()=>{if(throws)throw error;return{allowed:false};}}),null);assert.equal(ops.length,0);const flow=capturedSignedTapeFourHourFlow({contract,now:T});assert.equal(flow.check_completed,false);assert.equal(flow.saved_ring_read_diagnostic.failure_stage,'D1_ADMISSION');assert.equal(flow.saved_ring_read_diagnostic.evaluated_ts,T);assert.equal(flow.saved_ring_diagnostic.observed_ts,null);assert.ok(!JSON.stringify(flow).includes('DO_NOT_EXPORT_SECRET'));assert.equal(flow.evidence.length,0);}
});
test('one failed admitted cache read preserves its stage and safe code through the N05 consumer',async()=>{
 clearHtxSignedTapeSnapshots();const ops=[],error=Object.assign(new Error('DO_NOT_EXPORT_SECRET'),{code:'D1_TEST_UNAVAILABLE'}),db=database(null,ops,{error});assert.equal(await readSavedHtxSignedTape({db,contract,now:T,db_admit:()=>({allowed:true})}),null);assert.equal(ops.length,1);
 const source=buildHtxFuturesFlowPrimary({contract,now:T}),final=finalizeCandidateBlockCoverage({evidence_result:{evidence:[],decision_ts:T},decision_ts:T,primary_sources:{PRIMARY_HTX_FUTURES_FLOW:source}}),check=final.block_coverage.blocks.N05.source_checks.PRIMARY_HTX_FUTURES_FLOW;
 assert.equal(source.check_completed,false);assert.equal(check.checked,false);assert.equal(check.source_diagnostic.saved_ring_read.failure_stage,'READ_SAVED_FALLBACK_RING');assert.equal(check.source_diagnostic.saved_ring_read.error_code,'D1_TEST_UNAVAILABLE');assert.ok(!JSON.stringify(final).includes('DO_NOT_EXPORT_SECRET'));assert.ok(Buffer.byteLength(JSON.stringify(source.closure_diagnostic))<=2048);assert.equal(source.network_calls,0);
});
test('missing row and damaged compressed storage are distinguished, without writes or new tables',async()=>{
 for(const [payload,status,stage]of [[null,'NO_SAVED_RAW_TAPE','READ_SAVED_FALLBACK_RING'],[{version:'htx-signed-tape-storage-gzip-v1',encoding:'GZIP_BASE64',uncompressed_bytes:1,sha256:'0'.repeat(64),data:'eA==',contract},'SAVED_RAW_TAPE_STORAGE_INTEGRITY_NOT_CLOSED','DECODE_SAVED_FALLBACK_RING']]){clearHtxSignedTapeSnapshots();const ops=[];assert.equal(await readSavedHtxSignedTape({db:database(payload,ops),contract,now:T,db_admit:()=>({allowed:true})}),null);assert.equal(ops.length,1);assert.ok(ops.every(o=>o.sql.startsWith('SELECT')));const flow=capturedSignedTapeFourHourFlow({contract,now:T});assert.equal(flow.saved_ring_read_diagnostic.status,status);assert.equal(flow.saved_ring_read_diagnostic.failure_stage,stage);assert.equal(flow.evidence.length,0);}
});
test('real retained 240-minute window retains all facts after an optional read fails and assembled canonical decision is identical',async()=>{
 clearHtxSignedTapeSnapshots();const ops=[],loaded=await readSavedHtxSignedTape({db:database(ring,ops),contract,now:T,db_admit:()=>({allowed:true})});assert.deepEqual(loaded,ring);const first=buildHtxFuturesFlowPrimary({contract,now:T});assert.equal(first.check_completed,true);assert.equal(first.evidence[0].verified_minutes,240);
 const input={contract,run_id:row.canonical.run_id,snapshot_id:row.canonical.snapshot_id,observed_ts:T,discovery_row:{current_price:row.canonical.current_price||1},publication_shadow:{entry_signal:{state:'REJECTED',direction:null}}},before=buildRuntimeCanonicalBundle({...input,internal_market_context:{internal_only:true,evidence_v2:{...first,block_coverage:finalizeCandidateBlockCoverage({evidence_result:first,decision_ts:T,primary_sources:{PRIMARY_HTX_FUTURES_FLOW:first}}).block_coverage}}});
 const failure=Object.assign(new Error('DO_NOT_EXPORT_SECRET'),{code:'D1_TEMPORARY'});assert.equal(await readSavedHtxSignedTape({db:database(null,ops,{error:failure}),contract,now:T,db_admit:()=>({allowed:true})}),null);
 const second=buildHtxFuturesFlowPrimary({contract,now:T});assert.equal(second.check_completed,true);assert.deepEqual(second.evidence,first.evidence);assert.equal(second.closure_diagnostic.saved_ring_read.error_code,'D1_TEMPORARY');
 const after=buildRuntimeCanonicalBundle({...input,internal_market_context:{internal_only:true,evidence_v2:{...second,block_coverage:finalizeCandidateBlockCoverage({evidence_result:second,decision_ts:T,primary_sources:{PRIMARY_HTX_FUTURES_FLOW:second}}).block_coverage}}});
 assert.deepEqual(after.canonical.scores,before.canonical.scores);assert.equal(after.canonical.state,before.canonical.state);assert.equal(after.canonical.direction,before.canonical.direction);assert.equal(after.manual.text,before.manual.text);assert.ok(after.block_rendered_results.used_context_block_ids.includes('N05'));assert.equal(second.evidence[0].source_ts,first.evidence[0].source_ts);assert.equal(second.evidence[0].observed_ts,first.evidence[0].observed_ts);
 fs.writeFileSync('audit-output/signed-tape-fallback-read-proof.json',JSON.stringify({schema:'SIGNED_TAPE_FALLBACK_ORIGINAL_CLOCK_CONNECTED_V1',original_gzip_sha256:createHash('sha256').update(bytes).digest('hex'),scope:'RETAINED_ACTUAL_WINDOW_AT_ORIGINAL_CLOCK_NOT_CURRENT_BR_REPAIR',contract,source_ts:second.evidence[0].source_ts,observed_ts:second.evidence[0].observed_ts,read_failure:second.closure_diagnostic.saved_ring_read,rendered:after.block_rendered_results.used_context_block_ids,scores_unchanged:true,state_unchanged:true,direction_unchanged:true,manual_unchanged:true,sourceHTTP:0,D1:0,MAIN:0,Telegram:0,new_fresh_SENT:false,BR_root_cause_closed:false},null,2)+'\n');
});
test('future diagnostic or unsafe error code is refused without exporting its message',async()=>{
 clearHtxSignedTapeSnapshots();const ops=[],error=Object.assign(new Error('DO_NOT_EXPORT_SECRET'),{code:'token=DO_NOT_EXPORT_SECRET'});await readSavedHtxSignedTape({db:database(null,ops,{error}),contract,now:T,db_admit:()=>({allowed:true})});const source=buildHtxFuturesFlowPrimary({contract,now:T});assert.equal(source.closure_diagnostic.saved_ring_read.error_code,'READ_EXCEPTION');assert.ok(!JSON.stringify(source).includes('DO_NOT_EXPORT_SECRET'));const earlier=capturedSignedTapeFourHourFlow({contract,now:T-1});assert.equal(earlier.saved_ring_read_diagnostic,null);assert.equal(earlier.evidence.length,0);clearHtxSignedTapeSnapshots();
});
