import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {signedTapeFourHourFlow,clearHtxSignedTapeSnapshots} from '../files/src/htx-signed-tape.mjs';
import {buildHtxFlowClosureDiagnostic,retainHtxFlowClosureDiagnostic} from '../files/src/source-closure-diagnostics.mjs';
import {buildHtxFuturesFlowPrimary,finalizeCandidateBlockCoverage} from '../files/src/candidate-evidence-v2-runtime.mjs';
import {auditCanonicalBlockDecisionUse} from '../files/src/block-decision-use-audit.mjs';
const gz=fs.readFileSync(new URL('./fixtures/exact-current-37395903856.json.gz',import.meta.url));assert.equal(createHash('sha256').update(gz).digest('hex'),'d3e6ac9394f57739a1ea7ffe89a4aade9ff52a52fd271f5612fdf17f575dc50f');
const fixture=JSON.parse(gunzipSync(gz)),row=fixture.rows.find(r=>r.contract_code==='LSK-USDT'),original=signedTapeFourHourFlow({ring:row.tape.ring,contract:row.contract_code,now:row.canonical.observed_ts}),e=original.evidence[0];assert.equal(e.verified_minutes,240);
function exactRetainedTrajectory(){const count=e.raw_trade_count;return{source:'HTX official public API',market:'HTX USDT-M Futures',contract:row.contract_code,timestamp:row.canonical.observed_ts,contract_info:{contract_code:row.contract_code,contract_size:row.tape.ring.contract_size},coverage:{flow_4h:'closed'},windows:{'4h':{label:'4h',order_flow:{window_start_ts:e.window_start_ts,window_end_ts:e.window_end_ts,usable:true,cvd_delta_reliable:true,raw_delta_is_diagnostic_only:false,sample_trades:count,taker_buy_usdt:e.buy_quote_turnover_usdt,taker_sell_usdt:e.sell_quote_turnover_usdt,delta_usdt:e.value,cvd_delta_quality:{status:'COMPLETE',reliable:true,trade_count_exact_match:true,raw_record_integrity_complete:true,raw_trade_count:count,factual_1m_trade_count:count,factual_coverage:{status:'COMPLETE',exact_1m_bars:true,trade_count_fields_complete:true,expected_1m_bars:240,received_1m_bars:240,factual_1m_trade_count:count},record_integrity:{status:'COMPLETE',complete:true,source_truncated:false,missing_trade_id_count:0,duplicate_trade_id_count:0,invalid_payload_count:0,source_rows_dropped:0,raw_records:count,unique_trade_ids:count}}},price:{usable:true,exact_1m_bars:true,trade_count_complete:true,expected_1m_bars:240,received_1m_bars:240,trade_count:count}}}};}
test('original actual240minute source facts remain admitted at their clock; later stale clock produces exact diagnostics instead of refreshed evidence',()=>{
 clearHtxSignedTapeSnapshots();const trajectory=exactRetainedTrajectory(),before=JSON.stringify(trajectory);
 const good=buildHtxFuturesFlowPrimary({contract:row.contract_code,trajectory,now:row.canonical.observed_ts});assert.equal(good.check_completed,true);assert.equal(good.evidence[0].source_ts,e.window_end_ts);assert.equal(good.evidence[0].value,e.value);
 const later=e.window_end_ts+300001,bad=buildHtxFuturesFlowPrimary({contract:row.contract_code,trajectory,now:later});assert.equal(bad.check_completed,false);assert.deepEqual(bad.blocking_checks,['WINDOW_FRESH']);assert.equal(bad.evidence.length,0);assert.equal(bad.closure_diagnostic.trajectory.window_end_ts,e.window_end_ts);assert.equal(bad.closure_diagnostic.trajectory.window_age_ms,300001);assert.equal(bad.closure_diagnostic.freshness_limit_ms,300000);assert.equal(bad.closure_diagnostic.source_clocks_refreshed,false);assert.equal(bad.network_calls,0);assert.equal(JSON.stringify(trajectory),before);
});
test('missing source clock diagnostics survive the source-to-coverage-to-consumer audit without creating a check, participation or entry',()=>{
 const now=e.window_end_ts+300001,source=buildHtxFuturesFlowPrimary({contract:row.contract_code,trajectory:exactRetainedTrajectory(),now});
 const final=finalizeCandidateBlockCoverage({evidence_result:{evidence:[],decision_ts:now},decision_ts:now,primary_sources:{PRIMARY_HTX_FUTURES_FLOW:source}}),check=final.block_coverage.blocks.N05.source_checks.PRIMARY_HTX_FUTURES_FLOW;
 assert.deepEqual(check.source_diagnostic,source.closure_diagnostic);assert.equal(check.checked,false);const c=structuredClone(row.canonical);c.observed_ts=now;c.metadata.internal_market_context.evidence_v2={...final,evidence:[],decision_ts:now};
 const a=auditCanonicalBlockDecisionUse(c);assert.deepEqual(a.blocks.N05.source_accounting.details.PRIMARY_HTX_FUTURES_FLOW.source_diagnostic,source.closure_diagnostic);assert.equal(a.blocks.N05.participating,false);assert.equal(a.blocks.N05.valid_fact_count,0);assert.equal(a.score_applied_block_count,0);assert.equal(c.state,'REJECTED');assert.equal(c.direction,null);
});
test('bounded diagnostics report original acquisition and ring clocks and exclude raw payloads or oversize diagnostics',()=>{
 const now=row.canonical.observed_ts,signed_flow={status:'SIGNED_FLOW_240_EXACT_MINUTES_REQUIRED',saved_ring_diagnostic:{status:'SIGNED_FLOW_240_EXACT_MINUTES_REQUIRED',observed_ts:row.tape.ring.observed_ts,reported_window_end_ts:e.window_end_ts,reported_window_age_ms:now-e.window_end_ts,reported_minute_rows:row.tape.ring.minutes.length,diagnostic_only:true,source_clock_unchanged:true},raw_acquisition_diagnostic:{status:'SOURCE_NOT_CLOSED',observed_ts:now,new_verified_minutes:0,unverified_recent_minutes:1,persisted_minutes:null,source_clocks:{trades:{status:'SOURCE_CAPTURE_NOT_FRESH',source_ts:now-120001,received_ts:now-1,age_ms:120001}},payload:{secret:'MUST_NOT_APPEAR'}}};
 const d=buildHtxFlowClosureDiagnostic({contract:row.contract_code,now,signed_flow,trajectory:exactRetainedTrajectory()});assert.equal(d.acquisition.source_clocks.trades.source_ts,now-120001);assert.equal(d.acquisition.source_clocks.trades.age_ms,120001);assert.equal(d.signed_raw_ring.reported_window_end_ts,e.window_end_ts);assert.equal(d.network_calls,0);assert.ok(!JSON.stringify(d).includes('MUST_NOT_APPEAR'));assert.ok(Buffer.byteLength(JSON.stringify(d))<=2048);assert.equal(retainHtxFlowClosureDiagnostic({...d,internal_only:false}),null);assert.equal(retainHtxFlowClosureDiagnostic({...d,source_clocks_refreshed:true}),null);assert.equal(retainHtxFlowClosureDiagnostic({...d,extra:'x'.repeat(3000)}),null);
});

test('original acquisition persistence failure reaches bounded N05 diagnostics without exposing error messages or creating a fact',()=>{
 const now=row.canonical.observed_ts,source={status:'SIGNED_FLOW_EXACT_RING_REQUIRED',raw_acquisition_diagnostic:{status:'RAW_TAPE_PERSISTENCE_NOT_CLOSED',observed_ts:now,failure_stage:'WRITE_MERGED_RING',error_code:'D1_TEST_DENIAL',error:'DO_NOT_EXPORT_SECRET',source_clocks:{trades:{status:'CLOSED',source_ts:now-1000,received_ts:now,age_ms:1000}}}};
 const d=buildHtxFlowClosureDiagnostic({contract:row.contract_code,now,signed_flow:source});assert.equal(d.acquisition.failure_stage,'WRITE_MERGED_RING');assert.equal(d.acquisition.error_code,'D1_TEST_DENIAL');assert.equal(d.acquisition.source_clocks.trades.source_ts,now-1000);assert.equal(d.network_calls,0);assert.equal(d.source_clocks_refreshed,false);assert.ok(!JSON.stringify(d).includes('DO_NOT_EXPORT_SECRET'));assert.ok(Buffer.byteLength(JSON.stringify(d))<=2048);
});
