import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=path.resolve(process.argv[2]||'runtime');
const {buildRuntimeCanonicalBundle}=await import(pathToFileURL(path.join(root,'src/canonical-runtime-adapter.mjs')));
const {normalizeVyx,normalizeNansen}=await import(pathToFileURL(path.join(root,'src/specialist-candidate-context.mjs')));
const now=Date.parse('2026-09-30T14:12:00Z');
const sources={VYX:normalizeVyx({symbol_name:'SOL',symbol_id:123,candles:[{timestamp:'2026-09-30T14:11:00Z',interval:'1m',close:120,ofi:3,microprice:120.01,imb_cum_l10:-12}]},{base:'SOL',now,primary_price:120}),NANSEN:normalizeNansen({data:[{smart_trader_longs_usd:80,smart_trader_shorts_usd:20,smart_trader_total_usd:100}]},{base:'SOL',now})};
const input={contract:'SOL-USDT',run_id:'consumer-fixture',snapshot_id:'consumer-fixture',observed_ts:now,discovery_row:{current_price:120},publication_shadow:{entry_signal:{state:'REJECTED',direction:'LONG'}}};
const before=buildRuntimeCanonicalBundle(input);
const after=buildRuntimeCanonicalBundle({...input,internal_market_context:{internal_only:true,htx_reference_price:120,candidate_sources:sources}});
assert.equal(after.canonical.metadata.supporting_context.blocks.order_flow.status,'CLOSED');
assert.equal(after.canonical.metadata.supporting_context.blocks.cohort_positions.status,'CONTEXT_UNTIMED');
assert.match(after.manual.text,/VYX/);
assert.doesNotMatch(after.manual.text,/NANSEN|успешные трейдеры/);
assert.deepEqual(after.canonical.scores,before.canonical.scores);
assert.equal(after.canonical.state,before.canonical.state);
const stale=buildRuntimeCanonicalBundle({...input,observed_ts:now+200000,internal_market_context:{internal_only:true,htx_reference_price:120,candidate_sources:sources}});
assert.doesNotMatch(stale.manual.text,/VYX/);
console.log(JSON.stringify({status:'SPECIALIST_CONSUMERS_RUNTIME_PASS',statistics_collected:0,live_calls:0,weights_changed:false}));
