import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {gunzipSync} from 'node:zlib';
import crypto from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'current-generation/files');
const {RemoteD1Database}=await import(process.env.REPORT2_TEST_RUNTIME?pathToFileURL(root+'/report2-d1-adapter.mjs'):new URL('../../runner/report2-d1-adapter.mjs',import.meta.url));
const {verifyTriggeredRecheck,admitTriggeredRecheck,TRIGGERED_RECHECK_D1_RESERVATION,proveTriggeredRecheckD1Budget}=await import(pathToFileURL(root+'/src/triggered-entry-recheck.mjs'));
const {claimDueRecheck}=await import(pathToFileURL(root+'/src/recheck-scheduler.mjs'));
const {compareOrdinaryDeepCandidates}=await import(pathToFileURL(root+'/src/deep-candidate-order.mjs'));
const scheduler=await import(process.env.REPORT2_TEST_RUNTIME?pathToFileURL(root+'/src/scheduler-control.mjs'):new URL('../../post-v7-consolidated/final-reconciliation/files/src/scheduler-control.mjs',import.meta.url));
const source=JSON.parse(gunzipSync(fs.readFileSync('checkpoints/post-pr229-bome-sent-read-37682711022/exact-current-data.json.gz')));
const original=source.rows.find(r=>r.contract_code==='BOME-USDT'),c=original.canonical;
const originalBytes=JSON.stringify(c),NOW=c.observed_ts+20*60000;
const proof={schema:'EXACT_SENT_TRIGGERED_ENTRY_RECHECK_V1',source_run:c.run_id,snapshot:c.snapshot_id,publication_id:original.publication_id,fingerprint:c.analytical_fingerprint,message_id:'155',observed_ts:c.observed_ts,original_ttl:c.trigger.expires_ts,case_clock:NOW,collector_receipts:'CONTROLLED_INPUTS_AT_ORIGINAL_CLOCK_NOT_ACTUAL_MARKET_CROSSINGS',actual_ENTRY:false,sourceHTTP:0,D1:0,Telegram:0,cases:[]};
const caseDone=n=>proof.cases.push(n);
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const hash=c=>{const copy={...c};delete copy.analytical_fingerprint;return crypto.createHash('sha256').update(JSON.stringify(stable(copy))).digest('hex');};
function task(index=0,{canonical=c,now=NOW}={}){
 const r={...original,canonical:undefined,task_id:'CONTROLLED:RCHK:'+index,publication_id:index?original.publication_id+':'+index:original.publication_id,canonical_json:JSON.stringify(canonical),analytical_fingerprint:canonical.analytical_fingerprint,telegram_message_id:'155',state:'PENDING',direction:canonical.direction,due_ts:canonical.trigger.next_recheck_ts,expires_ts:canonical.trigger.expires_ts,updated_ts:now-1000,created_ts:canonical.observed_ts,attempt_count:0};
 const receipt={schema:'LIGHT_PRICE_RECHECK_V1',scope:'PRICE_AND_CANCELLATION_ONLY',status:'TRIGGER_PRICE_REACHED_FULL_ANALYSIS_REQUIRED',checked_ts:now-1000,source_ts:now-2000,observed_ts:now-1500,source:'HTX_OFFICIAL_COLLECTOR',price:canonical.trigger.value,entry_authorized:false,full_analysis_completed:false,settlement_confirmed:false,last_bucket:Math.floor((now-1000)/300000)*300000,task_id:r.task_id,publication_id:r.publication_id,run_id:r.run_id,snapshot_id:r.snapshot_id,analytical_fingerprint:r.analytical_fingerprint,telegram_message_id:r.telegram_message_id};
 r.last_result=JSON.stringify(receipt);return r;
}
function mutate(row,key,value){const r=structuredClone(row),receipt=JSON.parse(r.last_result);receipt[key]=value;r.last_result=JSON.stringify(receipt);return r;}
class D1{
 usageSnapshot(){return {rows_read:0,rows_written:0,unknown_ops:0};}
 constructor(){this.sql=new DatabaseSync(':memory:');this.sql.exec(`
 CREATE TABLE v3_recheck_task_shadow(task_id TEXT PRIMARY KEY,publication_id TEXT,contract_code TEXT,direction TEXT,wave_id TEXT,snapshot_id TEXT,run_id TEXT,due_ts INTEGER,expires_ts INTEGER,state TEXT,attempt_count INTEGER,lease_owner TEXT,lease_started_ts INTEGER,lease_expires_ts INTEGER,last_result TEXT,created_ts INTEGER,updated_ts INTEGER);
 CREATE INDEX idx_due ON v3_recheck_task_shadow(state,due_ts,expires_ts);
 CREATE TABLE canonical_publication_shadow(publication_id TEXT PRIMARY KEY,contract_code TEXT,direction TEXT,wave_id TEXT,run_id TEXT,snapshot_id TEXT,observed_ts INTEGER,analytical_fingerprint TEXT,canonical_json TEXT,actionability_status TEXT);
 CREATE TABLE v3_dispatch_publication_binding_shadow(idempotency_key TEXT PRIMARY KEY,publication_id TEXT,contract_code TEXT,direction TEXT,wave_id TEXT,run_id TEXT,snapshot_id TEXT,analytical_fingerprint TEXT,lifecycle_event TEXT,rules_version TEXT,observed_ts INTEGER);
 CREATE TABLE v3_telegram_dispatch_shadow(idempotency_key TEXT PRIMARY KEY,state TEXT,contract TEXT,direction TEXT,wave_id TEXT,telegram_message_id TEXT);
 CREATE TABLE v3_user_lifecycle_shadow(contract TEXT,direction TEXT,wave_id TEXT,rules_version TEXT,status TEXT,observation_ts INTEGER,valid_until_ts INTEGER);
 `);}
 prepare(sql){const db=this,statement=args=>({bind:(...a)=>statement(a),async run(){const r=db.sql.prepare(sql).run(...args);return {meta:{changes:r.changes}};},async first(){return db.sql.prepare(sql).get(...args)||null;},async all(){return {results:db.sql.prepare(sql).all(...args)};}});return statement([]);}
 seed(r){const fields=['task_id','publication_id','contract_code','direction','wave_id','snapshot_id','run_id','due_ts','expires_ts','state','attempt_count','last_result','created_ts','updated_ts'];this.sql.prepare('INSERT INTO v3_recheck_task_shadow('+fields.join(',')+') VALUES('+fields.map(()=>'?').join(',')+')').run(...fields.map(k=>r[k]));
  const ca=JSON.parse(r.canonical_json);this.sql.prepare('INSERT INTO canonical_publication_shadow VALUES(?,?,?,?,?,?,?,?,?,?)').run(r.publication_id,r.contract_code,r.direction,r.wave_id,r.run_id,r.snapshot_id,ca.observed_ts,r.analytical_fingerprint,r.canonical_json,'ACTIONABLE');
  const key='IDEMP:'+r.task_id;this.sql.prepare('INSERT INTO v3_dispatch_publication_binding_shadow VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(key,r.publication_id,r.contract_code,r.direction,r.wave_id,r.run_id,r.snapshot_id,r.analytical_fingerprint,'OBSERVE','RULE',ca.observed_ts);
  this.sql.prepare('INSERT INTO v3_telegram_dispatch_shadow VALUES(?,?,?,?,?,?)').run(key,'SENT',r.contract_code,r.direction,r.wave_id,r.telegram_message_id);
  this.sql.prepare('INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?)').run(r.contract_code,r.direction,r.wave_id,'RULE','OBSERVE',ca.observed_ts,r.expires_ts);
 }
}
function retainedAdapter(db){
 db.sql.exec('CREATE VIEW report2_canonical_retained_v1 AS SELECT * FROM canonical_publication_shadow');
 const requests=[];
 const remote=new RemoteD1Database('https://controlled.invalid/d1','CONTROLLED_ONLY',{fetchImpl:async(_,init)=>{
  const p=JSON.parse(init.body);requests.push(p);const stmt=db.sql.prepare(p.sql);let result,rowsWritten=0;
  if(p.op==='run'){const r=stmt.run(...p.params);rowsWritten=Number(r.changes);result={meta:{changes:rowsWritten}};}
  else if(p.op==='first')result=stmt.get(...p.params)||null;
  else if(p.op==='all')result={results:stmt.all(...p.params)};
  else throw Error('UNEXPECTED_BRIDGE_OPERATION');
  return new Response(JSON.stringify({ok:true,result,usage:{measured:true,rows_read:1,rows_written:rowsWritten}}));
 }});
 remote.enableRetainedHistory({max_fetches:0,fetch_impl:async()=>{throw Error('NO_ARCHIVED_OR_LIVE_SOURCE_REQUEST');}});
 return {remote,requests};
}
const admit=(db,now=NOW)=>admitTriggeredRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:now,admit:()=>({allowed:true})});
test('exact kicked task cannot admit another otherwise eligible SENT publication',async()=>{const db=new D1();db.seed(task());const no=await admitTriggeredRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:NOW,task_id:'OTHER_TASK',admit:()=>({allowed:true})});assert.equal(no.claimed,false);assert.equal(no.status,'NO_FRESH_EXACT_SENT_TRIGGER');assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM report2_triggered_recheck_admission').get().n,0);caseDone('EXACT_KICK_CANNOT_SELECT_OTHER_TASK');});
test('exact kicked task uses the original admission and unchanged new-analysis-only authority',async()=>{const db=new D1(),t=task();db.seed(t);const yes=await admitTriggeredRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:NOW,task_id:t.task_id,admit:()=>({allowed:true})});assert.equal(yes.claimed,true);assert.equal(yes.task.task_id,t.task_id);assert.equal(yes.entry_authorized,false);assert.equal(yes.task.expires_ts,t.expires_ts);assert.equal((await admitTriggeredRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:NOW,task_id:t.task_id,admit:()=>({allowed:true})})).claimed,false);caseDone('EXACT_KICK_PRESERVES_ORIGINAL_ADMISSION');});
test('production retained-history adapter accepts empty NOT_DUE trigger admission without source requests',async()=>{const db=new D1(),{remote,requests}=retainedAdapter(db);assert.equal((await admit(remote)).status,'NO_FRESH_EXACT_SENT_TRIGGER');assert.equal(requests.length,3);assert.equal(requests.some(p=>/report2_canonical_retained_v1/.test(p.sql)),false);caseDone('PRODUCTION_RETAINED_ADAPTER_EMPTY_NOT_DUE');});
test('production retained-history adapter separates mutable JSON selection from exact canonical restoration',async()=>{const db=new D1();db.seed(task());const {remote,requests}=retainedAdapter(db),r=await admit(remote);assert.equal(r.claimed,true);assert.equal(r.task.publication_id,original.publication_id);const reads=requests.filter(p=>/report2_canonical_retained_v1/.test(p.sql));assert.equal(reads.length,1);assert.doesNotMatch(reads[0].sql,/json_\w+\s*\(/i);assert.equal(remote.usageSnapshot().unknown_ops,0);caseDone('PRODUCTION_RETAINED_ADAPTER_EXACT_SENT_SEPARATE_READER');});
test('retained history JSON SQL guard still rejects the original mixed query and unsafe canonical parsing',async()=>{const db=new D1(),{remote,requests}=retainedAdapter(db);for(const sql of ["SELECT t.* FROM v3_recheck_task_shadow t JOIN canonical_publication_shadow p ON p.publication_id=t.publication_id WHERE json_valid(t.last_result)","SELECT json_extract(canonical_json,'$.state') FROM canonical_publication_shadow"]){await assert.rejects(remote.prepare(sql).all(),/HISTORY_JSON_SQL_REQUIRES_EXPLICIT_READER/);}assert.equal(requests.length,0);caseDone('ORIGINAL_PRODUCTION_FAILURE_AND_ARCHIVE_GUARD_REPRODUCED');});
test('original SENT155 has a reachable analysis window before the original30-minute TTL',()=>{const r=task();assert.equal(verifyTriggeredRecheck(r,{now_ts:NOW}).eligible,true);assert.equal(JSON.stringify(c),originalBytes);assert.equal(r.expires_ts,c.trigger.expires_ts);caseDone('ORIGINAL_BOME_SENT155_CLOCKS_AND_FINGERPRINT_PRESERVED_CONTROLLED_TRIGGER');});
test('receipt cannot authorize entry, execution or invented settlement',()=>{for(const k of ['entry_authorized','full_analysis_completed','settlement_confirmed'])assert.equal(verifyTriggeredRecheck(mutate(task(),k,true),{now_ts:NOW}).eligible,false);caseDone('PRICE_RECEIPT_NEVER_ENTRY');});
test('changed identity, canonical payload, absent SENT id and stale future receipts cannot enter the burst lane',()=>{for(const r of [{...task(),telegram_message_id:null},mutate(task(),'snapshot_id','FOREIGN'),mutate(task(),'analytical_fingerprint','0'.repeat(64)),mutate(task(),'source_ts',NOW+1),mutate(task(),'checked_ts',NOW-180001),{...task(),canonical_json:JSON.stringify({...c,direction:'SHORT'})}])assert.equal(verifyTriggeredRecheck(r,{now_ts:NOW}).eligible,false);caseDone('IDENTITY_FRESHNESS_GUARDS');});
test('price below trigger, cancellation, expiration and exact expiry are rejected',()=>{assert.equal(verifyTriggeredRecheck(mutate(task(),'price',.00097),{now_ts:NOW}).eligible,false);assert.equal(verifyTriggeredRecheck(mutate(task(),'status','CANCELLED'),{now_ts:NOW}).eligible,false);assert.equal(verifyTriggeredRecheck(task(),{now_ts:c.trigger.expires_ts}).status,'ORIGINAL_TRIGGER_WINDOW_CLOSED');assert.equal(verifyTriggeredRecheck(task(),{now_ts:c.trigger.next_recheck_ts-1}).eligible,false);caseDone('PRICE_CANCELLATION_AND_ORIGINAL_TTL');});
test('SHORT uses its own threshold and cancellation without reversing native conditions',()=>{const s=structuredClone(c);s.direction='SHORT';s.trigger.operator='<=';s.trigger.value=.00096;s.trigger.cancel_condition='price>0.001';s.analytical_fingerprint=hash(s);assert.equal(verifyTriggeredRecheck(task(0,{canonical:s}),{now_ts:NOW}).eligible,true);assert.equal(verifyTriggeredRecheck(mutate(task(0,{canonical:s}),'price',.0011),{now_ts:NOW}).eligible,false);caseDone('CONTROLLED_SHORT');});
test('exact SENT trigger admits one candidate without consuming or renewing ordinary cadence',async()=>{const db=new D1();db.seed(task());const r=await admit(db);assert.equal(r.claimed,true);assert.equal(r.max_per_run,1);assert.equal(r.entry_authorized,false);assert.equal(r.task.expires_ts,c.trigger.expires_ts);assert.equal(db.sql.prepare('SELECT count(*) n FROM report2_triggered_recheck_admission').get().n,1);assert.equal(db.sql.prepare('SELECT state FROM v3_recheck_task_shadow').get().state,'PENDING');caseDone('DURABLE_ONE_CANDIDATE_BURST_ADMISSION');});
for(const triggerOnly of [false,true])test(triggerOnly?'the actual exact-kick runner bypasses only the regular cadence claim and preserves its clock':'the actual runner NOT_DUE branch continues into a fresh exact full recheck and preserves the regular clock',async()=>{
 const db=new D1();db.seed(task());db.sql.exec(`CREATE TABLE v3_scheduler_job_ownership_shadow(job_key TEXT PRIMARY KEY,owner TEXT,updated_ts INTEGER);INSERT INTO v3_scheduler_job_ownership_shadow VALUES('PERIODIC_ANALYTICS','GITHUB_ACTIONS',0);CREATE TABLE v3_maintenance_cadence_shadow(job_key TEXT PRIMARY KEY,interval_ms INTEGER,last_success_ts INTEGER,lease_owner TEXT,lease_started_ts INTEGER,lease_expires_ts INTEGER,updated_ts INTEGER,shadow_only INTEGER,last_result TEXT);`);
 const prior=c.observed_ts-(triggerOnly?3600000:60000);db.sql.prepare('INSERT INTO v3_maintenance_cadence_shadow VALUES(?,2400000,?,NULL,NULL,NULL,?,1,?)').run('TWO_CANDIDATE_ANALYTICS_40M',prior,prior,'ATTEMPT_ADMITTED');
 const runner=fs.readFileSync(root+'/runner-main.mjs','utf8'),start=runner.indexOf("  if(source==='schedule'){",runner.indexOf("console.log('TWO_CANDIDATE_EXECUTION_BUDGET'")),end=runner.indexOf('  if(manualCommandClaim.claimed&&',start);
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 const call=new AsyncFunction('source','env','preflight','manualCommandActor','started','TWO_CANDIDATE_PLAN','actorOwnsPeriodicAnalytics','claimMaintenanceCadence','completeMaintenanceCadence','releaseAnalyticsLease','console','admitTriggeredRecheck','loadDailyUsageAggregate','evaluateDailyReservationBudget','envNumber','TRIGGERED_RECHECK_D1_RESERVATION','proveTriggeredRecheckD1Budget','reserveRunBudget','finalizeRunUsage','sha','triggerOnly','triggerKickTaskId',runner.slice(start,end)+"\nreturn 'ANALYTICS_ADMITTED';");
 const env={DATA_DB:retainedAdapter(db).remote,REPORT2_DEEP_RUNTIME_OPTIONS:{execution_runtime:'GITHUB_ACTIONS_NODE',max_per_run:2}};let releaseCount=0,budgetCount=0,reserved=0,finalized=0;
 const result=await call('schedule',env,{actor:'GITHUB_ACTIONS'},'EXACT_NODE',NOW,{scheduled_interval_minutes:40,d1_run_cap:{rows_read:54000,rows_written:840}},scheduler.actorOwnsPeriodicAnalytics,scheduler.claimMaintenanceCadence,scheduler.completeMaintenanceCadence,async()=>{releaseCount++;return {finished:true};},{log(){}},admitTriggeredRecheck,async()=>({}),args=>{budgetCount++;assert.deepEqual(args.nextReservation,{rows_read:55500,rows_written:856});return {allowed:true};},(_,v)=>v,TRIGGERED_RECHECK_D1_RESERVATION,proveTriggeredRecheckD1Budget,async(_,args)=>{reserved++;assert.deepEqual(args.reservation,TRIGGERED_RECHECK_D1_RESERVATION);},async()=>{finalized++;},'CONTROLLED_RUNTIME_HASH',triggerOnly,task().task_id);
 assert.equal(result,'ANALYTICS_ADMITTED');assert.equal(releaseCount,0);assert.equal(budgetCount,1);assert.equal(reserved,1);assert.equal(finalized,1);assert.equal(env.REPORT2_TRIGGERED_RECHECK_TASK_ID,task().task_id);assert.equal(env.REPORT2_DEEP_RUNTIME_OPTIONS.max_per_run,1);assert.equal(db.sql.prepare('SELECT last_success_ts FROM v3_maintenance_cadence_shadow').get().last_success_ts,prior);caseDone('ACTUAL_RUNNER_NOT_DUE_BRANCH_CONNECTED');
});
test('all72 possible admission ledgers still fit the unchanged daily D1 allowance',()=>{const p=proveTriggeredRecheckD1Budget();assert.equal(p.safe,true);assert.equal(p.maximum_planned_rows_read,3498020);assert.equal(p.maximum_planned_rows_written,69664);caseDone('ALL_72_ADMISSION_LEDGERS_D1_WORST_CASE');});
test('duplicate attempts and concurrent executors cannot charge or launch a fourth daily burst',async()=>{const db=new D1();for(let i=0;i<4;i++)db.seed(task(i));for(let i=0;i<3;i++)assert.equal((await admit(db)).claimed,true);assert.equal((await admit(db)).status,'DAILY_BURST_CAP_OR_CONCURRENT_ADMISSION');assert.equal(db.sql.prepare('SELECT count(*) n FROM report2_triggered_recheck_admission').get().n,3);caseDone('THREE_DAILY_BURSTS_AND_DEDUP_NO_REFUND');});
test('unsent or foreign-wave lifecycle cannot admit full analysis',async()=>{for(const q of ["UPDATE v3_telegram_dispatch_shadow SET state='PENDING'","UPDATE v3_user_lifecycle_shadow SET wave_id='FOREIGN'","UPDATE v3_dispatch_publication_binding_shadow SET analytical_fingerprint='FOREIGN'","UPDATE canonical_publication_shadow SET actionability_status='REJECTED'"]){const db=new D1();db.seed(task());db.sql.exec(q);assert.equal((await admit(db)).claimed,false);}caseDone('EXACT_CURRENT_SENT_SQL_JOIN');});
test('a foreign actor and exhausted D1 budget create no admission tables or source calls',async()=>{const db=new D1();assert.equal((await admitTriggeredRecheck(db,{actor:'CLOUDFLARE',now_ts:NOW,admit:()=>({allowed:true})})).claimed,false);assert.equal((await admitTriggeredRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:NOW,admit:()=>({allowed:false})})).status,'D1_BUDGET_BLOCKED');assert.equal(db.sql.prepare("SELECT count(*) n FROM sqlite_master WHERE name='report2_triggered_recheck_admission'").get().n,0);caseDone('OWNER_AND_D1_ADMISSION');});
test('targeted scheduler selects the admitted task even when an older waiting task exists',async()=>{const db=new D1(),older=task(1),target=task();older.due_ts-=1;older.last_result=JSON.stringify({...JSON.parse(older.last_result),status:'WAITING_FOR_PRICE'});db.seed(older);db.seed(target);const admission=await admit(db);assert.equal(admission.task.task_id,target.task_id);const claim=await claimDueRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:NOW,task_id:admission.task.task_id});assert.equal(claim.claimed,true);assert.equal(claim.task.task_id,target.task_id);assert.equal(db.sql.prepare('SELECT state FROM v3_recheck_task_shadow WHERE task_id=?').get(older.task_id).state,'PENDING');caseDone('EXACT_TARGET_CLAIM_NO_OLDER_TASK_SUBSTITUTION');});
test('cancellation or expiry between admission and worker claim never falls back to another coin',async()=>{for(const change of ["state='CANCELLED'","expires_ts="+NOW,"last_result='{}'"]){const db=new D1();db.seed(task());db.seed(task(1));const a=await admit(db);db.sql.exec('UPDATE v3_recheck_task_shadow SET '+change+" WHERE task_id='"+a.task.task_id+"'");const r=await claimDueRecheck(db,{actor:'GITHUB_ACTIONS',now_ts:NOW,task_id:a.task.task_id});assert.equal(r.claimed,false);assert.equal(db.sql.prepare("SELECT state FROM v3_recheck_task_shadow WHERE task_id='CONTROLLED:RCHK:1'").get().state,'PENDING');}caseDone('POST_ADMISSION_CANCEL_EXPIRE_NO_FALLBACK');});
test('the effective deep planner rechecks the exact contract inside the30-minute cooldown at one slot',()=>{const worker=fs.readFileSync(root+'/src/worker.js','utf8'),body=worker.match(/function buildBoundedDeepCheckPlan\([\s\S]*?\n\}/)?.[0];assert.ok(body);const plan=new Function('schedulerNumber','compareOrdinaryDeepCandidates',`const STAGE0_EXTERNAL_REQUESTS=4,DEEP_CHECK_EXTERNAL_REQUESTS=39,SMART_MONEY_EXTERNAL_REQUESTS=1,WORKERS_FREE_EXTERNAL_LIMIT=50,EXTERNAL_REQUEST_RESERVE=6;${body};return buildBoundedDeepCheckPlan;`)(v=>v==null?null:Number(v),compareOrdinaryDeepCandidates);
 const shortlist=[{contract:'BOME-USDT',priority_rank:0},{contract:'OTHER-USDT',priority_rank:1}],rows=[{contract_code:'BOME-USDT',last_deep_check_ts:c.observed_ts}];
 const options={execution_runtime:'GITHUB_ACTIONS_NODE',max_per_run:1,confirmed_scope_contracts:['BOME-USDT','OTHER-USDT'],require_exact_contract:true,required_contract:'BOME-USDT',cooldown_sec:1800};
 const result=plan({shortlist},rows,NOW,{...options,bypass_cooldown:true,cooldown_sec:0});assert.deepEqual(result.selected.map(r=>r.contract),['BOME-USDT']);assert.equal(result.selected.length,1);
 assert.match(worker,/task_id:env\?\.REPORT2_TRIGGERED_RECHECK_TASK_ID\|\|null/);assert.match(worker,/TRIGGERED_RECHECK_CLAIM_NOT_CLOSED/);assert.match(worker,/Boolean\(env\?\.REPORT2_TRIGGERED_RECHECK_TASK_ID\).*postV7RecheckClaim/);caseDone('ASSEMBLED_DEEP_PLANNER_EXACT_SINGLE_SLOT_COOLDOWN');});
test.after(()=>{assert.equal(JSON.stringify(c),originalBytes);fs.mkdirSync('audit-output',{recursive:true});fs.writeFileSync('audit-output/triggered-recheck-proof.json',JSON.stringify({...proof,canonical_unchanged:true},null,2)+'\n');});

// The production SENT159 and SENT160 lifecycle context expires BEFORE their
// first scheduled price check. This is separate from the original30min task.
test('an expired prior analytical context cannot shorten the exact SENT task window for a new full analysis',async()=>{
 const db=new D1(),row=task();db.seed(row);db.sql.prepare('UPDATE v3_user_lifecycle_shadow SET valid_until_ts=?').run(row.due_ts-1000);
 const before=db.sql.prepare('SELECT valid_until_ts FROM v3_user_lifecycle_shadow').get().valid_until_ts;
 const result=await admit(db);assert.equal(result.claimed,true);assert.equal(result.entry_authorized,false);assert.equal(result.task.expires_ts,row.expires_ts);
 assert.equal(db.sql.prepare('SELECT valid_until_ts FROM v3_user_lifecycle_shadow').get().valid_until_ts,before);assert.equal(JSON.stringify(c),originalBytes);
});
test('original task expiry and changed lifecycle still reject analysis even when the prior context has expired',async()=>{
 for(const update of ["status='IDEA_REMOVED'","observation_ts=observation_ts+1","direction='SHORT'"]){const db=new D1();db.seed(task());db.sql.exec('UPDATE v3_user_lifecycle_shadow SET valid_until_ts=0,'+update);assert.equal((await admit(db)).claimed,false);}
 const db=new D1(),r=task();db.seed(r);db.sql.prepare('UPDATE v3_user_lifecycle_shadow SET valid_until_ts=?').run(r.due_ts-1000);assert.equal((await admit(db,r.expires_ts)).claimed,false);
});
test('original SENT159 canonical and retained reached price reproduce the old clock veto; SENT160 unreached price stays blocked',async()=>{
 const file='checkpoints/ORIGINAL_LIFECYCLE_TRIGGER_CLOCKS_20261008.json',bytes=fs.readFileSync(file),actual=JSON.parse(bytes),prices=JSON.parse(fs.readFileSync('checkpoints/ORIGINAL_TRIGGER_PRICE_WINDOWS_20261008.json'));
 assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+bytes.length+'\0'),bytes])).digest('hex'),'d2331a4a9214857896379d3b4a53957d27947771');
 const savedHash=crypto.createHash('sha256').update(bytes).digest('hex'),results=[];
 class PriorClockD1 extends D1{prepare(sql){return super.prepare(sql.replace('l.observation_ts=b.observed_ts','l.observation_ts=b.observed_ts AND l.valid_until_ts>?1'));}}
 for(const input of actual.cases){
  assert.equal(input.original_row_exact,true);assert.equal(input.lifecycle_expires_before_due,true);
  const canonical=JSON.parse(input.publication.canonical_json),history=prices.cases.find(c=>c.publication_id===input.publication_id),point=history.points.find(p=>p.ts_bucket===(input.contract==='NEAR-USDT'?1791459900000:1791471300000));
  assert.ok(point);assert.equal(hash(canonical),input.analytical_fingerprint);const now=point.ts+60000;
  const r={...input.task,state:'PENDING',canonical_json:input.publication.canonical_json,analytical_fingerprint:input.analytical_fingerprint,telegram_message_id:input.receipt.telegram_message_id,updated_ts:point.ts+1000};
  r.last_result=JSON.stringify({schema:'LIGHT_PRICE_RECHECK_V1',scope:'PRICE_AND_CANCELLATION_ONLY',status:point.trigger_price_reached&&!point.cancel_price_reached?'TRIGGER_PRICE_REACHED_FULL_ANALYSIS_REQUIRED':'WAITING_FOR_PRICE',checked_ts:point.ts+1000,source_ts:point.ts,observed_ts:point.ts,source:'HTX_OFFICIAL_COLLECTOR',price:point.price,entry_authorized:false,full_analysis_completed:false,settlement_confirmed:false,task_id:r.task_id,publication_id:r.publication_id,run_id:r.run_id,snapshot_id:r.snapshot_id,analytical_fingerprint:r.analytical_fingerprint,telegram_message_id:r.telegram_message_id});
  const setup=db=>{db.seed(r);db.sql.prepare('UPDATE v3_user_lifecycle_shadow SET valid_until_ts=?').run(input.lifecycle.valid_until_ts);return db;};
  const prior=await admit(setup(new PriorClockD1()),now),current=await admit(setup(new D1()),now);
  assert.equal(prior.claimed,false);assert.equal(current.claimed,input.contract==='NEAR-USDT');assert.equal(current.entry_authorized,false);
  if(current.claimed){assert.equal(current.task.snapshot_id,input.snapshot_id);assert.equal(current.task.analytical_fingerprint,input.analytical_fingerprint);assert.equal(current.task.expires_ts,input.original_trigger.expires_ts);}
  results.push({contract:input.contract,publication_id:input.publication_id,source_run:input.run_id,source_head:input.source_head,source_snapshot:input.snapshot_id,fingerprint:input.analytical_fingerprint,actual_SENT_message_id:input.receipt.telegram_message_id,original_lifecycle_until:input.lifecycle.valid_until_ts,original_due:input.original_trigger.next_recheck_ts,original_expires:input.original_trigger.expires_ts,original_price:point.price,original_price_ts:point.ts,controlled_receipt_at_original_clock:true,old_admission:prior.status,new_admission:current.status,entry_authorized:false});
 }
 assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),savedHash);
 fs.mkdirSync('audit-output',{recursive:true});fs.writeFileSync('audit-output/actual-lifecycle-trigger-replay.json',JSON.stringify({schema:'ACTUAL_ORIGINAL_SENT_CLOCK_VETO_REPLAY_V1',original_blob_sha:'d2331a4a9214857896379d3b4a53957d27947771',original_bytes_sha256:savedHash,cases:results,scope:'ORIGINAL_CANONICAL_LIFECYCLE_AND_RETAINED_PRICE_CONTROLLED_RECEIPT_REPLAY_NOT_HISTORICAL_MUTABLE_RECEIPT_READ_OR_ACTUAL_ENTRY',sourceHTTP:0,D1:0,MAIN:0,Telegram:0,source_clocks_refreshed:false,actual_ENTRY:false},null,2)+'\n');
});

