import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(process.argv[2]||'runtime');
const source=fs.readFileSync(path.join(runtime,'src/worker.js'),'utf8').replace(/from (['"])\.\/([^'"\n]+)\1/g,(_,q,name)=>`from ${JSON.stringify(pathToFileURL(path.join(runtime,'src',name)).href)}`);
const api=await import('data:text/javascript;base64,'+Buffer.from(source+'\nexport { buildTrajectoryWindow, bindVerifiedFuturesFlow };\n').toString('base64'));
const END=1790788020000,START=END-900000,NOW=END+30000;
const klines=Array.from({length:15},(_,i)=>({ts:START+i*60000,open:100,high:101,low:99,close:100,volume_contracts:1,volume_base:1,turnover_usdt:100,trade_count:1}));
const orderedTrades=klines.map((r,i)=>({'trade-id':`exact-${i}`,ts:r.ts,price:100,amount:1,quantity:1,trade_turnover:100,direction:i%2?'buy':'sell'}));
const window=api.buildTrajectoryWindow({label:'15m',startMs:START,endMs:END,klines,orderedTrades,contractSize:1,minTrades:10,oi:null});
assert.equal(window.order_flow.usable,true);
const common={contract:'NIL-USDT',source:'HTX official public API',market:'HTX USDT-M Futures',timestamp:NOW-1000,contract_info:{contract_code:'NIL-USDT',contract_size:1}};
const snapshot={...common,coverage:{htx_futures_order_flow:'not_closed'},order_flow:{raw_delta_is_diagnostic_only:true}};
const trajectory={...common,coverage:{flow_15m:'closed',flow_24h:'not_closed'},windows:{'15m':window}};
const result=api.bindVerifiedFuturesFlow(snapshot,trajectory,NOW);
assert.equal(result.coverage.htx_futures_order_flow,'closed');assert.equal(result.verified_order_flow.binding.raw_trade_count,15);
assert.equal(result.order_flow,snapshot.order_flow);assert.equal(trajectory.coverage.flow_24h,'not_closed');
const missing=api.buildTrajectoryWindow({label:'15m',startMs:START,endMs:END,klines,orderedTrades:orderedTrades.slice(1),contractSize:1,minTrades:10,oi:null});
assert.equal(api.bindVerifiedFuturesFlow(snapshot,{...trajectory,windows:{'15m':missing}},NOW),snapshot);
assert.match(source,/futures.data = bindVerifiedFuturesFlow\(futures.data, trajectory.data, componentsAvailableTs\)/);
console.log(JSON.stringify({status:'EXACT_ASSEMBLED_VERIFIED_FLOW_BINDING_PASS',producer:'REAL_WORKER_TRAJECTORY',window:'15m',same_contract:true,missing_trade_rejected:true,unwindowed_sample_diagnostic:true,full_24h_not_claimed:true,additional_directional_votes:0,external_http_calls:0,d1_writes:0,telegram_calls:0}));
