import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';import {wireFixture} from './volume-profile-fixture.mjs';
const runtime=path.resolve(process.argv[2]||'runtime'),imp=file=>import(pathToFileURL(path.join(runtime,'src',file)).href),{parseHtxMarketJson}=await imp('htx-trade-json.mjs'),{buildRuntimeCanonicalBundle}=await imp('canonical-runtime-adapter.mjs'),{readReadyHtxVolumeProfile,clearVolumeProfileSnapshots}=await imp('htx-volume-profile.mjs');
const f=wireFixture(),now=f.provenance.now,contract='QNT-USDT';
const input={contract,run_id:'VOLUME_REPLAY',snapshot_id:'VOLUME_REPLAY',observed_ts:now,discovery_row:{contract,current_price:296.22,early_candidate_bridge:true,early_candidate_quality_0_100:70,early_candidate_wave_id:'W',early_candidate_receipt:{status:'CLOSED',contract,wave_id:'W',direction_hint:'LONG',direction_state:'CONFIRMED',source_ts:now-1000,available_at:now-1000,evidence:[{status:'CLOSED',side:'LONG'}],evidence_ids:['FIXTURE']}},publication_shadow:{entry_signal:{state:'REJECTED',hard_veto:true,direction:'LONG'}}};
clearVolumeProfileSnapshots();const before=buildRuntimeCanonicalBundle(input);const clock=Date.now;Date.now=()=>now;
try{parseHtxMarketJson(f['1'],`https://api.hbdm.com/linear-swap-api/v1/swap_contract_info?contract_code=${contract}`);parseHtxMarketJson(f['2'],`https://api.hbdm.com/linear-swap-ex/market/history/kline?contract_code=${contract}&period=1min`);parseHtxMarketJson(f['10'],`https://api.hbdm.com/linear-swap-ex/market/history/trade?contract_code=${contract}`);}finally{Date.now=clock;}
const profile=readReadyHtxVolumeProfile({contract,now});assert.equal(profile.status,'CLOSED');const after=buildRuntimeCanonicalBundle(input);
assert.equal(before.canonical.scores.coin_interest_0_100,70);assert.equal(after.canonical.scores.coin_interest_0_100,70);assert.equal(after.canonical.state,'REJECTED','volume cannot bypass a hard veto or absent plan');assert.equal(after.canonical.metadata.supplemental_score_adjustment.adjustment,0);assert.equal(after.canonical.metadata.supporting_context.blocks.volume_profile.unique_trades,1257);assert.match(after.manual.text,/Боковой объём HTX/);assert.match(after.manual.text,/284.9975/);assert.ok(JSON.stringify(after.telegram).includes('Боковой объём HTX'));
const comparable=readReadyHtxVolumeProfile({contract,now,window_minutes:240,window_end:profile.window_end-120000});assert.equal(comparable.status,'CLOSED');
// Peer agreement is an explicitly synthetic control; the HTX history is real.
const peers={BINANCE:{profiles:[{...comparable,source:'BINANCE'}]},BYBIT:{profiles:[{...comparable,source:'BYBIT'}]}};const agreed=buildRuntimeCanonicalBundle({...input,internal_market_context:{cross_exchange_risk:{volume_profiles:{sources:peers}}}});assert.equal(agreed.canonical.metadata.supplemental_score_adjustment.adjustment,1.5);assert.equal(agreed.canonical.scores.coin_interest_0_100,72);assert.match(agreed.manual.text,/BINANCE\+BYBIT/);assert.equal(agreed.canonical.state,'REJECTED');
const stale=buildRuntimeCanonicalBundle({...input,observed_ts:now+181000});assert.doesNotMatch(stale.manual.text,/Боковой объём HTX/);clearVolumeProfileSnapshots();
console.log(JSON.stringify({status:'VOLUME_PROFILE_RUNTIME_PASS',existing_source_run:36704685645,minutes:240,unique_trades:1257,score_before:70,single_venue_score:70,single_venue_zero_reason:'ONE_CONFIRMING_MINUTE_HAS_NO_TRADES',synthetic_agreement_control_score:72,hard_veto_preserved:true,manual_and_telegram:'PASS',new_history_accumulated:false,live_calls:0}));
