import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=path.resolve(process.env.REPORT2_TEST_RUNTIME||'runtime'),load=f=>import(pathToFileURL(path.join(root,'src',f)));
const {normalizeWikimediaAttention,collectWikimediaAttention,exactWikimediaPage}=await load('wikimedia-attention-context.mjs'),{consumeBlockResultContext}=await load('block-result-context.mjs'),{consumeEvidenceV2}=await load('evidence-v2.mjs'),{buildRuntimeCanonicalBundle}=await load('canonical-runtime-adapter.mjs'),{writeEvidenceSourceCache}=await load('evidence-source-store.mjs');
const NOW=Date.parse('2026-10-07T20:00:00Z'),DAY=86400000,identity=chain=>({chain,asset_kind:'NATIVE',native_asset_id:chain+':mainnet',contract_or_mint:null}),params=(contract,chain,page)=>({contract,asset_identity:identity(chain),observed_ts:NOW,payload:{items:Array.from({length:14},(_,i)=>({project:'en.wikipedia',article:page,access:'all-access',agent:'user',granularity:'daily',timestamp:new Date(Math.floor(NOW/DAY)*DAY-15*DAY+i*DAY).toISOString().slice(0,10).replaceAll('-','')+'00',views:i<7?100:200}))}}),ETH=params('ETH-USDT','ethereum','Ethereum'),BTC=params('BTC-USDT','bitcoin','Bitcoin'),SOL=params('SOL-USDT','solana','Solana_(blockchain_platform)'),DOGE=params('DOGE-USDT','dogecoin','Dogecoin');
function db(){const sqlite=new DatabaseSync(':memory:');return{prepare(sql){return{args:[],bind(...args){this.args=args;return this;},async run(){return sqlite.prepare(sql).run(...this.args);},async first(){return sqlite.prepare(sql).get(...this.args)||null;}};},async batch(rows){return Promise.all(rows.map(x=>x.run()));}};}
test('exact native network registry covers five verified pages without ticker or wrapped bindings',()=>{for(const p of [ETH,BTC,SOL,DOGE,params('ADA-USDT','cardano','Cardano_(blockchain_platform)')]){assert.equal(exactWikimediaPage(p),p.payload.items[0].article);for(const bad of [{...p.asset_identity,asset_kind:'WRAPPED'},{...p.asset_identity,native_asset_id:p.asset_identity.chain+':testnet'},{...p.asset_identity,contract_or_mint:'0x'+'1'.repeat(40)}])assert.equal(exactWikimediaPage({...p,asset_identity:bad}),null);}assert.equal(exactWikimediaPage({...BTC,contract:'BCH-USDT'}),null);});
for(const p of [ETH,BTC,SOL,DOGE])test(p.contract+' actual consumer and canonical report remain direction and score neutral',()=>{const r=normalizeWikimediaAttention(p);assert.equal(r.status,'CLOSED');assert.equal(r.evidence[0].asset_id,p.asset_identity.chain+':native:mainnet');const c=consumeBlockResultContext({evidence:r.evidence,contract:p.contract,now:NOW});assert.equal(c.facts.length,1);const input={contract:p.contract,run_id:'WIKI_CONTROL',snapshot_id:'WIKI_CONTROL:'+p.contract,observed_ts:NOW},before=buildRuntimeCanonicalBundle(input),after=buildRuntimeCanonicalBundle({...input,internal_market_context:{internal_only:true,evidence_v2:{evidence:r.evidence,sources:{WIKIMEDIA_ATTENTION:r}}}});assert.ok(after.manual.text.includes('Внимание к статье '+p.payload.items[0].article));assert.deepEqual(after.canonical.scores,before.canonical.scores);assert.equal(after.canonical.direction,before.canonical.direction);assert.equal(after.canonical.state,before.canonical.state);assert.deepEqual(after.canonical.targets,before.canonical.targets);assert.equal(consumeEvidenceV2(r.evidence,{base_interest:70,decision_ts:NOW}).adjustment,0);});
test('foreign contract, asset, page and URL cannot pass the assigned consumer',()=>{const r=normalizeWikimediaAttention(ETH);for(const mutate of [x=>x.asset_id='solana:native:mainnet',x=>x.article='Solana_(blockchain_platform)',x=>x.page_url='https://en.wikipedia.org/wiki/Solana_(blockchain_platform)',x=>x.asset_id='bitcoin:native:mainnet',x=>x.htx_contract='BTC-USDT',x=>x.article='Bitcoin',x=>x.page_url='https://en.wikipedia.org/wiki/Bitcoin']){const row=structuredClone(r.evidence[0]);mutate(row);assert.equal(consumeBlockResultContext({evidence:[row],contract:row.htx_contract,now:NOW}).facts.length,0);}});
test('missing duplicate stale future or bot days cannot become current pageview totals',()=>{for(const mutate of [r=>r.pop(),r=>r[0].timestamp=r[1].timestamp,r=>r[0].timestamp='2020010100',r=>r[0].timestamp='2099010100',r=>r[0].agent='all-agents']){const payload=structuredClone(ETH.payload);mutate(payload.items);assert.notEqual(normalizeWikimediaAttention({...ETH,payload}).status,'CLOSED');}});
test('cache HIT retains source clocks and reports zero HTTP and no old reservation',async()=>{const database=db();let calls=0;const b={db:database,contract:ETH.contract,asset_identity:ETH.asset_identity,now:NOW,clock:()=>NOW,request_admit:()=>({allowed:true}),fetch_impl:async()=>{calls++;return new Response(JSON.stringify(ETH.payload));}};const first=await collectWikimediaAttention({...b,run_id:'W1'}),hit=await collectWikimediaAttention({...b,run_id:'W2',now:NOW+1000});assert.equal(hit.status,'CLOSED');assert.equal(hit.network_calls,0);assert.equal(hit.admission,null);assert.equal(hit.evidence[0].source_ts,first.evidence[0].source_ts);assert.equal(hit.evidence[0].observed_ts,first.evidence[0].observed_ts);assert.equal(calls,1);});
test('copied foreign cache cannot substitute an exact native asset',async()=>{const database=db();let calls=0;const b={db:database,contract:ETH.contract,asset_identity:ETH.asset_identity,now:NOW,clock:()=>NOW,request_admit:()=>({allowed:true}),fetch_impl:async()=>{calls++;return new Response(JSON.stringify(ETH.payload));}};await collectWikimediaAttention({...b,run_id:'W3'});const cached=normalizeWikimediaAttention(BTC);await writeEvidenceSourceCache(database,{source:'WIKIMEDIA_ATTENTION',asset_key:'wikimedia-attention-v2-exact-native-pages-20261007:Ethereum',observed_ts:NOW,expires_ts:NOW+10000,payload:cached});const result=await collectWikimediaAttention({...b,run_id:'W4'});assert.equal(result.evidence[0].htx_contract,'ETH-USDT');assert.equal(calls,2);});
test('negative observation clock and overflowing totals remain unclosed',()=>{assert.notEqual(normalizeWikimediaAttention({...ETH,observed_ts:-1}).status,'CLOSED');const payload=structuredClone(ETH.payload);payload.items.forEach(x=>x.views=Number.MAX_SAFE_INTEGER);assert.notEqual(normalizeWikimediaAttention({...ETH,payload}).status,'CLOSED');});
fs.mkdirSync('audit-output',{recursive:true});fs.writeFileSync('audit-output/wikimedia-native-pages-controlled-proof.json',JSON.stringify({schema:'WIKIMEDIA_NATIVE_PAGES_CONTROLLED_20261007_V1',sourceHTTP:0,D1:0,MAIN:0,Telegram:0,synthetic_inputs_labelled:true,source_clocks_refreshed:false})+'\n');
