import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const root=path.resolve(process.argv[2]||'runtime'),load=p=>import(pathToFileURL(path.join(root,p))),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const {RemoteD1Database}=await load('report2-d1-adapter.mjs'),{collectSpecialistContext,consumeSpecialistContext}=await load('src/specialist-candidate-context.mjs'),{compileOfficialSourceRegistry}=await load('src/official-source-registry.mjs'),{nansenFlowEvidence,resolveNansenFlowPrimary,auditCandidateBlocks}=await load('src/candidate-evidence-v2-runtime.mjs'),{consumeBlockResultContext}=await load('src/block-result-context.mjs'),{consumeEvidenceV2}=await load('src/evidence-v2.mjs'),{buildRuntimeCanonicalBundle}=await load('src/canonical-runtime-adapter.mjs'),{createUnifiedHttpBudget}=await load('src/unified-budget.mjs');
const phase=JSON.parse(fs.readFileSync('checkpoints/CLOUD_PHASE_STATE_20261004.json'));assert.equal(phase.current_phase,'CORE_BLOCKS');assert.equal(phase.lease?.owner,process.env.REPORT2_CONTINUATION_OWNER);assert.ok(phase.lease.expires_ts>Date.now());
const universeBytes=fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'),universe=JSON.parse(zlib.gunzipSync(universeBytes));assert.equal(universe.assets.length,102);assert.equal(universe.contracts.length,119);assert.ok(universe.assets.some(x=>x.symbol==='BTW'));
const metadata=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'main-official-event-sources.json')))).registry.BTW,identity={chain:metadata.chain,contract_or_mint:metadata.contract_or_mint};assert.equal(identity.chain,'bsc');assert.equal(identity.contract_or_mint,'0x444045b0ee1ee319a660a5e3d604ca0ffa35acaa');
const files=['src/candidate-evidence-v2-runtime.mjs','src/specialist-candidate-context.mjs'],runtime_sha256=Object.fromEntries(files.map(p=>{const h=hash(fs.readFileSync(path.join(root,p)));assert.equal(h,hash(fs.readFileSync(path.join('current-generation/files',p))));return[p,h];}));
const db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN),budget=createUnifiedHttpBudget(),run_id=`GENERAL_LABELLED_FLOW:${process.env.GITHUB_RUN_ID}`,raw=[],results=[],now=Date.now();let acquisition=null;
function save(error=null){fs.writeFileSync('audit-output/labelled-flow-source-body.json',JSON.stringify(raw)+'\n');fs.writeFileSync('audit-output/labelled-flow-live-verification.json',JSON.stringify({schema:'report2-general-labelled-flow-acceptance-v1',github_head:process.env.GITHUB_SHA,run_id,error,runtime_sha256,common_universe_sha256:hash(universeBytes),common_future_assets:102,common_future_contracts:119,acquisition,results,source_http:raw.length,database_usage:db.usageSnapshot(),limits:{official_flow_credits:1,free_daily_top_up_balance:10,provider_free_per_second:15,provider_free_per_minute:300,shared_internal_nansen_attempts_per_day:8,ordinary_and_manual_share_same_ledger:true,retries:0,maximum_source_http:1,shared_job_http:164,no_paid_top_up_or_pay_per_request:true},production_canonical_writes:0,full_main_acceptance:false,all_15_live_accepted:false,telegram_calls:0,telegram_delivery_proven:false},null,2)+'\n');}process.on('uncaughtExceptionMonitor',e=>save(String(e)));
const params={contract:'BTW-USDT',asset_identity:identity,identity_method:'HTX_OFFICIAL_CURRENCY_CHAIN_ADDRESS',now};
const cachedRow=await db.prepare('SELECT payload_json FROM report2_candidate_source_cache WHERE contract_code=?1 AND source=?2 AND expires_ts>?3').bind(params.contract,'NANSEN_FLOWS',now).first();let source=null;
try{const cached=JSON.parse(cachedRow?.payload_json||'null');if(nansenFlowEvidence(cached,params).length)source=cached;}catch{}
if(source)acquisition={status:'VALIDATED_CURRENT_EXACT_SOURCE_CACHE',actual_http:0,source_observed_ts:source.observed_ts};
else{
 assert.ok(process.env.NANSEN_API_KEY,'EXISTING_NANSEN_KEY_UNAVAILABLE_NO_NEW_SOURCE_ENABLE');const admission=budget.reserve({logical_request_id:run_id,lane:'background',attempts:1});assert.equal(admission.allowed,true);
 const fetch_impl=async(url,opts)=>{assert.equal(String(url),'https://api.nansen.ai/api/v1/tgm/flows');assert.equal(raw.length,0);const request=JSON.parse(opts.body);assert.equal(request.chain,'bnb');assert.equal(request.token_address,identity.contract_or_mint);assert.equal(request.label,'exchange');const response=await fetch(url,opts),body=await response.clone().text();raw.push({url:String(url),request,http_status:response.status,observed_ts:Date.now(),body_sha256:hash(body),body,credit_cost:response.headers.get('X-Nansen-Credits-Cost'),credit_used:response.headers.get('X-Nansen-Credits-Used'),credit_remaining:response.headers.get('X-Nansen-Credits-Remaining')});save();return response;};
 acquisition=await collectSpecialistContext({db,fetch_impl,base:'BTW',asset_identity:identity,now,remaining:1,nansen_api_key:process.env.NANSEN_API_KEY});source=acquisition.payloads.find(x=>x.source==='NANSEN_FLOWS')?.payload;
 for(const receipt of raw)if(receipt.credit_cost!==null)assert.equal(Number(receipt.credit_cost),1);assert.ok(raw.length<=1);
}
const observed_ts=Date.now(),currentParams={...params,now:observed_ts},resolved=resolveNansenFlowPrimary(source,currentParams);assert.equal(resolved.status,'CLOSED',JSON.stringify(acquisition));const evidence=nansenFlowEvidence(source,currentParams);assert.equal(evidence.length,1);assert.equal(evidence[0].label_authority,'NANSEN');assert.equal(evidence[0].individual_addresses_verified,false);
const context=consumeBlockResultContext({evidence,contract:params.contract,now:observed_ts}),specialist=consumeSpecialistContext({sources:{NANSEN_FLOWS:source},contract:params.contract,now:observed_ts,asset_identity:identity}),audit=auditCandidateBlocks({evidence,sources:{NANSEN_FLOWS:resolved},decision_ts:observed_ts});assert.equal(context.facts.length,1);assert.equal(specialist.blocks.exchange_flows.status,'CLOSED');assert.equal(audit.blocks.N05.checked,true);assert.equal(audit.blocks.N05.observed_facts,1);
const inheritedWeight=consumeEvidenceV2(evidence,{base_interest:70,decision_ts:observed_ts});assert.ok(Math.abs(inheritedWeight.adjustment)<=1);const before=buildRuntimeCanonicalBundle({contract:params.contract,run_id,snapshot_id:run_id,observed_ts}),after=buildRuntimeCanonicalBundle({contract:params.contract,run_id,snapshot_id:run_id,observed_ts,internal_market_context:{internal_only:true,candidate_context:{asset_identity:identity},candidate_sources:{NANSEN_FLOWS:source},evidence_v2:{evidence,sources:{NANSEN_FLOWS:resolved}}}});assert.equal(after.manual.ok,true);assert.ok(after.block_rendered_results.used_context_block_ids.includes('N05'));assert.equal(after.canonical.direction,before.canonical.direction);assert.equal(after.canonical.state,before.canonical.state);assert.deepEqual(after.canonical.targets,before.canonical.targets);
results.push({contract:params.contract,identity,source,evidence,context,specialist,audit,existing_bounded_weight_receipt:inheritedWeight,canonical:after.canonical,manual:after.manual,rendered_use:after.block_rendered_results,scope:'CURRENT_EXACT_LABELLED_TWO_HOUR_FLOW_SHARED_SUPPORTED_TOKEN_CONSUMER_NOT_NATIVE_OR_ALL102'});save();const usage=db.usageSnapshot();assert.equal(usage.unknown_ops,0);assert.ok(usage.rows_read<=1000&&usage.rows_written<=30);save();console.log(JSON.stringify({status:'CLOSED_ACTUAL_GENERAL_LABELLED_FLOW_TO_APPROVED_MANUAL',source_http:raw.length,database_usage:usage,full_main_acceptance:false,telegram_calls:0}));
