import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const root=path.resolve(process.argv[2]||'runtime'),load=p=>import(pathToFileURL(path.join(root,p))),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const {RemoteD1Database}=await load('report2-d1-adapter.mjs'),{collectOfficialTokenSchedule}=await load('src/official-token-schedule.mjs'),{collectOfficialEventsEvidence}=await load('src/official-events-evidence.mjs'),{compileOfficialSourceRegistry}=await load('src/official-source-registry.mjs'),{consumeBlockResultContext}=await load('src/block-result-context.mjs'),{buildRuntimeCanonicalBundle}=await load('src/canonical-runtime-adapter.mjs'),{selectSupportingContextFacts,SUPPORTING_CONTEXT_SELECTION_VERSION}=await load('src/manual-report-formatter.mjs'),{createUnifiedHttpBudget}=await load('src/unified-budget.mjs');
const phase=JSON.parse(fs.readFileSync('checkpoints/CLOUD_PHASE_STATE_20261004.json'));assert.equal(phase.current_phase,'CORE_BLOCKS');assert.equal(phase.lease?.owner,process.env.REPORT2_CONTINUATION_OWNER);assert.ok(phase.lease.expires_ts>Date.now());
const universeBytes=fs.readFileSync('checkpoints/htx-all-modes-crypto-futures-universe-20261004.json.gz'),universe=JSON.parse(zlib.gunzipSync(universeBytes));assert.equal(universe.assets.length,102);assert.equal(universe.contracts.length,119);
const files=['src/manual-report-formatter.mjs','src/sector-context.mjs','src/specialist-candidate-context.mjs'],runtime_sha256=Object.fromEntries(files.map(p=>{const h=hash(fs.readFileSync(path.join(root,p)));assert.equal(h,hash(fs.readFileSync(path.join('current-generation/files',p))));return[p,h];}));
const registry=compileOfficialSourceRegistry(JSON.parse(fs.readFileSync(path.join(root,'main-official-event-sources.json')))),metadata=registry.registry.ADA,identity={chain:metadata.chain,asset_kind:metadata.asset_kind,native_asset_id:metadata.native_asset_id,contract_or_mint:metadata.contract_or_mint};assert.deepEqual(identity,{chain:'cardano',asset_kind:'NATIVE',native_asset_id:'cardano:mainnet',contract_or_mint:null});
const db=new RemoteD1Database(process.env.REPORT2_D1_BRIDGE_URL,process.env.REPORT2_D1_BRIDGE_TOKEN),budget=createUnifiedHttpBudget(),run_id=`GENERAL_CONTEXT_SELECTION:${process.env.GITHUB_RUN_ID}`,results=[];
function save(error=null){fs.writeFileSync('audit-output/context-selection-live-verification.json',JSON.stringify({schema:'report2-general-context-selection-acceptance-v1',github_head:process.env.GITHUB_SHA,run_id,error,runtime_sha256,selection_version:SUPPORTING_CONTEXT_SELECTION_VERSION,common_universe_sha256:hash(universeBytes),common_future_assets:102,common_future_contracts:119,results,source_http:0,database_usage:db.usageSnapshot(),source_cache_evidence_reused_without_retiming:true,overflow_regression_scope:'UNIT_TEST_ONLY_NOT_LIVE_ALL15_ACCEPTANCE',production_canonical_writes:0,full_main_acceptance:false,all_15_live_accepted:false,telegram_calls:0,telegram_delivery_proven:false},null,2)+'\n');}process.on('uncaughtExceptionMonitor',e=>save(String(e)));
const params={db,fetch_impl:async()=>{throw Error('FRESH_ACCEPTED_CACHE_ONLY_NO_NEW_SOURCE_REQUEST');},request_admit:r=>budget.reserve(r),contract:'ADA-USDT',run_id,asset_identity:identity,asset_metadata:metadata,now:Date.now(),clock:Date.now,strict_fresh_manual:false};
const document=await collectOfficialTokenSchedule(params),feed=await collectOfficialEventsEvidence({...params,now:Date.now()});
for(const result of [document,feed]){assert.equal(result.status,'CLOSED');assert.equal(result.network_calls,0);assert.equal(result.cache_status,'HIT');assert.ok(result.evidence.length>0);}
const evidence=[...document.evidence,...feed.evidence],sources={OFFICIAL_TOKEN_SCHEDULE:document,OFFICIAL_EVENTS:feed},observed_ts=Date.now(),context=consumeBlockResultContext({evidence,contract:'ADA-USDT',now:observed_ts});assert.ok(context.facts.some(f=>f.block_id==='N01'));assert.ok(context.facts.some(f=>f.block_id==='N07'));assert.ok(evidence.every(e=>e.htx_contract==='ADA-USDT'&&e.asset_id==='cardano:native:mainnet'&&e.observed_ts<=observed_ts&&e.expires_at>=observed_ts));
const input={contract:'ADA-USDT',run_id,snapshot_id:`${run_id}:${observed_ts}`,observed_ts},before=buildRuntimeCanonicalBundle(input),after=buildRuntimeCanonicalBundle({...input,internal_market_context:{internal_only:true,evidence_v2:{evidence,sources}}});assert.equal(after.manual.ok,true);assert.ok(after.block_rendered_results.used_context_block_ids.includes('N01'));assert.ok(after.block_rendered_results.used_context_block_ids.includes('N07'));assert.deepEqual(after.canonical.scores,before.canonical.scores);assert.equal(after.canonical.direction,before.canonical.direction);assert.equal(after.canonical.state,before.canonical.state);assert.deepEqual(after.canonical.targets,before.canonical.targets);
const facts=after.canonical.metadata.supporting_context.facts,selected=selectSupportingContextFacts(facts);assert.ok(selected.length<=24);assert.ok(selected.every(f=>facts.includes(f)));assert.deepEqual(selected,facts);
results.push({contract:'ADA-USDT',identity,document,feed,context,canonical:after.canonical,manual:after.manual,rendered_use:after.block_rendered_results,selected_fact_count:selected.length,available_fact_count:facts.length,scope:'CURRENT_VALID_SOURCE_CACHE_TO_SHARED_APPROVED_MANUAL_NOT_NEW_SOURCE_OR_ALL15'});save();const usage=db.usageSnapshot();assert.equal(usage.unknown_ops,0);assert.ok(usage.rows_read<=1000&&usage.rows_written<=40);save();console.log(JSON.stringify({status:'CLOSED_ACTUAL_VALID_CACHE_TO_GENERAL_MANUAL_SELECTION',source_http:0,database_usage:usage,selected_fact_count:selected.length,full_main_acceptance:false,telegram_calls:0}));
