import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GUARDED_CODE_PATHS,verifyCurrentMainCode,dispatchExactTriggerKick,runContinuousBackup,CONTINUOUS_WORKER_PLAN,createCollectorJobBudget} from './continuous-backup-worker.mjs';
const T=Date.UTC(2026,9,8,20,1),task_id='RCHK:'+'a'.repeat(40),head='b'.repeat(40);
const kick={schema:'EXACT_TRIGGER_ANALYSIS_KICK_V1',dispatch:true,entry_authorized:false,task_id,kick_ts:T,expires_ts:T+1800000};
const manifest=()=>Object.fromEntries(GUARDED_CODE_PATHS.map(p=>[p,'a'.repeat(40)]));
test('source HTTP164 cap is shared across bootstrap and continuous cycles; failed attempts are charged before transport',async()=>{const charges=[];let calls=0;const b=createCollectorJobBudget({used:4,on_charge:used=>charges.push(used),fetch_impl:async()=>{calls++;throw Error('CONTROLLED_TRANSPORT_FAILURE');}});await assert.rejects(()=>b.fetch('https://controlled.invalid'));assert.equal(b.used,5);assert.deepEqual(charges,[5]);for(let i=5;i<164;i++)await assert.rejects(()=>b.fetch('https://controlled.invalid'));assert.equal(b.used,164);assert.equal(calls,160);await assert.rejects(()=>b.fetch('https://controlled.invalid'),/SOURCE_HTTP_CAP/);assert.equal(calls,160);assert.equal(b.can_collect,false);assert.equal(b.snapshot.failed_attempts_not_refunded,true);});
test('whole-job source envelope ends the current worker before an unsafe additional collection',async()=>{let clock=T,cycles=0,guards=0;const b=createCollectorJobBudget({used:160,fetch_impl:async()=>new Response('{}')});const r=await runContinuousBackup({duration_minutes:15,now:()=>clock,sleep:async ms=>{clock+=ms;},should_continue:()=>b.can_collect,source_guard:async()=>{guards++;return {allowed:true};},cycle:async()=>{cycles++;for(let i=0;i<3;i++)await b.fetch('https://controlled.invalid');return {};}});assert.equal(cycles,1);assert.equal(guards,1);assert.equal(b.used,163);assert.equal(r.status,'ORIGINAL_SOURCE_JOB_HTTP_CAP_REACHED');});
test('source budget is persisted within the same cloud job and injected only into the exact original collector',()=>{const s=fs.readFileSync(new URL('./github-backup.mjs',import.meta.url),'utf8');assert.match(s,/previousBudget.cloud_run!==cloudRun/);assert.match(s,/used:previousBudget\?\.attempted_source_http/);assert.match(s,/loadExactCollector\(source,sourceBudget.fetch\)/);assert.match(s,/should_continue:\(\)=>sourceBudget.can_collect/);assert.match(s,/source_job_budget=sourceBudget.snapshot/);assert.throws(()=>createCollectorJobBudget({used:165}),/SOURCE_BUDGET_INVALID/);});
test('current main code guard permits documentation-only commits but rejects changed production code',async()=>{
 for(const changed of [null,'cloudflare/public-collector/trigger-analysis-kick.mjs','current-generation/files/src/worker.js','.github/workflows/report2.yml']){let calls=0;const m=manifest();const result=await verifyCurrentMainCode({repository:'owner/repo',token:'CONTROLLED_ONLY',manifest:m,fetch_impl:async url=>{calls++;return new Response(JSON.stringify(String(url).includes('/git/ref/')?{object:{sha:head}}:{truncated:false,tree:GUARDED_CODE_PATHS.map(path=>({path,type:'blob',sha:path===changed?'c'.repeat(40):m[path]}))}));}});assert.equal(result.allowed,!changed);assert.equal(calls,2);assert.equal(result.current_main,head);assert.equal(result.source_http,0);}
});
test('missing auth, incomplete tree, malformed ref and transport failure stop before source or database work',async()=>{
 assert.equal((await verifyCurrentMainCode({})).allowed,false);
 for(const data of [{object:{sha:'wrong'}},{object:{sha:head},truncated:true}])assert.equal((await verifyCurrentMainCode({repository:'owner/repo',token:'CONTROLLED_ONLY',manifest:manifest(),fetch_impl:async()=>new Response(JSON.stringify(data))})).allowed,false);
 assert.equal((await verifyCurrentMainCode({repository:'owner/repo',token:'CONTROLLED_ONLY',manifest:manifest(),fetch_impl:async()=>{throw Error('CONTROLLED_FAILURE');}})).allowed,false);
});
test('an exact live kick immediately dispatches only the gated main workflow and cannot authorize entry',async()=>{
 let calls=0;const r=await dispatchExactTriggerKick({kick,repository:'owner/repo',token:'CONTROLLED_ONLY',now:T+1000,fetch_impl:async(url,options)=>{calls++;assert.equal(url,'https://api.github.com/repos/owner/repo/actions/workflows/report2.yml/dispatches');assert.equal(options.method,'POST');const body=JSON.parse(options.body);assert.deepEqual(body,{ref:'main',inputs:{reason:'EXACT_SENT_PRICE_TRIGGER_WAKE_UP',trigger_only_run:true,trigger_task_id:task_id,manual_run_authorized:false}});return new Response(null,{status:204});}});assert.equal(r.dispatched,true);assert.equal(r.entry_authorized,false);assert.equal(calls,1);
});
test('expired, future, malformed, missing-token and entry-authorized hints never dispatch',async()=>{
 for(const [patch,token] of [[{expires_ts:T},'CONTROLLED'],[{kick_ts:T+1},'CONTROLLED'],[{task_id:'FOREIGN'},'CONTROLLED'],[{entry_authorized:true},'CONTROLLED'],[{},''],[{dispatch:false},'CONTROLLED']]){let calls=0;const r=await dispatchExactTriggerKick({kick:{...kick,...patch},repository:'owner/repo',token,now:T,fetch_impl:async()=>{calls++;return new Response(null,{status:204});}});assert.equal(r.dispatched,false);assert.equal(calls,0);}
});
test('failed dispatch keeps the durable consumed kick and never invents an accepted workflow',async()=>{for(const fetch_impl of [async()=>new Response(null,{status:403}),async()=>{throw Error('CONTROLLED');}]){const r=await dispatchExactTriggerKick({kick,repository:'owner/repo',token:'CONTROLLED_ONLY',now:T,fetch_impl});assert.equal(r.dispatched,false);assert.equal(r.failed_dispatch_consumes_kick,true);assert.equal(r.entry_authorized,false);}});
test('one cloud worker checks each five-minute slot without depending on new scheduled job starts',async()=>{
 let clock=T;const cycles=[],receipts=[],waits=[];const r=await runContinuousBackup({duration_minutes:11,now:()=>clock,sleep:async ms=>{waits.push(ms);clock+=ms;},source_guard:async()=>({allowed:true,status:'CURRENT_MAIN_CODE_VERIFIED'}),cycle:async()=>{cycles.push(clock);return {status:'PRIMARY_CLOSED',source_http:0,telegram:false};},on_receipt:async x=>receipts.push(x)});assert.deepEqual(cycles,[T,T+300000,T+600000]);assert.equal(r.cycles,3);assert(waits.every(x=>x>0&&x<=60000));assert.equal(receipts.length,3);assert.equal(r.entry_authorized,false);
});
test('current code changes or unclosed source guard stop the old worker before the next cycle',async()=>{
 let clock=T,guards=0,cycles=0;const r=await runContinuousBackup({duration_minutes:20,now:()=>clock,sleep:async ms=>{clock+=ms;},source_guard:async()=>++guards===1?{allowed:true}:{allowed:false,status:'CURRENT_MAIN_CODE_CHANGED'},cycle:async()=>{cycles++;return {status:'PRIMARY_CLOSED'};}});assert.equal(cycles,1);assert.equal(r.status,'CURRENT_MAIN_CODE_CHANGED');assert.equal(guards,2);
});
test('a failed slot does not reset budgets and the next original slot may recover',async()=>{let clock=T,n=0;const r=await runContinuousBackup({duration_minutes:6,now:()=>clock,sleep:async ms=>{clock+=ms;},source_guard:async()=>({allowed:true}),cycle:async()=>{if(++n===1)throw Error('CONTROLLED');return {status:'PRIMARY_CLOSED'};}});assert.equal(r.cycles,2);assert.equal(r.failures,1);assert.equal(r.provider_http_added,0);});
test('one-shot bootstrap stays bounded and worker windows cannot exceed five hours',async()=>{let n=0;assert.equal((await runContinuousBackup({duration_minutes:0,now:()=>T,source_guard:async()=>({allowed:true}),cycle:async()=>{n++;return {};}})).cycles,1);assert.equal(n,1);for(const minutes of [-1,301,NaN])await assert.rejects(()=>runContinuousBackup({duration_minutes:minutes,source_guard:async()=>({allowed:true}),cycle:async()=>({})}),/PLAN_INVALID/);assert.equal(CONTINUOUS_WORKER_PLAN.maximum_minutes,300);});
test('public standard runner, initial immutable receipt, bounded job and no delayed end-of-job dispatch are wired',()=>{const s=fs.readFileSync(new URL('../../.github/workflows/report2-public-collector-backup.yml',import.meta.url),'utf8');assert.match(s,/runs-on: ubuntu-latest/);assert.match(s,/timeout-minutes: 315/);assert.match(s,/r.private!==false/);assert.match(s,/REPORT2_BACKUP_WORKER_MINUTES: "300"/);assert.match(s,/REPORT2_BACKUP_WORKER_MINUTES: "0"/);assert.match(s,/report2-collector-backup-bootstrap-/);assert.doesNotMatch(s,/createWorkflowDispatch/);assert.match(s,/actions: write/);});
