import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {claimTriggerKick,freshTriggerHint,proveTriggerKickBudget} from './trigger-analysis-kick.mjs';
const fixture=JSON.parse(fs.readFileSync(new URL('../../current-generation/tests/fixtures/exact-ct161-price-window-20261008.json',import.meta.url)));
const originalBytes=JSON.stringify(fixture.original),T=fixture.price_window[0].original_row.ts,NOW=T+170000;
test('actual workflow gate admits only enabled exact trigger jobs and uses scheduled integrity instead of broad manual replay',()=>{
 const workflow=fs.readFileSync(new URL('../../.github/workflows/report2.yml',import.meta.url),'utf8');
 const gate=workflow.slice(workflow.indexOf('          normalize_true()'),workflow.indexOf('  enqueue-manual-command:'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'exact-trigger-gate-'));
 try{for(const [enabled,id,expected] of [['false','RCHK:'+ 'a'.repeat(40),false],['true','',false],['true','RCHK:'+ 'a'.repeat(40),true]]){const out=path.join(dir,'out');fs.writeFileSync(out,'');const r=spawnSync('bash',['-c',gate],{env:{...process.env,EVENT_NAME:'workflow_dispatch',LEGACY_RUNNER_ENABLED:enabled,TRIGGER_ONLY_RUN:'true',TRIGGER_TASK_ID:id,MANUAL_AUTHORIZED:'false',GITHUB_OUTPUT:out},encoding:'utf8'});assert.equal(r.status,0);assert.equal(fs.readFileSync(out,'utf8').trim(),'admitted='+expected);}
 assert.match(workflow,/Verify early evidence repair and frozen policy\n\s*if: \$\{\{ github.event_name != 'schedule' && inputs.trigger_only_run != true/);
 assert.match(workflow,/Scheduled runtime integrity check\n\s*if: \$\{\{ github.event_name == 'schedule' \|\| inputs.trigger_only_run == true/);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
function row(id=fixture.original.task.task_id){
 const r={...fixture.original.task,task_id:id,state:'PENDING',updated_ts:T+1000};
 r.last_result=JSON.stringify({schema:'LIGHT_PRICE_RECHECK_V1',scope:'PRICE_AND_CANCELLATION_ONLY',status:'TRIGGER_PRICE_REACHED_FULL_ANALYSIS_REQUIRED',checked_ts:T+1000,source_ts:T,observed_ts:T,price:fixture.price_window[0].price,source:'HTX_OFFICIAL_COLLECTOR',entry_authorized:false,full_analysis_completed:false,settlement_confirmed:false,task_id:id,publication_id:r.publication_id,run_id:r.run_id,snapshot_id:r.snapshot_id,analytical_fingerprint:fixture.original.analytical_fingerprint,telegram_message_id:'161'});return r;
}
class DB{
 constructor(){this.raw=new DatabaseSync(':memory:');this.raw.exec('CREATE TABLE v3_recheck_task_shadow(task_id TEXT PRIMARY KEY,publication_id TEXT,contract_code TEXT,direction TEXT,run_id TEXT,snapshot_id TEXT,due_ts INTEGER,expires_ts INTEGER,state TEXT,created_ts INTEGER,updated_ts INTEGER,last_result TEXT); CREATE INDEX idx_report2_recheck_trigger_ready ON v3_recheck_task_shadow(expires_ts,due_ts) WHERE state=\'PENDING\' AND json_valid(last_result) AND json_extract(last_result,\'$.status\')=\'TRIGGER_PRICE_REACHED_FULL_ANALYSIS_REQUIRED\';');this.calls=[];this.corruptAck=false;this.race=false;}
 prepare(sql){const db=this;return {args:[],bind(...a){this.args=a;return this;},query(){const indexes=[],q=sql.replace(/\?(\d+)/g,(_,n)=>{indexes.push(+n-1);return '?'});return [q,indexes.length?indexes.map(i=>this.args[i]):this.args];},async first(){const [q,a]=this.query();db.calls.push(sql);const r=db.raw.prepare(q).get(...a)||null;return db.corruptAck&&sql.startsWith('SELECT day_key,slot')?{...r,kick_ts:0}:r;},async all(){const [q,a]=this.query();db.calls.push(sql);return {results:db.raw.prepare(q).all(...a)};},async run(){const [q,a]=this.query();db.calls.push(sql);if(db.race&&sql.startsWith('INSERT INTO report2_trigger_kick_slot'))return {meta:{changes:0}};return {meta:{changes:Number(db.raw.prepare(q).run(...a).changes)}};}};}
 seed(r=row()){const keys=['task_id','publication_id','contract_code','direction','run_id','snapshot_id','due_ts','expires_ts','state','created_ts','updated_ts','last_result'];this.raw.prepare('INSERT INTO v3_recheck_task_shadow('+keys.join(',')+') VALUES('+keys.map(()=>'?').join(',')+')').run(...keys.map(k=>r[k]));}
 close(){this.raw.close();}
}
test('retained CT price crossed inside original window; controlled early wake-up works and delayed cron remains expired',async()=>{
 assert.equal(fixture.original.receipt.telegram_message_id,'161');assert.equal(fixture.original.task.attempt_count,0);assert.equal(fixture.price_window.filter(x=>x.price_trigger_reached).length,3);
 const db=new DB();try{db.seed();const before=db.raw.prepare('SELECT * FROM v3_recheck_task_shadow').get();const p=await claimTriggerKick(db,{now_ts:NOW});assert.equal(p.dispatch,true);assert.equal(p.expires_ts,fixture.original.task.expires_ts);assert.equal(p.entry_authorized,false);assert.equal(freshTriggerHint(row(),Date.parse(fixture.next_analytics_actual_start_utc)),false);assert.deepEqual(db.raw.prepare('SELECT * FROM v3_recheck_task_shadow').get(),before);assert.equal(JSON.stringify(fixture.original),originalBytes);}finally{db.close();}
});
test('all polls and additional admission reservations fit original caps without extra full-analysis slots',()=>{const p=proveTriggerKickBudget();assert.equal(p.safe,true);assert.equal(p.maximum_planned_rows_read,3498308);assert.equal(p.maximum_planned_rows_written,69664);assert.equal(p.kicks_per_day,3);assert.equal(p.regular_analytics_interval_minutes,40);});
for(const [name,patch] of [['stale',{source_ts:NOW-180001}],['future',{checked_ts:NOW+1}],['wrong task',{task_id:'WRONG'}],['wrong publication',{publication_id:'WRONG'}],['wrong run',{run_id:'WRONG'}],['wrong snapshot',{snapshot_id:'WRONG'}],['invalid SENT id',{telegram_message_id:'0'}],['wrong fingerprint',{analytical_fingerprint:'WRONG'}],['waiting',{status:'WAITING_FOR_PRICE'}],['entry authorization',{entry_authorized:true}],['claimed completion',{full_analysis_completed:true}],['cancelled',{status:'CANCELLED'}]])test(name+' cannot wake analysis',async()=>{const db=new DB();try{const r=row();r.last_result=JSON.stringify({...JSON.parse(r.last_result),...patch});db.seed(r);assert.equal((await claimTriggerKick(db,{now_ts:NOW})).dispatch,false);}finally{db.close();}});
test('original expiration and claimed tasks cannot be revived',async()=>{for(const patch of [{expires_ts:NOW},{state:'EXPIRED'},{state:'CLAIMED'}]){const db=new DB();try{db.seed({...row(),...patch});assert.equal((await claimTriggerKick(db,{now_ts:NOW})).dispatch,false);}finally{db.close();}}});
test('same task and bucket are idempotent, next original bucket cannot duplicate a kick',async()=>{const db=new DB();try{db.seed();assert.equal((await claimTriggerKick(db,{now_ts:NOW})).dispatch,true);assert.equal((await claimTriggerKick(db,{now_ts:NOW})).status,'POLL_ALREADY_COUNTED_OR_DAILY_CAP');assert.equal((await claimTriggerKick(db,{now_ts:NOW+300000})).dispatch,false);assert.equal(db.raw.prepare('SELECT COUNT(*) n FROM report2_trigger_kick_slot').get().n,1);}finally{db.close();}});
test('three durable kicks exhaust the day; failed/racing dispatches do not refund slots',async()=>{const db=new DB();try{db.seed();await claimTriggerKick(db,{now_ts:NOW});db.raw.prepare('INSERT INTO report2_trigger_kick_slot VALUES(?,?,?,?)').run(new Date(NOW).toISOString().slice(0,10),1,'SECOND',NOW);db.raw.prepare('INSERT INTO report2_trigger_kick_slot VALUES(?,?,?,?)').run(new Date(NOW).toISOString().slice(0,10),2,'THIRD',NOW);assert.equal((await claimTriggerKick(db,{now_ts:NOW+300000})).status,'KICK_DAILY_CAP');}finally{db.close();}});
test('288 original polls are a durable daily ceiling even if an extra job is invoked',async()=>{const db=new DB();try{await claimTriggerKick(db,{now_ts:NOW});db.raw.exec('UPDATE report2_trigger_kick_poll SET polls=288');assert.equal((await claimTriggerKick(db,{now_ts:NOW+300000})).status,'POLL_ALREADY_COUNTED_OR_DAILY_CAP');}finally{db.close();}});
test('missing trigger index, failed exact ACK, race and unknown D1 costs never dispatch',async()=>{for(const mode of ['index','ack','race','cost']){const db=new DB();try{db.seed();if(mode==='index'){db.raw.exec('DROP INDEX idx_report2_recheck_trigger_ready');await assert.rejects(()=>claimTriggerKick(db,{now_ts:NOW}));continue;}if(mode==='ack')db.corruptAck=true;if(mode==='race')db.race=true;if(mode==='cost'){let n=0;db.usageSnapshot=()=>({rows_read:0,rows_written:0,unknown_ops:n++?1:0});}assert.equal((await claimTriggerKick(db,{now_ts:NOW})).dispatch,false);}finally{db.close();}}});
test('SQL uses the partial trigger index and LIMIT2 before any growing scan; only kick tables change',async()=>{const db=new DB();try{db.seed();for(let i=0;i<500;i++){const r=row('WAIT:'+i);r.last_result=JSON.stringify({...JSON.parse(r.last_result),status:'WAITING_FOR_PRICE'});db.seed(r);}await claimTriggerKick(db,{now_ts:NOW});const sql=db.calls.find(x=>x.includes('INDEXED BY idx_report2_recheck_trigger_ready'));const plan=db.raw.prepare('EXPLAIN QUERY PLAN '+sql.replaceAll('?1',String(NOW))).all();assert(plan.some(x=>x.detail.includes('idx_report2_recheck_trigger_ready')));assert(!plan.some(x=>/SCAN t(?:$| )/.test(x.detail)));assert(db.calls.every(x=>!/^UPDATE v3_|^INSERT INTO v3_|^DELETE/.test(x)));}finally{db.close();}});
test('workflow wake-up is internal scheduled mode, exact task only, preserves normal cron and disables manual queue',()=>{const main=fs.readFileSync(new URL('../../.github/workflows/report2.yml',import.meta.url),'utf8'),backup=fs.readFileSync(new URL('../../.github/workflows/report2-public-collector-backup.yml',import.meta.url),'utf8'),runner=fs.readFileSync(new URL('../../current-generation/files/runner-main.mjs',import.meta.url),'utf8');assert.match(main,/cron: "7,27,47 \* \* \* \*"/);assert.match(main,/inputs.trigger_only_run != true &&/);assert.match(main,/REPORT2_TRIGGER_KICK_TASK_ID:/);assert.match(main,/REPORT2_RUN_SOURCE:.*inputs.trigger_only_run == true.*'schedule'/);const dispatcher=fs.readFileSync(new URL('./continuous-backup-worker.mjs',import.meta.url),'utf8');assert.match(dispatcher,/actions\/workflows\/report2.yml\/dispatches/);assert.match(dispatcher,/manual_run_authorized:false/);assert.match(runner,/TRIGGER_KICK_DOES_NOT_RECOVER_MANUAL_COMMAND/);assert.match(runner,/TRIGGER_ONLY_PRESERVES_REGULAR_CADENCE/);assert.match(runner,/task_id:triggerOnly\?triggerKickTaskId:null/);});
