import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
const root=path.dirname(fileURLToPath(import.meta.url));if(Number(process.versions.node.split('.')[0])!==24)throw Error('NODE_24_REQUIRED');
const stamp=new Date().toISOString().replace(/[-:.]/g,''),out=path.join(root,'validation-runs',stamp);fs.mkdirSync(out,{recursive:true});const steps=[];
function run(name,args){const r=spawnSync(process.execPath,args,{cwd:root,encoding:'utf8',timeout:90000,maxBuffer:20000000});const data=(r.stdout??'')+(r.stderr??'');const file=path.join(out,name+'.log');fs.writeFileSync(file,data);const rec={name,status:r.status,signal:r.signal??null,path:path.relative(root,file),sha256:createHash('sha256').update(data).digest('hex')};steps.push(rec);if(r.status!==0){fs.writeFileSync(path.join(out,'FAILED.json'),JSON.stringify({node:process.version,steps},null,2));throw Error('VALIDATION_FAILED:'+name+'; '+rec.path);}return data;}
run('prepare-public-canonical',['integration/prepare-test-runtime.mjs']);run('prepare-exact-postv7',['integration/prepare-exact-postv7.mjs']);run('prepare-merged',['integration/prepare-merged-unified.mjs']);
const cases=['tests','integration/tests'].flatMap(d=>fs.readdirSync(path.join(root,d)).filter(n=>n.endsWith('.test.mjs')).sort().map(n=>path.join(d,n)));
const tap=run('liquidation-and-integration',['--test','--test-reporter=tap',...cases]);
const inherited=fs.readdirSync(path.join(root,'../unified-delivery-base/tests-inherited')).filter(n=>n.endsWith('.test.mjs')).sort().map(n=>'../unified-delivery-base/tests-inherited/'+n);
const old=run('selected-inherited-delivery',['--test','--test-reporter=tap',...inherited]);
const count=s=>({tests:Number(s.match(/^# tests (\d+)$/m)?.[1]),pass:Number(s.match(/^# pass (\d+)$/m)?.[1]),fail:Number(s.match(/^# fail (\d+)$/m)?.[1])});
const a=count(tap),b=count(old);if(!Number.isInteger(a.tests)||a.tests<194||a.fail!==0||a.pass!==a.tests||b.tests!==33||b.fail!==0)throw Error('TEST_COUNT_OR_RESULT_NOT_CLOSED');
const proof={status:'VERIFIED_PREPARATION_NOT_PRODUCTION_RELEASE',node:process.version,checked_at:new Date().toISOString(),scope:'NEW_LIQUIDATION_MODULES_AND_SELECTED_INHERITED_DELIVERY_TESTS',main_suite:a,selected_inherited:b,steps,actual_user_telegram_send:false,full_project_inherited_suite:false,full_worker_runtime_import:false,production_changed:false};fs.writeFileSync(path.join(out,'VERIFICATION.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
