import test from 'node:test';import assert from 'node:assert/strict';
import {buildTz101PublicationGate} from '../src/tz101-publication-gate.mjs';
const NOW=Date.UTC(2026,8,17,10,0,0);
const fd={entry_action:'SHADOW_ENTRY_ELIGIBLE',entry_quality:'CLOSED',hard_veto:false,hard_veto_state:'CLEAR',risk_state:'CLEAR',timing_state:'ENTRY_WINDOW',execution_quality:'CLOSED',data_quality:'CLOSED',independence_state:'CLOSED'};
const score={is_probability:false,score_lower_bound:75,score_upper_bound:78,wholly_missing_blocks:[],weighted_blocks:[],calibration_status:'RULE_SCORE_DRAFT_NOT_PROBABILITY'};
const plan={status:'CLOSED',entry_area:'100–101',target:'108',invalidation:'97',required_evidence_status:'CLOSED',current_price_in_entry_area:true,valid_until_ts:NOW+300000,risk_summary:'структура ухудшится ниже 97',reasons:['a','b']};
const costs={status:'CLOSED',fees_usdt:1,spread_cost_usdt:1,slippage_cost_usdt:2,funding_cost_usdt:0.5,double_count_free:true,risk_reward_after_costs_status:'CLOSED'};
const funding={rate_pct:-.02,interval_hours:8,observed_ts:NOW-30000};
const make=(o={})=>buildTz101PublicationGate({final_decision:fd,score_interval:score,scenario_plan:plan,cost_assessment:costs,funding_context:funding,observed_ts:NOW,...o});

test('fully explicit publication inputs close while user position remains unknown',()=>{const r=make();assert.equal(r.status,'CLOSED');assert.equal(r.user_position_semantics.user_portfolio_state,'UNKNOWN');assert.equal(r.user_position_semantics.alert_implies_user_trade,false);assert.ok(r.telegram_context)});
test('rule-based score does not require OOS validation for publication gate',()=>{const r=make({score_interval:{...score,calibration_status:'RULE_SCORE_DRAFT_NOT_PROBABILITY'}});assert.equal(r.status,'CLOSED');assert.ok(!r.missing.some(x=>x.code==='SCORE_CALIBRATION_NOT_VALIDATED'));assert.ok(r.telegram_context)});
test('probability-labelled score remains blocked',()=>{const r=make({score_interval:{...score,is_probability:true}});assert.equal(r.status,'BLOCKED');assert.ok(r.blockers.some(x=>x.code==='SCORE_MISLABELED_AS_PROBABILITY'))});
test('whole missing block and lower bound below 70 cannot publish',()=>{const r=make({score_interval:{...score,score_lower_bound:65,wholly_missing_blocks:['SMART_MONEY_ONCHAIN']}});assert.equal(r.status,'NOT_CLOSED');assert.ok(r.missing.some(x=>x.code==='WHOLE_WEIGHTED_BLOCK_MISSING'));assert.ok(r.missing.some(x=>x.code==='SCORE_LOWER_BOUND_BELOW_TELEGRAM_THRESHOLD'))});
test('missing target/invalidation/area never default from liquidation map',()=>{const r=make({scenario_plan:{...plan,entry_area:null,target:null,invalidation:null},liquidation_context:{status:'CONFIRMED',short_above:'200',long_below:'50'}});assert.equal(r.status,'NOT_CLOSED');for(const c of ['ENTRY_AREA_MISSING','REALISTIC_TARGET_MISSING','INVALIDATION_MISSING']) assert.ok(r.missing.some(x=>x.code===c))});
test('all four cost components and double-count proof are mandatory',()=>{const bad={...costs,funding_cost_usdt:null,double_count_free:false};const r=make({cost_assessment:bad});assert.equal(r.status,'BLOCKED');assert.ok(r.missing.some(x=>x.code==='COST_COMPONENT_MISSING:funding_cost_usdt'));assert.ok(r.blockers.some(x=>x.code==='COST_DOUBLE_COUNT_PROTECTION_NOT_PROVEN'))});
test('funding sign alone never changes gate outcome',()=>{for(const rate of [-.1,0,.1]) assert.equal(make({funding_context:{...funding,rate_pct:rate}}).status,'CLOSED')});
test('unknown portfolio cannot be injected as known flat',()=>{const r=make({user_portfolio:{state:'FLAT',quantity:999}});assert.equal(r.user_position_semantics.user_portfolio_state,'UNKNOWN');assert.equal(r.user_position_semantics.user_position_confirmed,false)});
test('active final hard veto blocks regardless of score',()=>{const r=make({final_decision:{...fd,hard_veto:true,hard_veto_state:'ACTIVE',risk_state:'INVALIDATED'}});assert.equal(r.status,'BLOCKED');assert.ok(r.blockers.some(x=>x.code==='FINAL_HARD_VETO_NOT_CLEAR'))});
