import assert from 'node:assert/strict';
import { buildHtxFeeScheduleReceipt, buildHtxAccountFeeScheduleReceipt } from '../src/tz101-fee-source.mjs';
const NOW=Date.UTC(2026,8,17,13,0,0), C='BTC-USDT';
const baseTier={source_kind:'PUBLIC_BASE_TIER',venue:'HTX',market_type:'USDT_PERP',contract_code:C,fee_role:'TAKER',entry_rate:0.0004,exit_rate:0.0004,source_receipt_id:'PUBLIC1',account_scope_fingerprint:'public',source_ts:NOW-1000,valid_until_ts:NOW+10000};
assert.equal(buildHtxFeeScheduleReceipt({contract_code:C,source_record:baseTier,observed_ts:NOW}).status,'NOT_CLOSED');
const account={...baseTier,source_kind:'ACCOUNT_EFFECTIVE_RATE',source_receipt_id:'ACCOUNT-RATE-1',account_scope_fingerprint:'acct:deadbeef'};
const closed=buildHtxAccountFeeScheduleReceipt({contract_code:C,source_record:account,observed_ts:NOW});
assert.equal(closed.status,'CLOSED');
assert.equal(closed.fee_schedule.schema_version,'tz101-htx-fee-schedule-v1');
assert.equal(closed.fee_schedule.source_kind,'ACCOUNT_EFFECTIVE_RATE');
assert.equal(closed.credentials_stored,false);
const official={...baseTier,source_kind:'OFFICIAL_CONSERVATIVE_RATE',source_receipt_id:'HTX-OFFICIAL-1',source_authority:'HTX_OFFICIAL',source_url:'https://www.htx.com/support/example-current-fee',conservative_for_unknown_account:true};
const conservative=buildHtxFeeScheduleReceipt({contract_code:C,source_record:official,observed_ts:NOW});
assert.equal(conservative.status,'CLOSED');
assert.equal(conservative.fee_schedule.source_kind,'OFFICIAL_CONSERVATIVE_RATE');
assert.equal(conservative.fee_schedule.conservative_for_unknown_account,true);
assert.equal(buildHtxFeeScheduleReceipt({contract_code:C,source_record:{...official,source_authority:'BLOG'},observed_ts:NOW}).status,'NOT_CLOSED');
assert.equal(buildHtxFeeScheduleReceipt({contract_code:C,source_record:{...official,source_url:'https://example.com/fees'},observed_ts:NOW}).status,'NOT_CLOSED');
assert.equal(buildHtxFeeScheduleReceipt({contract_code:C,source_record:{...account,api_key:'secret'},observed_ts:NOW}).reason,'SECRET_BEARING_FEE_RECORD_FORBIDDEN');
assert.equal(buildHtxFeeScheduleReceipt({contract_code:C,source_record:{...account,valid_until_ts:NOW-1},observed_ts:NOW}).status,'NOT_CLOSED');
assert.equal(buildHtxFeeScheduleReceipt({contract_code:C,source_record:{...account,entry_rate:1},observed_ts:NOW}).status,'NOT_CLOSED');
console.log(JSON.stringify({ok:true,suite:'tz101-fee-source-r9',public_base_tier_rejected:true,account_effective_receipt:closed.fee_schedule.persistence.receipt_id,official_conservative_receipt:conservative.fee_schedule.persistence.receipt_id}));
