import test from 'node:test';import assert from 'node:assert/strict';
import {buildAssetIdentity,identitiesCompatible,normalizeContractIdentity,normalizeTimestamp,quotesEquivalent,normalizeCrossVenueFact} from '../src/asset-identity.mjs';
test('Solana mint is case preserving and never lower-cased',()=>{const mint='So11111111111111111111111111111111111111112';const r=normalizeContractIdentity({chain:'solana',contract_or_mint:mint});assert.equal(r.status,'CLOSED');assert.equal(r.contract_or_mint,mint);assert.equal(r.address_case_preserved,true);});
test('EVM address canonicalizes lower case',()=>{const a='0xABCDEFabcdefABCDEFabcdefABCDEFabcdefABCD';const r=normalizeContractIdentity({chain:'ethereum',contract_or_mint:a});assert.equal(r.status,'CLOSED');assert.equal(r.contract_or_mint,a.toLowerCase());});
test('ticker collision is not enough for identity',()=>{const a=buildAssetIdentity({chain:'ethereum',contract_or_mint:'0x1111111111111111111111111111111111111111',base_asset:'ABC',quote_asset:'USDT',market_type:'SPOT'});const b=buildAssetIdentity({chain:'ethereum',contract_or_mint:'0x2222222222222222222222222222222222222222',base_asset:'ABC',quote_asset:'USDT',market_type:'SPOT'});assert.equal(identitiesCompatible(a,b).compatible,false);});
test('USD USDT USDC are not treated as equivalent',()=>{assert.equal(quotesEquivalent('USD','USDT'),false);assert.equal(quotesEquivalent('USDT','USDC'),false);assert.equal(quotesEquivalent('USDT','USDT'),true);});
test('multiplier mismatch blocks compatibility',()=>{const args={chain:'ethereum',contract_or_mint:'0x1111111111111111111111111111111111111111',base_asset:'SHIB',quote_asset:'USDT',market_type:'FUTURES'};assert.equal(identitiesCompatible(buildAssetIdentity({...args,multiplier:1}),buildAssetIdentity({...args,multiplier:1000})).compatible,false);});
test('seconds milliseconds microseconds normalize to same epoch',()=>{const s=1760000000,ms=s*1000,us=ms*1000;assert.equal(normalizeTimestamp(s).ms,ms);assert.equal(normalizeTimestamp(ms).ms,ms);assert.equal(normalizeTimestamp(us).ms,ms);});
test('normalized fact preserves raw and normalized values and freshness',()=>{const id=buildAssetIdentity({chain:'ethereum',contract_or_mint:'0x1111111111111111111111111111111111111111',base_asset:'ABC',quote_asset:'USDT',market_type:'FUTURES'});const now=1760000000000;const f=normalizeCrossVenueFact({provider:'X',venue:'X',symbol:'ABCUSDT',asset_identity:id,market_type:'FUTURES',unit:'contracts',event_ts:now-1000,received_ts:now,max_age_ms:5000,raw_value:'10',normalized_value:10});assert.equal(f.status,'CLOSED');assert.equal(f.freshness,'CURRENT');assert.equal(f.raw_value,'10');assert.equal(f.normalized_value,10);});
