import test from 'node:test';import assert from 'node:assert/strict';
import {buildBinanceArchiveUrl,parseChecksumText,normalizeBinanceTimestamp,validateClosedMinuteSeries,classifyAggressorFromArchiveTrade,archiveHistoryPlan} from '../src/binance-public-data-history.mjs';
const NOW=Date.UTC(2026,8,25,12,0,0);
function k(ts,closeTs=ts+59999){return [ts,'1','2','0.5','1.5','100',closeTs,'',10,'60'];}
test('Binance public archive builds separate Spot and USD-M paths',()=>{const d=new Date(Date.UTC(2026,8,24));const a=buildBinanceArchiveUrl({market:'spot',frequency:'daily',data_type:'klines',symbol:'ongusdt',interval:'1m',date:d});const b=buildBinanceArchiveUrl({market:'usd_m_futures',frequency:'daily',data_type:'aggTrades',symbol:'ONGUSDT',date:d});assert.match(a.url,/\/spot\/daily\/klines\/ONGUSDT\/1m\//);assert.match(b.url,/\/futures\/um\/daily\/aggTrades\/ONGUSDT\//);assert.notEqual(a.url,b.url);});
test('checksum parser requires SHA256',()=>{const x=parseChecksumText('a'.repeat(64)+'  ONG.zip');assert.equal(x.status,'CLOSED');assert.equal(parseChecksumText('bad').status,'NOT_CLOSED');});
test('2025+ microsecond timestamp auto normalizes',()=>{const ms=Date.UTC(2026,0,1);const r=normalizeBinanceTimestamp(ms*1000,{spot:true});assert.equal(r.status,'CLOSED');assert.equal(r.ms,ms);});
test('incomplete candle blocks classification',()=>{const ts=NOW-60_000;const rows=[k(ts,NOW+60_000)];const r=validateClosedMinuteSeries(rows,{now:NOW});assert.equal(r.status,'NOT_CLOSED');assert.equal(r.reason,'INCOMPLETE_CANDLE');});
test('missing minute blocks classification',()=>{const rows=[k(NOW-180000),k(NOW-60000)];const r=validateClosedMinuteSeries(rows,{now:NOW});assert.equal(r.status,'NOT_CLOSED');assert.equal(r.reason,'MINUTE_GAP');assert.equal(r.gaps.length,1);});
test('closed contiguous minute series passes',()=>{const rows=[k(NOW-180000),k(NOW-120000),k(NOW-60000)];assert.equal(validateClosedMinuteSeries(rows,{now:NOW}).status,'CLOSED');});
test('maker flag yields aggressor heuristic, never accumulation proof',()=>{const buy=classifyAggressorFromArchiveTrade({p:'2',q:'3',m:false});const sell=classifyAggressorFromArchiveTrade({p:'2',q:'3',m:true});assert.equal(buy.aggressor,'BUY');assert.equal(sell.aggressor,'SELL');assert.equal(buy.accumulation_proof,false);});
test('history plan is maintenance only and does not persist every trade',()=>{const p=archiveHistoryPlan({days:90,candidates:20,market_count:2});assert.equal(p.hot_cycle,false);assert.equal(p.persist_every_trade,false);});
