import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {buildRuntimeCanonicalBundle as before} from '../fixtures/base-runtime/src/canonical-runtime-adapter.mjs';
import {buildRuntimeCanonicalBundle as after} from '../../.verification/staged-runtime/src/canonical-runtime-adapter.mjs';
import {canonicalFingerprint} from '../../.verification/staged-runtime/src/canonical-analytical-result.mjs';
import {createLiquidationAcquisition,buildEarlyLiquidationView} from '../src/liq-canonical-context.mjs';
import {acquireLiquidationsForDeepCheck} from '../src/liq-deep-hook.mjs';
import {seal} from '../../src/core.mjs';
const live=JSON.parse(fs.readFileSync(new URL('../../proof/live-native-round2.json',import.meta.url),'utf8'));
const raw=live.receipt,asof=raw.analysis_as_of_ms;
const acquisition=()=>createLiquidationAcquisition({contract:'FIL-USDT',run_id:raw.run_id,acquisition_id:'ACQ:CAPTURED_NATIVE_FIL',receipts:[raw],requests:live.requests,started_ts:live.transport[0].started_ts,completed_ts:asof});
const args=()=>({contract:'FIL-USDT',run_id:raw.run_id,snapshot_id:'CANONICAL_CAPTURED_FIL',observed_ts:asof,
 discovery_row:{contract:'FIL-USDT',rolling_24h_change_pct:2},publication_shadow:{entry_signal:{state:'OBSERVE',direction:'LONG'},scenario_plan:{execution_reference_price:1.14}},
 public_evidence:{evidence:[]},liquidation_intelligence:{projected_clusters:[],projected_map_status:'NOT_CLOSED'},
 free_source_summary:{status:'CLOSED',owner:'source-registry.mjs',registry:{status:'CLOSED',entries:[]},entry_funnel:{status:'CLOSED',blockers:[],blocker_details:[]},continuous_collector_status:'PARTIAL_REALTIME_COVERAGE',hot_cycle_external_request_delta:0,d1_write_delta:0}});
const view=(acq=acquisition(),extra={})=>buildEarlyLiquidationView({legacy:null,acquisition:acq,...args(),max_age_ms:600000,...extra});
test('feature absent: actual V7 canonical and both formatter outputs are byte-equivalent',()=>{const x=args();assert.deepEqual(after(x),before(x));});
test('actual canonical consumes native liquidation receipts before a 20% pump',()=>{const x=args(),baseline=before(x),r=after({...x,free_liquidation_acquisition:acquisition()});assert.equal(x.discovery_row.rolling_24h_change_pct,2);assert.equal(baseline.canonical.liquidations.status,'NOT_APPLICABLE');assert.equal(r.canonical.liquidations.status,'CLOSED_SCOPED_NATIVE_CONTEXT');assert.equal(r.canonical.liquidations.map_visible_before_pump,true);assert(r.canonical.liquidations.above.length>0);assert(r.canonical.liquidations.below.length>0);});
test('both actual formatters read the same canonical fingerprint with venue-marked levels',()=>{const b=after({...args(),free_liquidation_acquisition:acquisition()});assert.equal(b.manual.ok,true,JSON.stringify(b.manual));assert.equal(b.telegram.ok,true,JSON.stringify(b.telegram));assert.equal(b.manual.analytical_fingerprint,b.telegram.analytical_fingerprint);assert.equal(b.parity_fingerprint,b.canonical.analytical_fingerprint);assert.match(b.telegram.message,/Hyperliquid FIL/);assert.match(b.manual.text,/Hyperliquid FIL/);assert.match(b.telegram.message,/USDC/);assert.match(b.manual.text,/0,9017706074/);assert.match(b.telegram.message,/0,9017706074/);});
test('new maps do not change existing score, direction, entry, hard gates or targets',()=>{const a=before(args()).canonical,b=after({...args(),free_liquidation_acquisition:acquisition()}).canonical;for(const k of ['scores','direction','state','entry','trigger','invalidation','targets','hard_gates','safety'])assert.deepEqual(b[k],a[k],k);assert.equal(b.liquidations.score_eligible,false);assert.equal(b.liquidations.entry_eligible,false);assert.equal(b.liquidations.targets_created,false);});
test('fingerprint really covers newly added liquidation facts before rendering',()=>{const b=after({...args(),free_liquidation_acquisition:acquisition()});assert.equal(canonicalFingerprint({...b.canonical,analytical_fingerprint:undefined}),b.canonical.analytical_fingerprint);const edited=structuredClone(b.canonical);edited.liquidations.above[0].native_price=9;assert.notEqual(canonicalFingerprint({...edited,analytical_fingerprint:undefined}),b.canonical.analytical_fingerprint);});
test('two data clocks stay separate: acquisition and final canonical cutoff',()=>{const later=asof+30000,r=view(acquisition(),{observed_ts:later});assert.equal(r.analysis_binding.observed_ts,later);assert.equal(r.sources[0].source_ts,raw.source_ts);assert.equal(r.sources[0].acquisition_as_of_ms,asof);assert.equal(r.source_timestamps_rewritten,false);});
test('future-acquisition frame is not used for an older canonical snapshot',()=>{assert.equal(view(acquisition(),{observed_ts:asof-1}).reason,'ACQUISITION_FROM_FUTURE');});
test('wrong contract/run and receipt-content tampering are rejected before display',()=>{for(const change of [{contract:'ETH-USDT'},{run_id:'OTHER'}])assert.equal(view(acquisition(),change).reason,'ACQUISITION_IDENTITY_OR_HASH_MISMATCH');const a=acquisition();a.receipts[0].zones[0].native_price=100;assert.equal(view(a).reason,'ACQUISITION_IDENTITY_OR_HASH_MISMATCH');});
test('new source timestamp missing does not become collection timestamp',()=>{const r=seal({...raw,source_ts:null});const a=createLiquidationAcquisition({contract:'FIL-USDT',run_id:raw.run_id,acquisition_id:'a',receipts:[r],requests:1,started_ts:asof-1000,completed_ts:asof});const v=view(a);assert.equal(v.status,'NOT_CLOSED');assert(v.quarantined.some(x=>x.reason==='NATIVE_SOURCE_CLOCK_NOT_CLOSED'));});
test('realized events and model-only sources do not leak into future native levels',()=>{const r=seal({...raw,evidence_class:'REALIZED_EVENTS'});const a=createLiquidationAcquisition({contract:'FIL-USDT',run_id:raw.run_id,acquisition_id:'a',receipts:[r],requests:1,started_ts:asof-1000,completed_ts:asof});const v=view(a);assert.equal(v.above.length,0);assert.equal(v.below.length,0);});
test('large distant native levels remain with explicit cross-margin context, not HTX targets',()=>{const r=view();assert(r.above.some(z=>z.native_price>10));assert(r.above.every(z=>z.not_htx_target));assert.equal(r.prices_converted_to_htx,false);assert.match(r.display_lines.join(' '),/кросс-маржа/);});
test('same provider receipt cannot duplicate exposure on a retry',()=>{const a=createLiquidationAcquisition({contract:'FIL-USDT',run_id:raw.run_id,acquisition_id:'a',receipts:[raw,raw],requests:1,started_ts:asof-1000,completed_ts:asof});assert.equal(view(a).sources.length,1);assert.equal(view(a).notional_summed_across_sources,false);});
test('negative source age boundary: fresh request does not renew an old native snapshot',()=>{const r=view(acquisition(),{observed_ts:asof+900000});assert.equal(r.status,'NOT_CLOSED');assert.equal(r.above.length,0);});
test('deep hook off never touches network or persistence',async()=>{let n=0;const r=await acquireLiquidationsForDeepCheck({mode:'OFF',collect:async()=>{n++;}},{contract:'FIL-USDT',run_id:'r',cycle_started_ts:asof});assert.equal(r,null);assert.equal(n,0);});
test('deep hook errors remain diagnostic and do not manufacture a closed receipt',async()=>{let calls=0;const r=await acquireLiquidationsForDeepCheck({mode:'SHADOW_ONLY',collect:async()=>{throw Error('timeout');},diagnostic:()=>calls++},{contract:'FIL-USDT',run_id:'r',cycle_started_ts:asof});assert.equal(r,null);assert.equal(calls,1);});
test('deep hook collects before the fixed canonical clock and keeps native timestamps',async()=>{const r=await acquireLiquidationsForDeepCheck({mode:'SHADOW_ONLY',collect:async()=>({...live,completed_ts:asof,started_ts:asof-2000})},{contract:'FIL-USDT',run_id:raw.run_id,cycle_started_ts:asof-2000});assert(r);assert.equal(r.receipts[0].source_ts,raw.source_ts);assert.equal(r.completed_ts,asof);});
