import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {createLiquidationAcquisition,buildEarlyLiquidationView} from '../src/liq-canonical-context.mjs';
const runtime=new URL('../../../unified-delivery-base/test-runtime/src/',import.meta.url);
const {persistCanonicalSnapshot,canonicalFingerprint}=await import(new URL('canonical-publication.mjs',runtime));
const {runBoundTelegramDeliverySidecar}=await import(new URL('bound-telegram-delivery-sidecar.mjs',runtime));
function norm(sql,args){const picks=[];const q=String(sql).replace(/\?(\d+)/g,(_,n)=>{picks.push(Number(n)-1);return '?';});return picks.length?[q,picks.map(i=>args[i])]:[sql,args];}
class Prep{constructor(owner,sql,args=[]){this.owner=owner;this.sql=sql;this.args=args;}bind(...args){return new Prep(this.owner,this.sql,args);}async first(){const[q,a]=norm(this.sql,this.args),r=this.owner.db.prepare(q).get(...a)??null;this.owner.read(r?1:0);return r;}async all(){const[q,a]=norm(this.sql,this.args),r=this.owner.db.prepare(q).all(...a);this.owner.read(r.length);return{results:r};}async run(){const[q,a]=norm(this.sql,this.args),r=this.owner.db.prepare(q).run(...a),c=Number(r.changes||0);this.owner.write(c);return{meta:{changes:c}};}}
class DB{constructor(){this.db=new DatabaseSync(':memory:');this.u={requests:0,rows_read:0,rows_written:0,unknown_ops:0};}prepare(s){return new Prep(this,s);}read(n){this.u.requests++;this.u.rows_read+=n||0;}write(n){this.u.requests++;this.u.rows_written+=n||0;}usageSnapshot(){return structuredClone(this.u);}async batch(stmts){const out=[];this.db.exec('BEGIN');try{for(const s of stmts){const[q,a]=norm(s.sql,s.args);if(/^\s*(SELECT|PRAGMA)/i.test(q)){const rows=this.db.prepare(q).all(...a);this.read(rows.length);out.push({results:rows});}else{const r=this.db.prepare(q).run(...a),c=Number(r.changes||0);this.write(c);out.push({meta:{changes:c}});}}this.db.exec('COMMIT');return out;}catch(e){this.db.exec('ROLLBACK');throw e;}}}
function schema(d){d.db.exec(fs.readFileSync(new URL('../../../unified-delivery-base/migrations.sql',import.meta.url),'utf8'));d.db.exec(`CREATE TABLE v3_user_lifecycle_shadow(contract TEXT,direction TEXT,wave_id TEXT,rules_version TEXT,status TEXT,reason TEXT,observation_ts INTEGER,valid_until_ts INTEGER,updated_ts INTEGER,shadow_only INTEGER,PRIMARY KEY(contract,direction,wave_id,rules_version));CREATE TABLE v3_telegram_dispatch_shadow(dispatch_id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE,contract TEXT,direction TEXT,wave_id TEXT,lifecycle_event TEXT,rules_version TEXT,state TEXT,decision_id TEXT,message_hash TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);CREATE TABLE v3_pipeline_health_shadow(namespace TEXT PRIMARY KEY,status TEXT,reasons_json TEXT,changed_ts INTEGER,last_checked_ts INTEGER,shadow_only INTEGER);CREATE TABLE v3_pipeline_health_event_shadow(event_id TEXT PRIMARY KEY,transition TEXT,from_status TEXT,to_status TEXT,reasons_json TEXT,state TEXT,telegram_message_id TEXT,last_error TEXT,created_ts INTEGER,updated_ts INTEGER,sent_ts INTEGER,shadow_only INTEGER);`);}
const live=JSON.parse(fs.readFileSync(new URL('../../proof/live-native-round2.json',import.meta.url),'utf8')),frame=live.receipt,now=frame.analysis_as_of_ms;
function canonical(){const acq=createLiquidationAcquisition({contract:'FIL-USDT',run_id:frame.run_id,acquisition_id:'ACQ:BOUND',receipts:[frame],requests:live.requests,started_ts:live.transport[0].started_ts,completed_ts:frame.analysis_as_of_ms});const liq=buildEarlyLiquidationView({legacy:{pump:{is_pump:false}},acquisition:acq,contract:'FIL-USDT',run_id:frame.run_id,snapshot_id:'SNAP:BOUND',observed_ts:now,max_age_ms:600000});const c={version:'fixture',status:'CLOSED',snapshot_id:'SNAP:BOUND',run_id:frame.run_id,observed_ts:now,snapshot_time_utc:new Date(now).toISOString(),universe:[{contract:'FIL-USDT'}],candidates:[{contract:'FIL-USDT'}],state:'OBSERVE',direction:'LONG',scores:{overall_0_100:null,coin_interest_0_100:72,entry_readiness_0_100:null,is_probability:false},reasons:[],source_receipts:[],hard_gates:[],current_price:1.14,entry:{area:'1,10–1,15 USDT'},trigger:{metric:'price',operator:'>=',value:1.15,unit:'USDT',timeframe:'5m',cancel_condition:'price<1.05',expires_ts:now+1800000,next_recheck_ts:now+300000},invalidation:null,targets:[],liquidations:liq,metadata:{contract:'FIL-USDT',source_role_view:{status:'CLOSED',classified:[{source_key:'HTX_OFFICIAL',assigned_roles:['EXECUTION_TRUTH'],registry_known:true,source_family:'HTX'},{source_key:'HYPERLIQUID_OFFICIAL',assigned_roles:['PROJECTED_LIQUIDATION_CONTEXT'],registry_known:true,source_family:'HYPERLIQUID'}]}},safety:{strategy_weights_changed:false,hard_gates_bypassed:false,automatic_execution:false,validated_signal:false}};c.analytical_fingerprint=canonicalFingerprint(c);return c;}
async function seed(d){const c=canonical(),p=await persistCanonicalSnapshot(d,{canonical:c,wave_id:'W:FIL',now_ts:now});assert.equal(p.persisted,true);d.db.prepare('INSERT INTO v3_user_lifecycle_shadow VALUES(?,?,?,?,?,?,?,?,?,1)').run('FIL-USDT','LONG','W:FIL','v3','OBSERVE','EARLY',now,now+1800000,now);d.db.prepare(`INSERT INTO v3_telegram_dispatch_shadow(dispatch_id,idempotency_key,contract,direction,wave_id,lifecycle_event,rules_version,state,decision_id,message_hash,created_ts,updated_ts,shadow_only) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)`).run('DF','KF','FIL-USDT','LONG','W:FIL','OBSERVE','v3','PENDING',null,null,now,now);return{c,p};}
test('actual bound sender delivers stored native liquidation context to isolated receiver',async()=>{const d=new DB();schema(d);const {c,p}=await seed(d);let body=null,calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://isolated.invalid',relay_key:'test',source_run_id:frame.run_id,now_ts:now+1000,fetch_impl:async(_u,o)=>{calls++;body=JSON.parse(o.body);return{ok:true,status:200,json:async()=>({ok:true,status:'SENT',message_id:12345})};}});assert.equal(calls,1);assert.equal(r.sent,1);assert.match(body.text,/Hyperliquid FIL/);assert.match(body.text,/USDC/);assert.match(body.text,/как цели на HTX отдельно не подтверждены/);assert.doesNotMatch(body.text,/12,1582895551 USDT/);const stored=d.db.prepare('SELECT telegram_text,manual_text,analytical_fingerprint FROM canonical_publication_shadow WHERE publication_id=?').get(p.publication_id);assert.equal(body.text,stored.telegram_text);assert.equal(stored.analytical_fingerprint,c.analytical_fingerprint);assert.match(stored.manual_text,/Hyperliquid FIL/);assert.match(stored.manual_text,/USDC/);assert.equal(d.db.prepare("SELECT state FROM v3_telegram_dispatch_shadow WHERE idempotency_key='KF'").get().state,'SENT');d.db.close();});
test('sender never transmits native liquidation context from a different run',async()=>{const d=new DB();schema(d);await seed(d);let calls=0;const r=await runBoundTelegramDeliverySidecar(d,{enabled:true,relay_url:'https://isolated.invalid',relay_key:'test',source_run_id:'WRONG-RUN',now_ts:now+1000,fetch_impl:async()=>{calls++;throw Error('must not send')}});assert.equal(calls,0);assert.equal(r.sent,0);assert.equal(d.db.prepare("SELECT state FROM v3_telegram_dispatch_shadow WHERE idempotency_key='KF'").get().state,'FAILED_RETRYABLE');d.db.close();});
