import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {RemoteD1Database} from '../fixtures/runner/report2-d1-adapter.mjs';
import {reserveLiquidationAllowance} from '../src/liq-quota-d1.mjs';import {createRunnerLiqService} from '../src/liq-runner-service.mjs';
const now=1790490107000;const identity={contract:'FIL-USDT',run_id:'r',acquisition_id:'a'};
function bridge(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(new URL('../migrations/liq-quota-candidate.sql',import.meta.url),'utf8'));
 const history=[];let ackLost=false;
 const fetchImpl=async(url,init)=>{
  assert.equal(url,'https://local-bridge.test/d1');const payload=JSON.parse(init.body);history.push(payload);assert.equal(payload.op,'batch');
  sqlite.exec('BEGIN IMMEDIATE');const result=[],cost=[];
  try{for(const stmt of payload.statements){const q=sqlite.prepare(stmt.sql);if(/^\s*SELECT/i.test(stmt.sql)){const rows=q.all(...stmt.params);result.push({success:true,meta:{changes:0},results:rows});cost.push({measured:true,rows_read:rows.length,rows_written:0});}else{const r=q.run(...stmt.params);result.push({success:true,meta:{changes:Number(r.changes)},results:[]});cost.push({measured:true,rows_read:1,rows_written:Number(r.changes)});}}
   sqlite.exec('COMMIT');if(ackLost){ackLost=false;throw Error('COMMITTED_ACK_LOST');}
   return new Response(JSON.stringify({ok:true,result,usage:{statements:cost}}),{status:200});
  }catch(e){if(sqlite.isTransaction)sqlite.exec('ROLLBACK');return new Response(JSON.stringify({ok:false,error:'INJECTED_LOCAL_TRANSACTION_FAILURE'}),{status:500});}
 };
 const db=new RemoteD1Database('https://local-bridge.test/d1','TEST_ONLY_NOT_A_SECRET',{fetchImpl});
 return {db,sqlite,history,provision:(key,cap,until=now+600000,policy='verified-fixture')=>sqlite.prepare('INSERT INTO report2_liq_quota_v1(quota_key,capacity,valid_until_ms,policy_receipt) VALUES(?,?,?,?)').run(key,cap,until,policy),loseAck:()=>{ackLost=true;},close:()=>sqlite.close()};
}
const req=()=>[{quota_key:'monthly-LF',policy_receipt:'verified-fixture',units:1},{quota_key:'monthly-HL',policy_receipt:'verified-fixture',units:5},{quota_key:'run-r',policy_receipt:'verified-fixture',units:6}];
const reserve=(b,extra={})=>reserveLiquidationAllowance(b.db,{reservation_id:'a',acquisition_identity:identity,requirements:req(),now_ms:now,...extra});
function filled(){const b=bridge();for(const [key,cap] of [['monthly-LF',2],['monthly-HL',10],['run-r',12]])b.provision(key,cap);return b;}
test('actual project RemoteD1Database batch wire grants all quotas and exact ACK',async()=>{const b=filled(),r=await reserve(b);assert.equal(r.allowed,true);assert.equal(r.logical_statements,6);assert.equal(b.history.length,1);assert.equal(b.db.usageSnapshot().unknown_ops,0);assert.equal(b.db.usageSnapshot().requests,6);assert.equal(b.sqlite.prepare('SELECT state FROM report2_liq_reservation_v1').get().state,'RESERVED');b.close();});
test('one exhausted quota leaves every other allowance unchanged',async()=>{const b=bridge();b.provision('monthly-LF',1);b.provision('monthly-HL',4);b.provision('run-r',24);const r=await reserve(b);assert.equal(r.allowed,false);assert.equal(b.sqlite.prepare('SELECT sum(reserved) n FROM report2_liq_quota_v1').get().n,0);assert.equal(b.sqlite.prepare('SELECT count(*) n FROM report2_liq_reservation_v1').get().n,0);b.close();});
test('duplicate with same nonce never debits again or re-authorizes network',async()=>{const b=filled();const first=await reserve(b,{nonce:'deterministic-test'}),second=await reserve(b,{nonce:'deterministic-test'});assert(first.allowed);assert.equal(second.allowed,false);assert.equal(second.status,'ALREADY_RESERVED_DO_NOT_REEXECUTE');assert.equal(b.sqlite.prepare("SELECT reserved FROM report2_liq_quota_v1 WHERE quota_key='monthly-HL'").get().reserved,5);b.close();});
test('same acquisition ID with a different run is rejected, not deduplicated as success',async()=>{const b=filled();await reserve(b);const r=await reserve(b,{acquisition_identity:{...identity,run_id:'another'}});assert.equal(r.status,'RESERVATION_ID_COLLISION');b.close();});
test('expired and unknown quota policy cannot spend a request',async()=>{for(const mode of ['expired','wrongpolicy']){const b=filled();b.sqlite.prepare('UPDATE report2_liq_quota_v1 SET '+(mode==='expired'?'valid_until_ms=?':'policy_receipt=?')+" WHERE quota_key='monthly-LF'").run(mode==='expired'?now-1:'other');assert.equal((await reserve(b)).allowed,false);assert.equal(b.sqlite.prepare('SELECT sum(reserved) n FROM report2_liq_quota_v1').get().n,0);b.close();}});
test('injected SQL failure rolls back insert and all earlier quota updates',async()=>{const b=filled();b.sqlite.exec("CREATE TRIGGER test_failure BEFORE UPDATE ON report2_liq_quota_v1 WHEN NEW.quota_key='run-r' BEGIN SELECT RAISE(ABORT,'TEST_FAIL'); END;");assert.equal((await reserve(b)).allowed,false);assert.equal(b.sqlite.prepare('SELECT sum(reserved) n FROM report2_liq_quota_v1').get().n,0);assert.equal(b.sqlite.prepare('SELECT count(*) n FROM report2_liq_reservation_v1').get().n,0);b.close();});
test('lost HTTP ACK conservatively burns reservation but never retries collection',async()=>{const b=filled();b.loseAck();assert.equal((await reserve(b)).allowed,false);assert.equal((await reserve(b)).status,'ALREADY_RESERVED_DO_NOT_REEXECUTE');assert.equal(b.sqlite.prepare("SELECT reserved FROM report2_liq_quota_v1 WHERE quota_key='monthly-HL'").get().reserved,5);b.close();});
test('competing calls cannot exceed a whole-run quota',async()=>{const b=filled();b.sqlite.exec("UPDATE report2_liq_quota_v1 SET capacity=6 WHERE quota_key='run-r'");const rows=await Promise.all([reserve(b),reserve(b,{reservation_id:'b',acquisition_identity:{...identity,acquisition_id:'b'}})]);assert.equal(rows.filter(x=>x.allowed).length,1);assert.equal(b.sqlite.prepare("SELECT reserved FROM report2_liq_quota_v1 WHERE quota_key='run-r'").get().reserved,6);b.close();});
function service(b,{d1=true,fetch_impl=async()=>{throw Error('SHOULD_NOT_FETCH');}}={}){return createRunnerLiqService({mode:'SHADOW_ONLY',quota_db:b.db,max_accounts:4,clock:()=>now,fetch_impl,
 quota_keys:{run:{key:'run-r',policy_receipt:'verified-fixture'},liqflow:{key:'monthly-LF',policy_receipt:'verified-fixture'},hyperliquid:{key:'monthly-HL',policy_receipt:'verified-fixture'}},scope_registry:{'FIL-USDT':{execution_contract:'FIL-USDT',native_venue:'Hyperliquid',native_symbol:'FIL',multiplier:1,policy_receipt:'scope-fixture'}},d1_admission:async()=>({allowed:d1,measurement_status:d1?'VALIDATED':'UNKNOWN'})});}
test('disabled service creates zero D1 and HTTP operations',()=>{assert.equal(createRunnerLiqService({mode:'OFF'}),null);});
test('missing cost proof stops collection before touching budget tables',async()=>{const b=filled(),s=service(b,{d1:false});const r=await s.collect({...identity,cycle_started_ts:now});assert.equal(r.status,'D1_COST_ENVELOPE_NOT_VALIDATED_OR_NO_CAPACITY');assert.equal(b.history.length,0);b.close();});
test('unlisted pair does not inherit another symbol authorization',async()=>{const b=filled(),s=service(b);const r=await s.collect({...identity,contract:'ETH-USDT',cycle_started_ts:now});assert.equal(r.requests,0);assert.equal(b.history.length,0);b.close();});
test('bounded service spends reserved calls and returns exact native snapshot only',async()=>{
 const b=filled(),calls=[];let nativeIndex=0;const capture=JSON.parse(fs.readFileSync(new URL('../../evidence/hl_account_0.raw',import.meta.url),'utf8'));capture.time=now;
 const transport=async(url,init)=>{calls.push(url);const body=init?.body?JSON.parse(init.body):null;if(body?.type==='metaAndAssetCtxs')return new Response(JSON.stringify([{universe:[{name:'FIL'}]},[]]));if(String(url).includes('node.liqflow.app'))return new Response(JSON.stringify({coin:'FIL',positions:[{address:'0x'+'1'.repeat(40)}],total:10000,page:1}));if(body?.type==='clearinghouseState'){nativeIndex++;return new Response(JSON.stringify(capture));}throw Error('UNEXPECTED_URL');};
 const s=service(b,{fetch_impl:transport}),r=await s.collect({...identity,cycle_started_ts:now});assert.equal(r.status,'NATIVE_VALIDATED_SAMPLE_COLLECTED');assert.equal(r.requests,3);assert.equal(nativeIndex,1);assert.equal(r.receipt.model_prices_used,false);assert.equal(r.receipt.account_count,1);assert.equal(r.receipt.whole_book_coverage_pct,null);assert.equal(r.source_prices_are_htx_targets,false);
 assert.equal((await s.collect({...identity,cycle_started_ts:now})).requests,0);assert.equal(calls.length,3);b.close();});
