import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createNativeAcquisition,bindNativeAcquisition,attachNativeContext} from '../../src/runtime-bridge.mjs';
const runtime=new URL('../../../unified-delivery-base/test-runtime/src/',import.meta.url);const {canonicalFingerprint,renderCanonicalTelegram,renderCanonicalManual}=await import(new URL('canonical-publication.mjs',runtime));
const load=n=>JSON.parse(fs.readFileSync(new URL('../../evidence/'+n,import.meta.url),'utf8'));
const accounts=[0,6].map(i=>({address:load(`hl_account_${i}.receipt.json`).request_body.user,state:load(`hl_account_${i}.raw`),http_receipt:load(`hl_account_${i}.receipt.json`)}));
const start=Math.min(...accounts.map(x=>x.http_receipt.started_ts)),completed=Math.max(...accounts.map(x=>x.http_receipt.received_ts)),observed=completed+1000,run='RUN:NATIVE:REAL';
function acquisition(){return createNativeAcquisition({contract:'FIL-USDT',native_symbol:'FIL',run_id:run,acquisition_id:'ACQ:RUNTIME',collection_started_ts:start,collection_completed_ts:completed,accounts,provenance:{selection_bias:'TEST_CAPTURED_PUBLIC_ACCOUNTS',raw_model_prices_used:false}});}
function canonical(){const legacy={version:'pump',status:'NOT_APPLICABLE',pump:{is_pump:false},above:[],below:[]};const liquidations=attachNativeContext(legacy,acquisition(),{contract:'FIL-USDT',run_id:run,snapshot_id:'SNAP:RUNTIME',observed_ts:observed,direction:'LONG'});const c={status:'CLOSED',snapshot_id:'SNAP:RUNTIME',run_id:run,observed_ts:observed,snapshot_time_utc:new Date(observed).toISOString(),universe:[{contract:'FIL-USDT'}],candidates:[{contract:'FIL-USDT'}],state:'OBSERVE',direction:'LONG',scores:{overall_0_100:null,coin_interest_0_100:72,entry_readiness_0_100:null,is_probability:false},reasons:[],source_receipts:[],hard_gates:[],entry:{area:'1,10–1,15 USDT'},trigger:{metric:'price',operator:'>=',value:1.15,unit:'USDT',timeframe:'5m',cancel_condition:'price<1.05',expires_ts:observed+600000,next_recheck_ts:observed+120000},targets:[],liquidations,metadata:{contract:'FIL-USDT',source_role_view:{status:'CLOSED',classified:[{source_key:'HTX_OFFICIAL',assigned_roles:['EXECUTION_TRUTH'],registry_known:true,source_family:'HTX'},{source_key:'HYPERLIQUID_OFFICIAL',assigned_roles:['PROJECTED_LIQUIDATION_CONTEXT'],registry_known:true,source_family:'HYPERLIQUID'}]}},safety:{strategy_weights_changed:false,hard_gates_bypassed:false,automatic_execution:false,validated_signal:false}};c.analytical_fingerprint=canonicalFingerprint(c);return c;}
test('actual runtime bridge produces bounded native context with original exchange clock',()=>{const a=acquisition(),x=bindNativeAcquisition(a,{contract:'FIL-USDT',run_id:run,snapshot_id:'SNAP:RUNTIME',observed_ts:observed,direction:'LONG'});assert.equal(x.status,'USABLE_NATIVE_SAMPLE');assert.equal(x.price_quote,'USDC');assert.equal(x.sample_accounts,2);assert.equal(x.returned_positive_levels,1);assert.equal(x.missing_native_liquidation_prices,1);assert.equal(x.above[0].native_price,44.5850344972);assert.equal(x.above[0].price_quote,'USDC');assert.equal(x.above[0].source_ts,load('hl_account_0.raw').time);assert.equal(x.entry_eligible,false);assert.equal(x.render_enabled,true);assert.equal(x.automatic_execution,false); /* User-facing context is allowed; entry/trading still forbidden. */});
test('candidate publication understands exact native_extension schema used by worker hook',()=>{const c=canonical(),tg=renderCanonicalTelegram({canonical:c,lifecycle_event:'OBSERVE'}),man=renderCanonicalManual({canonical:c,lifecycle_event:'OBSERVE'});assert(tg.ok&&man.ok);for(const t of [tg.text,man.text]){assert.match(t,/Hyperliquid FIL/);assert.match(t,/44,5850345 USDC/);assert.match(t,/кросс-маржа/);assert.match(t,/как цели на HTX отдельно не подтверждены/);assert.doesNotMatch(t,/44,5850345 USDT/);}assert.equal(tg.analytical_fingerprint,c.analytical_fingerprint);assert.equal(man.analytical_fingerprint,c.analytical_fingerprint);});
test('actual runtime bridge remains invisible when acquisition is absent',()=>{const legacy={status:'NOT_APPLICABLE',pump:{is_pump:false},above:[],below:[]};assert.equal(attachNativeContext(legacy,null,{contract:'FIL-USDT'}),legacy);});
test('receipt tampering is rejected before native context reaches canonical',()=>{const a=acquisition();a.accounts[0].state.assetPositions.find(x=>x.position.coin==='FIL').position.liquidationPx='1';const x=bindNativeAcquisition(a,{contract:'FIL-USDT',run_id:run,snapshot_id:'SNAP:RUNTIME',observed_ts:observed,direction:'LONG'});assert.equal(x.status,'NOT_CLOSED');assert.equal(x.reason,'RAW_ACQUISITION_DIGEST_OR_SCHEMA_INVALID');});
test('late acquisition cannot be attached to an older canonical cutoff',()=>{const x=bindNativeAcquisition(acquisition(),{contract:'FIL-USDT',run_id:run,snapshot_id:'SNAP:RUNTIME',observed_ts:completed-1,direction:'LONG'});assert.equal(x.status,'NOT_CLOSED');assert.equal(x.reason,'ACQUISITION_AFTER_ANALYTICAL_CUTOFF');});
